In [3]:
## SONGS WAV and AIFF
# -----######-----###### FILE SYSTEM TYPE BREAKDOWN IN GB -----######-----###### #
import os
import pandas as pd
from collections import defaultdict

def _fs_1807_breakdown_GET_types_gbtotal(folder_path):
    """
    Walks a folder recursively and returns a breakdown of:
    - File count and total size per extension (in GB)
    - Grand total size in GB
    """
    ext_sizes = defaultdict(float)
    ext_counts = defaultdict(int)

    for root, _, files in os.walk(folder_path):
        for f in files:
            if f.startswith('._') or f in ['.DS_Store']:
                continue
            ext = os.path.splitext(f)[1].lower().strip('.')
            f_path = os.path.join(root, f)
            try:
                size_bytes = os.path.getsize(f_path)
                size_gb = size_bytes / (1024**3)
                ext_sizes[ext] += size_gb
                ext_counts[ext] += 1
            except Exception as e:
                print(f"⚠️ Skipping: {f_path} | {e}")

    df_stats = pd.DataFrame({
        'Extension': list(ext_sizes.keys()),
        'File Count': list(ext_counts.values()),
        'Size (GB)': [round(size, 4) for size in ext_sizes.values()]
    }).sort_values('Size (GB)', ascending=False).reset_index(drop=True)

    grand_total_gb = round(sum(ext_sizes.values()), 4)
    print(f"\n🎯 Grand Total Size: {grand_total_gb} GB")

    return df_stats
folder_path = "/Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/Contents"
df_breakdown = _fs_1807_breakdown_GET_types_gbtotal(folder_path)
print(df_breakdown)

🎯 Grand Total Size: 198.5529 GB
  Extension  File Count  Size (GB)
0       mp3       17327   131.5420
1      flac        1166    49.2038
2      aiff         137    10.3902
3       wav          94     4.8889
4       aif          33     2.3230
5       m4a          19     0.2050

In [5]:
# -----######-----###### GET PATHS & SIZES FOR SPECIFIC EXTENSIONS -----######-----###### #
import os
import pandas as pd

def _fs_1807_extpaths_GET_df_pathsizes(folder_path, target_extensions):
    """
    Finds all files with extensions in `target_extensions` inside `folder_path`.
    Returns a DataFrame with columns: Path, Extension, Size (GB)
    """
    paths, exts, sizes = [], [], []

    target_extensions = [ext.lower() for ext in target_extensions]

    for root, _, files in os.walk(folder_path):
        for f in files:
            if f.startswith('._') or f == '.DS_Store':
                continue
            ext = os.path.splitext(f)[1].lower().strip('.')
            if ext in target_extensions:
                f_path = os.path.join(root, f)
                try:
                    size_gb = os.path.getsize(f_path) / (1024**3)
                    paths.append(f_path)
                    exts.append(ext)
                    sizes.append(round(size_gb, 5))
                except Exception as e:
                    print(f"⚠️ Skipping: {f_path} | {e}")

    df = pd.DataFrame({'Path': paths, 'Extension': exts, 'Size (GB)': sizes})
    df = df.sort_values('Size (GB)', ascending=False).reset_index(drop=True)
    return df
folder_path = "/Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/Contents"
target_extensions = ['flac', 'aiff', 'wav', 'aif']
df = _fs_1807_extpaths_GET_df_pathsizes(folder_path, target_extensions)
df

                                                   Path Extension  Size (GB)
0     /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...       wav    0.22369
1     /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...       wav    0.18603
2     /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...       wav    0.16556
3     /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...       aif    0.14404
4     /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...      aiff    0.14383
...                                                 ...       ...        ...
1425  /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...      flac    0.00099
1426  /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...      flac    0.00097
1427  /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...      flac    0.00097
1428  /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...      flac    0.00082
1429  /Volumes/MUSIC_PROD/_5_MISC-zarch/_SINC_music/...      flac    0.00078

[1430 rows x 3 columns]

In [ ]:
####

In [10]:
# -----######-----###### EXTENSION-BASED CHUNKED COPY WITH LOG -----######-----###### #
import os
import shutil
import pandas as pd
from tqdm import tqdm

def _fileops_1807_chunkcopy_GET_extchunk_sorted(df, dest_base_path):
    """
    Groups by Extension, copies files in chunks of 50 to folders like _24_ARCH_rk_<ext>_<chunk#>.
    Ensures no filename collisions. Adds 'Copied_To' column with TQM progress bar.
    """
    tqdm.pandas()
    os.makedirs(dest_base_path, exist_ok=True)
    df = df.copy()
    
    # Ensure required columns
    df['file_name'] = df['Path'].apply(os.path.basename)
    df['Extension'] = df['Extension'].str.lower()
    
    copied_to = [None] * len(df)
    tq_bar = tqdm(total=len(df), desc="🎯 COPY FLOW", ncols=100)

    folder_index_by_ext = {}

    for ext, group in df.groupby('Extension'):
        group = group.sort_values(by='Size (GB)', ascending=False).reset_index()
        chunk_files = set()
        current_chunk = []
        chunk_counter = 1
        
        for _, row in group.iterrows():
            src = row['Path']
            fname = row['file_name']
            orig_idx = row['index']

            # Start new chunk if name conflict or chunk full
            if fname in chunk_files or len(current_chunk) >= 50:
                folder_name = f"_25_SINC_rk_{ext}_{chunk_counter}"
                dest_folder = os.path.join(dest_base_path, folder_name)
                os.makedirs(dest_folder, exist_ok=True)

                for p, n, i in current_chunk:
                    dest_path = os.path.join(dest_folder, n)
                    try:
                        shutil.copy2(p, dest_path)
                        copied_to[i] = dest_path
                        tq_bar.update(1)
                    except Exception as e:
                        tqdm.write(f"❌ Error copying {p} → {dest_path} | {e}")

                tqdm.write(f"📦 Finished: {folder_name} ({len(current_chunk)} files)")
                chunk_counter += 1
                chunk_files = set()
                current_chunk = []

            chunk_files.add(fname)
            current_chunk.append((src, fname, orig_idx))

        # Final chunk
        if current_chunk:
            folder_name = f"_25_SINC_rk_{ext}_{chunk_counter}"
            dest_folder = os.path.join(dest_base_path, folder_name)
            os.makedirs(dest_folder, exist_ok=True)

            for p, n, i in current_chunk:
                dest_path = os.path.join(dest_folder, n)
                try:
                    shutil.copy2(p, dest_path)
                    copied_to[i] = dest_path
                    tq_bar.update(1)
                except Exception as e:
                    tqdm.write(f"❌ Error copying {p} → {dest_path} | {e}")

            tqdm.write(f"📦 Final: {folder_name} ({len(current_chunk)} files)")

    tq_bar.close()
    df['Copied_To'] = copied_to

    # Save log
    log_path = os.path.join(dest_base_path, "copied_log.csv")
    df.to_csv(log_path, index=False)
    print(f"\n✅ Done. Log saved at: {log_path}")
    return df

In [11]:
dest_base_path = "/Volumes/MUSIC_PROD/_5_MISC-zarch/_music_SIN"
df = _fileops_1807_chunkcopy_GET_extchunk_sorted(df, dest_base_path)

🎯 COPY FLOW:   0%|                                                        | 0/1430 [00:00<?, ?it/s]

🎯 COPY FLOW:   0%|                                              | 1/1430 [00:11<4:39:06, 11.72s/it]

🎯 COPY FLOW:   0%|                                              | 2/1430 [00:17<3:21:36,  8.47s/it]

🎯 COPY FLOW:   0%|                                              | 3/1430 [00:23<2:52:24,  7.25s/it]

🎯 COPY FLOW:   0%|▏                                             | 4/1430 [00:29<2:36:41,  6.59s/it]

🎯 COPY FLOW:   0%|▏                                             | 5/1430 [00:38<2:55:01,  7.37s/it]

🎯 COPY FLOW:   0%|▏                                             | 6/1430 [00:43<2:37:16,  6.63s/it]

🎯 COPY FLOW:   0%|▏                                             | 7/1430 [00:48<2:25:30,  6.14s/it]

🎯 COPY FLOW:   1%|▎                                             | 8/1430 [00:53<2:16:46,  5.77s/it]

🎯 COPY FLOW:   1%|▎                                             | 9/1430 [00:58<2:09:18,  5.46s/it]

🎯 COPY FLOW:   1%|▎                                            | 10/1430 [01:05<2:24:50,  6.12s/it]

🎯 COPY FLOW:   1%|▎                                            | 11/1430 [01:10<2:12:46,  5.61s/it]

🎯 COPY FLOW:   1%|▍                                            | 12/1430 [01:14<2:03:28,  5.22s/it]

🎯 COPY FLOW:   1%|▍                                            | 13/1430 [01:18<1:56:43,  4.94s/it]

🎯 COPY FLOW:   1%|▍                                            | 14/1430 [01:23<1:51:46,  4.74s/it]

🎯 COPY FLOW:   1%|▍                                            | 15/1430 [01:27<1:47:11,  4.55s/it]

🎯 COPY FLOW:   1%|▌                                            | 16/1430 [01:31<1:43:33,  4.39s/it]

🎯 COPY FLOW:   1%|▌                                            | 17/1430 [01:38<2:02:09,  5.19s/it]

🎯 COPY FLOW:   1%|▌                                            | 18/1430 [01:42<1:53:54,  4.84s/it]

🎯 COPY FLOW:   1%|▌                                            | 19/1430 [01:46<1:47:15,  4.56s/it]

🎯 COPY FLOW:   1%|▋                                            | 20/1430 [01:50<1:43:10,  4.39s/it]

🎯 COPY FLOW:   1%|▋                                            | 21/1430 [01:53<1:38:47,  4.21s/it]

🎯 COPY FLOW:   2%|▋                                            | 22/1430 [01:57<1:35:00,  4.05s/it]

🎯 COPY FLOW:   2%|▋                                            | 23/1430 [02:01<1:32:19,  3.94s/it]

🎯 COPY FLOW:   2%|▊                                            | 24/1430 [02:07<1:49:49,  4.69s/it]

🎯 COPY FLOW:   2%|▊                                            | 25/1430 [02:11<1:42:22,  4.37s/it]

🎯 COPY FLOW:   2%|▊                                            | 26/1430 [02:15<1:38:12,  4.20s/it]

🎯 COPY FLOW:   2%|▊                                            | 27/1430 [02:18<1:33:34,  4.00s/it]

🎯 COPY FLOW:   2%|▉                                            | 28/1430 [02:22<1:29:02,  3.81s/it]

🎯 COPY FLOW:   2%|▉                                            | 29/1430 [02:25<1:25:20,  3.66s/it]

🎯 COPY FLOW:   2%|▉                                            | 30/1430 [02:28<1:21:09,  3.48s/it]

🎯 COPY FLOW:   2%|▉                                            | 31/1430 [02:31<1:17:56,  3.34s/it]

🎯 COPY FLOW:   2%|█                                            | 32/1430 [02:37<1:33:20,  4.01s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [04:24<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [03:20<2:39:36,  6.72s/it]

🎯 COPY FLOW:   2%|█                                            | 33/1430 [02:39<1:21:06,  3.48s/it]

📦 Final: _25_SINC_rk_aif_1 (33 files)

🎯 COPY FLOW:   2%|█                                            | 34/1430 [02:48<1:58:43,  5.10s/it]

🎯 COPY FLOW:   2%|█                                            | 35/1430 [02:56<2:21:35,  6.09s/it]

🎯 COPY FLOW:   3%|█▏                                           | 36/1430 [03:07<2:55:14,  7.54s/it]

🎯 COPY FLOW:   3%|█▏                                           | 37/1430 [03:15<2:58:27,  7.69s/it]

🎯 COPY FLOW:   3%|█▏                                           | 38/1430 [03:22<2:56:48,  7.62s/it]

🎯 COPY FLOW:   3%|█▏                                           | 39/1430 [03:30<2:52:46,  7.45s/it]

🎯 COPY FLOW:   3%|█▎                                           | 40/1430 [03:39<3:09:08,  8.16s/it]

🎯 COPY FLOW:   3%|█▎                                           | 41/1430 [03:46<2:58:14,  7.70s/it]

🎯 COPY FLOW:   3%|█▎                                           | 42/1430 [03:53<2:50:15,  7.36s/it]

🎯 COPY FLOW:   3%|█▎                                           | 43/1430 [03:59<2:43:34,  7.08s/it]

🎯 COPY FLOW:   3%|█▍                                           | 44/1430 [04:08<2:56:17,  7.63s/it]

🎯 COPY FLOW:   3%|█▍                                           | 45/1430 [04:14<2:46:15,  7.20s/it]

🎯 COPY FLOW:   3%|█▍                                           | 46/1430 [04:20<2:39:12,  6.90s/it]

🎯 COPY FLOW:   3%|█▍                                           | 47/1430 [04:26<2:33:41,  6.67s/it]

🎯 COPY FLOW:   3%|█▌                                           | 48/1430 [04:35<2:49:48,  7.37s/it]

🎯 COPY FLOW:   3%|█▌                                           | 49/1430 [04:41<2:37:56,  6.86s/it]

🎯 COPY FLOW:   3%|█▌                                           | 50/1430 [04:47<2:29:01,  6.48s/it]

🎯 COPY FLOW:   4%|█▌                                           | 51/1430 [04:52<2:22:45,  6.21s/it]

🎯 COPY FLOW:   4%|█▋                                           | 52/1430 [04:58<2:17:29,  5.99s/it]

🎯 COPY FLOW:   4%|█▋                                           | 53/1430 [05:04<2:22:14,  6.20s/it]

🎯 COPY FLOW:   4%|█▋                                           | 54/1430 [05:10<2:17:56,  6.01s/it]

🎯 COPY FLOW:   4%|█▋                                           | 55/1430 [05:16<2:16:24,  5.95s/it]

🎯 COPY FLOW:   4%|█▊                                           | 56/1430 [05:21<2:12:56,  5.81s/it]

🎯 COPY FLOW:   4%|█▊                                           | 57/1430 [05:27<2:08:49,  5.63s/it]

🎯 COPY FLOW:   4%|█▊                                           | 58/1430 [05:33<2:17:05,  6.00s/it]

🎯 COPY FLOW:   4%|█▊                                           | 59/1430 [05:39<2:11:50,  5.77s/it]

🎯 COPY FLOW:   4%|█▉                                           | 60/1430 [05:44<2:10:58,  5.74s/it]

🎯 COPY FLOW:   4%|█▉                                           | 61/1430 [05:50<2:09:16,  5.67s/it]

🎯 COPY FLOW:   4%|█▉                                           | 62/1430 [05:55<2:04:49,  5.47s/it]

🎯 COPY FLOW:   4%|█▉                                           | 63/1430 [06:00<2:02:18,  5.37s/it]

🎯 COPY FLOW:   4%|██                                           | 64/1430 [06:05<2:02:40,  5.39s/it]

🎯 COPY FLOW:   5%|██                                           | 65/1430 [06:10<1:59:23,  5.25s/it]

🎯 COPY FLOW:   5%|██                                           | 66/1430 [06:16<2:01:18,  5.34s/it]

🎯 COPY FLOW:   5%|██                                           | 67/1430 [06:21<2:01:48,  5.36s/it]

🎯 COPY FLOW:   5%|██▏                                          | 68/1430 [06:27<2:02:00,  5.38s/it]

🎯 COPY FLOW:   5%|██▏                                          | 69/1430 [06:32<2:00:16,  5.30s/it]

🎯 COPY FLOW:   5%|██▏                                          | 70/1430 [06:37<1:57:28,  5.18s/it]

🎯 COPY FLOW:   5%|██▏                                          | 71/1430 [06:42<1:55:39,  5.11s/it]

🎯 COPY FLOW:   5%|██▎                                          | 72/1430 [06:47<1:54:51,  5.07s/it]

🎯 COPY FLOW:   5%|██▎                                          | 73/1430 [06:51<1:53:10,  5.00s/it]

🎯 COPY FLOW:   5%|██▎                                          | 74/1430 [06:57<1:53:29,  5.02s/it]

🎯 COPY FLOW:   5%|██▎                                          | 75/1430 [07:01<1:52:25,  4.98s/it]

🎯 COPY FLOW:   5%|██▍                                          | 76/1430 [07:06<1:51:55,  4.96s/it]

🎯 COPY FLOW:   5%|██▍                                          | 77/1430 [07:11<1:50:26,  4.90s/it]

🎯 COPY FLOW:   5%|██▍                                          | 78/1430 [07:16<1:50:03,  4.88s/it]

🎯 COPY FLOW:   6%|██▍                                          | 79/1430 [07:21<1:49:13,  4.85s/it]

🎯 COPY FLOW:   6%|██▌                                          | 80/1430 [07:25<1:48:17,  4.81s/it]

🎯 COPY FLOW:   6%|██▌                                          | 81/1430 [07:30<1:48:38,  4.83s/it]

🎯 COPY FLOW:   6%|██▌                                          | 82/1430 [07:38<2:06:28,  5.63s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [09:28<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [08:23<2:39:36,  6.72s/it]

🎯 COPY FLOW:   6%|██▌                                          | 83/1430 [07:42<2:00:10,  5.35s/it]

📦 Finished: _25_SINC_rk_aiff_1 (50 files)

🎯 COPY FLOW:   6%|██▋                                          | 84/1430 [07:47<1:55:41,  5.16s/it]

🎯 COPY FLOW:   6%|██▋                                          | 85/1430 [07:52<1:52:06,  5.00s/it]

🎯 COPY FLOW:   6%|██▋                                          | 86/1430 [07:56<1:49:31,  4.89s/it]

🎯 COPY FLOW:   6%|██▋                                          | 87/1430 [08:01<1:47:38,  4.81s/it]

🎯 COPY FLOW:   6%|██▊                                          | 88/1430 [08:09<2:06:47,  5.67s/it]

🎯 COPY FLOW:   6%|██▊                                          | 89/1430 [08:13<1:59:39,  5.35s/it]

🎯 COPY FLOW:   6%|██▊                                          | 90/1430 [08:18<1:54:36,  5.13s/it]

🎯 COPY FLOW:   6%|██▊                                          | 91/1430 [08:23<1:51:04,  4.98s/it]

🎯 COPY FLOW:   6%|██▉                                          | 92/1430 [08:27<1:48:12,  4.85s/it]

🎯 COPY FLOW:   7%|██▉                                          | 93/1430 [08:32<1:45:56,  4.75s/it]

🎯 COPY FLOW:   7%|██▉                                          | 94/1430 [08:36<1:44:52,  4.71s/it]

🎯 COPY FLOW:   7%|██▉                                          | 95/1430 [08:41<1:44:49,  4.71s/it]

🎯 COPY FLOW:   7%|███                                          | 96/1430 [08:46<1:43:29,  4.65s/it]

🎯 COPY FLOW:   7%|███                                          | 97/1430 [08:50<1:42:06,  4.60s/it]

🎯 COPY FLOW:   7%|███                                          | 98/1430 [08:54<1:41:12,  4.56s/it]

🎯 COPY FLOW:   7%|███                                          | 99/1430 [08:59<1:40:32,  4.53s/it]

🎯 COPY FLOW:   7%|███                                         | 100/1430 [09:06<1:58:46,  5.36s/it]

🎯 COPY FLOW:   7%|███                                         | 101/1430 [09:11<1:52:57,  5.10s/it]

🎯 COPY FLOW:   7%|███▏                                        | 102/1430 [09:15<1:49:58,  4.97s/it]

🎯 COPY FLOW:   7%|███▏                                        | 103/1430 [09:20<1:46:42,  4.83s/it]

🎯 COPY FLOW:   7%|███▏                                        | 104/1430 [09:24<1:44:03,  4.71s/it]

🎯 COPY FLOW:   7%|███▏                                        | 105/1430 [09:29<1:41:57,  4.62s/it]

🎯 COPY FLOW:   7%|███▎                                        | 106/1430 [09:36<1:58:37,  5.38s/it]

🎯 COPY FLOW:   7%|███▎                                        | 107/1430 [09:40<1:53:21,  5.14s/it]

🎯 COPY FLOW:   8%|███▎                                        | 108/1430 [09:45<1:49:07,  4.95s/it]

🎯 COPY FLOW:   8%|███▎                                        | 109/1430 [09:50<1:46:28,  4.84s/it]

🎯 COPY FLOW:   8%|███▍                                        | 110/1430 [09:54<1:43:06,  4.69s/it]

🎯 COPY FLOW:   8%|███▍                                        | 111/1430 [09:58<1:40:13,  4.56s/it]

🎯 COPY FLOW:   8%|███▍                                        | 112/1430 [10:05<1:55:52,  5.28s/it]

🎯 COPY FLOW:   8%|███▍                                        | 113/1430 [10:09<1:50:11,  5.02s/it]

🎯 COPY FLOW:   8%|███▌                                        | 114/1430 [10:14<1:44:56,  4.78s/it]

🎯 COPY FLOW:   8%|███▌                                        | 115/1430 [10:18<1:41:32,  4.63s/it]

🎯 COPY FLOW:   8%|███▌                                        | 116/1430 [10:22<1:38:41,  4.51s/it]

🎯 COPY FLOW:   8%|███▌                                        | 117/1430 [10:26<1:36:18,  4.40s/it]

🎯 COPY FLOW:   8%|███▋                                        | 118/1430 [10:31<1:34:34,  4.32s/it]

🎯 COPY FLOW:   8%|███▋                                        | 119/1430 [10:38<1:53:31,  5.20s/it]

🎯 COPY FLOW:   8%|███▋                                        | 120/1430 [10:42<1:46:40,  4.89s/it]

🎯 COPY FLOW:   8%|███▋                                        | 121/1430 [10:46<1:41:42,  4.66s/it]

🎯 COPY FLOW:   9%|███▊                                        | 122/1430 [10:50<1:38:00,  4.50s/it]

🎯 COPY FLOW:   9%|███▊                                        | 123/1430 [10:54<1:35:16,  4.37s/it]

🎯 COPY FLOW:   9%|███▊                                        | 124/1430 [10:58<1:33:09,  4.28s/it]

🎯 COPY FLOW:   9%|███▊                                        | 125/1430 [11:05<1:48:11,  4.97s/it]

🎯 COPY FLOW:   9%|███▉                                        | 126/1430 [11:09<1:44:09,  4.79s/it]

🎯 COPY FLOW:   9%|███▉                                        | 127/1430 [11:13<1:39:16,  4.57s/it]

🎯 COPY FLOW:   9%|███▉                                        | 128/1430 [11:17<1:35:56,  4.42s/it]

🎯 COPY FLOW:   9%|███▉                                        | 129/1430 [11:21<1:32:56,  4.29s/it]

🎯 COPY FLOW:   9%|████                                        | 130/1430 [11:25<1:30:40,  4.19s/it]

🎯 COPY FLOW:   9%|████                                        | 131/1430 [11:29<1:28:56,  4.11s/it]

🎯 COPY FLOW:   9%|████                                        | 132/1430 [11:36<1:46:55,  4.94s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [13:25<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [12:21<2:39:36,  6.72s/it]

🎯 COPY FLOW:   9%|████                                        | 133/1430 [11:40<1:40:22,  4.64s/it]

📦 Finished: _25_SINC_rk_aiff_2 (50 files)

🎯 COPY FLOW:   9%|████                                        | 134/1430 [11:44<1:36:27,  4.47s/it]

🎯 COPY FLOW:   9%|████▏                                       | 135/1430 [11:48<1:33:28,  4.33s/it]

🎯 COPY FLOW:  10%|████▏                                       | 136/1430 [11:52<1:30:34,  4.20s/it]

🎯 COPY FLOW:  10%|████▏                                       | 137/1430 [11:56<1:28:22,  4.10s/it]

🎯 COPY FLOW:  10%|████▏                                       | 138/1430 [12:00<1:26:53,  4.04s/it]

🎯 COPY FLOW:  10%|████▎                                       | 139/1430 [12:07<1:44:34,  4.86s/it]

🎯 COPY FLOW:  10%|████▎                                       | 140/1430 [12:10<1:38:11,  4.57s/it]

🎯 COPY FLOW:  10%|████▎                                       | 141/1430 [12:14<1:33:39,  4.36s/it]

🎯 COPY FLOW:  10%|████▎                                       | 142/1430 [12:18<1:31:29,  4.26s/it]

🎯 COPY FLOW:  10%|████▍                                       | 143/1430 [12:22<1:28:39,  4.13s/it]

🎯 COPY FLOW:  10%|████▍                                       | 144/1430 [12:26<1:26:19,  4.03s/it]

🎯 COPY FLOW:  10%|████▍                                       | 145/1430 [12:30<1:24:35,  3.95s/it]

🎯 COPY FLOW:  10%|████▍                                       | 146/1430 [12:36<1:41:23,  4.74s/it]

🎯 COPY FLOW:  10%|████▌                                       | 147/1430 [12:40<1:35:20,  4.46s/it]

🎯 COPY FLOW:  10%|████▌                                       | 148/1430 [12:44<1:30:38,  4.24s/it]

🎯 COPY FLOW:  10%|████▌                                       | 149/1430 [12:48<1:27:45,  4.11s/it]

🎯 COPY FLOW:  10%|████▌                                       | 150/1430 [12:51<1:25:10,  3.99s/it]

🎯 COPY FLOW:  11%|████▋                                       | 151/1430 [12:55<1:24:24,  3.96s/it]

🎯 COPY FLOW:  11%|████▋                                       | 152/1430 [12:59<1:22:39,  3.88s/it]

🎯 COPY FLOW:  11%|████▋                                       | 153/1430 [13:04<1:29:00,  4.18s/it]

🎯 COPY FLOW:  11%|████▋                                       | 154/1430 [13:07<1:25:15,  4.01s/it]

🎯 COPY FLOW:  11%|████▊                                       | 155/1430 [13:11<1:22:38,  3.89s/it]

🎯 COPY FLOW:  11%|████▊                                       | 156/1430 [13:15<1:22:50,  3.90s/it]

🎯 COPY FLOW:  11%|████▊                                       | 157/1430 [13:19<1:24:22,  3.98s/it]

🎯 COPY FLOW:  11%|████▊                                       | 158/1430 [13:23<1:22:59,  3.91s/it]

🎯 COPY FLOW:  11%|████▉                                       | 159/1430 [13:27<1:24:01,  3.97s/it]

🎯 COPY FLOW:  11%|████▉                                       | 160/1430 [13:31<1:22:54,  3.92s/it]

🎯 COPY FLOW:  11%|████▉                                       | 161/1430 [13:35<1:24:13,  3.98s/it]

🎯 COPY FLOW:  11%|████▉                                       | 162/1430 [13:38<1:20:29,  3.81s/it]

🎯 COPY FLOW:  11%|█████                                       | 163/1430 [13:42<1:17:03,  3.65s/it]

🎯 COPY FLOW:  11%|█████                                       | 164/1430 [13:45<1:14:40,  3.54s/it]

🎯 COPY FLOW:  12%|█████                                       | 165/1430 [13:48<1:12:13,  3.43s/it]

🎯 COPY FLOW:  12%|█████                                       | 166/1430 [13:51<1:10:18,  3.34s/it]

🎯 COPY FLOW:  12%|█████▏                                      | 167/1430 [13:54<1:08:30,  3.25s/it]

🎯 COPY FLOW:  12%|█████▏                                      | 168/1430 [13:57<1:05:51,  3.13s/it]

🎯 COPY FLOW:  12%|█████▏                                      | 169/1430 [13:59<1:00:35,  2.88s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [15:47<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [14:42<2:39:36,  6.72s/it]

🎯 COPY FLOW:  12%|█████▍                                        | 170/1430 [14:02<55:57,  2.66s/it]

📦 Final: _25_SINC_rk_aiff_3 (37 files)

🎯 COPY FLOW:  12%|█████▎                                      | 171/1430 [14:09<1:25:52,  4.09s/it]

🎯 COPY FLOW:  12%|█████▎                                      | 172/1430 [14:16<1:44:31,  4.99s/it]

🎯 COPY FLOW:  12%|█████▎                                      | 173/1430 [14:23<1:57:01,  5.59s/it]

🎯 COPY FLOW:  12%|█████▎                                      | 174/1430 [14:30<2:04:01,  5.92s/it]

🎯 COPY FLOW:  12%|█████▍                                      | 175/1430 [14:39<2:24:05,  6.89s/it]

🎯 COPY FLOW:  12%|█████▍                                      | 176/1430 [14:45<2:18:45,  6.64s/it]

🎯 COPY FLOW:  12%|█████▍                                      | 177/1430 [14:51<2:14:19,  6.43s/it]

🎯 COPY FLOW:  12%|█████▍                                      | 178/1430 [14:57<2:10:41,  6.26s/it]

🎯 COPY FLOW:  13%|█████▌                                      | 179/1430 [15:05<2:25:20,  6.97s/it]

🎯 COPY FLOW:  13%|█████▌                                      | 180/1430 [15:11<2:17:38,  6.61s/it]

🎯 COPY FLOW:  13%|█████▌                                      | 181/1430 [15:17<2:13:09,  6.40s/it]

🎯 COPY FLOW:  13%|█████▌                                      | 182/1430 [15:23<2:08:38,  6.18s/it]

🎯 COPY FLOW:  13%|█████▋                                      | 183/1430 [15:28<2:05:01,  6.02s/it]

🎯 COPY FLOW:  13%|█████▋                                      | 184/1430 [15:37<2:19:02,  6.70s/it]

🎯 COPY FLOW:  13%|█████▋                                      | 185/1430 [15:42<2:11:54,  6.36s/it]

🎯 COPY FLOW:  13%|█████▋                                      | 186/1430 [15:48<2:07:48,  6.16s/it]

🎯 COPY FLOW:  13%|█████▊                                      | 187/1430 [15:53<2:03:44,  5.97s/it]

🎯 COPY FLOW:  13%|█████▊                                      | 188/1430 [15:59<2:00:34,  5.82s/it]

🎯 COPY FLOW:  13%|█████▊                                      | 189/1430 [16:07<2:15:29,  6.55s/it]

🎯 COPY FLOW:  13%|█████▊                                      | 190/1430 [16:13<2:08:22,  6.21s/it]

🎯 COPY FLOW:  13%|█████▉                                      | 191/1430 [16:18<2:03:14,  5.97s/it]

🎯 COPY FLOW:  13%|█████▉                                      | 192/1430 [16:24<2:00:20,  5.83s/it]

🎯 COPY FLOW:  13%|█████▉                                      | 193/1430 [16:29<1:57:20,  5.69s/it]

🎯 COPY FLOW:  14%|█████▉                                      | 194/1430 [16:37<2:12:38,  6.44s/it]

🎯 COPY FLOW:  14%|██████                                      | 195/1430 [16:42<2:05:56,  6.12s/it]

🎯 COPY FLOW:  14%|██████                                      | 196/1430 [16:48<2:01:11,  5.89s/it]

🎯 COPY FLOW:  14%|██████                                      | 197/1430 [16:53<1:57:51,  5.74s/it]

🎯 COPY FLOW:  14%|██████                                      | 198/1430 [16:59<1:56:29,  5.67s/it]

🎯 COPY FLOW:  14%|██████                                      | 199/1430 [17:07<2:12:24,  6.45s/it]

🎯 COPY FLOW:  14%|██████▏                                     | 200/1430 [17:12<2:05:12,  6.11s/it]

🎯 COPY FLOW:  14%|██████▏                                     | 201/1430 [17:18<1:59:56,  5.86s/it]

🎯 COPY FLOW:  14%|██████▏                                     | 202/1430 [17:23<1:56:12,  5.68s/it]

🎯 COPY FLOW:  14%|██████▏                                     | 203/1430 [17:28<1:53:23,  5.54s/it]

🎯 COPY FLOW:  14%|██████▎                                     | 204/1430 [17:35<1:59:38,  5.86s/it]

🎯 COPY FLOW:  14%|██████▎                                     | 205/1430 [17:40<1:55:41,  5.67s/it]

🎯 COPY FLOW:  14%|██████▎                                     | 206/1430 [17:45<1:52:40,  5.52s/it]

🎯 COPY FLOW:  14%|██████▎                                     | 207/1430 [17:50<1:50:19,  5.41s/it]

🎯 COPY FLOW:  15%|██████▍                                     | 208/1430 [17:55<1:48:42,  5.34s/it]

🎯 COPY FLOW:  15%|██████▍                                     | 209/1430 [18:01<1:48:24,  5.33s/it]

🎯 COPY FLOW:  15%|██████▍                                     | 210/1430 [18:08<2:03:36,  6.08s/it]

🎯 COPY FLOW:  15%|██████▍                                     | 211/1430 [18:14<1:57:42,  5.79s/it]

🎯 COPY FLOW:  15%|██████▌                                     | 212/1430 [18:19<1:53:29,  5.59s/it]

🎯 COPY FLOW:  15%|██████▌                                     | 213/1430 [18:24<1:50:28,  5.45s/it]

🎯 COPY FLOW:  15%|██████▌                                     | 214/1430 [18:29<1:49:01,  5.38s/it]

🎯 COPY FLOW:  15%|██████▌                                     | 215/1430 [18:37<2:03:57,  6.12s/it]

🎯 COPY FLOW:  15%|██████▋                                     | 216/1430 [18:42<1:57:34,  5.81s/it]

🎯 COPY FLOW:  15%|██████▋                                     | 217/1430 [18:47<1:52:56,  5.59s/it]

🎯 COPY FLOW:  15%|██████▋                                     | 218/1430 [18:52<1:49:39,  5.43s/it]

🎯 COPY FLOW:  15%|██████▋                                     | 219/1430 [18:57<1:47:14,  5.31s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [20:51<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [19:46<2:39:36,  6.72s/it]

🎯 COPY FLOW:  15%|██████▊                                     | 220/1430 [19:05<2:04:32,  6.18s/it]

📦 Finished: _25_SINC_rk_flac_1 (50 files)

🎯 COPY FLOW:  15%|██████▊                                     | 221/1430 [19:11<2:00:36,  5.99s/it]

🎯 COPY FLOW:  16%|██████▊                                     | 222/1430 [19:16<1:54:33,  5.69s/it]

🎯 COPY FLOW:  16%|██████▊                                     | 223/1430 [19:21<1:50:26,  5.49s/it]

🎯 COPY FLOW:  16%|██████▉                                     | 224/1430 [19:26<1:47:19,  5.34s/it]

🎯 COPY FLOW:  16%|██████▉                                     | 225/1430 [19:31<1:44:42,  5.21s/it]

🎯 COPY FLOW:  16%|██████▉                                     | 226/1430 [19:39<1:59:53,  5.98s/it]

🎯 COPY FLOW:  16%|██████▉                                     | 227/1430 [19:43<1:53:21,  5.65s/it]

🎯 COPY FLOW:  16%|███████                                     | 228/1430 [19:48<1:48:36,  5.42s/it]

🎯 COPY FLOW:  16%|███████                                     | 229/1430 [19:53<1:45:21,  5.26s/it]

🎯 COPY FLOW:  16%|███████                                     | 230/1430 [19:58<1:43:02,  5.15s/it]

🎯 COPY FLOW:  16%|███████                                     | 231/1430 [20:06<1:58:41,  5.94s/it]

🎯 COPY FLOW:  16%|███████▏                                    | 232/1430 [20:11<1:51:53,  5.60s/it]

🎯 COPY FLOW:  16%|███████▏                                    | 233/1430 [20:16<1:47:00,  5.36s/it]

🎯 COPY FLOW:  16%|███████▏                                    | 234/1430 [20:20<1:43:38,  5.20s/it]

🎯 COPY FLOW:  16%|███████▏                                    | 235/1430 [20:25<1:40:58,  5.07s/it]

🎯 COPY FLOW:  17%|███████▎                                    | 236/1430 [20:30<1:39:13,  4.99s/it]

🎯 COPY FLOW:  17%|███████▎                                    | 237/1430 [20:38<1:55:02,  5.79s/it]

🎯 COPY FLOW:  17%|███████▎                                    | 238/1430 [20:43<1:50:06,  5.54s/it]

🎯 COPY FLOW:  17%|███████▎                                    | 239/1430 [20:47<1:45:35,  5.32s/it]

🎯 COPY FLOW:  17%|███████▍                                    | 240/1430 [20:52<1:42:20,  5.16s/it]

🎯 COPY FLOW:  17%|███████▍                                    | 241/1430 [20:57<1:40:59,  5.10s/it]

🎯 COPY FLOW:  17%|███████▍                                    | 242/1430 [21:05<1:59:03,  6.01s/it]

🎯 COPY FLOW:  17%|███████▍                                    | 243/1430 [21:10<1:51:36,  5.64s/it]

🎯 COPY FLOW:  17%|███████▌                                    | 244/1430 [21:15<1:47:27,  5.44s/it]

🎯 COPY FLOW:  17%|███████▌                                    | 245/1430 [21:20<1:43:24,  5.24s/it]

🎯 COPY FLOW:  17%|███████▌                                    | 246/1430 [21:25<1:40:35,  5.10s/it]

🎯 COPY FLOW:  17%|███████▌                                    | 247/1430 [21:29<1:38:26,  4.99s/it]

🎯 COPY FLOW:  17%|███████▋                                    | 248/1430 [21:37<1:53:27,  5.76s/it]

🎯 COPY FLOW:  17%|███████▋                                    | 249/1430 [21:42<1:47:18,  5.45s/it]

🎯 COPY FLOW:  17%|███████▋                                    | 250/1430 [21:46<1:42:48,  5.23s/it]

🎯 COPY FLOW:  18%|███████▋                                    | 251/1430 [21:51<1:40:34,  5.12s/it]

🎯 COPY FLOW:  18%|███████▊                                    | 252/1430 [21:56<1:37:53,  4.99s/it]

🎯 COPY FLOW:  18%|███████▊                                    | 253/1430 [22:00<1:35:58,  4.89s/it]

🎯 COPY FLOW:  18%|███████▊                                    | 254/1430 [22:08<1:50:44,  5.65s/it]

🎯 COPY FLOW:  18%|███████▊                                    | 255/1430 [22:12<1:44:20,  5.33s/it]

🎯 COPY FLOW:  18%|███████▉                                    | 256/1430 [22:17<1:39:54,  5.11s/it]

🎯 COPY FLOW:  18%|███████▉                                    | 257/1430 [22:22<1:36:43,  4.95s/it]

🎯 COPY FLOW:  18%|███████▉                                    | 258/1430 [22:26<1:35:41,  4.90s/it]

🎯 COPY FLOW:  18%|███████▉                                    | 259/1430 [22:31<1:33:41,  4.80s/it]

🎯 COPY FLOW:  18%|████████                                    | 260/1430 [22:37<1:39:48,  5.12s/it]

🎯 COPY FLOW:  18%|████████                                    | 261/1430 [22:42<1:37:21,  5.00s/it]

🎯 COPY FLOW:  18%|████████                                    | 262/1430 [22:46<1:35:36,  4.91s/it]

🎯 COPY FLOW:  18%|████████                                    | 263/1430 [22:51<1:33:13,  4.79s/it]

🎯 COPY FLOW:  18%|████████                                    | 264/1430 [22:55<1:31:12,  4.69s/it]

🎯 COPY FLOW:  19%|████████▏                                   | 265/1430 [23:00<1:30:54,  4.68s/it]

🎯 COPY FLOW:  19%|████████▏                                   | 266/1430 [23:07<1:45:58,  5.46s/it]

🎯 COPY FLOW:  19%|████████▏                                   | 267/1430 [23:12<1:40:03,  5.16s/it]

🎯 COPY FLOW:  19%|████████▏                                   | 268/1430 [23:16<1:35:50,  4.95s/it]

🎯 COPY FLOW:  19%|████████▎                                   | 269/1430 [23:21<1:32:55,  4.80s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [25:10<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [24:06<2:39:36,  6.72s/it]

🎯 COPY FLOW:  19%|████████▎                                   | 270/1430 [23:25<1:30:43,  4.69s/it]

📦 Finished: _25_SINC_rk_flac_2 (50 files)

🎯 COPY FLOW:  19%|████████▎                                   | 271/1430 [23:29<1:29:06,  4.61s/it]

🎯 COPY FLOW:  19%|████████▎                                   | 272/1430 [23:37<1:45:37,  5.47s/it]

🎯 COPY FLOW:  19%|████████▍                                   | 273/1430 [23:41<1:39:33,  5.16s/it]

🎯 COPY FLOW:  19%|████████▍                                   | 274/1430 [23:46<1:35:10,  4.94s/it]

🎯 COPY FLOW:  19%|████████▍                                   | 275/1430 [23:50<1:32:07,  4.79s/it]

🎯 COPY FLOW:  19%|████████▍                                   | 276/1430 [23:55<1:29:55,  4.68s/it]

🎯 COPY FLOW:  19%|████████▌                                   | 277/1430 [23:59<1:28:07,  4.59s/it]

🎯 COPY FLOW:  19%|████████▌                                   | 278/1430 [24:06<1:43:08,  5.37s/it]

🎯 COPY FLOW:  20%|████████▌                                   | 279/1430 [24:11<1:37:06,  5.06s/it]

🎯 COPY FLOW:  20%|████████▌                                   | 280/1430 [24:15<1:33:02,  4.85s/it]

🎯 COPY FLOW:  20%|████████▋                                   | 281/1430 [24:19<1:30:04,  4.70s/it]

🎯 COPY FLOW:  20%|████████▋                                   | 282/1430 [24:24<1:28:00,  4.60s/it]

🎯 COPY FLOW:  20%|████████▋                                   | 283/1430 [24:28<1:26:25,  4.52s/it]

🎯 COPY FLOW:  20%|████████▋                                   | 284/1430 [24:35<1:42:54,  5.39s/it]

🎯 COPY FLOW:  20%|████████▊                                   | 285/1430 [24:40<1:36:44,  5.07s/it]

🎯 COPY FLOW:  20%|████████▊                                   | 286/1430 [24:44<1:32:26,  4.85s/it]

🎯 COPY FLOW:  20%|████████▊                                   | 287/1430 [24:48<1:29:18,  4.69s/it]

🎯 COPY FLOW:  20%|████████▊                                   | 288/1430 [24:53<1:27:01,  4.57s/it]

🎯 COPY FLOW:  20%|████████▉                                   | 289/1430 [24:57<1:25:24,  4.49s/it]

🎯 COPY FLOW:  20%|████████▉                                   | 290/1430 [25:01<1:24:13,  4.43s/it]

🎯 COPY FLOW:  20%|████████▉                                   | 291/1430 [25:08<1:40:06,  5.27s/it]

🎯 COPY FLOW:  20%|████████▉                                   | 292/1430 [25:13<1:34:17,  4.97s/it]

🎯 COPY FLOW:  20%|█████████                                   | 293/1430 [25:17<1:30:11,  4.76s/it]

🎯 COPY FLOW:  21%|█████████                                   | 294/1430 [25:21<1:26:57,  4.59s/it]

🎯 COPY FLOW:  21%|█████████                                   | 295/1430 [25:25<1:25:00,  4.49s/it]

🎯 COPY FLOW:  21%|█████████                                   | 296/1430 [25:30<1:23:31,  4.42s/it]

🎯 COPY FLOW:  21%|█████████▏                                  | 297/1430 [25:37<1:37:48,  5.18s/it]

🎯 COPY FLOW:  21%|█████████▏                                  | 298/1430 [25:41<1:35:41,  5.07s/it]

🎯 COPY FLOW:  21%|█████████▏                                  | 299/1430 [25:46<1:30:48,  4.82s/it]

🎯 COPY FLOW:  21%|█████████▏                                  | 300/1430 [25:50<1:27:11,  4.63s/it]

🎯 COPY FLOW:  21%|█████████▎                                  | 301/1430 [25:54<1:24:52,  4.51s/it]

🎯 COPY FLOW:  21%|█████████▎                                  | 302/1430 [25:58<1:23:08,  4.42s/it]

🎯 COPY FLOW:  21%|█████████▎                                  | 303/1430 [26:05<1:35:54,  5.11s/it]

🎯 COPY FLOW:  21%|█████████▎                                  | 304/1430 [26:09<1:31:33,  4.88s/it]

🎯 COPY FLOW:  21%|█████████▍                                  | 305/1430 [26:14<1:27:38,  4.67s/it]

🎯 COPY FLOW:  21%|█████████▍                                  | 306/1430 [26:18<1:24:46,  4.53s/it]

🎯 COPY FLOW:  21%|█████████▍                                  | 307/1430 [26:22<1:22:41,  4.42s/it]

🎯 COPY FLOW:  22%|█████████▍                                  | 308/1430 [26:26<1:21:03,  4.33s/it]

🎯 COPY FLOW:  22%|█████████▌                                  | 309/1430 [26:30<1:19:58,  4.28s/it]

🎯 COPY FLOW:  22%|█████████▌                                  | 310/1430 [26:37<1:35:18,  5.11s/it]

🎯 COPY FLOW:  22%|█████████▌                                  | 311/1430 [26:41<1:29:48,  4.82s/it]

🎯 COPY FLOW:  22%|█████████▌                                  | 312/1430 [26:46<1:26:41,  4.65s/it]

🎯 COPY FLOW:  22%|█████████▋                                  | 313/1430 [26:50<1:23:25,  4.48s/it]

🎯 COPY FLOW:  22%|█████████▋                                  | 314/1430 [26:54<1:21:13,  4.37s/it]

🎯 COPY FLOW:  22%|█████████▋                                  | 315/1430 [26:58<1:19:31,  4.28s/it]

🎯 COPY FLOW:  22%|█████████▋                                  | 316/1430 [27:05<1:34:02,  5.07s/it]

🎯 COPY FLOW:  22%|█████████▊                                  | 317/1430 [27:09<1:28:15,  4.76s/it]

🎯 COPY FLOW:  22%|█████████▊                                  | 318/1430 [27:13<1:24:19,  4.55s/it]

🎯 COPY FLOW:  22%|█████████▊                                  | 319/1430 [27:17<1:21:26,  4.40s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [29:07<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [28:02<2:39:36,  6.72s/it]

🎯 COPY FLOW:  22%|█████████▊                                  | 320/1430 [27:21<1:20:15,  4.34s/it]

📦 Finished: _25_SINC_rk_flac_3 (50 files)

🎯 COPY FLOW:  22%|█████████▉                                  | 321/1430 [27:25<1:18:28,  4.25s/it]

🎯 COPY FLOW:  23%|█████████▉                                  | 322/1430 [27:29<1:17:08,  4.18s/it]

🎯 COPY FLOW:  23%|█████████▉                                  | 323/1430 [27:36<1:32:04,  4.99s/it]

🎯 COPY FLOW:  23%|█████████▉                                  | 324/1430 [27:40<1:26:43,  4.70s/it]

🎯 COPY FLOW:  23%|██████████                                  | 325/1430 [27:44<1:22:53,  4.50s/it]

🎯 COPY FLOW:  23%|██████████                                  | 326/1430 [27:48<1:20:10,  4.36s/it]

🎯 COPY FLOW:  23%|██████████                                  | 327/1430 [27:52<1:18:17,  4.26s/it]

🎯 COPY FLOW:  23%|██████████                                  | 328/1430 [27:56<1:17:39,  4.23s/it]

🎯 COPY FLOW:  23%|██████████                                  | 329/1430 [28:00<1:16:21,  4.16s/it]

🎯 COPY FLOW:  23%|██████████▏                                 | 330/1430 [28:07<1:29:49,  4.90s/it]

🎯 COPY FLOW:  23%|██████████▏                                 | 331/1430 [28:11<1:24:40,  4.62s/it]

🎯 COPY FLOW:  23%|██████████▏                                 | 332/1430 [28:15<1:21:04,  4.43s/it]

🎯 COPY FLOW:  23%|██████████▏                                 | 333/1430 [28:19<1:18:19,  4.28s/it]

🎯 COPY FLOW:  23%|██████████▎                                 | 334/1430 [28:23<1:16:15,  4.17s/it]

🎯 COPY FLOW:  23%|██████████▎                                 | 335/1430 [28:27<1:14:47,  4.10s/it]

🎯 COPY FLOW:  23%|██████████▎                                 | 336/1430 [28:31<1:14:30,  4.09s/it]

🎯 COPY FLOW:  24%|██████████▎                                 | 337/1430 [28:37<1:27:55,  4.83s/it]

🎯 COPY FLOW:  24%|██████████▍                                 | 338/1430 [28:41<1:22:33,  4.54s/it]

🎯 COPY FLOW:  24%|██████████▍                                 | 339/1430 [28:45<1:18:42,  4.33s/it]

🎯 COPY FLOW:  24%|██████████▍                                 | 340/1430 [28:49<1:15:55,  4.18s/it]

🎯 COPY FLOW:  24%|██████████▍                                 | 341/1430 [28:53<1:13:54,  4.07s/it]

🎯 COPY FLOW:  24%|██████████▌                                 | 342/1430 [28:57<1:12:34,  4.00s/it]

🎯 COPY FLOW:  24%|██████████▌                                 | 343/1430 [29:00<1:11:34,  3.95s/it]

🎯 COPY FLOW:  24%|██████████▌                                 | 344/1430 [29:07<1:26:21,  4.77s/it]

🎯 COPY FLOW:  24%|██████████▌                                 | 345/1430 [29:11<1:21:08,  4.49s/it]

🎯 COPY FLOW:  24%|██████████▋                                 | 346/1430 [29:15<1:17:16,  4.28s/it]

🎯 COPY FLOW:  24%|██████████▋                                 | 347/1430 [29:19<1:14:41,  4.14s/it]

🎯 COPY FLOW:  24%|██████████▋                                 | 348/1430 [29:22<1:12:55,  4.04s/it]

🎯 COPY FLOW:  24%|██████████▋                                 | 349/1430 [29:26<1:11:29,  3.97s/it]

🎯 COPY FLOW:  24%|██████████▊                                 | 350/1430 [29:30<1:10:20,  3.91s/it]

🎯 COPY FLOW:  25%|██████████▊                                 | 351/1430 [29:37<1:25:28,  4.75s/it]

🎯 COPY FLOW:  25%|██████████▊                                 | 352/1430 [29:40<1:19:59,  4.45s/it]

🎯 COPY FLOW:  25%|██████████▊                                 | 353/1430 [29:44<1:16:13,  4.25s/it]

🎯 COPY FLOW:  25%|██████████▉                                 | 354/1430 [29:48<1:13:26,  4.10s/it]

🎯 COPY FLOW:  25%|██████████▉                                 | 355/1430 [29:52<1:11:31,  3.99s/it]

🎯 COPY FLOW:  25%|██████████▉                                 | 356/1430 [29:55<1:10:09,  3.92s/it]

🎯 COPY FLOW:  25%|██████████▉                                 | 357/1430 [29:59<1:09:07,  3.86s/it]

🎯 COPY FLOW:  25%|███████████                                 | 358/1430 [30:06<1:23:29,  4.67s/it]

🎯 COPY FLOW:  25%|███████████                                 | 359/1430 [30:09<1:18:28,  4.40s/it]

🎯 COPY FLOW:  25%|███████████                                 | 360/1430 [30:13<1:15:51,  4.25s/it]

🎯 COPY FLOW:  25%|███████████                                 | 361/1430 [30:17<1:13:00,  4.10s/it]

🎯 COPY FLOW:  25%|███████████▏                                | 362/1430 [30:21<1:10:49,  3.98s/it]

🎯 COPY FLOW:  25%|███████████▏                                | 363/1430 [30:24<1:09:18,  3.90s/it]

🎯 COPY FLOW:  25%|███████████▏                                | 364/1430 [30:28<1:08:12,  3.84s/it]

🎯 COPY FLOW:  26%|███████████▏                                | 365/1430 [30:35<1:22:31,  4.65s/it]

🎯 COPY FLOW:  26%|███████████▎                                | 366/1430 [30:38<1:16:57,  4.34s/it]

🎯 COPY FLOW:  26%|███████████▎                                | 367/1430 [30:42<1:13:12,  4.13s/it]

🎯 COPY FLOW:  26%|███████████▎                                | 368/1430 [30:46<1:11:23,  4.03s/it]

🎯 COPY FLOW:  26%|███████████▎                                | 369/1430 [30:49<1:09:04,  3.91s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [32:38<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [31:34<2:39:36,  6.72s/it]

🎯 COPY FLOW:  26%|███████████▍                                | 370/1430 [30:53<1:07:29,  3.82s/it]

📦 Finished: _25_SINC_rk_flac_4 (50 files)

🎯 COPY FLOW:  26%|███████████▍                                | 371/1430 [30:57<1:06:15,  3.75s/it]

🎯 COPY FLOW:  26%|███████████▍                                | 372/1430 [31:00<1:05:18,  3.70s/it]

🎯 COPY FLOW:  26%|███████████▍                                | 373/1430 [31:07<1:19:22,  4.51s/it]

🎯 COPY FLOW:  26%|███████████▌                                | 374/1430 [31:10<1:14:20,  4.22s/it]

🎯 COPY FLOW:  26%|███████████▌                                | 375/1430 [31:14<1:10:44,  4.02s/it]

🎯 COPY FLOW:  26%|███████████▌                                | 376/1430 [31:17<1:08:09,  3.88s/it]

🎯 COPY FLOW:  26%|███████████▌                                | 377/1430 [31:21<1:07:16,  3.83s/it]

🎯 COPY FLOW:  26%|███████████▋                                | 378/1430 [31:25<1:05:38,  3.74s/it]

🎯 COPY FLOW:  27%|███████████▋                                | 379/1430 [31:28<1:04:16,  3.67s/it]

🎯 COPY FLOW:  27%|███████████▋                                | 380/1430 [31:31<1:03:10,  3.61s/it]

🎯 COPY FLOW:  27%|███████████▋                                | 381/1430 [31:35<1:02:28,  3.57s/it]

🎯 COPY FLOW:  27%|███████████▊                                | 382/1430 [31:38<1:01:51,  3.54s/it]

🎯 COPY FLOW:  27%|███████████▊                                | 383/1430 [31:42<1:01:22,  3.52s/it]

🎯 COPY FLOW:  27%|███████████▊                                | 384/1430 [31:45<1:00:53,  3.49s/it]

🎯 COPY FLOW:  27%|███████████▊                                | 385/1430 [31:49<1:00:31,  3.48s/it]

🎯 COPY FLOW:  27%|███████████▉                                | 386/1430 [31:52<1:01:09,  3.51s/it]

🎯 COPY FLOW:  27%|███████████▉                                | 387/1430 [31:56<1:00:40,  3.49s/it]

🎯 COPY FLOW:  27%|███████████▉                                | 388/1430 [31:59<1:00:15,  3.47s/it]

🎯 COPY FLOW:  27%|███████████▉                                | 389/1430 [32:05<1:14:14,  4.28s/it]

🎯 COPY FLOW:  27%|████████████                                | 390/1430 [32:09<1:09:43,  4.02s/it]

🎯 COPY FLOW:  27%|████████████                                | 391/1430 [32:12<1:06:19,  3.83s/it]

🎯 COPY FLOW:  27%|████████████                                | 392/1430 [32:16<1:04:48,  3.75s/it]

🎯 COPY FLOW:  27%|████████████                                | 393/1430 [32:19<1:03:00,  3.65s/it]

🎯 COPY FLOW:  28%|████████████                                | 394/1430 [32:23<1:01:42,  3.57s/it]

🎯 COPY FLOW:  28%|████████████▏                               | 395/1430 [32:26<1:00:42,  3.52s/it]

🎯 COPY FLOW:  28%|████████████▋                                 | 396/1430 [32:29<59:51,  3.47s/it]

🎯 COPY FLOW:  28%|████████████▏                               | 397/1430 [32:35<1:12:42,  4.22s/it]

🎯 COPY FLOW:  28%|████████████▏                               | 398/1430 [32:39<1:08:19,  3.97s/it]

🎯 COPY FLOW:  28%|████████████▎                               | 399/1430 [32:42<1:05:07,  3.79s/it]

🎯 COPY FLOW:  28%|████████████▎                               | 400/1430 [32:45<1:02:47,  3.66s/it]

🎯 COPY FLOW:  28%|████████████▎                               | 401/1430 [32:49<1:01:04,  3.56s/it]

🎯 COPY FLOW:  28%|████████████▉                                 | 402/1430 [32:52<59:49,  3.49s/it]

🎯 COPY FLOW:  28%|████████████▉                                 | 403/1430 [32:56<59:51,  3.50s/it]

🎯 COPY FLOW:  28%|████████████▉                                 | 404/1430 [32:59<58:59,  3.45s/it]

🎯 COPY FLOW:  28%|████████████▍                               | 405/1430 [33:05<1:11:31,  4.19s/it]

🎯 COPY FLOW:  28%|████████████▍                               | 406/1430 [33:08<1:06:57,  3.92s/it]

🎯 COPY FLOW:  28%|████████████▌                               | 407/1430 [33:11<1:03:49,  3.74s/it]

🎯 COPY FLOW:  29%|████████████▌                               | 408/1430 [33:15<1:01:22,  3.60s/it]

🎯 COPY FLOW:  29%|█████████████▏                                | 409/1430 [33:18<59:35,  3.50s/it]

🎯 COPY FLOW:  29%|█████████████▏                                | 410/1430 [33:21<58:27,  3.44s/it]

🎯 COPY FLOW:  29%|█████████████▏                                | 411/1430 [33:25<58:18,  3.43s/it]

🎯 COPY FLOW:  29%|█████████████▎                                | 412/1430 [33:28<57:27,  3.39s/it]

🎯 COPY FLOW:  29%|█████████████▎                                | 413/1430 [33:31<56:45,  3.35s/it]

🎯 COPY FLOW:  29%|████████████▋                               | 414/1430 [33:36<1:06:03,  3.90s/it]

🎯 COPY FLOW:  29%|████████████▊                               | 415/1430 [33:40<1:02:37,  3.70s/it]

🎯 COPY FLOW:  29%|████████████▊                               | 416/1430 [33:43<1:00:16,  3.57s/it]

🎯 COPY FLOW:  29%|█████████████▍                                | 417/1430 [33:46<58:41,  3.48s/it]

🎯 COPY FLOW:  29%|█████████████▍                                | 418/1430 [33:49<57:29,  3.41s/it]

🎯 COPY FLOW:  29%|█████████████▍                                | 419/1430 [33:53<56:39,  3.36s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [35:41<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [34:37<2:39:36,  6.72s/it]

🎯 COPY FLOW:  29%|█████████████▌                                | 420/1430 [33:56<55:56,  3.32s/it]

📦 Finished: _25_SINC_rk_flac_5 (50 files)

🎯 COPY FLOW:  29%|█████████████▌                                | 421/1430 [33:59<55:28,  3.30s/it]

🎯 COPY FLOW:  30%|████████████▉                               | 422/1430 [34:05<1:10:21,  4.19s/it]

🎯 COPY FLOW:  30%|█████████████                               | 423/1430 [34:09<1:05:22,  3.90s/it]

🎯 COPY FLOW:  30%|█████████████                               | 424/1430 [34:12<1:01:49,  3.69s/it]

🎯 COPY FLOW:  30%|█████████████▋                                | 425/1430 [34:15<59:19,  3.54s/it]

🎯 COPY FLOW:  30%|█████████████▋                                | 426/1430 [34:18<57:27,  3.43s/it]

🎯 COPY FLOW:  30%|█████████████▋                                | 427/1430 [34:21<56:18,  3.37s/it]

🎯 COPY FLOW:  30%|█████████████▊                                | 428/1430 [34:25<55:18,  3.31s/it]

🎯 COPY FLOW:  30%|█████████████▊                                | 429/1430 [34:28<54:32,  3.27s/it]

🎯 COPY FLOW:  30%|█████████████▊                                | 430/1430 [34:31<54:03,  3.24s/it]

🎯 COPY FLOW:  30%|█████████████▎                              | 431/1430 [34:37<1:07:07,  4.03s/it]

🎯 COPY FLOW:  30%|█████████████▎                              | 432/1430 [34:40<1:02:41,  3.77s/it]

🎯 COPY FLOW:  30%|█████████████▉                                | 433/1430 [34:43<59:31,  3.58s/it]

🎯 COPY FLOW:  30%|█████████████▉                                | 434/1430 [34:46<57:57,  3.49s/it]

🎯 COPY FLOW:  30%|█████████████▉                                | 435/1430 [34:50<56:15,  3.39s/it]

🎯 COPY FLOW:  30%|██████████████                                | 436/1430 [34:53<55:06,  3.33s/it]

🎯 COPY FLOW:  31%|██████████████                                | 437/1430 [34:56<54:16,  3.28s/it]

🎯 COPY FLOW:  31%|██████████████                                | 438/1430 [34:59<53:39,  3.25s/it]

🎯 COPY FLOW:  31%|█████████████▌                              | 439/1430 [35:05<1:06:55,  4.05s/it]

🎯 COPY FLOW:  31%|█████████████▌                              | 440/1430 [35:08<1:02:21,  3.78s/it]

🎯 COPY FLOW:  31%|██████████████▏                               | 441/1430 [35:11<59:01,  3.58s/it]

🎯 COPY FLOW:  31%|██████████████▏                               | 442/1430 [35:14<56:44,  3.45s/it]

🎯 COPY FLOW:  31%|██████████████▎                               | 443/1430 [35:18<55:52,  3.40s/it]

🎯 COPY FLOW:  31%|██████████████▎                               | 444/1430 [35:21<54:32,  3.32s/it]

🎯 COPY FLOW:  31%|██████████████▎                               | 445/1430 [35:24<53:32,  3.26s/it]

🎯 COPY FLOW:  31%|██████████████▎                               | 446/1430 [35:27<52:49,  3.22s/it]

🎯 COPY FLOW:  31%|██████████████▍                               | 447/1430 [35:30<52:15,  3.19s/it]

🎯 COPY FLOW:  31%|█████████████▊                              | 448/1430 [35:36<1:05:12,  3.98s/it]

🎯 COPY FLOW:  31%|█████████████▊                              | 449/1430 [35:39<1:00:40,  3.71s/it]

🎯 COPY FLOW:  31%|██████████████▍                               | 450/1430 [35:42<57:34,  3.52s/it]

🎯 COPY FLOW:  32%|██████████████▌                               | 451/1430 [35:45<55:12,  3.38s/it]

🎯 COPY FLOW:  32%|██████████████▌                               | 452/1430 [35:48<53:38,  3.29s/it]

🎯 COPY FLOW:  32%|██████████████▌                               | 453/1430 [35:52<53:13,  3.27s/it]

🎯 COPY FLOW:  32%|██████████████▌                               | 454/1430 [35:55<52:02,  3.20s/it]

🎯 COPY FLOW:  32%|██████████████▋                               | 455/1430 [35:58<51:21,  3.16s/it]

🎯 COPY FLOW:  32%|██████████████▋                               | 456/1430 [36:01<50:46,  3.13s/it]

🎯 COPY FLOW:  32%|██████████████                              | 457/1430 [36:06<1:03:22,  3.91s/it]

🎯 COPY FLOW:  32%|██████████████▋                               | 458/1430 [36:10<59:10,  3.65s/it]

🎯 COPY FLOW:  32%|██████████████▊                               | 459/1430 [36:13<56:12,  3.47s/it]

🎯 COPY FLOW:  32%|██████████████▊                               | 460/1430 [36:16<53:59,  3.34s/it]

🎯 COPY FLOW:  32%|██████████████▊                               | 461/1430 [36:19<52:37,  3.26s/it]

🎯 COPY FLOW:  32%|██████████████▊                               | 462/1430 [36:22<51:27,  3.19s/it]

🎯 COPY FLOW:  32%|██████████████▉                               | 463/1430 [36:25<50:40,  3.14s/it]

🎯 COPY FLOW:  32%|██████████████▉                               | 464/1430 [36:28<51:00,  3.17s/it]

🎯 COPY FLOW:  33%|██████████████▉                               | 465/1430 [36:31<50:19,  3.13s/it]

🎯 COPY FLOW:  33%|██████████████▎                             | 466/1430 [36:37<1:03:51,  3.97s/it]

🎯 COPY FLOW:  33%|███████████████                               | 467/1430 [36:40<59:12,  3.69s/it]

🎯 COPY FLOW:  33%|███████████████                               | 468/1430 [36:43<55:46,  3.48s/it]

🎯 COPY FLOW:  33%|███████████████                               | 469/1430 [36:46<53:23,  3.33s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [38:34<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [37:30<2:39:36,  6.72s/it]

🎯 COPY FLOW:  33%|███████████████                               | 470/1430 [36:49<51:46,  3.24s/it]

📦 Finished: _25_SINC_rk_flac_6 (50 files)

🎯 COPY FLOW:  33%|███████████████▏                              | 471/1430 [36:52<50:36,  3.17s/it]

🎯 COPY FLOW:  33%|███████████████▏                              | 472/1430 [36:55<49:46,  3.12s/it]

🎯 COPY FLOW:  33%|███████████████▏                              | 473/1430 [36:58<49:09,  3.08s/it]

🎯 COPY FLOW:  33%|███████████████▏                              | 474/1430 [37:01<49:25,  3.10s/it]

🎯 COPY FLOW:  33%|██████████████▌                             | 475/1430 [37:07<1:02:08,  3.90s/it]

🎯 COPY FLOW:  33%|███████████████▎                              | 476/1430 [37:10<57:37,  3.62s/it]

🎯 COPY FLOW:  33%|███████████████▎                              | 477/1430 [37:13<54:27,  3.43s/it]

🎯 COPY FLOW:  33%|███████████████▍                              | 478/1430 [37:16<52:15,  3.29s/it]

🎯 COPY FLOW:  33%|███████████████▍                              | 479/1430 [37:19<50:37,  3.19s/it]

🎯 COPY FLOW:  34%|███████████████▍                              | 480/1430 [37:22<49:20,  3.12s/it]

🎯 COPY FLOW:  34%|███████████████▍                              | 481/1430 [37:25<48:31,  3.07s/it]

🎯 COPY FLOW:  34%|███████████████▌                              | 482/1430 [37:28<47:50,  3.03s/it]

🎯 COPY FLOW:  34%|███████████████▌                              | 483/1430 [37:31<47:24,  3.00s/it]

🎯 COPY FLOW:  34%|██████████████▉                             | 484/1430 [37:36<1:01:06,  3.88s/it]

🎯 COPY FLOW:  34%|███████████████▌                              | 485/1430 [37:39<56:26,  3.58s/it]

🎯 COPY FLOW:  34%|███████████████▋                              | 486/1430 [37:42<53:13,  3.38s/it]

🎯 COPY FLOW:  34%|███████████████▋                              | 487/1430 [37:45<50:53,  3.24s/it]

🎯 COPY FLOW:  34%|███████████████▋                              | 488/1430 [37:48<49:15,  3.14s/it]

🎯 COPY FLOW:  34%|███████████████▋                              | 489/1430 [37:51<47:55,  3.06s/it]

🎯 COPY FLOW:  34%|███████████████▊                              | 490/1430 [37:54<47:08,  3.01s/it]

🎯 COPY FLOW:  34%|███████████████▊                              | 491/1430 [37:57<46:31,  2.97s/it]

🎯 COPY FLOW:  34%|███████████████▊                              | 492/1430 [38:00<45:58,  2.94s/it]

🎯 COPY FLOW:  34%|███████████████▊                              | 493/1430 [38:05<59:41,  3.82s/it]

🎯 COPY FLOW:  35%|███████████████▉                              | 494/1430 [38:08<55:21,  3.55s/it]

🎯 COPY FLOW:  35%|███████████████▉                              | 495/1430 [38:11<52:11,  3.35s/it]

🎯 COPY FLOW:  35%|███████████████▉                              | 496/1430 [38:14<49:54,  3.21s/it]

🎯 COPY FLOW:  35%|███████████████▉                              | 497/1430 [38:17<48:20,  3.11s/it]

🎯 COPY FLOW:  35%|████████████████                              | 498/1430 [38:20<47:15,  3.04s/it]

🎯 COPY FLOW:  35%|████████████████                              | 499/1430 [38:23<46:22,  2.99s/it]

🎯 COPY FLOW:  35%|████████████████                              | 500/1430 [38:26<45:36,  2.94s/it]

🎯 COPY FLOW:  35%|████████████████                              | 501/1430 [38:28<45:10,  2.92s/it]

🎯 COPY FLOW:  35%|████████████████▏                             | 502/1430 [38:31<44:44,  2.89s/it]

🎯 COPY FLOW:  35%|████████████████▏                             | 503/1430 [38:36<51:44,  3.35s/it]

🎯 COPY FLOW:  35%|████████████████▏                             | 504/1430 [38:39<49:24,  3.20s/it]

🎯 COPY FLOW:  35%|████████████████▏                             | 505/1430 [38:42<48:28,  3.14s/it]

🎯 COPY FLOW:  35%|████████████████▎                             | 506/1430 [38:44<47:02,  3.05s/it]

🎯 COPY FLOW:  35%|████████████████▎                             | 507/1430 [38:47<46:01,  2.99s/it]

🎯 COPY FLOW:  36%|████████████████▎                             | 508/1430 [38:50<45:13,  2.94s/it]

🎯 COPY FLOW:  36%|████████████████▎                             | 509/1430 [38:53<44:34,  2.90s/it]

🎯 COPY FLOW:  36%|████████████████▍                             | 510/1430 [38:56<44:09,  2.88s/it]

🎯 COPY FLOW:  36%|████████████████▍                             | 511/1430 [38:59<43:43,  2.85s/it]

🎯 COPY FLOW:  36%|████████████████▍                             | 512/1430 [39:01<43:25,  2.84s/it]

🎯 COPY FLOW:  36%|████████████████▌                             | 513/1430 [39:05<47:56,  3.14s/it]

🎯 COPY FLOW:  36%|████████████████▌                             | 514/1430 [39:08<46:19,  3.03s/it]

🎯 COPY FLOW:  36%|████████████████▌                             | 515/1430 [39:11<45:14,  2.97s/it]

🎯 COPY FLOW:  36%|████████████████▌                             | 516/1430 [39:14<44:26,  2.92s/it]

🎯 COPY FLOW:  36%|████████████████▋                             | 517/1430 [39:17<44:30,  2.92s/it]

🎯 COPY FLOW:  36%|████████████████▋                             | 518/1430 [39:19<43:46,  2.88s/it]

🎯 COPY FLOW:  36%|████████████████▋                             | 519/1430 [39:22<43:03,  2.84s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [41:10<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [40:06<2:39:36,  6.72s/it]

🎯 COPY FLOW:  36%|████████████████▋                             | 520/1430 [39:25<42:39,  2.81s/it]

📦 Finished: _25_SINC_rk_flac_7 (50 files)

🎯 COPY FLOW:  36%|████████████████▊                             | 521/1430 [39:28<42:23,  2.80s/it]

🎯 COPY FLOW:  37%|████████████████▊                             | 522/1430 [39:30<42:08,  2.78s/it]

🎯 COPY FLOW:  37%|████████████████▊                             | 523/1430 [39:36<54:18,  3.59s/it]

🎯 COPY FLOW:  37%|████████████████▊                             | 524/1430 [39:39<50:31,  3.35s/it]

🎯 COPY FLOW:  37%|████████████████▉                             | 525/1430 [39:41<47:51,  3.17s/it]

🎯 COPY FLOW:  37%|████████████████▉                             | 526/1430 [39:44<46:02,  3.06s/it]

🎯 COPY FLOW:  37%|████████████████▉                             | 527/1430 [39:47<44:43,  2.97s/it]

🎯 COPY FLOW:  37%|████████████████▉                             | 528/1430 [39:50<43:44,  2.91s/it]

🎯 COPY FLOW:  37%|█████████████████                             | 529/1430 [39:53<43:45,  2.91s/it]

🎯 COPY FLOW:  37%|█████████████████                             | 530/1430 [39:55<42:52,  2.86s/it]

🎯 COPY FLOW:  37%|█████████████████                             | 531/1430 [39:58<42:09,  2.81s/it]

🎯 COPY FLOW:  37%|█████████████████                             | 532/1430 [40:01<41:46,  2.79s/it]

🎯 COPY FLOW:  37%|█████████████████▏                            | 533/1430 [40:06<53:31,  3.58s/it]

🎯 COPY FLOW:  37%|█████████████████▏                            | 534/1430 [40:09<49:42,  3.33s/it]

🎯 COPY FLOW:  37%|█████████████████▏                            | 535/1430 [40:12<46:58,  3.15s/it]

🎯 COPY FLOW:  37%|█████████████████▏                            | 536/1430 [40:14<45:03,  3.02s/it]

🎯 COPY FLOW:  38%|█████████████████▎                            | 537/1430 [40:17<43:37,  2.93s/it]

🎯 COPY FLOW:  38%|█████████████████▎                            | 538/1430 [40:20<42:33,  2.86s/it]

🎯 COPY FLOW:  38%|█████████████████▎                            | 539/1430 [40:22<41:45,  2.81s/it]

🎯 COPY FLOW:  38%|█████████████████▎                            | 540/1430 [40:25<41:54,  2.83s/it]

🎯 COPY FLOW:  38%|█████████████████▍                            | 541/1430 [40:28<41:15,  2.78s/it]

🎯 COPY FLOW:  38%|█████████████████▍                            | 542/1430 [40:31<40:53,  2.76s/it]

🎯 COPY FLOW:  38%|█████████████████▍                            | 543/1430 [40:36<52:21,  3.54s/it]

🎯 COPY FLOW:  38%|█████████████████▍                            | 544/1430 [40:39<48:36,  3.29s/it]

🎯 COPY FLOW:  38%|█████████████████▌                            | 545/1430 [40:41<45:50,  3.11s/it]

🎯 COPY FLOW:  38%|█████████████████▌                            | 546/1430 [40:44<44:00,  2.99s/it]

🎯 COPY FLOW:  38%|█████████████████▌                            | 547/1430 [40:47<42:42,  2.90s/it]

🎯 COPY FLOW:  38%|█████████████████▋                            | 548/1430 [40:50<41:46,  2.84s/it]

🎯 COPY FLOW:  38%|█████████████████▋                            | 549/1430 [40:52<41:01,  2.79s/it]

🎯 COPY FLOW:  38%|█████████████████▋                            | 550/1430 [40:55<40:32,  2.76s/it]

🎯 COPY FLOW:  39%|█████████████████▋                            | 551/1430 [40:58<40:09,  2.74s/it]

🎯 COPY FLOW:  39%|█████████████████▊                            | 552/1430 [41:00<40:29,  2.77s/it]

🎯 COPY FLOW:  39%|█████████████████▊                            | 553/1430 [41:06<52:00,  3.56s/it]

🎯 COPY FLOW:  39%|█████████████████▊                            | 554/1430 [41:09<48:00,  3.29s/it]

🎯 COPY FLOW:  39%|█████████████████▊                            | 555/1430 [41:11<45:09,  3.10s/it]

🎯 COPY FLOW:  39%|█████████████████▉                            | 556/1430 [41:14<43:11,  2.97s/it]

🎯 COPY FLOW:  39%|█████████████████▉                            | 557/1430 [41:17<41:47,  2.87s/it]

🎯 COPY FLOW:  39%|█████████████████▉                            | 558/1430 [41:19<40:48,  2.81s/it]

🎯 COPY FLOW:  39%|█████████████████▉                            | 559/1430 [41:22<40:00,  2.76s/it]

🎯 COPY FLOW:  39%|██████████████████                            | 560/1430 [41:24<39:24,  2.72s/it]

🎯 COPY FLOW:  39%|██████████████████                            | 561/1430 [41:27<39:01,  2.69s/it]

🎯 COPY FLOW:  39%|██████████████████                            | 562/1430 [41:30<38:45,  2.68s/it]

🎯 COPY FLOW:  39%|██████████████████                            | 563/1430 [41:35<51:38,  3.57s/it]

🎯 COPY FLOW:  39%|██████████████████▏                           | 564/1430 [41:38<47:27,  3.29s/it]

🎯 COPY FLOW:  40%|██████████████████▏                           | 565/1430 [41:41<44:35,  3.09s/it]

🎯 COPY FLOW:  40%|██████████████████▏                           | 566/1430 [41:43<42:36,  2.96s/it]

🎯 COPY FLOW:  40%|██████████████████▏                           | 567/1430 [41:46<41:09,  2.86s/it]

🎯 COPY FLOW:  40%|██████████████████▎                           | 568/1430 [41:49<40:06,  2.79s/it]

🎯 COPY FLOW:  40%|██████████████████▎                           | 569/1430 [41:51<39:27,  2.75s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [43:39<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [42:35<2:39:36,  6.72s/it]

🎯 COPY FLOW:  40%|██████████████████▎                           | 570/1430 [41:54<38:49,  2.71s/it]

📦 Finished: _25_SINC_rk_flac_8 (50 files)

🎯 COPY FLOW:  40%|██████████████████▎                           | 571/1430 [41:56<38:24,  2.68s/it]

🎯 COPY FLOW:  40%|██████████████████▍                           | 572/1430 [41:59<38:05,  2.66s/it]

🎯 COPY FLOW:  40%|██████████████████▍                           | 573/1430 [42:02<37:52,  2.65s/it]

🎯 COPY FLOW:  40%|██████████████████▍                           | 574/1430 [42:04<37:46,  2.65s/it]

🎯 COPY FLOW:  40%|██████████████████▍                           | 575/1430 [42:07<37:34,  2.64s/it]

🎯 COPY FLOW:  40%|██████████████████▌                           | 576/1430 [42:10<38:05,  2.68s/it]

🎯 COPY FLOW:  40%|██████████████████▌                           | 577/1430 [42:12<37:46,  2.66s/it]

🎯 COPY FLOW:  40%|██████████████████▌                           | 578/1430 [42:15<37:31,  2.64s/it]

🎯 COPY FLOW:  40%|██████████████████▋                           | 579/1430 [42:18<37:23,  2.64s/it]

🎯 COPY FLOW:  41%|██████████████████▋                           | 580/1430 [42:20<37:21,  2.64s/it]

🎯 COPY FLOW:  41%|██████████████████▋                           | 581/1430 [42:23<37:15,  2.63s/it]

🎯 COPY FLOW:  41%|██████████████████▋                           | 582/1430 [42:25<37:06,  2.63s/it]

🎯 COPY FLOW:  41%|██████████████████▊                           | 583/1430 [42:28<36:54,  2.61s/it]

🎯 COPY FLOW:  41%|██████████████████▊                           | 584/1430 [42:31<36:44,  2.61s/it]

🎯 COPY FLOW:  41%|██████████████████▊                           | 585/1430 [42:36<48:18,  3.43s/it]

🎯 COPY FLOW:  41%|██████████████████▊                           | 586/1430 [42:39<44:43,  3.18s/it]

🎯 COPY FLOW:  41%|██████████████████▉                           | 587/1430 [42:41<42:05,  3.00s/it]

🎯 COPY FLOW:  41%|██████████████████▉                           | 588/1430 [42:44<40:55,  2.92s/it]

🎯 COPY FLOW:  41%|██████████████████▉                           | 589/1430 [42:46<39:28,  2.82s/it]

🎯 COPY FLOW:  41%|██████████████████▉                           | 590/1430 [42:49<38:27,  2.75s/it]

🎯 COPY FLOW:  41%|███████████████████                           | 591/1430 [42:52<37:39,  2.69s/it]

🎯 COPY FLOW:  41%|███████████████████                           | 592/1430 [42:54<37:03,  2.65s/it]

🎯 COPY FLOW:  41%|███████████████████                           | 593/1430 [42:57<36:38,  2.63s/it]

🎯 COPY FLOW:  42%|███████████████████                           | 594/1430 [42:59<36:24,  2.61s/it]

🎯 COPY FLOW:  42%|███████████████████▏                          | 595/1430 [43:05<47:23,  3.41s/it]

🎯 COPY FLOW:  42%|███████████████████▏                          | 596/1430 [43:07<43:35,  3.14s/it]

🎯 COPY FLOW:  42%|███████████████████▏                          | 597/1430 [43:10<41:08,  2.96s/it]

🎯 COPY FLOW:  42%|███████████████████▏                          | 598/1430 [43:12<39:21,  2.84s/it]

🎯 COPY FLOW:  42%|███████████████████▎                          | 599/1430 [43:15<38:10,  2.76s/it]

🎯 COPY FLOW:  42%|███████████████████▎                          | 600/1430 [43:17<37:14,  2.69s/it]

🎯 COPY FLOW:  42%|███████████████████▎                          | 601/1430 [43:20<37:19,  2.70s/it]

🎯 COPY FLOW:  42%|███████████████████▎                          | 602/1430 [43:23<36:39,  2.66s/it]

🎯 COPY FLOW:  42%|███████████████████▍                          | 603/1430 [43:25<36:04,  2.62s/it]

🎯 COPY FLOW:  42%|███████████████████▍                          | 604/1430 [43:28<35:43,  2.59s/it]

🎯 COPY FLOW:  42%|███████████████████▍                          | 605/1430 [43:30<35:29,  2.58s/it]

🎯 COPY FLOW:  42%|███████████████████▍                          | 606/1430 [43:35<46:39,  3.40s/it]

🎯 COPY FLOW:  42%|███████████████████▌                          | 607/1430 [43:38<43:04,  3.14s/it]

🎯 COPY FLOW:  43%|███████████████████▌                          | 608/1430 [43:41<41:06,  3.00s/it]

🎯 COPY FLOW:  43%|███████████████████▌                          | 609/1430 [43:43<39:03,  2.86s/it]

🎯 COPY FLOW:  43%|███████████████████▌                          | 610/1430 [43:46<37:40,  2.76s/it]

🎯 COPY FLOW:  43%|███████████████████▋                          | 611/1430 [43:48<36:40,  2.69s/it]

🎯 COPY FLOW:  43%|███████████████████▋                          | 612/1430 [43:51<36:59,  2.71s/it]

🎯 COPY FLOW:  43%|███████████████████▋                          | 613/1430 [43:54<36:51,  2.71s/it]

🎯 COPY FLOW:  43%|███████████████████▊                          | 614/1430 [43:56<36:02,  2.65s/it]

🎯 COPY FLOW:  43%|███████████████████▊                          | 615/1430 [43:59<35:25,  2.61s/it]

🎯 COPY FLOW:  43%|███████████████████▊                          | 616/1430 [44:01<34:57,  2.58s/it]

🎯 COPY FLOW:  43%|███████████████████▊                          | 617/1430 [44:06<44:09,  3.26s/it]

🎯 COPY FLOW:  43%|███████████████████▉                          | 618/1430 [44:09<40:58,  3.03s/it]

🎯 COPY FLOW:  43%|███████████████████▉                          | 619/1430 [44:11<38:47,  2.87s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [45:59<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [44:54<2:39:36,  6.72s/it]

🎯 COPY FLOW:  43%|███████████████████▉                          | 620/1430 [44:14<37:15,  2.76s/it]

📦 Finished: _25_SINC_rk_flac_9 (50 files)

🎯 COPY FLOW:  43%|███████████████████▉                          | 621/1430 [44:16<36:07,  2.68s/it]

🎯 COPY FLOW:  43%|████████████████████                          | 622/1430 [44:19<35:20,  2.62s/it]

🎯 COPY FLOW:  44%|████████████████████                          | 623/1430 [44:21<34:43,  2.58s/it]

🎯 COPY FLOW:  44%|████████████████████                          | 624/1430 [44:24<34:21,  2.56s/it]

🎯 COPY FLOW:  44%|████████████████████                          | 625/1430 [44:26<34:04,  2.54s/it]

🎯 COPY FLOW:  44%|████████████████████▏                         | 626/1430 [44:29<34:31,  2.58s/it]

🎯 COPY FLOW:  44%|████████████████████▏                         | 627/1430 [44:31<34:09,  2.55s/it]

🎯 COPY FLOW:  44%|████████████████████▏                         | 628/1430 [44:37<45:23,  3.40s/it]

🎯 COPY FLOW:  44%|████████████████████▏                         | 629/1430 [44:39<41:36,  3.12s/it]

🎯 COPY FLOW:  44%|████████████████████▎                         | 630/1430 [44:41<38:54,  2.92s/it]

🎯 COPY FLOW:  44%|████████████████████▎                         | 631/1430 [44:44<37:05,  2.79s/it]

🎯 COPY FLOW:  44%|████████████████████▎                         | 632/1430 [44:46<35:45,  2.69s/it]

🎯 COPY FLOW:  44%|████████████████████▎                         | 633/1430 [44:49<34:49,  2.62s/it]

🎯 COPY FLOW:  44%|████████████████████▍                         | 634/1430 [44:51<34:11,  2.58s/it]

🎯 COPY FLOW:  44%|████████████████████▍                         | 635/1430 [44:54<33:40,  2.54s/it]

🎯 COPY FLOW:  44%|████████████████████▍                         | 636/1430 [44:56<33:16,  2.51s/it]

🎯 COPY FLOW:  45%|████████████████████▍                         | 637/1430 [44:59<32:57,  2.49s/it]

🎯 COPY FLOW:  45%|████████████████████▌                         | 638/1430 [45:01<32:44,  2.48s/it]

🎯 COPY FLOW:  45%|████████████████████▌                         | 639/1430 [45:07<44:38,  3.39s/it]

🎯 COPY FLOW:  45%|████████████████████▌                         | 640/1430 [45:09<40:54,  3.11s/it]

🎯 COPY FLOW:  45%|████████████████████▌                         | 641/1430 [45:12<38:14,  2.91s/it]

🎯 COPY FLOW:  45%|████████████████████▋                         | 642/1430 [45:14<36:21,  2.77s/it]

🎯 COPY FLOW:  45%|████████████████████▋                         | 643/1430 [45:16<35:01,  2.67s/it]

🎯 COPY FLOW:  45%|████████████████████▋                         | 644/1430 [45:19<34:02,  2.60s/it]

🎯 COPY FLOW:  45%|████████████████████▋                         | 645/1430 [45:21<33:15,  2.54s/it]

🎯 COPY FLOW:  45%|████████████████████▊                         | 646/1430 [45:24<32:46,  2.51s/it]

🎯 COPY FLOW:  45%|████████████████████▊                         | 647/1430 [45:26<32:24,  2.48s/it]

🎯 COPY FLOW:  45%|████████████████████▊                         | 648/1430 [45:29<32:07,  2.46s/it]

🎯 COPY FLOW:  45%|████████████████████▉                         | 649/1430 [45:31<31:49,  2.44s/it]

🎯 COPY FLOW:  45%|████████████████████▉                         | 650/1430 [45:36<43:19,  3.33s/it]

🎯 COPY FLOW:  46%|████████████████████▉                         | 651/1430 [45:39<39:41,  3.06s/it]

🎯 COPY FLOW:  46%|████████████████████▉                         | 652/1430 [45:41<37:05,  2.86s/it]

🎯 COPY FLOW:  46%|█████████████████████                         | 653/1430 [45:44<35:21,  2.73s/it]

🎯 COPY FLOW:  46%|█████████████████████                         | 654/1430 [45:46<34:04,  2.64s/it]

🎯 COPY FLOW:  46%|█████████████████████                         | 655/1430 [45:48<33:09,  2.57s/it]

🎯 COPY FLOW:  46%|█████████████████████                         | 656/1430 [45:51<32:30,  2.52s/it]

🎯 COPY FLOW:  46%|█████████████████████▏                        | 657/1430 [45:53<32:01,  2.49s/it]

🎯 COPY FLOW:  46%|█████████████████████▏                        | 658/1430 [45:56<31:40,  2.46s/it]

🎯 COPY FLOW:  46%|█████████████████████▏                        | 659/1430 [45:58<31:24,  2.44s/it]

🎯 COPY FLOW:  46%|█████████████████████▏                        | 660/1430 [46:00<31:09,  2.43s/it]

🎯 COPY FLOW:  46%|█████████████████████▎                        | 661/1430 [46:06<42:09,  3.29s/it]

🎯 COPY FLOW:  46%|█████████████████████▎                        | 662/1430 [46:08<39:21,  3.08s/it]

🎯 COPY FLOW:  46%|█████████████████████▎                        | 663/1430 [46:11<36:40,  2.87s/it]

🎯 COPY FLOW:  46%|█████████████████████▎                        | 664/1430 [46:13<34:49,  2.73s/it]

🎯 COPY FLOW:  47%|█████████████████████▍                        | 665/1430 [46:15<33:28,  2.63s/it]

🎯 COPY FLOW:  47%|█████████████████████▍                        | 666/1430 [46:18<32:31,  2.55s/it]

🎯 COPY FLOW:  47%|█████████████████████▍                        | 667/1430 [46:20<31:49,  2.50s/it]

🎯 COPY FLOW:  47%|█████████████████████▍                        | 668/1430 [46:23<31:17,  2.46s/it]

🎯 COPY FLOW:  47%|█████████████████████▌                        | 669/1430 [46:25<30:55,  2.44s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [48:13<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [47:08<2:39:36,  6.72s/it]

🎯 COPY FLOW:  47%|█████████████████████▌                        | 670/1430 [46:27<30:30,  2.41s/it]

📦 Finished: _25_SINC_rk_flac_10 (50 files)

🎯 COPY FLOW:  47%|█████████████████████▌                        | 671/1430 [46:30<30:21,  2.40s/it]

🎯 COPY FLOW:  47%|█████████████████████▌                        | 672/1430 [46:35<40:55,  3.24s/it]

🎯 COPY FLOW:  47%|█████████████████████▋                        | 673/1430 [46:37<37:25,  2.97s/it]

🎯 COPY FLOW:  47%|█████████████████████▋                        | 674/1430 [46:40<35:10,  2.79s/it]

🎯 COPY FLOW:  47%|█████████████████████▋                        | 675/1430 [46:42<34:08,  2.71s/it]

🎯 COPY FLOW:  47%|█████████████████████▋                        | 676/1430 [46:45<32:43,  2.60s/it]

🎯 COPY FLOW:  47%|█████████████████████▊                        | 677/1430 [46:47<31:46,  2.53s/it]

🎯 COPY FLOW:  47%|█████████████████████▊                        | 678/1430 [46:49<31:04,  2.48s/it]

🎯 COPY FLOW:  47%|█████████████████████▊                        | 679/1430 [46:52<30:36,  2.45s/it]

🎯 COPY FLOW:  48%|█████████████████████▊                        | 680/1430 [46:54<30:16,  2.42s/it]

🎯 COPY FLOW:  48%|█████████████████████▉                        | 681/1430 [46:56<30:01,  2.41s/it]

🎯 COPY FLOW:  48%|█████████████████████▉                        | 682/1430 [46:59<29:51,  2.39s/it]

🎯 COPY FLOW:  48%|█████████████████████▉                        | 683/1430 [47:01<29:44,  2.39s/it]

🎯 COPY FLOW:  48%|██████████████████████                        | 684/1430 [47:06<39:43,  3.20s/it]

🎯 COPY FLOW:  48%|██████████████████████                        | 685/1430 [47:09<36:32,  2.94s/it]

🎯 COPY FLOW:  48%|██████████████████████                        | 686/1430 [47:11<34:19,  2.77s/it]

🎯 COPY FLOW:  48%|██████████████████████                        | 687/1430 [47:13<32:41,  2.64s/it]

🎯 COPY FLOW:  48%|██████████████████████▏                       | 688/1430 [47:16<31:38,  2.56s/it]

🎯 COPY FLOW:  48%|██████████████████████▏                       | 689/1430 [47:18<31:22,  2.54s/it]

🎯 COPY FLOW:  48%|██████████████████████▏                       | 690/1430 [47:20<30:37,  2.48s/it]

🎯 COPY FLOW:  48%|██████████████████████▏                       | 691/1430 [47:23<30:07,  2.45s/it]

🎯 COPY FLOW:  48%|██████████████████████▎                       | 692/1430 [47:25<29:35,  2.41s/it]

🎯 COPY FLOW:  48%|██████████████████████▎                       | 693/1430 [47:27<29:16,  2.38s/it]

🎯 COPY FLOW:  49%|██████████████████████▎                       | 694/1430 [47:30<29:06,  2.37s/it]

🎯 COPY FLOW:  49%|██████████████████████▎                       | 695/1430 [47:35<39:33,  3.23s/it]

🎯 COPY FLOW:  49%|██████████████████████▍                       | 696/1430 [47:37<36:15,  2.96s/it]

🎯 COPY FLOW:  49%|██████████████████████▍                       | 697/1430 [47:40<33:54,  2.78s/it]

🎯 COPY FLOW:  49%|██████████████████████▍                       | 698/1430 [47:42<32:09,  2.64s/it]

🎯 COPY FLOW:  49%|██████████████████████▍                       | 699/1430 [47:44<31:36,  2.59s/it]

🎯 COPY FLOW:  49%|██████████████████████▌                       | 700/1430 [47:47<30:30,  2.51s/it]

🎯 COPY FLOW:  49%|██████████████████████▌                       | 701/1430 [47:49<29:47,  2.45s/it]

🎯 COPY FLOW:  49%|██████████████████████▌                       | 702/1430 [47:51<29:19,  2.42s/it]

🎯 COPY FLOW:  49%|██████████████████████▌                       | 703/1430 [47:54<28:55,  2.39s/it]

🎯 COPY FLOW:  49%|██████████████████████▋                       | 704/1430 [47:56<28:39,  2.37s/it]

🎯 COPY FLOW:  49%|██████████████████████▋                       | 705/1430 [47:58<28:29,  2.36s/it]

🎯 COPY FLOW:  49%|██████████████████████▋                       | 706/1430 [48:01<28:17,  2.34s/it]

🎯 COPY FLOW:  49%|██████████████████████▋                       | 707/1430 [48:06<37:43,  3.13s/it]

🎯 COPY FLOW:  50%|██████████████████████▊                       | 708/1430 [48:08<34:50,  2.89s/it]

🎯 COPY FLOW:  50%|██████████████████████▊                       | 709/1430 [48:11<33:20,  2.78s/it]

🎯 COPY FLOW:  50%|██████████████████████▊                       | 710/1430 [48:13<31:42,  2.64s/it]

🎯 COPY FLOW:  50%|██████████████████████▊                       | 711/1430 [48:15<30:26,  2.54s/it]

🎯 COPY FLOW:  50%|██████████████████████▉                       | 712/1430 [48:17<29:32,  2.47s/it]

🎯 COPY FLOW:  50%|██████████████████████▉                       | 713/1430 [48:20<28:59,  2.43s/it]

🎯 COPY FLOW:  50%|██████████████████████▉                       | 714/1430 [48:22<28:36,  2.40s/it]

🎯 COPY FLOW:  50%|███████████████████████                       | 715/1430 [48:24<28:17,  2.37s/it]

🎯 COPY FLOW:  50%|███████████████████████                       | 716/1430 [48:27<28:03,  2.36s/it]

🎯 COPY FLOW:  50%|███████████████████████                       | 717/1430 [48:29<27:51,  2.34s/it]

🎯 COPY FLOW:  50%|███████████████████████                       | 718/1430 [48:31<27:45,  2.34s/it]

🎯 COPY FLOW:  50%|███████████████████████▏                      | 719/1430 [48:34<27:36,  2.33s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [50:21<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [49:17<2:39:36,  6.72s/it]

🎯 COPY FLOW:  50%|███████████████████████▏                      | 720/1430 [48:36<27:27,  2.32s/it]

📦 Finished: _25_SINC_rk_flac_11 (50 files)

🎯 COPY FLOW:  50%|███████████████████████▏                      | 721/1430 [48:38<27:22,  2.32s/it]

🎯 COPY FLOW:  50%|███████████████████████▏                      | 722/1430 [48:41<27:55,  2.37s/it]

🎯 COPY FLOW:  51%|███████████████████████▎                      | 723/1430 [48:43<27:43,  2.35s/it]

🎯 COPY FLOW:  51%|███████████████████████▎                      | 724/1430 [48:45<27:30,  2.34s/it]

🎯 COPY FLOW:  51%|███████████████████████▎                      | 725/1430 [48:48<27:21,  2.33s/it]

🎯 COPY FLOW:  51%|███████████████████████▎                      | 726/1430 [48:50<27:13,  2.32s/it]

🎯 COPY FLOW:  51%|███████████████████████▍                      | 727/1430 [48:52<27:07,  2.32s/it]

🎯 COPY FLOW:  51%|███████████████████████▍                      | 728/1430 [48:55<27:04,  2.31s/it]

🎯 COPY FLOW:  51%|███████████████████████▍                      | 729/1430 [48:57<26:57,  2.31s/it]

🎯 COPY FLOW:  51%|███████████████████████▍                      | 730/1430 [48:59<26:53,  2.31s/it]

🎯 COPY FLOW:  51%|███████████████████████▌                      | 731/1430 [49:02<26:50,  2.30s/it]

🎯 COPY FLOW:  51%|███████████████████████▌                      | 732/1430 [49:04<26:48,  2.31s/it]

🎯 COPY FLOW:  51%|███████████████████████▌                      | 733/1430 [49:06<26:44,  2.30s/it]

🎯 COPY FLOW:  51%|███████████████████████▌                      | 734/1430 [49:08<26:39,  2.30s/it]

🎯 COPY FLOW:  51%|███████████████████████▋                      | 735/1430 [49:11<27:11,  2.35s/it]

🎯 COPY FLOW:  51%|███████████████████████▋                      | 736/1430 [49:13<26:59,  2.33s/it]

🎯 COPY FLOW:  52%|███████████████████████▋                      | 737/1430 [49:16<26:49,  2.32s/it]

🎯 COPY FLOW:  52%|███████████████████████▋                      | 738/1430 [49:18<26:40,  2.31s/it]

🎯 COPY FLOW:  52%|███████████████████████▊                      | 739/1430 [49:20<26:28,  2.30s/it]

🎯 COPY FLOW:  52%|███████████████████████▊                      | 740/1430 [49:22<26:20,  2.29s/it]

🎯 COPY FLOW:  52%|███████████████████████▊                      | 741/1430 [49:25<26:17,  2.29s/it]

🎯 COPY FLOW:  52%|███████████████████████▊                      | 742/1430 [49:27<26:07,  2.28s/it]

🎯 COPY FLOW:  52%|███████████████████████▉                      | 743/1430 [49:29<26:08,  2.28s/it]

🎯 COPY FLOW:  52%|███████████████████████▉                      | 744/1430 [49:31<26:05,  2.28s/it]

🎯 COPY FLOW:  52%|███████████████████████▉                      | 745/1430 [49:34<26:05,  2.29s/it]

🎯 COPY FLOW:  52%|███████████████████████▉                      | 746/1430 [49:36<25:59,  2.28s/it]

🎯 COPY FLOW:  52%|████████████████████████                      | 747/1430 [49:38<25:57,  2.28s/it]

🎯 COPY FLOW:  52%|████████████████████████                      | 748/1430 [49:41<25:55,  2.28s/it]

🎯 COPY FLOW:  52%|████████████████████████                      | 749/1430 [49:43<25:54,  2.28s/it]

🎯 COPY FLOW:  52%|████████████████████████▏                     | 750/1430 [49:45<25:50,  2.28s/it]

🎯 COPY FLOW:  53%|████████████████████████▏                     | 751/1430 [49:47<25:41,  2.27s/it]

🎯 COPY FLOW:  53%|████████████████████████▏                     | 752/1430 [49:50<25:38,  2.27s/it]

🎯 COPY FLOW:  53%|████████████████████████▏                     | 753/1430 [49:52<26:12,  2.32s/it]

🎯 COPY FLOW:  53%|████████████████████████▎                     | 754/1430 [49:54<25:58,  2.31s/it]

🎯 COPY FLOW:  53%|████████████████████████▎                     | 755/1430 [49:57<25:48,  2.29s/it]

🎯 COPY FLOW:  53%|████████████████████████▎                     | 756/1430 [49:59<25:38,  2.28s/it]

🎯 COPY FLOW:  53%|████████████████████████▎                     | 757/1430 [50:01<25:33,  2.28s/it]

🎯 COPY FLOW:  53%|████████████████████████▍                     | 758/1430 [50:06<34:26,  3.07s/it]

🎯 COPY FLOW:  53%|████████████████████████▍                     | 759/1430 [50:08<31:43,  2.84s/it]

🎯 COPY FLOW:  53%|████████████████████████▍                     | 760/1430 [50:11<29:40,  2.66s/it]

🎯 COPY FLOW:  53%|████████████████████████▍                     | 761/1430 [50:13<28:16,  2.54s/it]

🎯 COPY FLOW:  53%|████████████████████████▌                     | 762/1430 [50:15<27:19,  2.45s/it]

🎯 COPY FLOW:  53%|████████████████████████▌                     | 763/1430 [50:17<26:39,  2.40s/it]

🎯 COPY FLOW:  53%|████████████████████████▌                     | 764/1430 [50:20<26:09,  2.36s/it]

🎯 COPY FLOW:  53%|████████████████████████▌                     | 765/1430 [50:22<25:47,  2.33s/it]

🎯 COPY FLOW:  54%|████████████████████████▋                     | 766/1430 [50:24<25:26,  2.30s/it]

🎯 COPY FLOW:  54%|████████████████████████▋                     | 767/1430 [50:26<25:13,  2.28s/it]

🎯 COPY FLOW:  54%|████████████████████████▋                     | 768/1430 [50:29<24:59,  2.27s/it]

🎯 COPY FLOW:  54%|████████████████████████▋                     | 769/1430 [50:31<24:52,  2.26s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [52:21<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [51:17<2:39:36,  6.72s/it]

🎯 COPY FLOW:  54%|████████████████████████▊                     | 770/1430 [50:36<34:42,  3.15s/it]

📦 Finished: _25_SINC_rk_flac_12 (50 files)

🎯 COPY FLOW:  54%|████████████████████████▊                     | 771/1430 [50:38<31:39,  2.88s/it]

🎯 COPY FLOW:  54%|████████████████████████▊                     | 772/1430 [50:41<29:31,  2.69s/it]

🎯 COPY FLOW:  54%|████████████████████████▊                     | 773/1430 [50:43<27:59,  2.56s/it]

🎯 COPY FLOW:  54%|████████████████████████▉                     | 774/1430 [50:45<26:50,  2.46s/it]

🎯 COPY FLOW:  54%|████████████████████████▉                     | 775/1430 [50:47<26:02,  2.39s/it]

🎯 COPY FLOW:  54%|████████████████████████▉                     | 776/1430 [50:50<25:32,  2.34s/it]

🎯 COPY FLOW:  54%|████████████████████████▉                     | 777/1430 [50:52<25:10,  2.31s/it]

🎯 COPY FLOW:  54%|█████████████████████████                     | 778/1430 [50:54<24:50,  2.29s/it]

🎯 COPY FLOW:  54%|█████████████████████████                     | 779/1430 [50:56<24:38,  2.27s/it]

🎯 COPY FLOW:  55%|█████████████████████████                     | 780/1430 [50:58<24:28,  2.26s/it]

🎯 COPY FLOW:  55%|█████████████████████████                     | 781/1430 [51:01<24:19,  2.25s/it]

🎯 COPY FLOW:  55%|█████████████████████████▏                    | 782/1430 [51:05<32:25,  3.00s/it]

🎯 COPY FLOW:  55%|█████████████████████████▏                    | 783/1430 [51:08<29:48,  2.76s/it]

🎯 COPY FLOW:  55%|█████████████████████████▏                    | 784/1430 [51:10<28:33,  2.65s/it]

🎯 COPY FLOW:  55%|█████████████████████████▎                    | 785/1430 [51:12<27:07,  2.52s/it]

🎯 COPY FLOW:  55%|█████████████████████████▎                    | 786/1430 [51:14<26:07,  2.43s/it]

🎯 COPY FLOW:  55%|█████████████████████████▎                    | 787/1430 [51:17<25:25,  2.37s/it]

🎯 COPY FLOW:  55%|█████████████████████████▎                    | 788/1430 [51:19<24:55,  2.33s/it]

🎯 COPY FLOW:  55%|█████████████████████████▍                    | 789/1430 [51:21<24:33,  2.30s/it]

🎯 COPY FLOW:  55%|█████████████████████████▍                    | 790/1430 [51:23<24:11,  2.27s/it]

🎯 COPY FLOW:  55%|█████████████████████████▍                    | 791/1430 [51:26<23:58,  2.25s/it]

🎯 COPY FLOW:  55%|█████████████████████████▍                    | 792/1430 [51:28<23:49,  2.24s/it]

🎯 COPY FLOW:  55%|█████████████████████████▌                    | 793/1430 [51:30<23:43,  2.23s/it]

🎯 COPY FLOW:  56%|█████████████████████████▌                    | 794/1430 [51:35<31:58,  3.02s/it]

🎯 COPY FLOW:  56%|█████████████████████████▌                    | 795/1430 [51:37<29:14,  2.76s/it]

🎯 COPY FLOW:  56%|█████████████████████████▌                    | 796/1430 [51:39<27:27,  2.60s/it]

🎯 COPY FLOW:  56%|█████████████████████████▋                    | 797/1430 [51:41<26:09,  2.48s/it]

🎯 COPY FLOW:  56%|█████████████████████████▋                    | 798/1430 [51:44<25:46,  2.45s/it]

🎯 COPY FLOW:  56%|█████████████████████████▋                    | 799/1430 [51:46<24:59,  2.38s/it]

🎯 COPY FLOW:  56%|█████████████████████████▋                    | 800/1430 [51:48<24:25,  2.33s/it]

🎯 COPY FLOW:  56%|█████████████████████████▊                    | 801/1430 [51:50<23:56,  2.28s/it]

🎯 COPY FLOW:  56%|█████████████████████████▊                    | 802/1430 [51:53<23:40,  2.26s/it]

🎯 COPY FLOW:  56%|█████████████████████████▊                    | 803/1430 [51:55<23:29,  2.25s/it]

🎯 COPY FLOW:  56%|█████████████████████████▊                    | 804/1430 [51:57<23:20,  2.24s/it]

🎯 COPY FLOW:  56%|█████████████████████████▉                    | 805/1430 [51:59<23:12,  2.23s/it]

🎯 COPY FLOW:  56%|█████████████████████████▉                    | 806/1430 [52:01<23:05,  2.22s/it]

🎯 COPY FLOW:  56%|█████████████████████████▉                    | 807/1430 [52:04<23:34,  2.27s/it]

🎯 COPY FLOW:  57%|█████████████████████████▉                    | 808/1430 [52:06<23:12,  2.24s/it]

🎯 COPY FLOW:  57%|██████████████████████████                    | 809/1430 [52:08<22:56,  2.22s/it]

🎯 COPY FLOW:  57%|██████████████████████████                    | 810/1430 [52:10<22:49,  2.21s/it]

🎯 COPY FLOW:  57%|██████████████████████████                    | 811/1430 [52:13<22:43,  2.20s/it]

🎯 COPY FLOW:  57%|██████████████████████████                    | 812/1430 [52:15<22:39,  2.20s/it]

🎯 COPY FLOW:  57%|██████████████████████████▏                   | 813/1430 [52:17<22:34,  2.19s/it]

🎯 COPY FLOW:  57%|██████████████████████████▏                   | 814/1430 [52:19<22:31,  2.19s/it]

🎯 COPY FLOW:  57%|██████████████████████████▏                   | 815/1430 [52:21<22:59,  2.24s/it]

🎯 COPY FLOW:  57%|██████████████████████████▏                   | 816/1430 [52:24<22:47,  2.23s/it]

🎯 COPY FLOW:  57%|██████████████████████████▎                   | 817/1430 [52:26<22:37,  2.21s/it]

🎯 COPY FLOW:  57%|██████████████████████████▎                   | 818/1430 [52:28<22:28,  2.20s/it]

🎯 COPY FLOW:  57%|██████████████████████████▎                   | 819/1430 [52:30<22:22,  2.20s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [54:20<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [53:16<2:39:36,  6.72s/it]

🎯 COPY FLOW:  57%|██████████████████████████▍                   | 820/1430 [52:35<30:30,  3.00s/it]

📦 Finished: _25_SINC_rk_flac_13 (50 files)

🎯 COPY FLOW:  57%|██████████████████████████▍                   | 821/1430 [52:37<27:58,  2.76s/it]

🎯 COPY FLOW:  57%|██████████████████████████▍                   | 822/1430 [52:39<26:08,  2.58s/it]

🎯 COPY FLOW:  58%|██████████████████████████▍                   | 823/1430 [52:42<24:52,  2.46s/it]

🎯 COPY FLOW:  58%|██████████████████████████▌                   | 824/1430 [52:44<23:58,  2.37s/it]

🎯 COPY FLOW:  58%|██████████████████████████▌                   | 825/1430 [52:46<23:20,  2.31s/it]

🎯 COPY FLOW:  58%|██████████████████████████▌                   | 826/1430 [52:48<22:53,  2.27s/it]

🎯 COPY FLOW:  58%|██████████████████████████▌                   | 827/1430 [52:50<22:30,  2.24s/it]

🎯 COPY FLOW:  58%|██████████████████████████▋                   | 828/1430 [52:52<22:10,  2.21s/it]

🎯 COPY FLOW:  58%|██████████████████████████▋                   | 829/1430 [52:55<21:57,  2.19s/it]

🎯 COPY FLOW:  58%|██████████████████████████▋                   | 830/1430 [52:57<22:23,  2.24s/it]

🎯 COPY FLOW:  58%|██████████████████████████▋                   | 831/1430 [52:59<22:04,  2.21s/it]

🎯 COPY FLOW:  58%|██████████████████████████▊                   | 832/1430 [53:01<21:54,  2.20s/it]

🎯 COPY FLOW:  58%|██████████████████████████▊                   | 833/1430 [53:06<29:43,  2.99s/it]

🎯 COPY FLOW:  58%|██████████████████████████▊                   | 834/1430 [53:08<27:15,  2.74s/it]

🎯 COPY FLOW:  58%|██████████████████████████▊                   | 835/1430 [53:10<25:30,  2.57s/it]

🎯 COPY FLOW:  58%|██████████████████████████▉                   | 836/1430 [53:13<24:15,  2.45s/it]

🎯 COPY FLOW:  59%|██████████████████████████▉                   | 837/1430 [53:15<23:22,  2.36s/it]

🎯 COPY FLOW:  59%|██████████████████████████▉                   | 838/1430 [53:17<22:43,  2.30s/it]

🎯 COPY FLOW:  59%|██████████████████████████▉                   | 839/1430 [53:19<22:16,  2.26s/it]

🎯 COPY FLOW:  59%|███████████████████████████                   | 840/1430 [53:21<21:55,  2.23s/it]

🎯 COPY FLOW:  59%|███████████████████████████                   | 841/1430 [53:23<21:38,  2.20s/it]

🎯 COPY FLOW:  59%|███████████████████████████                   | 842/1430 [53:26<21:28,  2.19s/it]

🎯 COPY FLOW:  59%|███████████████████████████                   | 843/1430 [53:28<21:18,  2.18s/it]

🎯 COPY FLOW:  59%|███████████████████████████▏                  | 844/1430 [53:30<21:12,  2.17s/it]

🎯 COPY FLOW:  59%|███████████████████████████▏                  | 845/1430 [53:35<29:35,  3.03s/it]

🎯 COPY FLOW:  59%|███████████████████████████▏                  | 846/1430 [53:37<26:50,  2.76s/it]

🎯 COPY FLOW:  59%|███████████████████████████▏                  | 847/1430 [53:39<24:56,  2.57s/it]

🎯 COPY FLOW:  59%|███████████████████████████▎                  | 848/1430 [53:41<23:38,  2.44s/it]

🎯 COPY FLOW:  59%|███████████████████████████▎                  | 849/1430 [53:43<22:44,  2.35s/it]

🎯 COPY FLOW:  59%|███████████████████████████▎                  | 850/1430 [53:46<22:05,  2.29s/it]

🎯 COPY FLOW:  60%|███████████████████████████▎                  | 851/1430 [53:48<21:36,  2.24s/it]

🎯 COPY FLOW:  60%|███████████████████████████▍                  | 852/1430 [53:50<21:15,  2.21s/it]

🎯 COPY FLOW:  60%|███████████████████████████▍                  | 853/1430 [53:52<21:01,  2.19s/it]

🎯 COPY FLOW:  60%|███████████████████████████▍                  | 854/1430 [53:54<20:51,  2.17s/it]

🎯 COPY FLOW:  60%|███████████████████████████▌                  | 855/1430 [53:56<20:41,  2.16s/it]

🎯 COPY FLOW:  60%|███████████████████████████▌                  | 856/1430 [53:58<20:35,  2.15s/it]

🎯 COPY FLOW:  60%|███████████████████████████▌                  | 857/1430 [54:00<20:26,  2.14s/it]

🎯 COPY FLOW:  60%|███████████████████████████▌                  | 858/1430 [54:06<29:05,  3.05s/it]

🎯 COPY FLOW:  60%|███████████████████████████▋                  | 859/1430 [54:08<26:22,  2.77s/it]

🎯 COPY FLOW:  60%|███████████████████████████▋                  | 860/1430 [54:10<24:24,  2.57s/it]

🎯 COPY FLOW:  60%|███████████████████████████▋                  | 861/1430 [54:12<23:08,  2.44s/it]

🎯 COPY FLOW:  60%|███████████████████████████▋                  | 862/1430 [54:14<22:13,  2.35s/it]

🎯 COPY FLOW:  60%|███████████████████████████▊                  | 863/1430 [54:16<21:32,  2.28s/it]

🎯 COPY FLOW:  60%|███████████████████████████▊                  | 864/1430 [54:18<21:04,  2.23s/it]

🎯 COPY FLOW:  60%|███████████████████████████▊                  | 865/1430 [54:21<20:46,  2.21s/it]

🎯 COPY FLOW:  61%|███████████████████████████▊                  | 866/1430 [54:23<20:34,  2.19s/it]

🎯 COPY FLOW:  61%|███████████████████████████▉                  | 867/1430 [54:25<20:20,  2.17s/it]

🎯 COPY FLOW:  61%|███████████████████████████▉                  | 868/1430 [54:27<20:10,  2.15s/it]

🎯 COPY FLOW:  61%|███████████████████████████▉                  | 869/1430 [54:29<20:00,  2.14s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [56:17<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [55:12<2:39:36,  6.72s/it]

🎯 COPY FLOW:  61%|███████████████████████████▉                  | 870/1430 [54:31<19:55,  2.13s/it]

📦 Finished: _25_SINC_rk_flac_14 (50 files)

🎯 COPY FLOW:  61%|████████████████████████████                  | 871/1430 [54:36<28:16,  3.04s/it]

🎯 COPY FLOW:  61%|████████████████████████████                  | 872/1430 [54:38<25:36,  2.75s/it]

🎯 COPY FLOW:  61%|████████████████████████████                  | 873/1430 [54:40<23:40,  2.55s/it]

🎯 COPY FLOW:  61%|████████████████████████████                  | 874/1430 [54:43<22:22,  2.41s/it]

🎯 COPY FLOW:  61%|████████████████████████████▏                 | 875/1430 [54:45<21:23,  2.31s/it]

🎯 COPY FLOW:  61%|████████████████████████████▏                 | 876/1430 [54:47<20:44,  2.25s/it]

🎯 COPY FLOW:  61%|████████████████████████████▏                 | 877/1430 [54:49<20:14,  2.20s/it]

🎯 COPY FLOW:  61%|████████████████████████████▏                 | 878/1430 [54:51<19:55,  2.17s/it]

🎯 COPY FLOW:  61%|████████████████████████████▎                 | 879/1430 [54:53<19:42,  2.15s/it]

🎯 COPY FLOW:  62%|████████████████████████████▎                 | 880/1430 [54:55<19:41,  2.15s/it]

🎯 COPY FLOW:  62%|████████████████████████████▎                 | 881/1430 [54:57<19:34,  2.14s/it]

🎯 COPY FLOW:  62%|████████████████████████████▎                 | 882/1430 [54:59<19:28,  2.13s/it]

🎯 COPY FLOW:  62%|████████████████████████████▍                 | 883/1430 [55:02<19:24,  2.13s/it]

🎯 COPY FLOW:  62%|████████████████████████████▍                 | 884/1430 [55:04<19:22,  2.13s/it]

🎯 COPY FLOW:  62%|████████████████████████████▍                 | 885/1430 [55:06<19:16,  2.12s/it]

🎯 COPY FLOW:  62%|████████████████████████████▌                 | 886/1430 [55:08<19:07,  2.11s/it]

🎯 COPY FLOW:  62%|████████████████████████████▌                 | 887/1430 [55:10<19:30,  2.16s/it]

🎯 COPY FLOW:  62%|████████████████████████████▌                 | 888/1430 [55:12<19:20,  2.14s/it]

🎯 COPY FLOW:  62%|████████████████████████████▌                 | 889/1430 [55:14<19:12,  2.13s/it]

🎯 COPY FLOW:  62%|████████████████████████████▋                 | 890/1430 [55:16<19:04,  2.12s/it]

🎯 COPY FLOW:  62%|████████████████████████████▋                 | 891/1430 [55:19<18:57,  2.11s/it]

🎯 COPY FLOW:  62%|████████████████████████████▋                 | 892/1430 [55:21<18:50,  2.10s/it]

🎯 COPY FLOW:  62%|████████████████████████████▋                 | 893/1430 [55:23<18:47,  2.10s/it]

🎯 COPY FLOW:  63%|████████████████████████████▊                 | 894/1430 [55:25<18:46,  2.10s/it]

🎯 COPY FLOW:  63%|████████████████████████████▊                 | 895/1430 [55:27<18:43,  2.10s/it]

🎯 COPY FLOW:  63%|████████████████████████████▊                 | 896/1430 [55:29<18:39,  2.10s/it]

🎯 COPY FLOW:  63%|████████████████████████████▊                 | 897/1430 [55:31<18:32,  2.09s/it]

🎯 COPY FLOW:  63%|████████████████████████████▉                 | 898/1430 [55:36<25:47,  2.91s/it]

🎯 COPY FLOW:  63%|████████████████████████████▉                 | 899/1430 [55:38<23:35,  2.66s/it]

🎯 COPY FLOW:  63%|████████████████████████████▉                 | 900/1430 [55:40<21:59,  2.49s/it]

🎯 COPY FLOW:  63%|████████████████████████████▉                 | 901/1430 [55:42<20:52,  2.37s/it]

🎯 COPY FLOW:  63%|█████████████████████████████                 | 902/1430 [55:44<20:33,  2.34s/it]

🎯 COPY FLOW:  63%|█████████████████████████████                 | 903/1430 [55:46<19:51,  2.26s/it]

🎯 COPY FLOW:  63%|█████████████████████████████                 | 904/1430 [55:49<19:22,  2.21s/it]

🎯 COPY FLOW:  63%|█████████████████████████████                 | 905/1430 [55:51<18:58,  2.17s/it]

🎯 COPY FLOW:  63%|█████████████████████████████▏                | 906/1430 [55:53<18:38,  2.13s/it]

🎯 COPY FLOW:  63%|█████████████████████████████▏                | 907/1430 [55:55<18:28,  2.12s/it]

🎯 COPY FLOW:  63%|█████████████████████████████▏                | 908/1430 [55:57<18:19,  2.11s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▏                | 909/1430 [55:59<18:13,  2.10s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▎                | 910/1430 [56:01<18:08,  2.09s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▎                | 911/1430 [56:06<25:18,  2.93s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▎                | 912/1430 [56:08<23:05,  2.68s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▎                | 913/1430 [56:10<21:28,  2.49s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▍                | 914/1430 [56:12<20:18,  2.36s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▍                | 915/1430 [56:14<19:31,  2.27s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▍                | 916/1430 [56:16<19:21,  2.26s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▍                | 917/1430 [56:18<18:47,  2.20s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▌                | 918/1430 [56:20<18:22,  2.15s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▌                | 919/1430 [56:23<18:04,  2.12s/it]




🎯 COPY FLOW:   0%|                                              | 2/1430 [58:10<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [57:06<2:39:36,  6.72s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▌                | 920/1430 [56:25<17:52,  2.10s/it]

📦 Finished: _25_SINC_rk_flac_15 (50 files)

🎯 COPY FLOW:  64%|█████████████████████████████▋                | 921/1430 [56:27<17:39,  2.08s/it]

🎯 COPY FLOW:  64%|█████████████████████████████▋                | 922/1430 [56:29<17:28,  2.06s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▋                | 923/1430 [56:31<17:24,  2.06s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▋                | 924/1430 [56:36<24:29,  2.90s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▊                | 925/1430 [56:38<22:15,  2.64s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▊                | 926/1430 [56:40<20:44,  2.47s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▊                | 927/1430 [56:42<19:37,  2.34s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▊                | 928/1430 [56:44<18:51,  2.25s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▉                | 929/1430 [56:46<18:18,  2.19s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▉                | 930/1430 [56:48<17:54,  2.15s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▉                | 931/1430 [56:50<17:59,  2.16s/it]

🎯 COPY FLOW:  65%|█████████████████████████████▉                | 932/1430 [56:52<17:41,  2.13s/it]

🎯 COPY FLOW:  65%|██████████████████████████████                | 933/1430 [56:54<17:21,  2.10s/it]

🎯 COPY FLOW:  65%|██████████████████████████████                | 934/1430 [56:56<17:10,  2.08s/it]

🎯 COPY FLOW:  65%|██████████████████████████████                | 935/1430 [56:58<17:01,  2.06s/it]

🎯 COPY FLOW:  65%|██████████████████████████████                | 936/1430 [57:00<16:58,  2.06s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▏               | 937/1430 [57:05<23:40,  2.88s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▏               | 938/1430 [57:07<21:33,  2.63s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▏               | 939/1430 [57:09<19:59,  2.44s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▏               | 940/1430 [57:11<18:57,  2.32s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▎               | 941/1430 [57:13<18:14,  2.24s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▎               | 942/1430 [57:15<17:44,  2.18s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▎               | 943/1430 [57:17<17:21,  2.14s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▎               | 944/1430 [57:19<17:06,  2.11s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▍               | 945/1430 [57:21<16:57,  2.10s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▍               | 946/1430 [57:23<16:49,  2.09s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▍               | 947/1430 [57:26<17:05,  2.12s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▍               | 948/1430 [57:28<16:50,  2.10s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▌               | 949/1430 [57:30<16:38,  2.08s/it]

🎯 COPY FLOW:  66%|██████████████████████████████▌               | 950/1430 [57:34<21:56,  2.74s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▌               | 951/1430 [57:36<20:25,  2.56s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▌               | 952/1430 [57:38<19:02,  2.39s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▋               | 953/1430 [57:40<18:03,  2.27s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▋               | 954/1430 [57:42<17:25,  2.20s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▋               | 955/1430 [57:44<16:56,  2.14s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▊               | 956/1430 [57:46<16:35,  2.10s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▊               | 957/1430 [57:48<16:20,  2.07s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▊               | 958/1430 [57:50<16:10,  2.06s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▊               | 959/1430 [57:52<16:02,  2.04s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▉               | 960/1430 [57:54<15:53,  2.03s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▉               | 961/1430 [57:56<15:49,  2.02s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▉               | 962/1430 [57:58<16:07,  2.07s/it]

🎯 COPY FLOW:  67%|██████████████████████████████▉               | 963/1430 [58:00<15:56,  2.05s/it]

🎯 COPY FLOW:  67%|███████████████████████████████               | 964/1430 [58:05<22:05,  2.84s/it]

🎯 COPY FLOW:  67%|███████████████████████████████               | 965/1430 [58:07<20:05,  2.59s/it]

🎯 COPY FLOW:  68%|███████████████████████████████               | 966/1430 [58:09<18:40,  2.41s/it]

🎯 COPY FLOW:  68%|███████████████████████████████               | 967/1430 [58:11<17:41,  2.29s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▏              | 968/1430 [58:13<16:58,  2.20s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▏              | 969/1430 [58:15<16:27,  2.14s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:00:02<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|▏                                             | 4/1430 [58:58<2:39:36,  6.72s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▏              | 970/1430 [58:17<16:05,  2.10s/it]

📦 Finished: _25_SINC_rk_flac_16 (50 files)

🎯 COPY FLOW:  68%|███████████████████████████████▏              | 971/1430 [58:19<15:45,  2.06s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▎              | 972/1430 [58:21<15:34,  2.04s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▎              | 973/1430 [58:23<15:24,  2.02s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▎              | 974/1430 [58:25<15:17,  2.01s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▎              | 975/1430 [58:27<15:09,  2.00s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▍              | 976/1430 [58:29<15:02,  1.99s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▍              | 977/1430 [58:31<14:57,  1.98s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▍              | 978/1430 [58:36<21:43,  2.88s/it]

🎯 COPY FLOW:  68%|███████████████████████████████▍              | 979/1430 [58:38<19:32,  2.60s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▌              | 980/1430 [58:40<18:08,  2.42s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▌              | 981/1430 [58:42<17:07,  2.29s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▌              | 982/1430 [58:44<16:22,  2.19s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▌              | 983/1430 [58:46<15:49,  2.12s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▋              | 984/1430 [58:48<15:27,  2.08s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▋              | 985/1430 [58:50<15:11,  2.05s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▋              | 986/1430 [58:52<14:58,  2.02s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▋              | 987/1430 [58:54<14:49,  2.01s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▊              | 988/1430 [58:56<14:43,  2.00s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▊              | 989/1430 [58:58<14:37,  1.99s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▊              | 990/1430 [59:00<14:32,  1.98s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▉              | 991/1430 [59:02<14:28,  1.98s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▉              | 992/1430 [59:04<14:27,  1.98s/it]

🎯 COPY FLOW:  69%|███████████████████████████████▉              | 993/1430 [59:05<14:22,  1.97s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▉              | 994/1430 [59:08<14:41,  2.02s/it]

🎯 COPY FLOW:  70%|████████████████████████████████              | 995/1430 [59:10<14:32,  2.01s/it]

🎯 COPY FLOW:  70%|████████████████████████████████              | 996/1430 [59:12<14:24,  1.99s/it]

🎯 COPY FLOW:  70%|████████████████████████████████              | 997/1430 [59:14<14:20,  1.99s/it]

🎯 COPY FLOW:  70%|████████████████████████████████              | 998/1430 [59:15<14:14,  1.98s/it]

🎯 COPY FLOW:  70%|████████████████████████████████▏             | 999/1430 [59:18<14:27,  2.01s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▍             | 1000/1430 [59:20<14:20,  2.00s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▍             | 1001/1430 [59:22<14:14,  1.99s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▌             | 1002/1430 [59:23<14:07,  1.98s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▌             | 1003/1430 [59:25<14:01,  1.97s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▌             | 1004/1430 [59:27<13:55,  1.96s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▋             | 1005/1430 [59:29<13:49,  1.95s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▋             | 1006/1430 [59:31<13:47,  1.95s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▋             | 1007/1430 [59:36<19:21,  2.75s/it]

🎯 COPY FLOW:  70%|███████████████████████████████▋             | 1008/1430 [59:38<17:38,  2.51s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▊             | 1009/1430 [59:40<16:24,  2.34s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▊             | 1010/1430 [59:42<15:54,  2.27s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▊             | 1011/1430 [59:44<15:11,  2.18s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▊             | 1012/1430 [59:46<14:40,  2.11s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▉             | 1013/1430 [59:48<14:18,  2.06s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▉             | 1014/1430 [59:50<14:02,  2.02s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▉             | 1015/1430 [59:52<13:50,  2.00s/it]

🎯 COPY FLOW:  71%|███████████████████████████████▉             | 1016/1430 [59:54<13:40,  1.98s/it]

🎯 COPY FLOW:  71%|████████████████████████████████             | 1017/1430 [59:55<13:31,  1.97s/it]

🎯 COPY FLOW:  71%|████████████████████████████████             | 1018/1430 [59:57<13:27,  1.96s/it]

🎯 COPY FLOW:  71%|████████████████████████████████             | 1019/1430 [59:59<13:19,  1.94s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:01:47<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:00:42<2:39:36,  6.72s/it]

🎯 COPY FLOW:  71%|██████████████████████████████▋            | 1020/1430 [1:00:01<13:12,  1.93s/it]

📦 Finished: _25_SINC_rk_flac_17 (50 files)

🎯 COPY FLOW:  71%|██████████████████████████████▋            | 1021/1430 [1:00:06<18:33,  2.72s/it]

🎯 COPY FLOW:  71%|██████████████████████████████▋            | 1022/1430 [1:00:08<16:57,  2.49s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▊            | 1023/1430 [1:00:10<15:45,  2.32s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▊            | 1024/1430 [1:00:12<14:55,  2.20s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▊            | 1025/1430 [1:00:14<14:20,  2.12s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▊            | 1026/1430 [1:00:16<14:13,  2.11s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▉            | 1027/1430 [1:00:18<13:47,  2.05s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▉            | 1028/1430 [1:00:19<13:30,  2.02s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▉            | 1029/1430 [1:00:21<13:17,  1.99s/it]

🎯 COPY FLOW:  72%|██████████████████████████████▉            | 1030/1430 [1:00:23<13:07,  1.97s/it]

🎯 COPY FLOW:  72%|███████████████████████████████            | 1031/1430 [1:00:25<12:56,  1.95s/it]

🎯 COPY FLOW:  72%|███████████████████████████████            | 1032/1430 [1:00:27<12:51,  1.94s/it]

🎯 COPY FLOW:  72%|███████████████████████████████            | 1033/1430 [1:00:29<12:51,  1.94s/it]

🎯 COPY FLOW:  72%|███████████████████████████████            | 1034/1430 [1:00:31<12:38,  1.92s/it]

🎯 COPY FLOW:  72%|███████████████████████████████            | 1035/1430 [1:00:36<18:11,  2.76s/it]

🎯 COPY FLOW:  72%|███████████████████████████████▏           | 1036/1430 [1:00:38<16:24,  2.50s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▏           | 1037/1430 [1:00:39<15:11,  2.32s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▏           | 1038/1430 [1:00:41<14:19,  2.19s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▏           | 1039/1430 [1:00:43<13:42,  2.10s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▎           | 1040/1430 [1:00:45<13:16,  2.04s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▎           | 1041/1430 [1:00:47<12:56,  2.00s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▎           | 1042/1430 [1:00:49<12:41,  1.96s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▎           | 1043/1430 [1:00:51<12:49,  1.99s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▍           | 1044/1430 [1:00:53<12:36,  1.96s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▍           | 1045/1430 [1:00:55<12:25,  1.94s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▍           | 1046/1430 [1:00:57<12:16,  1.92s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▍           | 1047/1430 [1:00:58<12:11,  1.91s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▌           | 1048/1430 [1:01:00<12:06,  1.90s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▌           | 1049/1430 [1:01:05<17:10,  2.70s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▌           | 1050/1430 [1:01:07<15:37,  2.47s/it]

🎯 COPY FLOW:  73%|███████████████████████████████▌           | 1051/1430 [1:01:09<14:28,  2.29s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▋           | 1052/1430 [1:01:11<13:41,  2.17s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▋           | 1053/1430 [1:01:13<13:06,  2.09s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▋           | 1054/1430 [1:01:14<12:40,  2.02s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▋           | 1055/1430 [1:01:16<12:20,  1.97s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▊           | 1056/1430 [1:01:18<12:09,  1.95s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▊           | 1057/1430 [1:01:20<12:00,  1.93s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▊           | 1058/1430 [1:01:22<11:53,  1.92s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▊           | 1059/1430 [1:01:24<11:47,  1.91s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▊           | 1060/1430 [1:01:26<12:01,  1.95s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▉           | 1061/1430 [1:01:28<11:52,  1.93s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▉           | 1062/1430 [1:01:30<11:45,  1.92s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▉           | 1063/1430 [1:01:32<11:40,  1.91s/it]

🎯 COPY FLOW:  74%|███████████████████████████████▉           | 1064/1430 [1:01:34<12:05,  1.98s/it]

🎯 COPY FLOW:  74%|████████████████████████████████           | 1065/1430 [1:01:36<11:53,  1.96s/it]

🎯 COPY FLOW:  75%|████████████████████████████████           | 1066/1430 [1:01:37<11:42,  1.93s/it]

🎯 COPY FLOW:  75%|████████████████████████████████           | 1067/1430 [1:01:39<11:31,  1.90s/it]

🎯 COPY FLOW:  75%|████████████████████████████████           | 1068/1430 [1:01:41<11:25,  1.89s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▏          | 1069/1430 [1:01:43<11:20,  1.89s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:03:30<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:02:26<2:39:36,  6.72s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▏          | 1070/1430 [1:01:45<11:17,  1.88s/it]

📦 Finished: _25_SINC_rk_flac_18 (50 files)

🎯 COPY FLOW:  75%|████████████████████████████████▏          | 1071/1430 [1:01:47<11:14,  1.88s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▏          | 1072/1430 [1:01:49<11:11,  1.87s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▎          | 1073/1430 [1:01:50<11:07,  1.87s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▎          | 1074/1430 [1:01:52<11:05,  1.87s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▎          | 1075/1430 [1:01:54<11:21,  1.92s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▎          | 1076/1430 [1:01:56<11:13,  1.90s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▍          | 1077/1430 [1:01:58<11:07,  1.89s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▍          | 1078/1430 [1:02:00<11:00,  1.88s/it]

🎯 COPY FLOW:  75%|████████████████████████████████▍          | 1079/1430 [1:02:02<10:57,  1.87s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▍          | 1080/1430 [1:02:04<10:55,  1.87s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▌          | 1081/1430 [1:02:06<10:51,  1.87s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▌          | 1082/1430 [1:02:07<10:46,  1.86s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▌          | 1083/1430 [1:02:09<10:44,  1.86s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▌          | 1084/1430 [1:02:11<10:40,  1.85s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▋          | 1085/1430 [1:02:13<10:39,  1.85s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▋          | 1086/1430 [1:02:15<10:37,  1.85s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▋          | 1087/1430 [1:02:17<10:33,  1.85s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▋          | 1088/1430 [1:02:18<10:31,  1.85s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▋          | 1089/1430 [1:02:20<10:30,  1.85s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▊          | 1090/1430 [1:02:22<10:31,  1.86s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▊          | 1091/1430 [1:02:24<10:42,  1.90s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▊          | 1092/1430 [1:02:26<10:34,  1.88s/it]

🎯 COPY FLOW:  76%|████████████████████████████████▊          | 1093/1430 [1:02:28<10:27,  1.86s/it]

🎯 COPY FLOW:  77%|████████████████████████████████▉          | 1094/1430 [1:02:30<10:23,  1.86s/it]

🎯 COPY FLOW:  77%|████████████████████████████████▉          | 1095/1430 [1:02:32<10:19,  1.85s/it]

🎯 COPY FLOW:  77%|████████████████████████████████▉          | 1096/1430 [1:02:34<10:39,  1.92s/it]

🎯 COPY FLOW:  77%|████████████████████████████████▉          | 1097/1430 [1:02:35<10:30,  1.89s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████          | 1098/1430 [1:02:37<10:21,  1.87s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████          | 1099/1430 [1:02:39<10:15,  1.86s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████          | 1100/1430 [1:02:41<10:11,  1.85s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████          | 1101/1430 [1:02:43<10:07,  1.85s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████▏         | 1102/1430 [1:02:45<10:04,  1.84s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████▏         | 1103/1430 [1:02:46<10:00,  1.84s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████▏         | 1104/1430 [1:02:48<09:57,  1.83s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████▏         | 1105/1430 [1:02:50<09:53,  1.83s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████▎         | 1106/1430 [1:02:52<09:51,  1.83s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████▎         | 1107/1430 [1:02:54<10:07,  1.88s/it]

🎯 COPY FLOW:  77%|█████████████████████████████████▎         | 1108/1430 [1:02:56<09:59,  1.86s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▎         | 1109/1430 [1:02:58<09:54,  1.85s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▍         | 1110/1430 [1:02:59<09:49,  1.84s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▍         | 1111/1430 [1:03:01<09:45,  1.84s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▍         | 1112/1430 [1:03:06<14:02,  2.65s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▍         | 1113/1430 [1:03:08<12:37,  2.39s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▍         | 1114/1430 [1:03:09<11:39,  2.21s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▌         | 1115/1430 [1:03:11<10:59,  2.09s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▌         | 1116/1430 [1:03:13<10:28,  2.00s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▌         | 1117/1430 [1:03:15<10:08,  1.94s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▌         | 1118/1430 [1:03:17<09:53,  1.90s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▋         | 1119/1430 [1:03:18<09:41,  1.87s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:05:05<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:04:01<2:39:36,  6.72s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▋         | 1120/1430 [1:03:20<09:31,  1.84s/it]

📦 Finished: _25_SINC_rk_flac_19 (50 files)

🎯 COPY FLOW:  78%|█████████████████████████████████▋         | 1121/1430 [1:03:22<09:25,  1.83s/it]

🎯 COPY FLOW:  78%|█████████████████████████████████▋         | 1122/1430 [1:03:24<09:19,  1.82s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▊         | 1123/1430 [1:03:25<09:15,  1.81s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▊         | 1124/1430 [1:03:27<09:11,  1.80s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▊         | 1125/1430 [1:03:29<09:08,  1.80s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▊         | 1126/1430 [1:03:31<09:04,  1.79s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▉         | 1127/1430 [1:03:35<12:57,  2.57s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▉         | 1128/1430 [1:03:37<11:40,  2.32s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▉         | 1129/1430 [1:03:39<10:48,  2.16s/it]

🎯 COPY FLOW:  79%|█████████████████████████████████▉         | 1130/1430 [1:03:40<10:11,  2.04s/it]

🎯 COPY FLOW:  79%|██████████████████████████████████         | 1131/1430 [1:03:42<09:46,  1.96s/it]

🎯 COPY FLOW:  79%|██████████████████████████████████         | 1132/1430 [1:03:44<09:27,  1.90s/it]

🎯 COPY FLOW:  79%|██████████████████████████████████         | 1133/1430 [1:03:46<09:13,  1.86s/it]

🎯 COPY FLOW:  79%|██████████████████████████████████         | 1134/1430 [1:03:48<09:03,  1.84s/it]

🎯 COPY FLOW:  79%|██████████████████████████████████▏        | 1135/1430 [1:03:50<09:09,  1.86s/it]

🎯 COPY FLOW:  79%|██████████████████████████████████▏        | 1136/1430 [1:03:51<08:58,  1.83s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▏        | 1137/1430 [1:03:53<08:51,  1.81s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▏        | 1138/1430 [1:03:55<08:46,  1.80s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▏        | 1139/1430 [1:03:57<08:41,  1.79s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▎        | 1140/1430 [1:03:58<08:38,  1.79s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▎        | 1141/1430 [1:04:00<08:34,  1.78s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▎        | 1142/1430 [1:04:02<08:30,  1.77s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▎        | 1143/1430 [1:04:04<08:28,  1.77s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▍        | 1144/1430 [1:04:05<08:25,  1.77s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▍        | 1145/1430 [1:04:07<08:22,  1.76s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▍        | 1146/1430 [1:04:09<08:20,  1.76s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▍        | 1147/1430 [1:04:11<08:17,  1.76s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▌        | 1148/1430 [1:04:12<08:15,  1.76s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▌        | 1149/1430 [1:04:14<08:11,  1.75s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▌        | 1150/1430 [1:04:16<08:08,  1.74s/it]

🎯 COPY FLOW:  80%|██████████████████████████████████▌        | 1151/1430 [1:04:18<08:07,  1.75s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▋        | 1152/1430 [1:04:19<08:06,  1.75s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▋        | 1153/1430 [1:04:21<08:04,  1.75s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▋        | 1154/1430 [1:04:23<08:16,  1.80s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▋        | 1155/1430 [1:04:25<08:10,  1.78s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▊        | 1156/1430 [1:04:27<08:05,  1.77s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▊        | 1157/1430 [1:04:28<08:01,  1.76s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▊        | 1158/1430 [1:04:30<07:56,  1.75s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▊        | 1159/1430 [1:04:32<07:53,  1.75s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▉        | 1160/1430 [1:04:33<07:51,  1.75s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▉        | 1161/1430 [1:04:35<07:49,  1.75s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▉        | 1162/1430 [1:04:37<07:46,  1.74s/it]

🎯 COPY FLOW:  81%|██████████████████████████████████▉        | 1163/1430 [1:04:39<07:42,  1.73s/it]

🎯 COPY FLOW:  81%|███████████████████████████████████        | 1164/1430 [1:04:40<07:40,  1.73s/it]

🎯 COPY FLOW:  81%|███████████████████████████████████        | 1165/1430 [1:04:42<07:39,  1.73s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████        | 1166/1430 [1:04:44<07:37,  1.73s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████        | 1167/1430 [1:04:46<07:32,  1.72s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████        | 1168/1430 [1:04:47<07:30,  1.72s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▏       | 1169/1430 [1:04:49<07:29,  1.72s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:06:36<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:05:32<2:39:36,  6.72s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▏       | 1170/1430 [1:04:51<07:28,  1.72s/it]

📦 Finished: _25_SINC_rk_flac_20 (50 files)

🎯 COPY FLOW:  82%|███████████████████████████████████▏       | 1171/1430 [1:04:52<07:26,  1.72s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▏       | 1172/1430 [1:04:54<07:24,  1.72s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▎       | 1173/1430 [1:04:56<07:22,  1.72s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▎       | 1174/1430 [1:04:58<07:32,  1.77s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▎       | 1175/1430 [1:04:59<07:26,  1.75s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▎       | 1176/1430 [1:05:01<07:22,  1.74s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▍       | 1177/1430 [1:05:05<10:10,  2.41s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▍       | 1178/1430 [1:05:07<09:09,  2.18s/it]

🎯 COPY FLOW:  82%|███████████████████████████████████▍       | 1179/1430 [1:05:09<08:30,  2.03s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▍       | 1180/1430 [1:05:10<08:03,  1.93s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▌       | 1181/1430 [1:05:12<07:43,  1.86s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▌       | 1182/1430 [1:05:14<07:29,  1.81s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▌       | 1183/1430 [1:05:15<07:17,  1.77s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▌       | 1184/1430 [1:05:17<07:08,  1.74s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▋       | 1185/1430 [1:05:19<07:02,  1.73s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▋       | 1186/1430 [1:05:20<06:57,  1.71s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▋       | 1187/1430 [1:05:22<06:52,  1.70s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▋       | 1188/1430 [1:05:24<06:49,  1.69s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▊       | 1189/1430 [1:05:25<06:47,  1.69s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▊       | 1190/1430 [1:05:27<06:44,  1.69s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▊       | 1191/1430 [1:05:29<06:42,  1.68s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▊       | 1192/1430 [1:05:30<06:39,  1.68s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▊       | 1193/1430 [1:05:35<10:05,  2.56s/it]

🎯 COPY FLOW:  83%|███████████████████████████████████▉       | 1194/1430 [1:05:37<09:01,  2.30s/it]

🎯 COPY FLOW:  84%|███████████████████████████████████▉       | 1195/1430 [1:05:38<08:12,  2.10s/it]

🎯 COPY FLOW:  84%|███████████████████████████████████▉       | 1196/1430 [1:05:40<07:39,  1.96s/it]

🎯 COPY FLOW:  84%|███████████████████████████████████▉       | 1197/1430 [1:05:42<07:16,  1.87s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████       | 1198/1430 [1:05:43<06:59,  1.81s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████       | 1199/1430 [1:05:45<06:46,  1.76s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████       | 1200/1430 [1:05:47<06:38,  1.73s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████       | 1201/1430 [1:05:48<06:31,  1.71s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████▏      | 1202/1430 [1:05:50<06:26,  1.69s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████▏      | 1203/1430 [1:05:52<06:21,  1.68s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████▏      | 1204/1430 [1:05:53<06:17,  1.67s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████▏      | 1205/1430 [1:05:55<06:13,  1.66s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████▎      | 1206/1430 [1:05:56<06:11,  1.66s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████▎      | 1207/1430 [1:05:58<06:08,  1.65s/it]

🎯 COPY FLOW:  84%|████████████████████████████████████▎      | 1208/1430 [1:06:00<06:06,  1.65s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▎      | 1209/1430 [1:06:01<06:03,  1.65s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▍      | 1210/1430 [1:06:05<08:23,  2.29s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▍      | 1211/1430 [1:06:07<07:38,  2.09s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▍      | 1212/1430 [1:06:08<07:05,  1.95s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▍      | 1213/1430 [1:06:10<06:42,  1.86s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▌      | 1214/1430 [1:06:12<06:25,  1.79s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▌      | 1215/1430 [1:06:13<06:12,  1.73s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▌      | 1216/1430 [1:06:15<06:03,  1.70s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▌      | 1217/1430 [1:06:17<05:56,  1.68s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▋      | 1218/1430 [1:06:18<05:51,  1.66s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▋      | 1219/1430 [1:06:20<05:45,  1.64s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:08:07<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:07:02<2:39:36,  6.72s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▋      | 1220/1430 [1:06:21<05:43,  1.63s/it]

📦 Finished: _25_SINC_rk_flac_21 (50 files)

🎯 COPY FLOW:  85%|████████████████████████████████████▋      | 1221/1430 [1:06:23<05:40,  1.63s/it]

🎯 COPY FLOW:  85%|████████████████████████████████████▋      | 1222/1430 [1:06:25<05:37,  1.62s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▊      | 1223/1430 [1:06:26<05:35,  1.62s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▊      | 1224/1430 [1:06:28<05:33,  1.62s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▊      | 1225/1430 [1:06:29<05:30,  1.61s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▊      | 1226/1430 [1:06:31<05:27,  1.61s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▉      | 1227/1430 [1:06:36<08:31,  2.52s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▉      | 1228/1430 [1:06:37<07:33,  2.25s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▉      | 1229/1430 [1:06:39<06:52,  2.05s/it]

🎯 COPY FLOW:  86%|████████████████████████████████████▉      | 1230/1430 [1:06:40<06:21,  1.91s/it]

🎯 COPY FLOW:  86%|█████████████████████████████████████      | 1231/1430 [1:06:42<06:00,  1.81s/it]

🎯 COPY FLOW:  86%|█████████████████████████████████████      | 1232/1430 [1:06:44<05:44,  1.74s/it]

🎯 COPY FLOW:  86%|█████████████████████████████████████      | 1233/1430 [1:06:45<05:33,  1.69s/it]

🎯 COPY FLOW:  86%|█████████████████████████████████████      | 1234/1430 [1:06:47<05:24,  1.66s/it]

🎯 COPY FLOW:  86%|█████████████████████████████████████▏     | 1235/1430 [1:06:48<05:18,  1.63s/it]

🎯 COPY FLOW:  86%|█████████████████████████████████████▏     | 1236/1430 [1:06:50<05:12,  1.61s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▏     | 1237/1430 [1:06:51<05:08,  1.60s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▏     | 1238/1430 [1:06:53<05:04,  1.59s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▎     | 1239/1430 [1:06:55<05:00,  1.57s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▎     | 1240/1430 [1:06:56<04:57,  1.56s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▎     | 1241/1430 [1:06:58<04:53,  1.55s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▎     | 1242/1430 [1:06:59<04:50,  1.55s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▍     | 1243/1430 [1:07:01<04:47,  1.54s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▍     | 1244/1430 [1:07:05<07:27,  2.40s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▍     | 1245/1430 [1:07:07<06:36,  2.14s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▍     | 1246/1430 [1:07:08<06:08,  2.00s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▍     | 1247/1430 [1:07:10<05:39,  1.85s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▌     | 1248/1430 [1:07:11<05:17,  1.74s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▌     | 1249/1430 [1:07:13<05:02,  1.67s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▌     | 1250/1430 [1:07:14<04:51,  1.62s/it]

🎯 COPY FLOW:  87%|█████████████████████████████████████▌     | 1251/1430 [1:07:16<04:43,  1.58s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▋     | 1252/1430 [1:07:17<04:35,  1.55s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▋     | 1253/1430 [1:07:19<04:29,  1.52s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▋     | 1254/1430 [1:07:20<04:23,  1.50s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▋     | 1255/1430 [1:07:22<04:19,  1.48s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▊     | 1256/1430 [1:07:23<04:16,  1.47s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▊     | 1257/1430 [1:07:25<04:13,  1.46s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▊     | 1258/1430 [1:07:26<04:10,  1.45s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▊     | 1259/1430 [1:07:27<04:06,  1.44s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▉     | 1260/1430 [1:07:29<04:03,  1.43s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▉     | 1261/1430 [1:07:30<04:00,  1.42s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▉     | 1262/1430 [1:07:32<03:55,  1.40s/it]

🎯 COPY FLOW:  88%|█████████████████████████████████████▉     | 1263/1430 [1:07:33<03:52,  1.39s/it]

🎯 COPY FLOW:  88%|██████████████████████████████████████     | 1264/1430 [1:07:34<03:49,  1.38s/it]

🎯 COPY FLOW:  88%|██████████████████████████████████████     | 1265/1430 [1:07:36<03:45,  1.36s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████     | 1266/1430 [1:07:37<03:41,  1.35s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████     | 1267/1430 [1:07:38<03:38,  1.34s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▏    | 1268/1430 [1:07:40<03:35,  1.33s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▏    | 1269/1430 [1:07:41<03:33,  1.33s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:09:28<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:08:23<2:39:36,  6.72s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▏    | 1270/1430 [1:07:42<03:31,  1.32s/it]

📦 Finished: _25_SINC_rk_flac_22 (50 files)

🎯 COPY FLOW:  89%|██████████████████████████████████████▏    | 1271/1430 [1:07:43<03:28,  1.31s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▏    | 1272/1430 [1:07:45<03:32,  1.35s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▎    | 1273/1430 [1:07:46<03:26,  1.32s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▎    | 1274/1430 [1:07:47<03:21,  1.29s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▎    | 1275/1430 [1:07:49<03:15,  1.26s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▎    | 1276/1430 [1:07:50<03:08,  1.22s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▍    | 1277/1430 [1:07:51<03:02,  1.19s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▍    | 1278/1430 [1:07:52<02:56,  1.16s/it]

🎯 COPY FLOW:  89%|██████████████████████████████████████▍    | 1279/1430 [1:07:53<02:50,  1.13s/it]

🎯 COPY FLOW:  90%|██████████████████████████████████████▍    | 1280/1430 [1:07:54<02:44,  1.09s/it]

🎯 COPY FLOW:  90%|██████████████████████████████████████▌    | 1281/1430 [1:07:55<02:39,  1.07s/it]

🎯 COPY FLOW:  90%|██████████████████████████████████████▌    | 1282/1430 [1:07:56<02:32,  1.03s/it]

🎯 COPY FLOW:  90%|██████████████████████████████████████▌    | 1283/1430 [1:07:57<02:27,  1.01s/it]

🎯 COPY FLOW:  90%|██████████████████████████████████████▌    | 1284/1430 [1:07:58<02:23,  1.02it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▋    | 1285/1430 [1:07:59<02:19,  1.04it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▋    | 1286/1430 [1:07:59<02:08,  1.12it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▋    | 1287/1430 [1:08:00<01:57,  1.21it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▋    | 1288/1430 [1:08:01<01:48,  1.31it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▊    | 1289/1430 [1:08:01<01:41,  1.39it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▊    | 1290/1430 [1:08:05<03:28,  1.49s/it]

🎯 COPY FLOW:  90%|██████████████████████████████████████▊    | 1291/1430 [1:08:05<02:49,  1.22s/it]

🎯 COPY FLOW:  90%|██████████████████████████████████████▊    | 1292/1430 [1:08:06<02:15,  1.02it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▉    | 1293/1430 [1:08:06<01:48,  1.26it/s]

🎯 COPY FLOW:  90%|██████████████████████████████████████▉    | 1294/1430 [1:08:06<01:27,  1.55it/s]

🎯 COPY FLOW:  91%|██████████████████████████████████████▉    | 1295/1430 [1:08:07<01:10,  1.91it/s]

🎯 COPY FLOW:  91%|██████████████████████████████████████▉    | 1296/1430 [1:08:07<00:56,  2.37it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████    | 1297/1430 [1:08:07<00:46,  2.88it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████    | 1298/1430 [1:08:07<00:38,  3.41it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████    | 1299/1430 [1:08:07<00:33,  3.94it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████    | 1300/1430 [1:08:07<00:29,  4.41it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████    | 1301/1430 [1:08:08<00:26,  4.85it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████▏   | 1302/1430 [1:08:08<00:24,  5.21it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████▏   | 1303/1430 [1:08:08<00:23,  5.49it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████▏   | 1304/1430 [1:08:08<00:22,  5.72it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████▏   | 1305/1430 [1:08:08<00:21,  5.90it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████▎   | 1306/1430 [1:08:08<00:20,  6.04it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████▎   | 1307/1430 [1:08:09<00:19,  6.15it/s]

🎯 COPY FLOW:  91%|███████████████████████████████████████▎   | 1308/1430 [1:08:09<00:19,  6.26it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▎   | 1309/1430 [1:08:09<00:19,  6.34it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▍   | 1310/1430 [1:08:09<00:18,  6.46it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▍   | 1311/1430 [1:08:09<00:18,  6.50it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▍   | 1312/1430 [1:08:09<00:18,  6.55it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▍   | 1313/1430 [1:08:09<00:17,  6.57it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▌   | 1314/1430 [1:08:10<00:17,  6.59it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▌   | 1315/1430 [1:08:10<00:17,  6.60it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▌   | 1316/1430 [1:08:10<00:17,  6.62it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▌   | 1317/1430 [1:08:10<00:16,  6.72it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▋   | 1318/1430 [1:08:10<00:16,  6.78it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▋   | 1319/1430 [1:08:10<00:15,  6.99it/s]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:09:56<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:08:51<2:39:36,  6.72s/it]

🎯 COPY FLOW:  92%|███████████████████████████████████████▋   | 1320/1430 [1:08:10<00:15,  7.10it/s]

🎯 COPY FLOW:  92%|███████████████████████████████████████▋   | 1321/1430 [1:08:11<00:14,  7.49it/s]

📦 Finished: _25_SINC_rk_flac_23 (50 files)

🎯 COPY FLOW:  92%|███████████████████████████████████████▊   | 1322/1430 [1:08:11<00:13,  7.76it/s]

🎯 COPY FLOW:  93%|███████████████████████████████████████▊   | 1323/1430 [1:08:11<00:13,  7.94it/s]

🎯 COPY FLOW:  93%|███████████████████████████████████████▊   | 1324/1430 [1:08:11<00:12,  8.34it/s]

🎯 COPY FLOW:  93%|███████████████████████████████████████▊   | 1326/1430 [1:08:11<00:10,  9.94it/s]

🎯 COPY FLOW:  93%|███████████████████████████████████████▉   | 1328/1430 [1:08:11<00:08, 11.40it/s]

🎯 COPY FLOW:  93%|███████████████████████████████████████▉   | 1330/1430 [1:08:11<00:07, 12.53it/s]

🎯 COPY FLOW:  93%|████████████████████████████████████████   | 1332/1430 [1:08:11<00:07, 13.51it/s]

🎯 COPY FLOW:  93%|████████████████████████████████████████   | 1334/1430 [1:08:12<00:06, 14.40it/s]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:09:57<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:08:53<2:39:36,  6.72s/it]

🎯 COPY FLOW:  93%|████████████████████████████████████████▏  | 1336/1430 [1:08:12<00:06, 15.54it/s]

📦 Final: _25_SINC_rk_flac_24 (16 files)

🎯 COPY FLOW:  93%|████████████████████████████████████████▏  | 1337/1430 [1:08:26<00:05, 15.54it/s]

🎯 COPY FLOW:  94%|████████████████████████████████████████▏  | 1338/1430 [1:08:39<06:42,  4.37s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▎  | 1339/1430 [1:08:49<08:12,  5.41s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▎  | 1340/1430 [1:08:58<08:58,  5.98s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▎  | 1342/1430 [1:09:15<10:10,  6.94s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▍  | 1343/1430 [1:09:21<09:44,  6.72s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▍  | 1344/1430 [1:09:27<09:24,  6.56s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▍  | 1345/1430 [1:09:35<09:56,  7.01s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▍  | 1346/1430 [1:09:41<09:18,  6.65s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▌  | 1347/1430 [1:09:46<08:43,  6.31s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▌  | 1348/1430 [1:09:51<08:14,  6.03s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▌  | 1349/1430 [1:09:56<07:40,  5.68s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▌  | 1350/1430 [1:10:00<07:04,  5.30s/it]

🎯 COPY FLOW:  94%|████████████████████████████████████████▌  | 1351/1430 [1:10:08<07:41,  5.84s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▋  | 1352/1430 [1:10:12<07:00,  5.39s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▋  | 1353/1430 [1:10:16<06:29,  5.06s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▋  | 1354/1430 [1:10:20<06:05,  4.81s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▋  | 1355/1430 [1:10:25<05:44,  4.60s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▊  | 1356/1430 [1:10:29<05:27,  4.42s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▊  | 1357/1430 [1:10:36<06:18,  5.19s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▊  | 1358/1430 [1:10:39<05:46,  4.82s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▊  | 1359/1430 [1:10:43<05:21,  4.53s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▉  | 1360/1430 [1:10:47<04:58,  4.26s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▉  | 1361/1430 [1:10:51<04:40,  4.06s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▉  | 1362/1430 [1:10:54<04:26,  3.92s/it]

🎯 COPY FLOW:  95%|████████████████████████████████████████▉  | 1363/1430 [1:10:58<04:15,  3.81s/it]

🎯 COPY FLOW:  95%|█████████████████████████████████████████  | 1364/1430 [1:11:01<04:05,  3.71s/it]

🎯 COPY FLOW:  95%|█████████████████████████████████████████  | 1365/1430 [1:11:08<04:52,  4.49s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████  | 1366/1430 [1:11:11<04:28,  4.19s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████  | 1367/1430 [1:11:14<04:08,  3.95s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▏ | 1368/1430 [1:11:18<03:54,  3.78s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▏ | 1369/1430 [1:11:21<03:42,  3.65s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▏ | 1370/1430 [1:11:24<03:29,  3.50s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▏ | 1371/1430 [1:11:27<03:19,  3.39s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▎ | 1372/1430 [1:11:30<03:10,  3.28s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▎ | 1373/1430 [1:11:36<03:48,  4.01s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▎ | 1374/1430 [1:11:39<03:26,  3.69s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▎ | 1375/1430 [1:11:42<03:13,  3.52s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▍ | 1376/1430 [1:11:45<02:59,  3.32s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▍ | 1377/1430 [1:11:48<02:48,  3.18s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▍ | 1378/1430 [1:11:51<02:38,  3.06s/it]

🎯 COPY FLOW:  96%|█████████████████████████████████████████▍ | 1379/1430 [1:11:53<02:31,  2.97s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▍ | 1380/1430 [1:11:56<02:25,  2.90s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▌ | 1381/1430 [1:11:59<02:19,  2.85s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▌ | 1382/1430 [1:12:02<02:15,  2.81s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▌ | 1383/1430 [1:12:04<02:10,  2.78s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▌ | 1384/1430 [1:12:07<02:06,  2.75s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▋ | 1385/1430 [1:12:10<02:03,  2.74s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:13:57<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:12:53<2:39:36,  6.72s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▋ | 1386/1430 [1:12:12<01:55,  2.62s/it]

📦 Finished: _25_SINC_rk_wav_1 (50 files)

🎯 COPY FLOW:  97%|█████████████████████████████████████████▋ | 1387/1430 [1:12:14<01:49,  2.55s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▋ | 1388/1430 [1:12:17<01:44,  2.49s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▊ | 1389/1430 [1:12:19<01:42,  2.50s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▊ | 1390/1430 [1:12:22<01:38,  2.46s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▊ | 1391/1430 [1:12:24<01:34,  2.42s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▊ | 1392/1430 [1:12:26<01:30,  2.38s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▉ | 1393/1430 [1:12:29<01:26,  2.33s/it]

🎯 COPY FLOW:  97%|█████████████████████████████████████████▉ | 1394/1430 [1:12:31<01:22,  2.29s/it]

🎯 COPY FLOW:  98%|█████████████████████████████████████████▉ | 1395/1430 [1:12:36<01:46,  3.05s/it]

🎯 COPY FLOW:  98%|█████████████████████████████████████████▉ | 1396/1430 [1:12:38<01:35,  2.82s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████ | 1397/1430 [1:12:40<01:26,  2.63s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████ | 1398/1430 [1:12:42<01:18,  2.46s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████ | 1399/1430 [1:12:44<01:12,  2.33s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████ | 1400/1430 [1:12:46<01:07,  2.23s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▏| 1401/1430 [1:12:48<01:02,  2.16s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▏| 1402/1430 [1:12:50<00:58,  2.10s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▏| 1403/1430 [1:12:52<00:55,  2.05s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▏| 1404/1430 [1:12:54<00:52,  2.03s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▏| 1405/1430 [1:12:56<00:49,  1.97s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▎| 1406/1430 [1:12:58<00:46,  1.93s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▎| 1407/1430 [1:12:59<00:43,  1.89s/it]

🎯 COPY FLOW:  98%|██████████████████████████████████████████▎| 1408/1430 [1:13:01<00:41,  1.86s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▎| 1409/1430 [1:13:05<00:50,  2.42s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▍| 1410/1430 [1:13:07<00:44,  2.22s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▍| 1411/1430 [1:13:09<00:39,  2.08s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▍| 1412/1430 [1:13:10<00:35,  1.98s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▍| 1413/1430 [1:13:12<00:32,  1.88s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▌| 1414/1430 [1:13:14<00:28,  1.80s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▌| 1415/1430 [1:13:15<00:26,  1.75s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▌| 1416/1430 [1:13:17<00:23,  1.71s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▌| 1417/1430 [1:13:18<00:21,  1.69s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▋| 1418/1430 [1:13:20<00:19,  1.65s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▋| 1419/1430 [1:13:21<00:17,  1.61s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▋| 1420/1430 [1:13:23<00:15,  1.57s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▋| 1421/1430 [1:13:24<00:13,  1.52s/it]

🎯 COPY FLOW:  99%|██████████████████████████████████████████▊| 1422/1430 [1:13:26<00:11,  1.46s/it]

🎯 COPY FLOW: 100%|██████████████████████████████████████████▊| 1423/1430 [1:13:27<00:09,  1.40s/it]

🎯 COPY FLOW: 100%|██████████████████████████████████████████▊| 1424/1430 [1:13:28<00:07,  1.33s/it]

🎯 COPY FLOW: 100%|██████████████████████████████████████████▊| 1425/1430 [1:13:29<00:06,  1.33s/it]

🎯 COPY FLOW: 100%|██████████████████████████████████████████▉| 1426/1430 [1:13:31<00:05,  1.27s/it]

🎯 COPY FLOW: 100%|██████████████████████████████████████████▉| 1427/1430 [1:13:32<00:03,  1.20s/it]

🎯 COPY FLOW: 100%|██████████████████████████████████████████▉| 1428/1430 [1:13:33<00:02,  1.15s/it]

🎯 COPY FLOW: 100%|██████████████████████████████████████████▉| 1429/1430 [1:13:34<00:01,  1.06s/it]




🎯 COPY FLOW:   0%|                                            | 2/1430 [1:15:20<2:51:37,  7.21s/it]
🎯 COPY FLOW:   0%|                                            | 4/1430 [1:14:15<2:39:36,  6.72s/it]

🎯 COPY FLOW: 100%|███████████████████████████████████████████| 1430/1430 [1:13:34<00:00,  3.09s/it]
🎯 COPY FLOW:   0%|                                        | 2/1430 [1:15:20<896:30:04, 2260.09s/it]

📦 Final: _25_SINC_rk_wav_2 (44 files)

✅ Done. Log saved at: /Volumes/MUSIC_PROD/_5_MISC-zarch/_music_SIN/copied_log.csv

In [18]:
# -----######-----###### UNIVERSAL TAB-DELIM IMPORT FIXER -----######-----######
import pandas as pd
import chardet
from collections import Counter

def _readfix_2304_txt_GET_df_autoclean(path_txt):
    """
    Reads a tab-delimited text file with inconsistent columns.
    Automatically:
    - Detects encoding
    - Finds dominant column count
    - Truncates or pads rows
    - Returns clean DataFrame
    """
    # Detect encoding
    with open(path_txt, 'rb') as f:
        raw_data = f.read()
        encoding = chardet.detect(raw_data)['encoding']

    lines = raw_data.decode(encoding).splitlines()

    # Split lines and count how many fields in each
    split_lines = [line.strip().split('\t') for line in lines]
    col_lengths = [len(row) for row in split_lines]
    count_freq = Counter(col_lengths)

    # Determine most common column count
    most_common_len = count_freq.most_common(1)[0][0]

    print(f"\n🧠 Most common column count: {most_common_len}")
    print(f"📊 Full column count distribution:")
    for length, freq in sorted(count_freq.items()):
        print(f"{length} columns → {freq} lines")

    # Use first row (or generate header) and fix all rows to match length
    header = split_lines[0]
    if len(header) != most_common_len:
        print("⚠️ Header length mismatch — fixing with auto header")
        header = [f'col_{i}' for i in range(most_common_len)]
        start_idx = 0
    else:
        start_idx = 1

    fixed_rows = []
    for row in split_lines[start_idx:]:
        if len(row) < most_common_len:
            row.extend([''] * (most_common_len - len(row)))
        elif len(row) > most_common_len:
            row = row[:most_common_len]
        fixed_rows.append(row)

    return pd.DataFrame(fixed_rows, columns=header)

# -----######-----######-----######-----######-----
# CORE FUNCTION TO SUM FILE SIZES IN GB
# -----######-----######-----######-----######-----

import os

def _size_2304_i1_GET_total_gb(df):
    """
    Sums the size of all valid files in df['Path'] and returns total in GB (rounded).
    Prints TQM logs.
    """
    total_bytes = 0
    valid_count = 0

    for path in df['Location']:
        if isinstance(path, str) and os.path.isfile(path):
            try:
                total_bytes += os.path.getsize(path)
                valid_count += 1
            except:
                continue

    total_gb = total_bytes / (1024 ** 3)

    print(f"\nTQM ✅ Completed file scan:")
    print(f"   • Valid Files: {valid_count}")
    print(f"   • Total Size: {total_gb:.2f} GB")

    return round(total_gb, 2)

In [19]:
txt_path = "/Users/yerik/Downloads/col_out_arch.txt"
df = _readfix_2304_txt_GET_df_autoclean(txt_path)

print("\n🔎 COLUMN NAMES:")
for i, col in enumerate(df.columns):
    print(f"{i:>2}: '{col}'")
df.head()

🧠 Most common column count: 21
📊 Full column count distribution:
1 columns → 34 lines
4 columns → 1 lines
5 columns → 17 lines
17 columns → 17 lines
18 columns → 1 lines
21 columns → 4826 lines

🔎 COLUMN NAMES:
 0: '#'
 1: 'File Type'
 2: 'Bitrate'
 3: 'BPM'
 4: 'Key'
 5: 'Track Title'
 6: 'Artist'
 7: 'Artwork'
 8: 'Genre'
 9: 'Label'
10: 'Remixer'
11: 'Release Date'
12: 'Year'
13: 'Location'
14: 'Rating'
15: 'File Name'
16: 'Comments'
17: 'Album'
18: 'Bitdepth'
19: 'Time'
20: 'Date Added'

,#,File Type,Bitrate,BPM,Key,Track Title,Artist,Artwork,Genre,Label,...,Release Date,Year,Location,Rating,File Name,Comments,Album,Bitdepth,Time,Date Added
0,1,WAV,1411 kbps,130.00,12A,Ha Dub(2PeKes Vogue Remix),2PeKes,,,,...,,0,/Users/yerik/Music/_0_OLD_SOURCE/_rk_music_35/...,,b9AOl-8_4Bpm_131_0Key_8B_5cnt-rnk_8B3B8B-123oc...,,,16,03:34,2024-08-08
1,2,AIFF,1411 kbps,131.00,6B,Big Moma Tech (Original Mix),Kyle Hall,,Tech House,DistroKid,...,2023-02-17,2023,/Users/yerik/Music/_0_OLD_SOURCE/_rk_music_51/...,,Big_Moma_Tech-BY-Kyle_Hall_(Original_Mix)_KEY_...,,Baci Ballers EP,16,05:39,2023-10-17
2,3,MP3,192 kbps,131.00,6A,Din Daa Daa (Clean),Baltimore Club,,B-More,,...,,0,/Users/yerik/Music/_0_OLD_SOURCE/_rk_music_130...,*,Din Daa Daa (Clean).mp3,,Bmore,16,03:55,2023-08-15
3,4,MP3,320 kbps,84.00,11B,Freak Hoe,Future,,Rap,Epic,...,,2015,/Users/yerik/Music/_0_OLD_SOURCE/_rk_music_133...,,07. Freak Hoe.mp3,,Dirty Sprite 2 (DS2),16,02:54,2023-08-15
4,5,MP3,320 kbps,127.00,1A,La Cocina Del Cabron (Original Mix),"Lee Van Dowski, Glimpse",,Electronica,Global Underground,...,2010-01-31,2010,/Users/yerik/Music/_0_OLD_SOURCE/_rk_music_193...,,"La_Cocina_Del_Cabron-BY-Lee_Van_Dowski,_Glimps...",,Global Underground #38: Carl Cox - Black Rock ...,16,07:11,2024-09-25

# copy files into a new folder

In [20]:
total_gb = _size_2304_i1_GET_total_gb(df)

TQM ✅ Completed file scan:
   • Valid Files: 4841
   • Total Size: 83.50 GB

In [27]:
# -----######-----###### FIXED COPY LOOP: CORRECT TUPLE UNPACKING -----######-----######
import os
import shutil
import pandas as pd
from tqdm import tqdm

def _fileops_2404_chunkedcopy_GET_genre_sorted_chunks(df, dest_base_path):
    """
    Sorts df by Genre, copies files in chunks of 50 to numbered folders with no filename collisions.
    Adds 'Copied_To' column and saves a CSV log. TQM bar active. No overwrite, all copied.
    """
    tqdm.pandas()
    os.makedirs(dest_base_path, exist_ok=True)
    df = df.copy()

    df = df.sort_values(by='Genre').reset_index(drop=True)
    df['file_name'] = df['Location'].apply(os.path.basename)
    
    copied_to = [None] * len(df)
    folder_idx = 1
    chunk_files = set()
    current_chunk = []

    tq_bar = tqdm(total=len(df), desc="💽 TQM COPY FLOW", ncols=100)

    for idx, row in df.iterrows():
        src = row['Location']
        fname = row['file_name']

        # Start new chunk if needed
        if fname in chunk_files or len(current_chunk) >= 50:
            dest_folder = os.path.join(dest_base_path, f"_24_ARCH_rk_{folder_idx}")
            os.makedirs(dest_folder, exist_ok=True)
            for path, name, i in current_chunk:
                dest_path = os.path.join(dest_folder, name)
                try:
                    shutil.copy2(path, dest_path)
                    copied_to[i] = dest_path
                    tq_bar.update(1)
                except Exception as e:
                    tqdm.write(f"❌ ERROR copying {path} → {dest_path} | {e}")
            tqdm.write(f"📦 Finished chunk: _24_ARCH_rk_{folder_idx} ({len(current_chunk)} files)")

            # Reset chunk
            folder_idx += 1
            chunk_files = set()
            current_chunk = []

        chunk_files.add(fname)
        current_chunk.append((src, fname, idx))

    # Final chunk flush
    if current_chunk:
        dest_folder = os.path.join(dest_base_path, f"_24_ARCH_rk_{folder_idx}")
        os.makedirs(dest_folder, exist_ok=True)
        for path, name, i in current_chunk:
            dest_path = os.path.join(dest_folder, name)
            try:
                shutil.copy2(path, dest_path)
                copied_to[i] = dest_path
                tq_bar.update(1)
            except Exception as e:
                tqdm.write(f"❌ ERROR copying {path} → {dest_path} | {e}")
        tqdm.write(f"📦 Final chunk: _24_ARCH_rk_{folder_idx} ({len(current_chunk)} files)")

    tq_bar.close()
    df['Copied_To'] = copied_to

    # Save log
    log_path = os.path.join(dest_base_path, "copied_log.csv")
    df.to_csv(log_path, index=False)
    print(f"\n✅ Done. Log saved at: {log_path}")
    return df

In [28]:
#!#!#!#!#! RUNNING STATEMENTS #!#!#!#!#!
updated_df = _fileops_2404_chunkedcopy_GET_genre_sorted_chunks(
    df,
    "/Volumes/MY1TB/_24_ARCH_SONGS"
)

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [00:00<?, ?it/s]


💽 TQM COPY FLOW:   0%|                                          | 1/4895 [00:02<3:33:27,  2.62s/it]


💽 TQM COPY FLOW:   0%|                                          | 2/4895 [00:03<1:55:21,  1.41s/it]


💽 TQM COPY FLOW:   0%|                                          | 3/4895 [00:03<1:25:49,  1.05s/it]


💽 TQM COPY FLOW:   0%|                                          | 4/4895 [00:04<1:02:55,  1.30it/s]


💽 TQM COPY FLOW:   0%|                                            | 5/4895 [00:04<54:05,  1.51it/s]


💽 TQM COPY FLOW:   0%|                                            | 6/4895 [00:05<50:27,  1.61it/s]


💽 TQM COPY FLOW:   0%|                                            | 7/4895 [00:06<59:04,  1.38it/s]


💽 TQM COPY FLOW:   0%|                                          | 8/4895 [00:06<1:00:32,  1.35it/s]


💽 TQM COPY FLOW:   0%|                                            | 9/4895 [00:07<54:41,  1.49it/s]


💽 TQM COPY FLOW:   0%|                                           | 10/4895 [00:08<54:04,  1.51it/s]


💽 TQM COPY FLOW:   0%|                                           | 11/4895 [00:08<45:12,  1.80it/s]


💽 TQM COPY FLOW:   0%|                                         | 12/4895 [00:09<1:01:48,  1.32it/s]


💽 TQM COPY FLOW:   0%|                                           | 13/4895 [00:10<56:58,  1.43it/s]


💽 TQM COPY FLOW:   0%|                                           | 14/4895 [00:10<56:54,  1.43it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 15/4895 [00:11<58:35,  1.39it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 16/4895 [00:12<59:43,  1.36it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 17/4895 [00:12<55:50,  1.46it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 18/4895 [00:13<57:27,  1.41it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 19/4895 [00:14<53:18,  1.52it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 20/4895 [00:15<56:18,  1.44it/s]


💽 TQM COPY FLOW:   0%|▏                                        | 21/4895 [00:15<1:02:21,  1.30it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 22/4895 [00:16<53:00,  1.53it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 23/4895 [00:16<49:35,  1.64it/s]


💽 TQM COPY FLOW:   0%|▏                                          | 24/4895 [00:17<50:20,  1.61it/s]


💽 TQM COPY FLOW:   1%|▏                                        | 25/4895 [00:18<1:01:51,  1.31it/s]


💽 TQM COPY FLOW:   1%|▏                                          | 26/4895 [00:19<56:30,  1.44it/s]


💽 TQM COPY FLOW:   1%|▏                                        | 27/4895 [00:20<1:01:02,  1.33it/s]


💽 TQM COPY FLOW:   1%|▏                                          | 28/4895 [00:20<53:07,  1.53it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 29/4895 [00:21<57:18,  1.41it/s]


💽 TQM COPY FLOW:   1%|▎                                        | 30/4895 [00:22<1:07:48,  1.20it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 31/4895 [00:22<52:40,  1.54it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 32/4895 [00:22<40:17,  2.01it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 33/4895 [00:22<31:13,  2.60it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 34/4895 [00:23<27:27,  2.95it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 35/4895 [00:23<37:33,  2.16it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 36/4895 [00:24<32:48,  2.47it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 37/4895 [00:25<43:58,  1.84it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 38/4895 [00:25<35:36,  2.27it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 39/4895 [00:25<34:13,  2.36it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 40/4895 [00:25<30:10,  2.68it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 41/4895 [00:26<28:15,  2.86it/s]


💽 TQM COPY FLOW:   1%|▎                                          | 42/4895 [00:26<29:50,  2.71it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 43/4895 [00:26<27:45,  2.91it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 44/4895 [00:27<32:22,  2.50it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 45/4895 [00:27<35:54,  2.25it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 46/4895 [00:28<38:22,  2.11it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 47/4895 [00:28<35:27,  2.28it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 48/4895 [00:29<34:27,  2.34it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 49/4895 [00:29<35:25,  2.28it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [06:28<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [00:57<?, ?it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 50/4895 [00:30<42:55,  1.88it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [01:04<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_1 (50 files)

💽 TQM COPY FLOW:   1%|▍                                          | 51/4895 [00:31<51:13,  1.58it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 52/4895 [00:31<51:31,  1.57it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 53/4895 [00:32<42:32,  1.90it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 54/4895 [00:32<39:34,  2.04it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 55/4895 [00:32<33:52,  2.38it/s]


💽 TQM COPY FLOW:   1%|▍                                          | 56/4895 [00:33<42:15,  1.91it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 57/4895 [00:34<43:57,  1.83it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 58/4895 [00:35<55:29,  1.45it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 59/4895 [00:35<43:16,  1.86it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 60/4895 [00:35<43:18,  1.86it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 61/4895 [00:36<40:34,  1.99it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 62/4895 [00:36<42:09,  1.91it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 63/4895 [00:37<40:45,  1.98it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 64/4895 [00:37<35:48,  2.25it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 65/4895 [00:37<28:24,  2.83it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 66/4895 [00:38<30:56,  2.60it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 67/4895 [00:39<40:03,  2.01it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 68/4895 [00:39<43:20,  1.86it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 69/4895 [00:39<34:26,  2.34it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 70/4895 [00:40<35:40,  2.25it/s]


💽 TQM COPY FLOW:   1%|▌                                          | 71/4895 [00:40<33:52,  2.37it/s]


💽 TQM COPY FLOW:   1%|▋                                          | 72/4895 [00:41<32:04,  2.51it/s]


💽 TQM COPY FLOW:   1%|▋                                          | 73/4895 [00:41<28:46,  2.79it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 74/4895 [00:41<30:06,  2.67it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 76/4895 [00:42<20:27,  3.93it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 77/4895 [00:42<22:50,  3.52it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 78/4895 [00:42<26:12,  3.06it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 79/4895 [00:43<33:31,  2.39it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 80/4895 [00:43<31:35,  2.54it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 81/4895 [00:44<31:49,  2.52it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 82/4895 [00:44<29:30,  2.72it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 83/4895 [00:45<32:26,  2.47it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 84/4895 [00:45<33:24,  2.40it/s]


💽 TQM COPY FLOW:   2%|▋                                          | 85/4895 [00:46<38:32,  2.08it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 86/4895 [00:46<40:03,  2.00it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 87/4895 [00:47<37:41,  2.13it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 88/4895 [00:47<35:56,  2.23it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 89/4895 [00:47<34:30,  2.32it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 90/4895 [00:48<39:08,  2.05it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 91/4895 [00:48<36:02,  2.22it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 92/4895 [00:49<33:03,  2.42it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [06:47<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [01:16<?, ?it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [00:49<30:48,  2.60it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [01:23<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_2/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:   2%|▊                                          | 95/4895 [00:49<21:40,  3.69it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 96/4895 [00:50<34:40,  2.31it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 97/4895 [00:51<33:45,  2.37it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 98/4895 [00:51<30:18,  2.64it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [06:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [01:19<?, ?it/s]


💽 TQM COPY FLOW:   2%|▊                                          | 99/4895 [00:51<30:39,  2.61it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [01:25<?, ?it/s]


💽 TQM COPY FLOW:   2%|▊                                         | 100/4895 [00:51<26:25,  3.02it/s]

📦 Finished chunk: _24_ARCH_rk_2 (50 files)

💽 TQM COPY FLOW:   2%|▊                                         | 101/4895 [00:52<39:40,  2.01it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 102/4895 [00:53<46:00,  1.74it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 103/4895 [00:53<35:39,  2.24it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 104/4895 [00:53<29:36,  2.70it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 105/4895 [00:54<23:15,  3.43it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 106/4895 [00:54<36:34,  2.18it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 107/4895 [00:55<49:08,  1.62it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 108/4895 [00:56<48:18,  1.65it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 109/4895 [00:56<39:10,  2.04it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 110/4895 [00:57<36:57,  2.16it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 111/4895 [00:57<33:44,  2.36it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 112/4895 [00:57<36:29,  2.18it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 113/4895 [00:58<31:50,  2.50it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 114/4895 [00:58<37:03,  2.15it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 115/4895 [00:59<31:49,  2.50it/s]


💽 TQM COPY FLOW:   2%|▉                                         | 116/4895 [00:59<26:04,  3.06it/s]


💽 TQM COPY FLOW:   2%|█                                         | 117/4895 [00:59<26:49,  2.97it/s]


💽 TQM COPY FLOW:   2%|█                                         | 118/4895 [00:59<25:35,  3.11it/s]


💽 TQM COPY FLOW:   2%|█                                         | 119/4895 [01:01<45:26,  1.75it/s]


💽 TQM COPY FLOW:   2%|█                                         | 120/4895 [01:01<45:10,  1.76it/s]


💽 TQM COPY FLOW:   2%|█                                         | 121/4895 [01:02<49:45,  1.60it/s]


💽 TQM COPY FLOW:   2%|█                                         | 122/4895 [01:02<37:42,  2.11it/s]


💽 TQM COPY FLOW:   3%|█                                         | 123/4895 [01:03<41:24,  1.92it/s]


💽 TQM COPY FLOW:   3%|█                                         | 124/4895 [01:03<36:01,  2.21it/s]


💽 TQM COPY FLOW:   3%|█                                         | 125/4895 [01:04<46:41,  1.70it/s]


💽 TQM COPY FLOW:   3%|█                                         | 126/4895 [01:04<45:33,  1.74it/s]


💽 TQM COPY FLOW:   3%|█                                       | 127/4895 [01:06<1:06:34,  1.19it/s]


💽 TQM COPY FLOW:   3%|█                                       | 128/4895 [01:06<1:02:00,  1.28it/s]


💽 TQM COPY FLOW:   3%|█                                       | 129/4895 [01:07<1:03:34,  1.25it/s]


💽 TQM COPY FLOW:   3%|█                                       | 130/4895 [01:08<1:06:25,  1.20it/s]


💽 TQM COPY FLOW:   3%|█                                       | 131/4895 [01:10<1:26:19,  1.09s/it]


💽 TQM COPY FLOW:   3%|█                                       | 132/4895 [01:11<1:23:18,  1.05s/it]


💽 TQM COPY FLOW:   3%|█                                       | 133/4895 [01:11<1:11:49,  1.11it/s]


💽 TQM COPY FLOW:   3%|█                                       | 134/4895 [01:12<1:02:39,  1.27it/s]


💽 TQM COPY FLOW:   3%|█▏                                        | 135/4895 [01:12<54:35,  1.45it/s]


💽 TQM COPY FLOW:   3%|█                                       | 136/4895 [01:13<1:04:13,  1.24it/s]


💽 TQM COPY FLOW:   3%|█                                       | 137/4895 [01:14<1:00:24,  1.31it/s]


💽 TQM COPY FLOW:   3%|█▏                                      | 138/4895 [01:15<1:02:16,  1.27it/s]


💽 TQM COPY FLOW:   3%|█▏                                        | 139/4895 [01:15<55:35,  1.43it/s]


💽 TQM COPY FLOW:   3%|█▏                                        | 140/4895 [01:16<53:29,  1.48it/s]


💽 TQM COPY FLOW:   3%|█▏                                        | 141/4895 [01:17<47:53,  1.65it/s]


💽 TQM COPY FLOW:   3%|█▏                                        | 142/4895 [01:17<52:33,  1.51it/s]


💽 TQM COPY FLOW:   3%|█▏                                      | 143/4895 [01:20<1:43:14,  1.30s/it]


💽 TQM COPY FLOW:   3%|█▏                                      | 144/4895 [01:20<1:20:08,  1.01s/it]


💽 TQM COPY FLOW:   3%|█▏                                      | 145/4895 [01:21<1:16:08,  1.04it/s]


💽 TQM COPY FLOW:   3%|█▏                                      | 146/4895 [01:23<1:36:11,  1.22s/it]


💽 TQM COPY FLOW:   3%|█▏                                      | 147/4895 [01:24<1:22:18,  1.04s/it]


💽 TQM COPY FLOW:   3%|█▏                                      | 148/4895 [01:25<1:22:54,  1.05s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [07:23<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [01:53<?, ?it/s]


💽 TQM COPY FLOW:   3%|█▏                                      | 149/4895 [01:25<1:13:31,  1.08it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [01:59<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_3 (50 files)

💽 TQM COPY FLOW:   3%|█▎                                        | 150/4895 [01:26<57:11,  1.38it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 151/4895 [01:26<46:31,  1.70it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 152/4895 [01:27<48:48,  1.62it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 153/4895 [01:27<43:04,  1.83it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 154/4895 [01:28<46:46,  1.69it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 155/4895 [01:28<45:57,  1.72it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 156/4895 [01:28<36:43,  2.15it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 157/4895 [01:29<33:21,  2.37it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 158/4895 [01:29<29:01,  2.72it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 159/4895 [01:29<29:24,  2.68it/s]


💽 TQM COPY FLOW:   3%|█▎                                        | 160/4895 [01:30<24:55,  3.17it/s]


💽 TQM COPY FLOW:   3%|█▍                                        | 161/4895 [01:30<23:43,  3.33it/s]


💽 TQM COPY FLOW:   3%|█▎                                      | 162/4895 [01:33<1:37:00,  1.23s/it]


💽 TQM COPY FLOW:   3%|█▎                                      | 163/4895 [01:36<2:09:47,  1.65s/it]


💽 TQM COPY FLOW:   3%|█▎                                      | 164/4895 [01:38<2:32:02,  1.93s/it]


💽 TQM COPY FLOW:   3%|█▎                                      | 165/4895 [01:41<2:45:46,  2.10s/it]


💽 TQM COPY FLOW:   3%|█▎                                      | 166/4895 [01:44<3:05:36,  2.35s/it]


💽 TQM COPY FLOW:   3%|█▎                                      | 167/4895 [01:45<2:23:45,  1.82s/it]


💽 TQM COPY FLOW:   3%|█▎                                      | 168/4895 [01:45<1:56:11,  1.47s/it]


💽 TQM COPY FLOW:   3%|█▍                                      | 169/4895 [01:46<1:32:59,  1.18s/it]


💽 TQM COPY FLOW:   3%|█▍                                      | 170/4895 [01:47<1:31:51,  1.17s/it]


💽 TQM COPY FLOW:   3%|█▍                                      | 171/4895 [01:48<1:30:51,  1.15s/it]


💽 TQM COPY FLOW:   4%|█▍                                      | 172/4895 [01:48<1:11:26,  1.10it/s]


💽 TQM COPY FLOW:   4%|█▍                                        | 173/4895 [01:49<59:51,  1.31it/s]


💽 TQM COPY FLOW:   4%|█▍                                      | 174/4895 [01:50<1:10:00,  1.12it/s]


💽 TQM COPY FLOW:   4%|█▍                                      | 175/4895 [01:51<1:13:13,  1.07it/s]


💽 TQM COPY FLOW:   4%|█▍                                      | 176/4895 [01:51<1:02:05,  1.27it/s]


💽 TQM COPY FLOW:   4%|█▌                                        | 177/4895 [01:52<52:42,  1.49it/s]


💽 TQM COPY FLOW:   4%|█▌                                        | 178/4895 [01:52<51:55,  1.51it/s]


💽 TQM COPY FLOW:   4%|█▍                                      | 179/4895 [01:54<1:03:05,  1.25it/s]


💽 TQM COPY FLOW:   4%|█▍                                      | 180/4895 [01:56<1:52:31,  1.43s/it]


💽 TQM COPY FLOW:   4%|█▍                                      | 181/4895 [01:58<1:55:18,  1.47s/it]


💽 TQM COPY FLOW:   4%|█▍                                      | 182/4895 [01:58<1:32:23,  1.18s/it]


💽 TQM COPY FLOW:   4%|█▍                                      | 183/4895 [02:00<1:33:22,  1.19s/it]


💽 TQM COPY FLOW:   4%|█▌                                      | 184/4895 [02:01<1:32:40,  1.18s/it]


💽 TQM COPY FLOW:   4%|█▌                                      | 185/4895 [02:03<2:05:18,  1.60s/it]


💽 TQM COPY FLOW:   4%|█▌                                      | 186/4895 [02:04<1:48:18,  1.38s/it]


💽 TQM COPY FLOW:   4%|█▌                                      | 187/4895 [02:05<1:37:34,  1.24s/it]


💽 TQM COPY FLOW:   4%|█▌                                      | 188/4895 [02:06<1:25:42,  1.09s/it]


💽 TQM COPY FLOW:   4%|█▌                                      | 189/4895 [02:06<1:11:05,  1.10it/s]


💽 TQM COPY FLOW:   4%|█▌                                      | 190/4895 [02:07<1:02:23,  1.26it/s]


💽 TQM COPY FLOW:   4%|█▋                                        | 191/4895 [02:08<58:19,  1.34it/s]


💽 TQM COPY FLOW:   4%|█▌                                      | 192/4895 [02:09<1:03:12,  1.24it/s]


💽 TQM COPY FLOW:   4%|█▌                                      | 193/4895 [02:10<1:13:19,  1.07it/s]


💽 TQM COPY FLOW:   4%|█▌                                      | 194/4895 [02:11<1:12:59,  1.07it/s]


💽 TQM COPY FLOW:   4%|█▌                                      | 195/4895 [02:11<1:09:26,  1.13it/s]


💽 TQM COPY FLOW:   4%|█▌                                      | 196/4895 [02:13<1:12:57,  1.07it/s]


💽 TQM COPY FLOW:   4%|█▋                                        | 197/4895 [02:13<56:49,  1.38it/s]


💽 TQM COPY FLOW:   4%|█▋                                        | 198/4895 [02:13<55:21,  1.41it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [08:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [02:41<?, ?it/s]


💽 TQM COPY FLOW:   4%|█▋                                        | 199/4895 [02:14<50:07,  1.56it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [02:48<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_4 (50 files)

💽 TQM COPY FLOW:   4%|█▋                                        | 200/4895 [02:14<43:46,  1.79it/s]


💽 TQM COPY FLOW:   4%|█▋                                        | 201/4895 [02:15<37:23,  2.09it/s]


💽 TQM COPY FLOW:   4%|█▋                                        | 202/4895 [02:15<44:24,  1.76it/s]


💽 TQM COPY FLOW:   4%|█▋                                        | 203/4895 [02:16<41:25,  1.89it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 204/4895 [02:16<37:11,  2.10it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 205/4895 [02:17<53:19,  1.47it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 206/4895 [02:18<47:27,  1.65it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 207/4895 [02:18<38:09,  2.05it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 208/4895 [02:18<29:34,  2.64it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 209/4895 [02:19<34:31,  2.26it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 210/4895 [02:19<30:58,  2.52it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 211/4895 [02:19<33:48,  2.31it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 212/4895 [02:20<32:06,  2.43it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 213/4895 [02:20<25:46,  3.03it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 214/4895 [02:20<24:28,  3.19it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 215/4895 [02:21<33:48,  2.31it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 216/4895 [02:22<38:48,  2.01it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 217/4895 [02:22<42:14,  1.85it/s]


💽 TQM COPY FLOW:   4%|█▊                                        | 218/4895 [02:23<51:16,  1.52it/s]


💽 TQM COPY FLOW:   4%|█▊                                      | 219/4895 [02:25<1:08:15,  1.14it/s]


💽 TQM COPY FLOW:   4%|█▊                                      | 220/4895 [02:25<1:00:23,  1.29it/s]


💽 TQM COPY FLOW:   5%|█▊                                      | 221/4895 [02:28<1:43:14,  1.33s/it]


💽 TQM COPY FLOW:   5%|█▊                                      | 222/4895 [02:28<1:29:21,  1.15s/it]


💽 TQM COPY FLOW:   5%|█▊                                      | 223/4895 [02:30<1:29:32,  1.15s/it]


💽 TQM COPY FLOW:   5%|█▊                                      | 224/4895 [02:30<1:11:07,  1.09it/s]


💽 TQM COPY FLOW:   5%|█▉                                        | 225/4895 [02:30<54:31,  1.43it/s]


💽 TQM COPY FLOW:   5%|█▊                                      | 226/4895 [02:31<1:08:36,  1.13it/s]


💽 TQM COPY FLOW:   5%|█▊                                      | 227/4895 [02:36<2:31:12,  1.94s/it]


💽 TQM COPY FLOW:   5%|█▊                                      | 228/4895 [02:36<1:58:24,  1.52s/it]


💽 TQM COPY FLOW:   5%|█▊                                      | 229/4895 [02:38<1:52:02,  1.44s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 230/4895 [02:39<1:39:20,  1.28s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 231/4895 [02:40<1:46:47,  1.37s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 232/4895 [02:42<1:56:27,  1.50s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 233/4895 [02:43<1:50:55,  1.43s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 234/4895 [02:47<2:36:09,  2.01s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 235/4895 [02:48<2:19:44,  1.80s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 236/4895 [02:48<1:48:06,  1.39s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 237/4895 [02:49<1:31:42,  1.18s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 238/4895 [02:50<1:26:57,  1.12s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 239/4895 [02:52<1:48:41,  1.40s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 240/4895 [02:53<1:41:33,  1.31s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 241/4895 [02:54<1:23:51,  1.08s/it]


💽 TQM COPY FLOW:   5%|█▉                                      | 242/4895 [02:54<1:07:04,  1.16it/s]


💽 TQM COPY FLOW:   5%|██                                        | 243/4895 [02:55<58:32,  1.32it/s]


💽 TQM COPY FLOW:   5%|██                                        | 244/4895 [02:55<49:00,  1.58it/s]


💽 TQM COPY FLOW:   5%|██                                        | 245/4895 [02:55<47:16,  1.64it/s]


💽 TQM COPY FLOW:   5%|██                                        | 246/4895 [02:56<40:30,  1.91it/s]


💽 TQM COPY FLOW:   5%|██                                        | 247/4895 [02:56<40:25,  1.92it/s]


💽 TQM COPY FLOW:   5%|██                                      | 248/4895 [02:58<1:00:50,  1.27it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [08:56<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [03:26<?, ?it/s]


💽 TQM COPY FLOW:   5%|██                                      | 249/4895 [02:59<1:02:28,  1.24it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [03:32<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_5 (50 files)

💽 TQM COPY FLOW:   5%|██▏                                       | 250/4895 [02:59<56:55,  1.36it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 251/4895 [03:00<48:42,  1.59it/s]


💽 TQM COPY FLOW:   5%|██                                      | 252/4895 [03:01<1:08:09,  1.14it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 253/4895 [03:01<53:46,  1.44it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 254/4895 [03:02<50:28,  1.53it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 255/4895 [03:02<48:09,  1.61it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 256/4895 [03:03<57:11,  1.35it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 257/4895 [03:04<49:26,  1.56it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 258/4895 [03:05<51:42,  1.49it/s]


💽 TQM COPY FLOW:   5%|██                                      | 259/4895 [03:06<1:02:45,  1.23it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 260/4895 [03:06<54:02,  1.43it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 261/4895 [03:07<51:25,  1.50it/s]


💽 TQM COPY FLOW:   5%|██▏                                       | 262/4895 [03:07<51:38,  1.50it/s]


💽 TQM COPY FLOW:   5%|██▎                                       | 263/4895 [03:08<53:54,  1.43it/s]


💽 TQM COPY FLOW:   5%|██▎                                       | 264/4895 [03:08<43:46,  1.76it/s]


💽 TQM COPY FLOW:   5%|██▎                                       | 265/4895 [03:09<42:21,  1.82it/s]


💽 TQM COPY FLOW:   5%|██▎                                       | 266/4895 [03:09<42:18,  1.82it/s]


💽 TQM COPY FLOW:   5%|██▎                                       | 267/4895 [03:10<41:58,  1.84it/s]


💽 TQM COPY FLOW:   5%|██▎                                       | 268/4895 [03:11<46:00,  1.68it/s]


💽 TQM COPY FLOW:   5%|██▎                                       | 269/4895 [03:11<42:55,  1.80it/s]


💽 TQM COPY FLOW:   6%|██▎                                       | 270/4895 [03:12<38:28,  2.00it/s]


💽 TQM COPY FLOW:   6%|██▎                                       | 271/4895 [03:12<40:43,  1.89it/s]


💽 TQM COPY FLOW:   6%|██▎                                       | 272/4895 [03:13<40:07,  1.92it/s]


💽 TQM COPY FLOW:   6%|██▎                                       | 273/4895 [03:13<46:46,  1.65it/s]


💽 TQM COPY FLOW:   6%|██▎                                       | 274/4895 [03:14<57:04,  1.35it/s]


💽 TQM COPY FLOW:   6%|██▏                                     | 275/4895 [03:16<1:11:49,  1.07it/s]


💽 TQM COPY FLOW:   6%|██▎                                     | 276/4895 [03:17<1:06:01,  1.17it/s]


💽 TQM COPY FLOW:   6%|██▍                                       | 277/4895 [03:17<56:46,  1.36it/s]


💽 TQM COPY FLOW:   6%|██▍                                       | 278/4895 [03:18<54:33,  1.41it/s]


💽 TQM COPY FLOW:   6%|██▍                                       | 279/4895 [03:18<46:51,  1.64it/s]


💽 TQM COPY FLOW:   6%|██▎                                     | 280/4895 [03:20<1:07:12,  1.14it/s]


💽 TQM COPY FLOW:   6%|██▎                                     | 281/4895 [03:20<1:01:39,  1.25it/s]


💽 TQM COPY FLOW:   6%|██▍                                       | 282/4895 [03:20<49:22,  1.56it/s]


💽 TQM COPY FLOW:   6%|██▍                                       | 283/4895 [03:21<45:23,  1.69it/s]


💽 TQM COPY FLOW:   6%|██▍                                       | 284/4895 [03:22<53:04,  1.45it/s]


💽 TQM COPY FLOW:   6%|██▎                                     | 285/4895 [03:27<2:34:53,  2.02s/it]


💽 TQM COPY FLOW:   6%|██▎                                     | 286/4895 [03:28<2:05:18,  1.63s/it]


💽 TQM COPY FLOW:   6%|██▎                                     | 287/4895 [03:28<1:47:00,  1.39s/it]


💽 TQM COPY FLOW:   6%|██▎                                     | 288/4895 [03:29<1:25:20,  1.11s/it]


💽 TQM COPY FLOW:   6%|██▎                                     | 289/4895 [03:30<1:15:21,  1.02it/s]


💽 TQM COPY FLOW:   6%|██▎                                     | 290/4895 [03:30<1:04:43,  1.19it/s]


💽 TQM COPY FLOW:   6%|██▍                                       | 291/4895 [03:30<52:54,  1.45it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 292/4895 [03:31<52:44,  1.45it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 293/4895 [03:32<48:20,  1.59it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 294/4895 [03:32<41:44,  1.84it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 295/4895 [03:32<39:58,  1.92it/s]


💽 TQM COPY FLOW:   6%|██▍                                     | 296/4895 [03:34<1:00:12,  1.27it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 297/4895 [03:34<54:47,  1.40it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 298/4895 [03:35<44:19,  1.73it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [09:34<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [04:04<?, ?it/s]


💽 TQM COPY FLOW:   6%|██▍                                     | 299/4895 [03:36<1:08:58,  1.11it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [04:10<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_6 (50 files)

💽 TQM COPY FLOW:   6%|██▍                                     | 300/4895 [03:38<1:22:03,  1.07s/it]


💽 TQM COPY FLOW:   6%|██▍                                     | 301/4895 [03:39<1:32:02,  1.20s/it]


💽 TQM COPY FLOW:   6%|██▍                                     | 302/4895 [03:40<1:18:16,  1.02s/it]


💽 TQM COPY FLOW:   6%|██▍                                     | 303/4895 [03:40<1:02:25,  1.23it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 304/4895 [03:41<52:02,  1.47it/s]


💽 TQM COPY FLOW:   6%|██▌                                       | 305/4895 [03:41<41:01,  1.86it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 306/4895 [03:41<37:00,  2.07it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 307/4895 [03:42<38:19,  2.00it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 308/4895 [03:42<36:51,  2.07it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 309/4895 [03:43<37:49,  2.02it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 310/4895 [03:43<39:43,  1.92it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 311/4895 [03:43<30:42,  2.49it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 312/4895 [03:44<34:30,  2.21it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 313/4895 [03:44<34:10,  2.23it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 314/4895 [03:45<34:15,  2.23it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 315/4895 [03:45<37:23,  2.04it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 316/4895 [03:46<39:10,  1.95it/s]


💽 TQM COPY FLOW:   6%|██▋                                       | 317/4895 [03:46<37:29,  2.04it/s]


💽 TQM COPY FLOW:   6%|██▌                                     | 318/4895 [03:50<1:42:27,  1.34s/it]


💽 TQM COPY FLOW:   7%|██▌                                     | 319/4895 [03:50<1:23:54,  1.10s/it]


💽 TQM COPY FLOW:   7%|██▌                                     | 320/4895 [03:51<1:05:31,  1.16it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 321/4895 [03:51<59:47,  1.28it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 322/4895 [03:52<50:32,  1.51it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 323/4895 [03:52<43:47,  1.74it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 324/4895 [03:52<42:16,  1.80it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 325/4895 [03:53<52:16,  1.46it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 326/4895 [03:54<48:44,  1.56it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 327/4895 [03:55<47:46,  1.59it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 328/4895 [03:55<36:02,  2.11it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 329/4895 [03:55<33:43,  2.26it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 330/4895 [03:55<32:31,  2.34it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 331/4895 [03:56<27:40,  2.75it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 332/4895 [03:56<24:44,  3.07it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 333/4895 [03:56<28:15,  2.69it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 334/4895 [03:57<30:49,  2.47it/s]


💽 TQM COPY FLOW:   7%|██▊                                       | 335/4895 [03:57<32:22,  2.35it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 336/4895 [03:58<30:04,  2.53it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 337/4895 [03:58<29:03,  2.61it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 338/4895 [03:58<29:05,  2.61it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 340/4895 [03:59<19:16,  3.94it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 341/4895 [03:59<20:43,  3.66it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 342/4895 [03:59<26:25,  2.87it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 343/4895 [04:00<26:38,  2.85it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 344/4895 [04:00<32:11,  2.36it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 345/4895 [04:01<39:52,  1.90it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 346/4895 [04:02<36:02,  2.10it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 347/4895 [04:03<47:24,  1.60it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 348/4895 [04:03<39:03,  1.94it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [10:01<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [04:31<?, ?it/s]


💽 TQM COPY FLOW:   7%|██▉                                       | 349/4895 [04:03<37:05,  2.04it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [04:37<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_7 (50 files)

💽 TQM COPY FLOW:   7%|███                                       | 350/4895 [04:04<43:36,  1.74it/s]


💽 TQM COPY FLOW:   7%|███                                       | 351/4895 [04:04<39:37,  1.91it/s]


💽 TQM COPY FLOW:   7%|███                                       | 352/4895 [04:06<52:54,  1.43it/s]


💽 TQM COPY FLOW:   7%|███                                       | 353/4895 [04:06<40:17,  1.88it/s]


💽 TQM COPY FLOW:   7%|███                                       | 354/4895 [04:07<49:24,  1.53it/s]


💽 TQM COPY FLOW:   7%|███                                       | 355/4895 [04:07<42:28,  1.78it/s]


💽 TQM COPY FLOW:   7%|███                                       | 356/4895 [04:07<33:06,  2.28it/s]


💽 TQM COPY FLOW:   7%|███                                       | 357/4895 [04:07<26:13,  2.88it/s]


💽 TQM COPY FLOW:   7%|███                                       | 358/4895 [04:08<26:09,  2.89it/s]


💽 TQM COPY FLOW:   7%|███                                       | 359/4895 [04:08<27:20,  2.77it/s]


💽 TQM COPY FLOW:   7%|███                                       | 360/4895 [04:09<30:16,  2.50it/s]


💽 TQM COPY FLOW:   7%|███                                       | 361/4895 [04:09<36:36,  2.06it/s]


💽 TQM COPY FLOW:   7%|███                                       | 362/4895 [04:10<38:32,  1.96it/s]


💽 TQM COPY FLOW:   7%|███                                       | 363/4895 [04:10<40:32,  1.86it/s]


💽 TQM COPY FLOW:   7%|███                                       | 364/4895 [04:11<46:00,  1.64it/s]


💽 TQM COPY FLOW:   7%|███▏                                      | 365/4895 [04:12<43:00,  1.76it/s]


💽 TQM COPY FLOW:   7%|███▏                                      | 366/4895 [04:12<32:45,  2.30it/s]


💽 TQM COPY FLOW:   7%|███▏                                      | 367/4895 [04:13<42:10,  1.79it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 368/4895 [04:13<48:08,  1.57it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 369/4895 [04:14<39:44,  1.90it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 370/4895 [04:14<35:16,  2.14it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 371/4895 [04:15<41:55,  1.80it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 372/4895 [04:15<45:14,  1.67it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 373/4895 [04:16<38:22,  1.96it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 374/4895 [04:16<39:12,  1.92it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 375/4895 [04:17<33:17,  2.26it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 376/4895 [04:17<29:59,  2.51it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 377/4895 [04:17<29:57,  2.51it/s]


💽 TQM COPY FLOW:   8%|███▏                                      | 378/4895 [04:17<24:47,  3.04it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 379/4895 [04:18<21:56,  3.43it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 380/4895 [04:18<21:47,  3.45it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 381/4895 [04:18<21:16,  3.54it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 382/4895 [04:19<23:15,  3.23it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 383/4895 [04:19<18:41,  4.02it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 384/4895 [04:19<30:06,  2.50it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 385/4895 [04:20<29:21,  2.56it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 386/4895 [04:20<24:05,  3.12it/s]


💽 TQM COPY FLOW:   8%|███▎                                      | 387/4895 [04:20<28:46,  2.61it/s]


💽 TQM COPY FLOW:   8%|███▏                                    | 388/4895 [04:34<5:35:04,  4.46s/it]


💽 TQM COPY FLOW:   8%|███▏                                    | 389/4895 [04:35<4:00:37,  3.20s/it]


💽 TQM COPY FLOW:   8%|███▏                                    | 390/4895 [04:35<2:58:42,  2.38s/it]


💽 TQM COPY FLOW:   8%|███▏                                    | 391/4895 [04:36<2:19:17,  1.86s/it]


💽 TQM COPY FLOW:   8%|███▏                                    | 392/4895 [04:36<1:48:10,  1.44s/it]


💽 TQM COPY FLOW:   8%|███▏                                    | 393/4895 [04:37<1:34:26,  1.26s/it]


💽 TQM COPY FLOW:   8%|███▏                                    | 394/4895 [04:38<1:16:44,  1.02s/it]


💽 TQM COPY FLOW:   8%|███▏                                    | 395/4895 [04:38<1:03:33,  1.18it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 396/4895 [04:38<52:24,  1.43it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 397/4895 [04:39<49:50,  1.50it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 398/4895 [04:40<52:20,  1.43it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [10:39<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [05:08<?, ?it/s]


💽 TQM COPY FLOW:   8%|███▎                                    | 399/4895 [04:41<1:00:09,  1.25it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [05:14<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_8 (50 files)

💽 TQM COPY FLOW:   8%|███▍                                      | 400/4895 [04:41<50:57,  1.47it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 401/4895 [04:42<43:10,  1.74it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 402/4895 [04:42<41:27,  1.81it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 403/4895 [04:43<42:46,  1.75it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 404/4895 [04:43<45:50,  1.63it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 405/4895 [04:44<43:14,  1.73it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 406/4895 [04:44<40:55,  1.83it/s]


💽 TQM COPY FLOW:   8%|███▍                                      | 407/4895 [04:45<41:26,  1.80it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 408/4895 [04:46<56:36,  1.32it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 409/4895 [04:47<54:41,  1.37it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 410/4895 [04:48<57:28,  1.30it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 411/4895 [04:48<51:55,  1.44it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 412/4895 [04:49<57:01,  1.31it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 413/4895 [04:50<54:12,  1.38it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 414/4895 [04:50<50:51,  1.47it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 415/4895 [04:51<41:21,  1.81it/s]


💽 TQM COPY FLOW:   8%|███▌                                      | 416/4895 [04:51<40:53,  1.83it/s]


💽 TQM COPY FLOW:   9%|███▌                                      | 417/4895 [04:52<44:54,  1.66it/s]


💽 TQM COPY FLOW:   9%|███▌                                      | 418/4895 [04:52<37:45,  1.98it/s]


💽 TQM COPY FLOW:   9%|███▌                                      | 419/4895 [04:53<41:44,  1.79it/s]


💽 TQM COPY FLOW:   9%|███▌                                      | 420/4895 [04:53<43:26,  1.72it/s]


💽 TQM COPY FLOW:   9%|███▌                                      | 421/4895 [04:54<41:17,  1.81it/s]


💽 TQM COPY FLOW:   9%|███▌                                      | 422/4895 [04:55<50:35,  1.47it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 423/4895 [04:56<59:04,  1.26it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 424/4895 [04:57<55:07,  1.35it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 425/4895 [04:57<56:48,  1.31it/s]


💽 TQM COPY FLOW:   9%|███▍                                    | 426/4895 [04:59<1:09:47,  1.07it/s]


💽 TQM COPY FLOW:   9%|███▍                                    | 427/4895 [05:00<1:13:15,  1.02it/s]


💽 TQM COPY FLOW:   9%|███▍                                    | 428/4895 [05:01<1:16:10,  1.02s/it]


💽 TQM COPY FLOW:   9%|███▌                                    | 429/4895 [05:02<1:09:25,  1.07it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 430/4895 [05:02<58:42,  1.27it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 431/4895 [05:03<51:41,  1.44it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 432/4895 [05:03<41:55,  1.77it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 433/4895 [05:04<45:01,  1.65it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 434/4895 [05:04<44:47,  1.66it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 435/4895 [05:05<45:09,  1.65it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 436/4895 [05:05<42:37,  1.74it/s]


💽 TQM COPY FLOW:   9%|███▋                                      | 437/4895 [05:06<40:23,  1.84it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 438/4895 [05:07<57:22,  1.29it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 439/4895 [05:08<54:39,  1.36it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 440/4895 [05:08<54:17,  1.37it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 441/4895 [05:09<51:29,  1.44it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 442/4895 [05:10<51:48,  1.43it/s]


💽 TQM COPY FLOW:   9%|███▌                                    | 443/4895 [05:11<1:01:57,  1.20it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 444/4895 [05:11<52:43,  1.41it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 445/4895 [05:11<41:10,  1.80it/s]


💽 TQM COPY FLOW:   9%|███▊                                      | 446/4895 [05:13<52:57,  1.40it/s]


💽 TQM COPY FLOW:   9%|███▋                                    | 447/4895 [05:14<1:03:16,  1.17it/s]


💽 TQM COPY FLOW:   9%|███▋                                    | 448/4895 [05:19<2:49:30,  2.29s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [11:18<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [05:47<?, ?it/s]


💽 TQM COPY FLOW:   9%|███▋                                    | 449/4895 [05:20<2:06:49,  1.71s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [05:53<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_9 (50 files)

💽 TQM COPY FLOW:   9%|███▋                                    | 450/4895 [05:20<1:39:56,  1.35s/it]


💽 TQM COPY FLOW:   9%|███▋                                    | 451/4895 [05:21<1:22:00,  1.11s/it]


💽 TQM COPY FLOW:   9%|███▋                                    | 452/4895 [05:21<1:13:20,  1.01it/s]


💽 TQM COPY FLOW:   9%|███▋                                    | 453/4895 [05:23<1:19:23,  1.07s/it]


💽 TQM COPY FLOW:   9%|███▋                                    | 454/4895 [05:23<1:04:43,  1.14it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 455/4895 [05:24<53:31,  1.38it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 456/4895 [05:24<49:14,  1.50it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 457/4895 [05:25<45:10,  1.64it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 458/4895 [05:25<39:41,  1.86it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 459/4895 [05:25<36:11,  2.04it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 460/4895 [05:26<32:07,  2.30it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 461/4895 [05:26<34:16,  2.16it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 462/4895 [05:27<37:15,  1.98it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 463/4895 [05:27<35:06,  2.10it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 464/4895 [05:28<45:10,  1.64it/s]


💽 TQM COPY FLOW:   9%|███▉                                      | 465/4895 [05:28<37:22,  1.98it/s]


💽 TQM COPY FLOW:  10%|███▉                                      | 466/4895 [05:29<35:59,  2.05it/s]


💽 TQM COPY FLOW:  10%|████                                      | 467/4895 [05:29<35:39,  2.07it/s]


💽 TQM COPY FLOW:  10%|████                                      | 468/4895 [05:30<45:38,  1.62it/s]


💽 TQM COPY FLOW:  10%|████                                      | 469/4895 [05:31<52:48,  1.40it/s]


💽 TQM COPY FLOW:  10%|████                                      | 470/4895 [05:32<53:08,  1.39it/s]


💽 TQM COPY FLOW:  10%|████                                      | 471/4895 [05:32<44:50,  1.64it/s]


💽 TQM COPY FLOW:  10%|████                                      | 472/4895 [05:33<44:01,  1.67it/s]


💽 TQM COPY FLOW:  10%|████                                      | 473/4895 [05:33<43:25,  1.70it/s]


💽 TQM COPY FLOW:  10%|███▊                                    | 474/4895 [05:35<1:03:02,  1.17it/s]


💽 TQM COPY FLOW:  10%|████                                      | 475/4895 [05:35<52:03,  1.42it/s]


💽 TQM COPY FLOW:  10%|████                                      | 476/4895 [05:35<42:08,  1.75it/s]


💽 TQM COPY FLOW:  10%|████                                      | 477/4895 [05:36<33:52,  2.17it/s]


💽 TQM COPY FLOW:  10%|████                                      | 478/4895 [05:36<33:48,  2.18it/s]


💽 TQM COPY FLOW:  10%|████                                      | 479/4895 [05:36<31:02,  2.37it/s]


💽 TQM COPY FLOW:  10%|████                                      | 480/4895 [05:37<28:43,  2.56it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 481/4895 [05:37<24:56,  2.95it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 482/4895 [05:38<29:30,  2.49it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 483/4895 [05:38<26:12,  2.81it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 484/4895 [05:38<26:13,  2.80it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 485/4895 [05:39<47:35,  1.54it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 486/4895 [05:40<53:02,  1.39it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 487/4895 [05:41<52:30,  1.40it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 488/4895 [05:42<54:50,  1.34it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 489/4895 [05:43<53:48,  1.36it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 490/4895 [05:43<54:54,  1.34it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 491/4895 [05:44<58:03,  1.26it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 492/4895 [05:45<53:14,  1.38it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 493/4895 [05:45<47:02,  1.56it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 494/4895 [05:46<44:19,  1.66it/s]


💽 TQM COPY FLOW:  10%|████▏                                     | 495/4895 [05:46<40:50,  1.80it/s]


💽 TQM COPY FLOW:  10%|████▎                                     | 496/4895 [05:47<36:48,  1.99it/s]


💽 TQM COPY FLOW:  10%|████                                    | 497/4895 [05:49<1:16:34,  1.04s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [11:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [06:19<?, ?it/s]


💽 TQM COPY FLOW:  10%|████                                    | 499/4895 [05:51<1:19:52,  1.09s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [06:25<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_10 (50 files)

💽 TQM COPY FLOW:  10%|████                                    | 500/4895 [05:52<1:10:28,  1.04it/s]


💽 TQM COPY FLOW:  10%|████                                    | 501/4895 [05:53<1:18:12,  1.07s/it]


💽 TQM COPY FLOW:  10%|████                                    | 502/4895 [05:54<1:09:48,  1.05it/s]


💽 TQM COPY FLOW:  10%|████                                    | 503/4895 [05:56<1:32:51,  1.27s/it]


💽 TQM COPY FLOW:  10%|████                                    | 504/4895 [06:02<3:09:12,  2.59s/it]


💽 TQM COPY FLOW:  10%|████▏                                   | 505/4895 [06:03<2:45:03,  2.26s/it]


💽 TQM COPY FLOW:  10%|████▏                                   | 506/4895 [06:05<2:28:19,  2.03s/it]


💽 TQM COPY FLOW:  10%|████▏                                   | 507/4895 [06:05<1:50:10,  1.51s/it]


💽 TQM COPY FLOW:  10%|████▏                                   | 508/4895 [06:06<1:30:10,  1.23s/it]


💽 TQM COPY FLOW:  10%|████▏                                   | 509/4895 [06:06<1:15:35,  1.03s/it]


💽 TQM COPY FLOW:  10%|████▏                                   | 510/4895 [06:06<1:02:17,  1.17it/s]


💽 TQM COPY FLOW:  10%|████▍                                     | 511/4895 [06:07<50:33,  1.44it/s]


💽 TQM COPY FLOW:  10%|████▍                                     | 512/4895 [06:07<41:30,  1.76it/s]


💽 TQM COPY FLOW:  10%|████▍                                     | 513/4895 [06:08<39:03,  1.87it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 514/4895 [06:08<38:19,  1.91it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 515/4895 [06:08<29:33,  2.47it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 516/4895 [06:08<26:04,  2.80it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 517/4895 [06:09<29:06,  2.51it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 518/4895 [06:10<38:57,  1.87it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 519/4895 [06:11<47:25,  1.54it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 520/4895 [06:11<40:07,  1.82it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 521/4895 [06:12<41:10,  1.77it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 522/4895 [06:12<41:29,  1.76it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 523/4895 [06:13<44:15,  1.65it/s]


💽 TQM COPY FLOW:  11%|████▍                                     | 524/4895 [06:14<45:53,  1.59it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 525/4895 [06:15<56:11,  1.30it/s]


💽 TQM COPY FLOW:  11%|████▎                                   | 526/4895 [06:20<2:29:15,  2.05s/it]


💽 TQM COPY FLOW:  11%|████▎                                   | 527/4895 [06:21<2:07:41,  1.75s/it]


💽 TQM COPY FLOW:  11%|████▎                                   | 528/4895 [06:22<1:50:10,  1.51s/it]


💽 TQM COPY FLOW:  11%|████▎                                   | 529/4895 [06:22<1:29:07,  1.22s/it]


💽 TQM COPY FLOW:  11%|████▎                                   | 530/4895 [06:23<1:09:53,  1.04it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 531/4895 [06:23<58:37,  1.24it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 532/4895 [06:24<51:20,  1.42it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 533/4895 [06:24<48:23,  1.50it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 534/4895 [06:24<41:25,  1.75it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 535/4895 [06:25<35:15,  2.06it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 536/4895 [06:25<33:35,  2.16it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 537/4895 [06:25<28:11,  2.58it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 538/4895 [06:26<28:22,  2.56it/s]


💽 TQM COPY FLOW:  11%|████▌                                     | 539/4895 [06:26<27:57,  2.60it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 540/4895 [06:27<28:06,  2.58it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 541/4895 [06:27<35:35,  2.04it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 542/4895 [06:27<29:59,  2.42it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 543/4895 [06:28<34:16,  2.12it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 544/4895 [06:28<28:41,  2.53it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 545/4895 [06:29<27:01,  2.68it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 546/4895 [06:29<27:35,  2.63it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 547/4895 [06:29<23:33,  3.08it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 548/4895 [06:30<25:46,  2.81it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [12:29<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [06:59<?, ?it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 549/4895 [06:31<49:46,  1.45it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [07:05<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_11 (50 files)

💽 TQM COPY FLOW:  11%|████▍                                   | 550/4895 [06:33<1:05:19,  1.11it/s]


💽 TQM COPY FLOW:  11%|████▌                                   | 551/4895 [06:34<1:09:04,  1.05it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 552/4895 [06:34<55:16,  1.31it/s]


💽 TQM COPY FLOW:  11%|████▋                                     | 553/4895 [06:34<42:43,  1.69it/s]


💽 TQM COPY FLOW:  11%|████▊                                     | 554/4895 [06:34<36:30,  1.98it/s]


💽 TQM COPY FLOW:  11%|████▌                                   | 555/4895 [06:37<1:13:08,  1.01s/it]


💽 TQM COPY FLOW:  11%|████▌                                   | 556/4895 [06:37<1:01:05,  1.18it/s]


💽 TQM COPY FLOW:  11%|████▊                                     | 557/4895 [06:38<58:12,  1.24it/s]


💽 TQM COPY FLOW:  11%|████▊                                     | 558/4895 [06:38<48:58,  1.48it/s]


💽 TQM COPY FLOW:  11%|████▊                                     | 559/4895 [06:39<43:23,  1.67it/s]


💽 TQM COPY FLOW:  11%|████▊                                     | 560/4895 [06:39<38:27,  1.88it/s]


💽 TQM COPY FLOW:  11%|████▊                                     | 561/4895 [06:40<45:14,  1.60it/s]


💽 TQM COPY FLOW:  11%|████▊                                     | 562/4895 [06:41<49:24,  1.46it/s]


💽 TQM COPY FLOW:  12%|████▊                                     | 563/4895 [06:41<40:26,  1.79it/s]


💽 TQM COPY FLOW:  12%|████▌                                   | 564/4895 [06:43<1:24:57,  1.18s/it]


💽 TQM COPY FLOW:  12%|████▌                                   | 565/4895 [06:44<1:18:54,  1.09s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 566/4895 [06:46<1:22:37,  1.15s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 567/4895 [06:47<1:26:39,  1.20s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 568/4895 [06:48<1:12:18,  1.00s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 569/4895 [06:55<3:41:18,  3.07s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 570/4895 [06:56<2:47:20,  2.32s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 571/4895 [06:57<2:09:26,  1.80s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 572/4895 [06:57<1:43:55,  1.44s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 573/4895 [06:57<1:18:32,  1.09s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 574/4895 [06:58<1:05:23,  1.10it/s]


💽 TQM COPY FLOW:  12%|████▉                                     | 575/4895 [06:58<54:03,  1.33it/s]


💽 TQM COPY FLOW:  12%|████▉                                     | 576/4895 [06:59<44:27,  1.62it/s]


💽 TQM COPY FLOW:  12%|████▋                                   | 577/4895 [07:01<1:18:33,  1.09s/it]


💽 TQM COPY FLOW:  12%|████▋                                   | 578/4895 [07:01<1:06:53,  1.08it/s]


💽 TQM COPY FLOW:  12%|████▉                                     | 579/4895 [07:02<57:36,  1.25it/s]


💽 TQM COPY FLOW:  12%|████▉                                     | 580/4895 [07:02<52:37,  1.37it/s]


💽 TQM COPY FLOW:  12%|████▉                                     | 581/4895 [07:03<45:20,  1.59it/s]


💽 TQM COPY FLOW:  12%|████▉                                     | 582/4895 [07:03<44:15,  1.62it/s]


💽 TQM COPY FLOW:  12%|█████                                     | 583/4895 [07:04<54:08,  1.33it/s]


💽 TQM COPY FLOW:  12%|█████                                     | 584/4895 [07:05<56:44,  1.27it/s]


💽 TQM COPY FLOW:  12%|█████                                     | 585/4895 [07:06<51:41,  1.39it/s]


💽 TQM COPY FLOW:  12%|█████                                     | 586/4895 [07:07<53:36,  1.34it/s]


💽 TQM COPY FLOW:  12%|█████                                     | 587/4895 [07:07<47:36,  1.51it/s]


💽 TQM COPY FLOW:  12%|████▊                                   | 588/4895 [07:09<1:18:47,  1.10s/it]


💽 TQM COPY FLOW:  12%|████▊                                   | 589/4895 [07:17<3:40:45,  3.08s/it]


💽 TQM COPY FLOW:  12%|████▊                                   | 590/4895 [07:18<2:46:03,  2.31s/it]


💽 TQM COPY FLOW:  12%|████▊                                   | 591/4895 [07:18<2:10:49,  1.82s/it]


💽 TQM COPY FLOW:  12%|████▊                                   | 592/4895 [07:19<1:48:11,  1.51s/it]


💽 TQM COPY FLOW:  12%|████▊                                   | 593/4895 [07:20<1:28:28,  1.23s/it]


💽 TQM COPY FLOW:  12%|████▊                                   | 594/4895 [07:20<1:05:20,  1.10it/s]


💽 TQM COPY FLOW:  12%|█████                                     | 595/4895 [07:20<55:54,  1.28it/s]


💽 TQM COPY FLOW:  12%|█████                                     | 596/4895 [07:21<55:59,  1.28it/s]


💽 TQM COPY FLOW:  12%|████▉                                   | 597/4895 [07:22<1:10:30,  1.02it/s]


💽 TQM COPY FLOW:  12%|████▉                                   | 598/4895 [07:23<1:08:41,  1.04it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [13:22<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [07:52<?, ?it/s]


💽 TQM COPY FLOW:  12%|████▉                                   | 599/4895 [07:24<1:04:58,  1.10it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [07:58<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_12 (50 files)

💽 TQM COPY FLOW:  12%|████▉                                   | 600/4895 [07:25<1:04:14,  1.11it/s]


💽 TQM COPY FLOW:  12%|█████▏                                    | 601/4895 [07:25<52:17,  1.37it/s]


💽 TQM COPY FLOW:  12%|█████▏                                    | 602/4895 [07:26<47:52,  1.49it/s]


💽 TQM COPY FLOW:  12%|████▉                                   | 603/4895 [07:28<1:20:56,  1.13s/it]


💽 TQM COPY FLOW:  12%|████▉                                   | 604/4895 [07:29<1:14:13,  1.04s/it]


💽 TQM COPY FLOW:  12%|████▉                                   | 605/4895 [07:30<1:09:59,  1.02it/s]


💽 TQM COPY FLOW:  12%|████▉                                   | 606/4895 [07:31<1:13:53,  1.03s/it]


💽 TQM COPY FLOW:  12%|████▉                                   | 607/4895 [07:32<1:07:19,  1.06it/s]


💽 TQM COPY FLOW:  12%|████▉                                   | 608/4895 [07:33<1:09:41,  1.03it/s]


💽 TQM COPY FLOW:  12%|████▉                                   | 609/4895 [07:35<1:48:29,  1.52s/it]


💽 TQM COPY FLOW:  12%|████▉                                   | 610/4895 [07:36<1:22:27,  1.15s/it]


💽 TQM COPY FLOW:  12%|████▉                                   | 611/4895 [07:37<1:12:51,  1.02s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 612/4895 [07:38<1:20:16,  1.12s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 613/4895 [07:41<2:06:07,  1.77s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 614/4895 [07:44<2:27:55,  2.07s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 615/4895 [07:50<3:44:31,  3.15s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 616/4895 [07:53<3:58:29,  3.34s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 617/4895 [07:57<3:58:38,  3.35s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 618/4895 [08:00<4:00:18,  3.37s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 619/4895 [08:03<3:42:56,  3.13s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 620/4895 [08:06<3:41:43,  3.11s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 621/4895 [08:09<3:52:55,  3.27s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 622/4895 [08:10<2:50:15,  2.39s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 623/4895 [08:13<2:59:06,  2.52s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 624/4895 [08:13<2:20:22,  1.97s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 625/4895 [08:14<1:57:28,  1.65s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 626/4895 [08:15<1:42:52,  1.45s/it]


💽 TQM COPY FLOW:  13%|█████                                   | 627/4895 [08:16<1:34:52,  1.33s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 628/4895 [08:17<1:13:34,  1.03s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 629/4895 [08:18<1:11:31,  1.01s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 630/4895 [08:19<1:11:45,  1.01s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 631/4895 [08:20<1:13:31,  1.03s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 632/4895 [08:20<1:00:45,  1.17it/s]


💽 TQM COPY FLOW:  13%|█████▍                                    | 633/4895 [08:21<55:43,  1.27it/s]


💽 TQM COPY FLOW:  13%|█████▍                                    | 634/4895 [08:21<49:56,  1.42it/s]


💽 TQM COPY FLOW:  13%|█████▍                                    | 635/4895 [08:22<45:09,  1.57it/s]


💽 TQM COPY FLOW:  13%|█████▏                                  | 636/4895 [08:24<1:30:56,  1.28s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 637/4895 [08:25<1:22:34,  1.16s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 638/4895 [08:28<1:53:17,  1.60s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 639/4895 [08:29<1:33:29,  1.32s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 640/4895 [08:32<2:20:48,  1.99s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 641/4895 [08:33<1:45:52,  1.49s/it]


💽 TQM COPY FLOW:  13%|█████▏                                  | 642/4895 [08:33<1:29:11,  1.26s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 643/4895 [08:34<1:14:33,  1.05s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 644/4895 [08:35<1:16:57,  1.09s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 645/4895 [08:43<3:38:03,  3.08s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 646/4895 [08:45<3:13:03,  2.73s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 647/4895 [08:45<2:31:32,  2.14s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 648/4895 [08:47<2:29:20,  2.11s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [14:46<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [09:15<?, ?it/s]


💽 TQM COPY FLOW:  13%|█████▎                                  | 649/4895 [08:48<1:58:53,  1.68s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [09:22<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_13 (50 files)

💽 TQM COPY FLOW:  13%|█████▎                                  | 650/4895 [08:49<1:39:09,  1.40s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 651/4895 [08:52<2:20:36,  1.99s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 652/4895 [08:53<1:56:02,  1.64s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 653/4895 [08:54<1:36:43,  1.37s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 654/4895 [08:54<1:22:50,  1.17s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 655/4895 [08:55<1:13:10,  1.04s/it]


💽 TQM COPY FLOW:  13%|█████▎                                  | 656/4895 [08:56<1:02:16,  1.13it/s]


💽 TQM COPY FLOW:  13%|█████▎                                  | 657/4895 [08:59<1:48:56,  1.54s/it]


💽 TQM COPY FLOW:  13%|█████▍                                  | 658/4895 [08:59<1:29:33,  1.27s/it]


💽 TQM COPY FLOW:  13%|█████▍                                  | 659/4895 [09:02<1:52:53,  1.60s/it]


💽 TQM COPY FLOW:  13%|█████▍                                  | 660/4895 [09:05<2:32:57,  2.17s/it]


💽 TQM COPY FLOW:  14%|█████▍                                  | 661/4895 [09:06<2:08:59,  1.83s/it]


💽 TQM COPY FLOW:  14%|█████▍                                  | 662/4895 [09:08<2:09:27,  1.84s/it]


💽 TQM COPY FLOW:  14%|█████▍                                  | 663/4895 [09:09<1:39:20,  1.41s/it]


💽 TQM COPY FLOW:  14%|█████▍                                  | 664/4895 [09:09<1:24:03,  1.19s/it]


💽 TQM COPY FLOW:  14%|█████▍                                  | 665/4895 [09:10<1:10:20,  1.00it/s]


💽 TQM COPY FLOW:  14%|█████▋                                    | 666/4895 [09:10<58:30,  1.20it/s]


💽 TQM COPY FLOW:  14%|█████▍                                  | 667/4895 [09:11<1:02:43,  1.12it/s]


💽 TQM COPY FLOW:  14%|█████▋                                    | 668/4895 [09:12<54:08,  1.30it/s]


💽 TQM COPY FLOW:  14%|█████▋                                    | 669/4895 [09:12<48:25,  1.45it/s]


💽 TQM COPY FLOW:  14%|█████▋                                    | 670/4895 [09:13<39:39,  1.78it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 671/4895 [09:13<43:14,  1.63it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 672/4895 [09:14<42:23,  1.66it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 673/4895 [09:14<36:05,  1.95it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 674/4895 [09:14<32:14,  2.18it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 675/4895 [09:15<26:45,  2.63it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 676/4895 [09:15<26:06,  2.69it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 677/4895 [09:15<26:35,  2.64it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 678/4895 [09:16<24:11,  2.90it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 679/4895 [09:16<21:34,  3.26it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 680/4895 [09:16<21:48,  3.22it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 681/4895 [09:17<21:57,  3.20it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 682/4895 [09:17<19:10,  3.66it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 683/4895 [09:17<18:06,  3.88it/s]


💽 TQM COPY FLOW:  14%|█████▊                                    | 684/4895 [09:17<17:26,  4.03it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 685/4895 [09:18<19:18,  3.63it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 686/4895 [09:18<18:37,  3.76it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 687/4895 [09:18<22:43,  3.09it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 688/4895 [09:19<27:10,  2.58it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 689/4895 [09:19<30:01,  2.33it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 690/4895 [09:21<50:33,  1.39it/s]


💽 TQM COPY FLOW:  14%|█████▋                                  | 691/4895 [09:26<2:35:59,  2.23s/it]


💽 TQM COPY FLOW:  14%|█████▋                                  | 692/4895 [09:27<1:58:33,  1.69s/it]


💽 TQM COPY FLOW:  14%|█████▋                                  | 693/4895 [09:28<1:51:33,  1.59s/it]


💽 TQM COPY FLOW:  14%|█████▋                                  | 694/4895 [09:29<1:35:41,  1.37s/it]


💽 TQM COPY FLOW:  14%|█████▋                                  | 695/4895 [09:29<1:15:59,  1.09s/it]


💽 TQM COPY FLOW:  14%|█████▋                                  | 696/4895 [09:30<1:02:37,  1.12it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 697/4895 [09:30<51:02,  1.37it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 698/4895 [09:31<45:42,  1.53it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [15:29<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [09:59<?, ?it/s]


💽 TQM COPY FLOW:  14%|█████▉                                    | 699/4895 [09:31<39:24,  1.77it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [10:05<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_14 (50 files)

💽 TQM COPY FLOW:  14%|██████                                    | 700/4895 [09:32<43:47,  1.60it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 701/4895 [09:33<45:14,  1.54it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 702/4895 [09:34<51:33,  1.36it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 703/4895 [09:34<46:30,  1.50it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 704/4895 [09:35<49:22,  1.41it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 705/4895 [09:35<44:51,  1.56it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 706/4895 [09:36<43:28,  1.61it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 707/4895 [09:37<48:38,  1.43it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 708/4895 [09:37<47:35,  1.47it/s]


💽 TQM COPY FLOW:  14%|██████                                    | 709/4895 [09:38<39:44,  1.76it/s]


💽 TQM COPY FLOW:  15%|██████                                    | 710/4895 [09:39<44:38,  1.56it/s]


💽 TQM COPY FLOW:  15%|██████                                    | 711/4895 [09:39<37:42,  1.85it/s]


💽 TQM COPY FLOW:  15%|██████                                    | 712/4895 [09:39<34:44,  2.01it/s]


💽 TQM COPY FLOW:  15%|██████                                    | 713/4895 [09:40<30:42,  2.27it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 714/4895 [09:41<47:17,  1.47it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 715/4895 [09:41<38:08,  1.83it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 716/4895 [09:41<34:59,  1.99it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 717/4895 [09:42<32:49,  2.12it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 718/4895 [09:42<35:33,  1.96it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 719/4895 [09:43<32:36,  2.13it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 720/4895 [09:43<31:11,  2.23it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 721/4895 [09:43<27:15,  2.55it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 722/4895 [09:44<30:27,  2.28it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 723/4895 [09:44<28:18,  2.46it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 724/4895 [09:45<42:19,  1.64it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 725/4895 [09:46<43:01,  1.62it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 726/4895 [09:47<40:49,  1.70it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 727/4895 [09:47<41:11,  1.69it/s]


💽 TQM COPY FLOW:  15%|██████▏                                   | 728/4895 [09:48<37:11,  1.87it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 729/4895 [09:48<38:25,  1.81it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 730/4895 [09:49<35:46,  1.94it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 731/4895 [09:49<37:02,  1.87it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 732/4895 [09:49<28:21,  2.45it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 733/4895 [09:49<22:00,  3.15it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 734/4895 [09:50<20:54,  3.32it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 735/4895 [09:50<18:57,  3.66it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 736/4895 [09:50<15:21,  4.51it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 737/4895 [09:50<13:15,  5.23it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 738/4895 [09:50<12:18,  5.63it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 740/4895 [09:50<10:05,  6.86it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 741/4895 [09:51<11:34,  5.98it/s]


💽 TQM COPY FLOW:  15%|██████▎                                   | 742/4895 [09:51<11:19,  6.11it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 743/4895 [09:51<14:54,  4.64it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 744/4895 [09:51<13:15,  5.22it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 745/4895 [09:52<13:14,  5.22it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 746/4895 [09:52<21:22,  3.23it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 747/4895 [09:53<27:19,  2.53it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 748/4895 [09:53<29:31,  2.34it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [15:53<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [10:23<?, ?it/s]


💽 TQM COPY FLOW:  15%|██████                                  | 749/4895 [09:55<1:06:21,  1.04it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [10:29<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_15 (50 files)

💽 TQM COPY FLOW:  15%|██████▍                                   | 750/4895 [09:56<59:24,  1.16it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 751/4895 [09:57<50:57,  1.36it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 752/4895 [09:57<43:26,  1.59it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 753/4895 [09:57<40:35,  1.70it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 754/4895 [09:58<37:30,  1.84it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 755/4895 [09:58<37:36,  1.83it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 756/4895 [09:59<45:25,  1.52it/s]


💽 TQM COPY FLOW:  15%|██████▍                                   | 757/4895 [10:00<48:33,  1.42it/s]


💽 TQM COPY FLOW:  15%|██████▌                                   | 758/4895 [10:01<43:42,  1.58it/s]


💽 TQM COPY FLOW:  16%|██████▌                                   | 759/4895 [10:01<39:21,  1.75it/s]


💽 TQM COPY FLOW:  16%|██████▌                                   | 760/4895 [10:02<38:12,  1.80it/s]


💽 TQM COPY FLOW:  16%|██████▌                                   | 761/4895 [10:02<41:37,  1.66it/s]


💽 TQM COPY FLOW:  16%|██████▌                                   | 762/4895 [10:03<52:46,  1.31it/s]


💽 TQM COPY FLOW:  16%|██████▌                                   | 763/4895 [10:04<59:47,  1.15it/s]


💽 TQM COPY FLOW:  16%|██████▏                                 | 764/4895 [10:06<1:05:58,  1.04it/s]


💽 TQM COPY FLOW:  16%|██████▎                                 | 765/4895 [10:12<3:02:23,  2.65s/it]


💽 TQM COPY FLOW:  16%|██████▎                                 | 766/4895 [10:13<2:15:06,  1.96s/it]


💽 TQM COPY FLOW:  16%|██████▎                                 | 767/4895 [10:13<1:40:59,  1.47s/it]


💽 TQM COPY FLOW:  16%|██████▎                                 | 768/4895 [10:13<1:16:09,  1.11s/it]


💽 TQM COPY FLOW:  16%|██████▎                                 | 769/4895 [10:14<1:05:01,  1.06it/s]


💽 TQM COPY FLOW:  16%|██████▎                                 | 770/4895 [10:15<1:04:32,  1.07it/s]


💽 TQM COPY FLOW:  16%|██████▎                                 | 771/4895 [10:16<1:04:00,  1.07it/s]


💽 TQM COPY FLOW:  16%|██████▎                                 | 772/4895 [10:17<1:07:49,  1.01it/s]


💽 TQM COPY FLOW:  16%|██████▎                                 | 773/4895 [10:17<1:00:05,  1.14it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 774/4895 [10:18<59:44,  1.15it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 775/4895 [10:18<47:57,  1.43it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 776/4895 [10:19<46:06,  1.49it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 777/4895 [10:20<43:53,  1.56it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 778/4895 [10:20<40:44,  1.68it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 779/4895 [10:21<38:18,  1.79it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 780/4895 [10:22<57:20,  1.20it/s]


💽 TQM COPY FLOW:  16%|██████▋                                   | 781/4895 [10:23<59:32,  1.15it/s]


💽 TQM COPY FLOW:  16%|██████▍                                 | 782/4895 [10:24<1:11:43,  1.05s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 783/4895 [10:26<1:19:49,  1.16s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 784/4895 [10:27<1:20:04,  1.17s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 785/4895 [10:36<4:02:01,  3.53s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 786/4895 [10:37<3:05:46,  2.71s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 787/4895 [10:38<2:22:29,  2.08s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 788/4895 [10:38<1:52:00,  1.64s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 789/4895 [10:39<1:29:13,  1.30s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 790/4895 [10:40<1:20:43,  1.18s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 791/4895 [10:40<1:11:20,  1.04s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 792/4895 [10:42<1:31:38,  1.34s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 793/4895 [10:45<2:06:32,  1.85s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 794/4895 [10:47<1:54:36,  1.68s/it]


💽 TQM COPY FLOW:  16%|██████▍                                 | 795/4895 [10:47<1:32:06,  1.35s/it]


💽 TQM COPY FLOW:  16%|██████▌                                 | 796/4895 [10:48<1:16:11,  1.12s/it]


💽 TQM COPY FLOW:  16%|██████▌                                 | 797/4895 [10:49<1:10:02,  1.03s/it]


💽 TQM COPY FLOW:  16%|██████▌                                 | 798/4895 [10:50<1:17:08,  1.13s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [16:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [11:18<?, ?it/s]


💽 TQM COPY FLOW:  16%|██████▌                                 | 799/4895 [10:51<1:08:47,  1.01s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [11:24<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_16 (50 files)

💽 TQM COPY FLOW:  16%|██████▌                                 | 800/4895 [10:52<1:09:53,  1.02s/it]


💽 TQM COPY FLOW:  16%|██████▌                                 | 801/4895 [10:52<1:00:15,  1.13it/s]


💽 TQM COPY FLOW:  16%|██████▉                                   | 802/4895 [10:53<55:23,  1.23it/s]


💽 TQM COPY FLOW:  16%|██████▉                                   | 803/4895 [10:54<50:31,  1.35it/s]


💽 TQM COPY FLOW:  16%|██████▉                                   | 804/4895 [10:54<43:28,  1.57it/s]


💽 TQM COPY FLOW:  16%|██████▉                                   | 805/4895 [10:55<45:24,  1.50it/s]


💽 TQM COPY FLOW:  16%|██████▉                                   | 806/4895 [10:55<45:52,  1.49it/s]


💽 TQM COPY FLOW:  16%|██████▉                                   | 807/4895 [10:56<44:02,  1.55it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 808/4895 [10:57<44:59,  1.51it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 809/4895 [10:58<54:52,  1.24it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 810/4895 [10:58<49:11,  1.38it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 811/4895 [10:59<47:11,  1.44it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 812/4895 [11:00<46:45,  1.46it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 813/4895 [11:00<43:30,  1.56it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 814/4895 [11:01<43:05,  1.58it/s]


💽 TQM COPY FLOW:  17%|██████▉                                   | 815/4895 [11:02<53:25,  1.27it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 816/4895 [11:03<57:48,  1.18it/s]


💽 TQM COPY FLOW:  17%|██████▋                                 | 817/4895 [11:04<1:02:37,  1.09it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 818/4895 [11:04<51:34,  1.32it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 819/4895 [11:05<55:10,  1.23it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 820/4895 [11:06<54:17,  1.25it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 821/4895 [11:07<56:23,  1.20it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 822/4895 [11:08<58:32,  1.16it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 823/4895 [11:09<57:38,  1.18it/s]


💽 TQM COPY FLOW:  17%|██████▋                                 | 824/4895 [11:10<1:00:32,  1.12it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 825/4895 [11:11<58:10,  1.17it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 826/4895 [11:11<53:39,  1.26it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 827/4895 [11:11<42:08,  1.61it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 828/4895 [11:12<37:21,  1.81it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 829/4895 [11:12<37:01,  1.83it/s]


💽 TQM COPY FLOW:  17%|███████                                   | 830/4895 [11:14<59:28,  1.14it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 831/4895 [11:14<47:27,  1.43it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 832/4895 [11:14<38:22,  1.76it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 833/4895 [11:15<37:42,  1.79it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 834/4895 [11:16<40:50,  1.66it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 835/4895 [11:16<41:03,  1.65it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 836/4895 [11:17<42:07,  1.61it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 837/4895 [11:18<44:29,  1.52it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 838/4895 [11:18<37:35,  1.80it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 839/4895 [11:19<50:58,  1.33it/s]


💽 TQM COPY FLOW:  17%|██████▊                                 | 840/4895 [11:22<1:23:15,  1.23s/it]


💽 TQM COPY FLOW:  17%|██████▊                                 | 841/4895 [11:22<1:12:52,  1.08s/it]


💽 TQM COPY FLOW:  17%|██████▉                                 | 842/4895 [11:23<1:03:15,  1.07it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 843/4895 [11:24<55:24,  1.22it/s]


💽 TQM COPY FLOW:  17%|███████▏                                  | 844/4895 [11:24<53:19,  1.27it/s]


💽 TQM COPY FLOW:  17%|███████▎                                  | 845/4895 [11:25<50:30,  1.34it/s]


💽 TQM COPY FLOW:  17%|███████▎                                  | 846/4895 [11:26<52:19,  1.29it/s]


💽 TQM COPY FLOW:  17%|███████▎                                  | 847/4895 [11:26<51:23,  1.31it/s]


💽 TQM COPY FLOW:  17%|███████▎                                  | 848/4895 [11:27<52:14,  1.29it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [17:27<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [11:56<?, ?it/s]


💽 TQM COPY FLOW:  17%|██████▉                                 | 849/4895 [11:29<1:06:15,  1.02it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [12:02<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_17 (50 files)

💽 TQM COPY FLOW:  17%|██████▉                                 | 850/4895 [11:30<1:13:40,  1.09s/it]


💽 TQM COPY FLOW:  17%|██████▉                                 | 851/4895 [11:31<1:15:10,  1.12s/it]


💽 TQM COPY FLOW:  17%|██████▉                                 | 852/4895 [11:32<1:08:11,  1.01s/it]


💽 TQM COPY FLOW:  17%|██████▉                                 | 853/4895 [11:35<1:46:30,  1.58s/it]


💽 TQM COPY FLOW:  17%|██████▉                                 | 854/4895 [11:37<2:04:57,  1.86s/it]


💽 TQM COPY FLOW:  17%|██████▉                                 | 855/4895 [11:38<1:47:29,  1.60s/it]


💽 TQM COPY FLOW:  17%|██████▉                                 | 856/4895 [11:41<1:58:47,  1.76s/it]


💽 TQM COPY FLOW:  18%|███████                                 | 857/4895 [11:42<1:45:32,  1.57s/it]


💽 TQM COPY FLOW:  18%|███████                                 | 858/4895 [11:42<1:27:57,  1.31s/it]


💽 TQM COPY FLOW:  18%|███████                                 | 859/4895 [11:43<1:16:01,  1.13s/it]


💽 TQM COPY FLOW:  18%|███████                                 | 860/4895 [11:46<1:43:55,  1.55s/it]


💽 TQM COPY FLOW:  18%|███████                                 | 861/4895 [11:47<1:34:37,  1.41s/it]


💽 TQM COPY FLOW:  18%|███████                                 | 862/4895 [11:47<1:12:49,  1.08s/it]


💽 TQM COPY FLOW:  18%|███████▍                                  | 863/4895 [11:47<59:48,  1.12it/s]


💽 TQM COPY FLOW:  18%|███████                                 | 864/4895 [11:49<1:03:41,  1.05it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 865/4895 [11:49<54:39,  1.23it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 866/4895 [11:49<46:30,  1.44it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 867/4895 [11:50<46:58,  1.43it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 868/4895 [11:51<47:20,  1.42it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 869/4895 [11:51<42:07,  1.59it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 870/4895 [11:52<45:12,  1.48it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 871/4895 [11:53<45:37,  1.47it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 872/4895 [11:54<54:32,  1.23it/s]


💽 TQM COPY FLOW:  18%|███████▏                                | 873/4895 [11:55<1:04:15,  1.04it/s]


💽 TQM COPY FLOW:  18%|███████▍                                  | 874/4895 [11:56<59:53,  1.12it/s]


💽 TQM COPY FLOW:  18%|███████▏                                | 875/4895 [11:58<1:15:14,  1.12s/it]


💽 TQM COPY FLOW:  18%|███████▏                                | 876/4895 [11:59<1:21:32,  1.22s/it]


💽 TQM COPY FLOW:  18%|███████▏                                | 877/4895 [12:00<1:23:10,  1.24s/it]


💽 TQM COPY FLOW:  18%|███████▏                                | 878/4895 [12:01<1:03:11,  1.06it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 879/4895 [12:01<50:20,  1.33it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 880/4895 [12:01<41:53,  1.60it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 881/4895 [12:02<42:39,  1.57it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 882/4895 [12:02<33:42,  1.98it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 883/4895 [12:03<31:51,  2.10it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 884/4895 [12:03<31:12,  2.14it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 885/4895 [12:03<28:57,  2.31it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 886/4895 [12:04<35:25,  1.89it/s]


💽 TQM COPY FLOW:  18%|███████▌                                  | 887/4895 [12:05<45:23,  1.47it/s]


💽 TQM COPY FLOW:  18%|███████▎                                | 888/4895 [12:09<1:58:53,  1.78s/it]


💽 TQM COPY FLOW:  18%|███████▎                                | 889/4895 [12:10<1:35:49,  1.44s/it]


💽 TQM COPY FLOW:  18%|███████▎                                | 890/4895 [12:11<1:18:32,  1.18s/it]


💽 TQM COPY FLOW:  18%|███████▎                                | 891/4895 [12:11<1:03:48,  1.05it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 892/4895 [12:12<53:36,  1.24it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 893/4895 [12:12<40:57,  1.63it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 894/4895 [12:13<56:42,  1.18it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 895/4895 [12:13<45:15,  1.47it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 896/4895 [12:14<38:31,  1.73it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 897/4895 [12:14<34:25,  1.94it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 898/4895 [12:15<34:15,  1.94it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [18:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [12:42<?, ?it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 899/4895 [12:15<32:04,  2.08it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [12:49<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_18 (50 files)

💽 TQM COPY FLOW:  18%|███████▋                                  | 900/4895 [12:16<37:44,  1.76it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 901/4895 [12:17<41:30,  1.60it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 902/4895 [12:17<42:58,  1.55it/s]


💽 TQM COPY FLOW:  18%|███████▋                                  | 903/4895 [12:18<43:06,  1.54it/s]


💽 TQM COPY FLOW:  18%|███████▊                                  | 904/4895 [12:18<34:33,  1.93it/s]


💽 TQM COPY FLOW:  18%|███████▊                                  | 905/4895 [12:19<31:49,  2.09it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 906/4895 [12:19<34:46,  1.91it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 907/4895 [12:20<39:59,  1.66it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 909/4895 [12:20<29:27,  2.26it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 910/4895 [12:21<32:59,  2.01it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 911/4895 [12:22<34:23,  1.93it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 912/4895 [12:22<30:12,  2.20it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 913/4895 [12:22<28:58,  2.29it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 914/4895 [12:23<24:06,  2.75it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 915/4895 [12:24<37:15,  1.78it/s]


💽 TQM COPY FLOW:  19%|███████▊                                  | 916/4895 [12:25<55:05,  1.20it/s]


💽 TQM COPY FLOW:  19%|███████▍                                | 917/4895 [12:29<1:49:09,  1.65s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 918/4895 [12:41<5:13:00,  4.72s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 919/4895 [12:42<4:07:47,  3.74s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 920/4895 [12:47<4:33:21,  4.13s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 921/4895 [12:50<4:11:03,  3.79s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 922/4895 [12:51<3:20:52,  3.03s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 923/4895 [12:57<4:05:40,  3.71s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 924/4895 [13:02<4:46:29,  4.33s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 925/4895 [13:03<3:33:01,  3.22s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 926/4895 [13:03<2:32:41,  2.31s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 927/4895 [13:03<1:49:53,  1.66s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 928/4895 [13:04<1:20:32,  1.22s/it]


💽 TQM COPY FLOW:  19%|███████▌                                | 929/4895 [13:04<1:06:25,  1.00s/it]


💽 TQM COPY FLOW:  19%|███████▉                                  | 930/4895 [13:05<54:23,  1.21it/s]


💽 TQM COPY FLOW:  19%|███████▉                                  | 931/4895 [13:05<41:02,  1.61it/s]


💽 TQM COPY FLOW:  19%|███████▉                                  | 932/4895 [13:05<37:39,  1.75it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 933/4895 [13:05<30:32,  2.16it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 934/4895 [13:06<28:18,  2.33it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 935/4895 [13:06<24:57,  2.64it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 936/4895 [13:06<24:28,  2.70it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 937/4895 [13:06<20:30,  3.22it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 938/4895 [13:07<16:57,  3.89it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 939/4895 [13:07<16:04,  4.10it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 940/4895 [13:07<15:37,  4.22it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 941/4895 [13:07<19:55,  3.31it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 942/4895 [13:08<17:16,  3.81it/s]


💽 TQM COPY FLOW:  19%|███████▋                                | 943/4895 [13:11<1:27:45,  1.33s/it]


💽 TQM COPY FLOW:  19%|███████▋                                | 944/4895 [13:12<1:06:46,  1.01s/it]


💽 TQM COPY FLOW:  19%|████████                                  | 945/4895 [13:12<49:39,  1.33it/s]


💽 TQM COPY FLOW:  19%|████████                                  | 946/4895 [13:12<39:24,  1.67it/s]


💽 TQM COPY FLOW:  19%|████████▏                                 | 947/4895 [13:12<31:02,  2.12it/s]


💽 TQM COPY FLOW:  19%|████████▏                                 | 948/4895 [13:13<27:08,  2.42it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [19:11<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [13:40<?, ?it/s]


💽 TQM COPY FLOW:  19%|████████▏                                 | 949/4895 [13:13<24:04,  2.73it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [13:47<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_19 (50 files)

💽 TQM COPY FLOW:  19%|████████▏                                 | 950/4895 [13:13<24:01,  2.74it/s]


💽 TQM COPY FLOW:  19%|████████▏                                 | 951/4895 [13:14<23:57,  2.74it/s]


💽 TQM COPY FLOW:  19%|████████▏                                 | 952/4895 [13:14<21:54,  3.00it/s]


💽 TQM COPY FLOW:  19%|████████▏                                 | 953/4895 [13:14<20:09,  3.26it/s]


💽 TQM COPY FLOW:  19%|████████▏                                 | 954/4895 [13:14<20:42,  3.17it/s]


💽 TQM COPY FLOW:  20%|███████▊                                | 955/4895 [13:17<1:12:07,  1.10s/it]


💽 TQM COPY FLOW:  20%|████████▏                                 | 956/4895 [13:18<59:16,  1.11it/s]


💽 TQM COPY FLOW:  20%|████████▏                                 | 957/4895 [13:18<45:47,  1.43it/s]


💽 TQM COPY FLOW:  20%|███████▊                                | 958/4895 [13:22<1:58:21,  1.80s/it]


💽 TQM COPY FLOW:  20%|███████▊                                | 959/4895 [13:26<2:31:52,  2.32s/it]


💽 TQM COPY FLOW:  20%|███████▊                                | 960/4895 [13:27<2:04:04,  1.89s/it]


💽 TQM COPY FLOW:  20%|███████▊                                | 961/4895 [13:27<1:29:54,  1.37s/it]


💽 TQM COPY FLOW:  20%|███████▊                                | 962/4895 [13:27<1:05:44,  1.00s/it]


💽 TQM COPY FLOW:  20%|████████▎                                 | 963/4895 [13:27<50:39,  1.29it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 964/4895 [13:28<45:00,  1.46it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 965/4895 [13:29<45:08,  1.45it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 966/4895 [13:29<46:20,  1.41it/s]


💽 TQM COPY FLOW:  20%|███████▉                                | 967/4895 [13:31<1:05:58,  1.01s/it]


💽 TQM COPY FLOW:  20%|████████▎                                 | 968/4895 [13:31<48:58,  1.34it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 969/4895 [13:31<37:28,  1.75it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 970/4895 [13:32<31:57,  2.05it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 971/4895 [13:32<30:56,  2.11it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 972/4895 [13:33<42:19,  1.54it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 973/4895 [13:33<37:03,  1.76it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 974/4895 [13:34<34:29,  1.89it/s]


💽 TQM COPY FLOW:  20%|████████▎                                 | 975/4895 [13:35<40:45,  1.60it/s]


💽 TQM COPY FLOW:  20%|███████▉                                | 976/4895 [13:40<2:19:54,  2.14s/it]


💽 TQM COPY FLOW:  20%|███████▉                                | 977/4895 [13:41<1:40:43,  1.54s/it]


💽 TQM COPY FLOW:  20%|███████▉                                | 978/4895 [13:41<1:15:34,  1.16s/it]


💽 TQM COPY FLOW:  20%|████████                                | 979/4895 [13:41<1:05:36,  1.01s/it]


💽 TQM COPY FLOW:  20%|████████▍                                 | 980/4895 [13:42<52:38,  1.24it/s]


💽 TQM COPY FLOW:  20%|████████                                | 981/4895 [13:44<1:27:24,  1.34s/it]


💽 TQM COPY FLOW:  20%|████████                                | 982/4895 [13:45<1:07:22,  1.03s/it]


💽 TQM COPY FLOW:  20%|████████▍                                 | 983/4895 [13:45<49:29,  1.32it/s]


💽 TQM COPY FLOW:  20%|████████▍                                 | 984/4895 [13:45<39:38,  1.64it/s]


💽 TQM COPY FLOW:  20%|████████                                | 985/4895 [13:50<2:02:04,  1.87s/it]


💽 TQM COPY FLOW:  20%|████████                                | 986/4895 [13:54<2:40:18,  2.46s/it]


💽 TQM COPY FLOW:  20%|████████                                | 987/4895 [13:54<1:54:32,  1.76s/it]


💽 TQM COPY FLOW:  20%|████████                                | 988/4895 [13:57<2:14:33,  2.07s/it]


💽 TQM COPY FLOW:  20%|████████                                | 989/4895 [13:58<1:58:00,  1.81s/it]


💽 TQM COPY FLOW:  20%|████████                                | 990/4895 [13:58<1:28:21,  1.36s/it]


💽 TQM COPY FLOW:  20%|████████                                | 991/4895 [14:02<2:07:26,  1.96s/it]


💽 TQM COPY FLOW:  20%|████████                                | 992/4895 [14:02<1:32:06,  1.42s/it]


💽 TQM COPY FLOW:  20%|████████                                | 993/4895 [14:02<1:07:59,  1.05s/it]


💽 TQM COPY FLOW:  20%|████████                                | 994/4895 [14:03<1:16:39,  1.18s/it]


💽 TQM COPY FLOW:  20%|████████▌                                 | 995/4895 [14:03<56:40,  1.15it/s]


💽 TQM COPY FLOW:  20%|████████▏                               | 996/4895 [14:05<1:04:52,  1.00it/s]


💽 TQM COPY FLOW:  20%|████████▌                                 | 997/4895 [14:05<49:11,  1.32it/s]


💽 TQM COPY FLOW:  20%|████████▌                                 | 998/4895 [14:06<48:52,  1.33it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [20:04<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [14:34<?, ?it/s]


💽 TQM COPY FLOW:  20%|████████▌                                 | 999/4895 [14:06<41:31,  1.56it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [14:40<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_20 (50 files)

💽 TQM COPY FLOW:  20%|███████▉                               | 1000/4895 [14:09<1:18:49,  1.21s/it]


💽 TQM COPY FLOW:  20%|███████▉                               | 1001/4895 [14:12<2:05:09,  1.93s/it]


💽 TQM COPY FLOW:  20%|███████▉                               | 1002/4895 [14:14<2:03:59,  1.91s/it]


💽 TQM COPY FLOW:  20%|███████▉                               | 1003/4895 [14:15<1:50:35,  1.70s/it]


💽 TQM COPY FLOW:  21%|███████▉                               | 1004/4895 [14:19<2:20:41,  2.17s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1005/4895 [14:19<1:49:08,  1.68s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1006/4895 [14:20<1:26:52,  1.34s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1007/4895 [14:21<1:22:51,  1.28s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1008/4895 [14:21<1:00:23,  1.07it/s]


💽 TQM COPY FLOW:  21%|████████                               | 1009/4895 [14:22<1:09:33,  1.07s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1010/4895 [14:28<2:37:09,  2.43s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1011/4895 [14:31<2:47:40,  2.59s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1012/4895 [14:32<2:14:15,  2.07s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1013/4895 [14:32<1:38:55,  1.53s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1014/4895 [14:33<1:25:01,  1.31s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1015/4895 [14:37<2:18:42,  2.15s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1016/4895 [14:37<1:44:30,  1.62s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1017/4895 [14:37<1:16:00,  1.18s/it]


💽 TQM COPY FLOW:  21%|████████                               | 1018/4895 [14:38<1:00:48,  1.06it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1019/4895 [14:38<45:31,  1.42it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1020/4895 [14:39<49:22,  1.31it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1022/4895 [14:40<37:57,  1.70it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1024/4895 [14:40<30:03,  2.15it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1025/4895 [14:40<26:56,  2.39it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1026/4895 [14:41<28:35,  2.26it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1027/4895 [14:41<27:16,  2.36it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1028/4895 [14:42<27:22,  2.36it/s]


💽 TQM COPY FLOW:  21%|████████▌                                | 1029/4895 [14:43<42:36,  1.51it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1030/4895 [14:43<34:00,  1.89it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1031/4895 [14:44<28:48,  2.24it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1032/4895 [14:44<37:00,  1.74it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1033/4895 [14:45<36:18,  1.77it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1034/4895 [14:45<33:27,  1.92it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1035/4895 [14:46<29:44,  2.16it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1036/4895 [14:46<27:10,  2.37it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1037/4895 [14:47<36:10,  1.78it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1038/4895 [14:48<42:32,  1.51it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1039/4895 [14:48<40:53,  1.57it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1040/4895 [14:49<31:45,  2.02it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1041/4895 [14:49<30:01,  2.14it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1042/4895 [14:49<25:32,  2.51it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1043/4895 [14:49<22:48,  2.81it/s]


💽 TQM COPY FLOW:  21%|████████▋                                | 1044/4895 [14:50<18:21,  3.50it/s]


💽 TQM COPY FLOW:  21%|████████▊                                | 1045/4895 [14:50<26:45,  2.40it/s]


💽 TQM COPY FLOW:  21%|████████▊                                | 1046/4895 [14:51<23:31,  2.73it/s]


💽 TQM COPY FLOW:  21%|████████▊                                | 1047/4895 [14:51<25:23,  2.53it/s]


💽 TQM COPY FLOW:  21%|████████▎                              | 1048/4895 [14:54<1:12:15,  1.13s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [20:52<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [15:22<?, ?it/s]


💽 TQM COPY FLOW:  21%|████████▎                              | 1049/4895 [14:54<1:00:51,  1.05it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [15:28<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_21 (50 files)

💽 TQM COPY FLOW:  21%|████████▊                                | 1050/4895 [14:55<54:09,  1.18it/s]


💽 TQM COPY FLOW:  21%|████████▊                                | 1052/4895 [14:56<40:50,  1.57it/s]


💽 TQM COPY FLOW:  22%|████████▊                                | 1053/4895 [14:56<42:26,  1.51it/s]


💽 TQM COPY FLOW:  22%|████████▊                                | 1054/4895 [14:57<42:37,  1.50it/s]


💽 TQM COPY FLOW:  22%|████████▊                                | 1055/4895 [14:58<38:48,  1.65it/s]


💽 TQM COPY FLOW:  22%|████████▊                                | 1056/4895 [14:58<35:04,  1.82it/s]


💽 TQM COPY FLOW:  22%|████████▊                                | 1057/4895 [14:58<28:30,  2.24it/s]


💽 TQM COPY FLOW:  22%|████████▊                                | 1058/4895 [14:58<25:18,  2.53it/s]


💽 TQM COPY FLOW:  22%|████████▊                                | 1059/4895 [14:59<23:19,  2.74it/s]


💽 TQM COPY FLOW:  22%|████████▉                                | 1060/4895 [15:00<31:43,  2.02it/s]


💽 TQM COPY FLOW:  22%|████████▉                                | 1061/4895 [15:00<25:02,  2.55it/s]


💽 TQM COPY FLOW:  22%|████████▉                                | 1062/4895 [15:00<28:59,  2.20it/s]


💽 TQM COPY FLOW:  22%|████████▍                              | 1063/4895 [15:04<1:24:59,  1.33s/it]


💽 TQM COPY FLOW:  22%|████████▍                              | 1064/4895 [15:06<1:38:58,  1.55s/it]


💽 TQM COPY FLOW:  22%|████████▍                              | 1065/4895 [15:06<1:15:48,  1.19s/it]


💽 TQM COPY FLOW:  22%|████████▍                              | 1066/4895 [15:07<1:11:30,  1.12s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1067/4895 [15:08<1:04:14,  1.01s/it]


💽 TQM COPY FLOW:  22%|████████▉                                | 1068/4895 [15:08<54:25,  1.17it/s]


💽 TQM COPY FLOW:  22%|████████▉                                | 1069/4895 [15:09<42:40,  1.49it/s]


💽 TQM COPY FLOW:  22%|████████▉                                | 1070/4895 [15:09<34:40,  1.84it/s]


💽 TQM COPY FLOW:  22%|████████▉                                | 1071/4895 [15:09<33:32,  1.90it/s]


💽 TQM COPY FLOW:  22%|████████▌                              | 1072/4895 [15:15<2:15:30,  2.13s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1073/4895 [15:17<2:10:12,  2.04s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1074/4895 [15:18<1:44:36,  1.64s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1075/4895 [15:18<1:18:14,  1.23s/it]


💽 TQM COPY FLOW:  22%|█████████                                | 1076/4895 [15:18<59:01,  1.08it/s]


💽 TQM COPY FLOW:  22%|████████▌                              | 1077/4895 [15:20<1:08:16,  1.07s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1078/4895 [15:24<2:01:54,  1.92s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1079/4895 [15:37<5:33:23,  5.24s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1080/4895 [15:39<4:34:51,  4.32s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1081/4895 [15:39<3:15:10,  3.07s/it]


💽 TQM COPY FLOW:  22%|████████▌                              | 1082/4895 [15:41<2:51:02,  2.69s/it]


💽 TQM COPY FLOW:  22%|████████▋                              | 1083/4895 [15:41<2:05:39,  1.98s/it]


💽 TQM COPY FLOW:  22%|████████▋                              | 1084/4895 [15:41<1:32:33,  1.46s/it]


💽 TQM COPY FLOW:  22%|████████▋                              | 1085/4895 [15:42<1:13:49,  1.16s/it]


💽 TQM COPY FLOW:  22%|████████▋                              | 1086/4895 [15:42<1:03:21,  1.00it/s]


💽 TQM COPY FLOW:  22%|█████████                                | 1087/4895 [15:43<51:06,  1.24it/s]


💽 TQM COPY FLOW:  22%|█████████                                | 1088/4895 [15:43<43:46,  1.45it/s]


💽 TQM COPY FLOW:  22%|█████████                                | 1089/4895 [15:43<37:57,  1.67it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1090/4895 [15:44<34:35,  1.83it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1091/4895 [15:44<27:18,  2.32it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1092/4895 [15:44<28:01,  2.26it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1093/4895 [15:45<24:58,  2.54it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1094/4895 [15:45<22:14,  2.85it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1095/4895 [15:46<31:43,  2.00it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1096/4895 [15:46<26:19,  2.41it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1097/4895 [15:47<27:00,  2.34it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [21:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [16:15<?, ?it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1099/4895 [15:47<27:09,  2.33it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [16:21<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_22 (50 files)

💽 TQM COPY FLOW:  22%|█████████▏                               | 1100/4895 [15:48<29:59,  2.11it/s]


💽 TQM COPY FLOW:  22%|█████████▏                               | 1101/4895 [15:48<29:09,  2.17it/s]


💽 TQM COPY FLOW:  23%|█████████▏                               | 1103/4895 [15:49<21:10,  2.98it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1105/4895 [15:49<15:35,  4.05it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1106/4895 [15:49<18:01,  3.51it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1107/4895 [15:50<16:09,  3.91it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1108/4895 [15:50<18:53,  3.34it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1109/4895 [15:50<17:05,  3.69it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1110/4895 [15:50<14:27,  4.36it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [21:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [16:18<?, ?it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1111/4895 [15:51<15:29,  4.07it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [16:24<?, ?it/s]

❌ ERROR copying /Users/yerik/Music/_0_OLD_SOURCE/2022_DJ/Bad Bunny Ft. El Alfa - La Romana (Fuego)- DjVivaEdit Dembow Drop In+Intro+Outro.mp3 → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_23/Bad Bunny Ft. El Alfa - La Romana (Fuego)- DjVivaEdit Dembow Drop In+Intro+Outro.mp3 | [Errno 2] No such file or directory: '/Users/yerik/Music/_0_OLD_SOURCE/2022_DJ/Bad Bunny Ft. El Alfa - La Romana (Fuego)\uf525\uf525\uf525- DjVivaEdit Dembow Drop In+Intro+Outro.mp3'

💽 TQM COPY FLOW:  23%|█████████▎                               | 1112/4895 [15:51<19:44,  3.19it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1113/4895 [15:52<26:29,  2.38it/s]


💽 TQM COPY FLOW:  23%|█████████▎                               | 1114/4895 [15:52<29:23,  2.14it/s]


💽 TQM COPY FLOW:  23%|████████▉                              | 1115/4895 [16:01<2:53:50,  2.76s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1116/4895 [16:03<2:50:50,  2.71s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1117/4895 [16:04<2:18:15,  2.20s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1118/4895 [16:05<1:53:09,  1.80s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1119/4895 [16:06<1:31:24,  1.45s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1120/4895 [16:07<1:22:33,  1.31s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1121/4895 [16:08<1:15:18,  1.20s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1122/4895 [16:09<1:25:51,  1.37s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1123/4895 [16:19<4:07:45,  3.94s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1124/4895 [16:20<3:05:19,  2.95s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1125/4895 [16:20<2:17:13,  2.18s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1126/4895 [16:21<1:42:59,  1.64s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1127/4895 [16:21<1:22:42,  1.32s/it]


💽 TQM COPY FLOW:  23%|████████▉                              | 1128/4895 [16:22<1:11:32,  1.14s/it]


💽 TQM COPY FLOW:  23%|█████████▍                               | 1129/4895 [16:22<58:49,  1.07it/s]


💽 TQM COPY FLOW:  23%|█████████▍                               | 1130/4895 [16:23<44:28,  1.41it/s]


💽 TQM COPY FLOW:  23%|█████████▍                               | 1131/4895 [16:23<46:51,  1.34it/s]


💽 TQM COPY FLOW:  23%|█████████▍                               | 1132/4895 [16:24<38:03,  1.65it/s]


💽 TQM COPY FLOW:  23%|█████████▍                               | 1133/4895 [16:24<34:24,  1.82it/s]


💽 TQM COPY FLOW:  23%|█████████▍                               | 1134/4895 [16:25<36:01,  1.74it/s]


💽 TQM COPY FLOW:  23%|█████████                              | 1135/4895 [16:28<1:31:25,  1.46s/it]


💽 TQM COPY FLOW:  23%|█████████                              | 1136/4895 [16:29<1:08:29,  1.09s/it]


💽 TQM COPY FLOW:  23%|█████████                              | 1137/4895 [16:30<1:10:26,  1.12s/it]


💽 TQM COPY FLOW:  23%|█████████                              | 1138/4895 [16:30<1:02:31,  1.00it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1139/4895 [16:31<49:30,  1.26it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1140/4895 [16:31<43:30,  1.44it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1141/4895 [16:32<37:25,  1.67it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1142/4895 [16:32<30:31,  2.05it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1143/4895 [16:32<26:42,  2.34it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1144/4895 [16:32<24:53,  2.51it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1145/4895 [16:33<27:02,  2.31it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1146/4895 [16:34<43:08,  1.45it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1147/4895 [16:35<42:08,  1.48it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [22:33<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [17:03<?, ?it/s]


💽 TQM COPY FLOW:  23%|█████████▌                               | 1148/4895 [16:35<35:34,  1.76it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [17:09<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_23 (50 files)

💽 TQM COPY FLOW:  23%|█████████▌                               | 1149/4895 [16:35<29:02,  2.15it/s]


💽 TQM COPY FLOW:  23%|█████████▋                               | 1150/4895 [16:36<28:16,  2.21it/s]


💽 TQM COPY FLOW:  24%|█████████▏                             | 1151/4895 [16:44<2:56:51,  2.83s/it]


💽 TQM COPY FLOW:  24%|█████████▏                             | 1152/4895 [16:45<2:08:38,  2.06s/it]


💽 TQM COPY FLOW:  24%|█████████▏                             | 1153/4895 [16:45<1:35:51,  1.54s/it]


💽 TQM COPY FLOW:  24%|█████████▏                             | 1154/4895 [16:45<1:09:15,  1.11s/it]


💽 TQM COPY FLOW:  24%|█████████▋                               | 1155/4895 [16:45<53:45,  1.16it/s]


💽 TQM COPY FLOW:  24%|█████████▋                               | 1156/4895 [16:46<43:22,  1.44it/s]


💽 TQM COPY FLOW:  24%|█████████▋                               | 1157/4895 [16:46<35:14,  1.77it/s]


💽 TQM COPY FLOW:  24%|█████████▏                             | 1158/4895 [16:50<1:40:29,  1.61s/it]


💽 TQM COPY FLOW:  24%|█████████▏                             | 1159/4895 [16:51<1:40:38,  1.62s/it]


💽 TQM COPY FLOW:  24%|█████████▏                             | 1160/4895 [16:53<1:37:28,  1.57s/it]


💽 TQM COPY FLOW:  24%|█████████▎                             | 1161/4895 [16:53<1:12:31,  1.17s/it]


💽 TQM COPY FLOW:  24%|█████████▎                             | 1162/4895 [16:54<1:09:24,  1.12s/it]


💽 TQM COPY FLOW:  24%|█████████▋                               | 1163/4895 [16:54<53:27,  1.16it/s]


💽 TQM COPY FLOW:  24%|█████████▋                               | 1164/4895 [16:55<46:39,  1.33it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1165/4895 [16:56<44:10,  1.41it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1166/4895 [16:56<44:02,  1.41it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1167/4895 [16:58<56:33,  1.10it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1168/4895 [16:58<48:41,  1.28it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1169/4895 [16:59<43:11,  1.44it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1170/4895 [16:59<40:51,  1.52it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1171/4895 [17:00<41:37,  1.49it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1172/4895 [17:01<49:13,  1.26it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1173/4895 [17:01<42:06,  1.47it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1174/4895 [17:02<42:16,  1.47it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1175/4895 [17:03<38:17,  1.62it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1176/4895 [17:03<31:35,  1.96it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1177/4895 [17:03<28:25,  2.18it/s]


💽 TQM COPY FLOW:  24%|█████████▊                               | 1178/4895 [17:04<28:00,  2.21it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1179/4895 [17:04<26:43,  2.32it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1180/4895 [17:04<26:35,  2.33it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1181/4895 [17:04<20:53,  2.96it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1182/4895 [17:05<22:21,  2.77it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1183/4895 [17:05<23:11,  2.67it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1184/4895 [17:07<40:23,  1.53it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1185/4895 [17:07<31:22,  1.97it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1186/4895 [17:07<23:56,  2.58it/s]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1187/4895 [17:07<22:41,  2.72it/s]


💽 TQM COPY FLOW:  24%|█████████▍                             | 1188/4895 [17:18<3:35:03,  3.48s/it]


💽 TQM COPY FLOW:  24%|█████████▍                             | 1189/4895 [17:18<2:36:23,  2.53s/it]


💽 TQM COPY FLOW:  24%|█████████▍                             | 1190/4895 [17:19<1:54:02,  1.85s/it]


💽 TQM COPY FLOW:  24%|█████████▍                             | 1191/4895 [17:19<1:30:36,  1.47s/it]


💽 TQM COPY FLOW:  24%|█████████▍                             | 1192/4895 [17:19<1:09:04,  1.12s/it]


💽 TQM COPY FLOW:  24%|█████████▉                               | 1193/4895 [17:20<54:45,  1.13it/s]


💽 TQM COPY FLOW:  24%|██████████                               | 1194/4895 [17:20<42:45,  1.44it/s]


💽 TQM COPY FLOW:  24%|██████████                               | 1195/4895 [17:20<36:11,  1.70it/s]


💽 TQM COPY FLOW:  24%|██████████                               | 1196/4895 [17:21<42:09,  1.46it/s]


💽 TQM COPY FLOW:  24%|██████████                               | 1197/4895 [17:22<48:35,  1.27it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [23:21<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [17:50<?, ?it/s]


💽 TQM COPY FLOW:  24%|██████████                               | 1198/4895 [17:23<41:54,  1.47it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [17:56<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_24 (50 files)

💽 TQM COPY FLOW:  24%|██████████                               | 1199/4895 [17:24<49:50,  1.24it/s]


💽 TQM COPY FLOW:  25%|█████████▌                             | 1200/4895 [17:27<1:24:50,  1.38s/it]


💽 TQM COPY FLOW:  25%|█████████▌                             | 1201/4895 [17:27<1:03:54,  1.04s/it]


💽 TQM COPY FLOW:  25%|█████████▌                             | 1202/4895 [17:28<1:16:40,  1.25s/it]


💽 TQM COPY FLOW:  25%|█████████▌                             | 1203/4895 [17:29<1:00:44,  1.01it/s]


💽 TQM COPY FLOW:  25%|██████████                               | 1204/4895 [17:29<48:27,  1.27it/s]


💽 TQM COPY FLOW:  25%|█████████▌                             | 1205/4895 [17:31<1:00:17,  1.02it/s]


💽 TQM COPY FLOW:  25%|██████████                               | 1206/4895 [17:31<55:47,  1.10it/s]


💽 TQM COPY FLOW:  25%|█████████▌                             | 1207/4895 [17:33<1:03:17,  1.03s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [23:31<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [18:01<?, ?it/s]


💽 TQM COPY FLOW:  25%|██████████                               | 1208/4895 [17:33<53:56,  1.14it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [18:07<?, ?it/s]

❌ ERROR copying /Users/yerik/Music/_0_OLD_SOURCE/2023_DJ 25 ACA/onlymp3.to - Angel Dior y su lirica extraña 樂-dpaGwP_jXT4-256k-1657428751199.mp3 → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_25/onlymp3.to - Angel Dior y su lirica extraña 樂-dpaGwP_jXT4-256k-1657428751199.mp3 | [Errno 2] No such file or directory: '/Users/yerik/Music/_0_OLD_SOURCE/2023_DJ 25 ACA/onlymp3.to - Angel Dior y su lirica extraña 樂-dpaGwP_jXT4-256k-1657428751199.mp3'

💽 TQM COPY FLOW:  25%|██████████▏                              | 1209/4895 [17:34<44:59,  1.37it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1210/4895 [17:34<37:08,  1.65it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1211/4895 [17:34<32:08,  1.91it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1212/4895 [17:35<28:58,  2.12it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1213/4895 [17:35<29:21,  2.09it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1214/4895 [17:36<34:27,  1.78it/s]


💽 TQM COPY FLOW:  25%|█████████▋                             | 1215/4895 [17:39<1:17:44,  1.27s/it]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1216/4895 [17:39<57:41,  1.06it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1217/4895 [17:39<48:16,  1.27it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1218/4895 [17:40<49:23,  1.24it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1219/4895 [17:40<38:37,  1.59it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1220/4895 [17:41<33:19,  1.84it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1221/4895 [17:41<36:33,  1.67it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1222/4895 [17:43<58:00,  1.06it/s]


💽 TQM COPY FLOW:  25%|██████████▏                              | 1223/4895 [17:44<48:35,  1.26it/s]


💽 TQM COPY FLOW:  25%|█████████▊                             | 1224/4895 [17:46<1:08:34,  1.12s/it]


💽 TQM COPY FLOW:  25%|█████████▊                             | 1225/4895 [17:46<1:04:32,  1.06s/it]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1226/4895 [17:47<55:31,  1.10it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1227/4895 [17:47<46:49,  1.31it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1228/4895 [17:48<36:40,  1.67it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1229/4895 [17:48<31:10,  1.96it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1230/4895 [17:49<36:24,  1.68it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1231/4895 [17:50<39:53,  1.53it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1232/4895 [17:50<32:29,  1.88it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1233/4895 [17:51<42:04,  1.45it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1234/4895 [17:51<39:04,  1.56it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1235/4895 [17:52<45:16,  1.35it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1236/4895 [17:53<35:32,  1.72it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1237/4895 [17:53<29:43,  2.05it/s]


💽 TQM COPY FLOW:  25%|██████████▎                              | 1238/4895 [17:53<25:00,  2.44it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1239/4895 [17:53<19:49,  3.07it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1240/4895 [17:54<19:39,  3.10it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1241/4895 [17:54<16:53,  3.61it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1242/4895 [17:54<21:41,  2.81it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1243/4895 [17:54<18:54,  3.22it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1244/4895 [17:55<15:47,  3.85it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1245/4895 [17:55<22:24,  2.71it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1246/4895 [17:55<20:56,  2.90it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [23:54<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [18:23<?, ?it/s]


💽 TQM COPY FLOW:  25%|██████████▍                              | 1247/4895 [17:56<22:37,  2.69it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [18:30<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_25 (50 files)

💽 TQM COPY FLOW:  25%|██████████▍                              | 1248/4895 [17:57<35:04,  1.73it/s]


💽 TQM COPY FLOW:  26%|██████████▍                              | 1249/4895 [17:58<34:59,  1.74it/s]


💽 TQM COPY FLOW:  26%|██████████▍                              | 1250/4895 [17:58<33:03,  1.84it/s]


💽 TQM COPY FLOW:  26%|██████████▍                              | 1251/4895 [17:58<29:22,  2.07it/s]


💽 TQM COPY FLOW:  26%|██████████▍                              | 1252/4895 [17:59<39:16,  1.55it/s]


💽 TQM COPY FLOW:  26%|██████████▍                              | 1253/4895 [18:00<36:44,  1.65it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1254/4895 [18:00<28:41,  2.11it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1255/4895 [18:01<37:29,  1.62it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1256/4895 [18:02<45:14,  1.34it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1257/4895 [18:03<55:17,  1.10it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1258/4895 [18:04<46:37,  1.30it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1259/4895 [18:04<42:24,  1.43it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1260/4895 [18:05<36:32,  1.66it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1261/4895 [18:05<33:07,  1.83it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1262/4895 [18:05<26:35,  2.28it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1263/4895 [18:06<25:31,  2.37it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1264/4895 [18:06<24:04,  2.51it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1265/4895 [18:06<19:28,  3.11it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1266/4895 [18:07<24:24,  2.48it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1267/4895 [18:07<20:11,  3.00it/s]


💽 TQM COPY FLOW:  26%|██████████▌                              | 1268/4895 [18:07<21:16,  2.84it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1269/4895 [18:08<24:31,  2.46it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1270/4895 [18:08<22:30,  2.68it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1271/4895 [18:09<23:44,  2.54it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1272/4895 [18:09<31:27,  1.92it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1273/4895 [18:11<53:02,  1.14it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1274/4895 [18:12<47:56,  1.26it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1275/4895 [18:12<41:38,  1.45it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1276/4895 [18:13<49:33,  1.22it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1277/4895 [18:14<44:30,  1.35it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1278/4895 [18:14<39:57,  1.51it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1279/4895 [18:15<36:23,  1.66it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1280/4895 [18:16<41:14,  1.46it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1281/4895 [18:17<49:35,  1.21it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1282/4895 [18:17<40:01,  1.50it/s]


💽 TQM COPY FLOW:  26%|██████████▋                              | 1283/4895 [18:17<32:03,  1.88it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1284/4895 [18:18<33:55,  1.77it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1285/4895 [18:18<26:44,  2.25it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1286/4895 [18:18<24:38,  2.44it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1287/4895 [18:19<20:39,  2.91it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1288/4895 [18:19<21:21,  2.82it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1289/4895 [18:19<19:23,  3.10it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1290/4895 [18:20<17:15,  3.48it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1291/4895 [18:20<17:09,  3.50it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1292/4895 [18:20<19:04,  3.15it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1293/4895 [18:21<19:46,  3.04it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1294/4895 [18:21<19:44,  3.04it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1295/4895 [18:21<24:41,  2.43it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1296/4895 [18:22<31:50,  1.88it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [24:21<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [18:50<?, ?it/s]


💽 TQM COPY FLOW:  26%|██████████▊                              | 1297/4895 [18:23<32:10,  1.86it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [18:57<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_26 (50 files)

💽 TQM COPY FLOW:  27%|██████████▊                              | 1298/4895 [18:23<31:46,  1.89it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1299/4895 [18:24<40:20,  1.49it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1300/4895 [18:25<46:21,  1.29it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1301/4895 [18:26<42:55,  1.40it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1302/4895 [18:26<33:48,  1.77it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1304/4895 [18:27<25:36,  2.34it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1305/4895 [18:27<24:53,  2.40it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1307/4895 [18:28<27:53,  2.14it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1308/4895 [18:28<23:56,  2.50it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1309/4895 [18:28<20:25,  2.93it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1310/4895 [18:29<17:59,  3.32it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1311/4895 [18:29<15:49,  3.77it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1312/4895 [18:29<13:53,  4.30it/s]


💽 TQM COPY FLOW:  27%|██████████▉                              | 1313/4895 [18:29<11:54,  5.02it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1314/4895 [18:30<23:38,  2.52it/s]


💽 TQM COPY FLOW:  27%|██████████▍                            | 1315/4895 [18:33<1:04:10,  1.08s/it]


💽 TQM COPY FLOW:  27%|███████████                              | 1316/4895 [18:33<53:51,  1.11it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1317/4895 [18:34<43:38,  1.37it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1318/4895 [18:34<35:07,  1.70it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1319/4895 [18:34<28:31,  2.09it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1320/4895 [18:34<23:50,  2.50it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1321/4895 [18:35<24:35,  2.42it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1322/4895 [18:35<22:09,  2.69it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1323/4895 [18:35<21:58,  2.71it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1324/4895 [18:36<22:19,  2.67it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1326/4895 [18:36<19:40,  3.02it/s]


💽 TQM COPY FLOW:  27%|███████████                              | 1328/4895 [18:36<13:53,  4.28it/s]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1329/4895 [18:37<18:57,  3.14it/s]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1330/4895 [18:37<19:12,  3.09it/s]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1331/4895 [18:38<20:44,  2.86it/s]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1332/4895 [18:38<23:00,  2.58it/s]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1333/4895 [18:38<19:30,  3.04it/s]


💽 TQM COPY FLOW:  27%|██████████▋                            | 1334/4895 [18:47<2:35:41,  2.62s/it]


💽 TQM COPY FLOW:  27%|██████████▋                            | 1335/4895 [18:52<3:16:58,  3.32s/it]


💽 TQM COPY FLOW:  27%|██████████▋                            | 1336/4895 [18:52<2:25:18,  2.45s/it]


💽 TQM COPY FLOW:  27%|██████████▋                            | 1337/4895 [18:56<2:50:55,  2.88s/it]


💽 TQM COPY FLOW:  27%|██████████▋                            | 1338/4895 [18:57<2:07:49,  2.16s/it]


💽 TQM COPY FLOW:  27%|██████████▋                            | 1339/4895 [18:57<1:37:08,  1.64s/it]


💽 TQM COPY FLOW:  27%|██████████▋                            | 1340/4895 [18:58<1:17:40,  1.31s/it]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1341/4895 [18:58<59:54,  1.01s/it]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1342/4895 [18:58<49:43,  1.19it/s]


💽 TQM COPY FLOW:  27%|███████████▏                             | 1343/4895 [18:59<41:21,  1.43it/s]


💽 TQM COPY FLOW:  27%|███████████▎                             | 1344/4895 [18:59<41:48,  1.42it/s]


💽 TQM COPY FLOW:  27%|███████████▎                             | 1345/4895 [19:00<36:25,  1.62it/s]


💽 TQM COPY FLOW:  27%|███████████▎                             | 1346/4895 [19:00<31:22,  1.89it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [24:58<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [19:28<?, ?it/s]


💽 TQM COPY FLOW:  28%|███████████▎                             | 1347/4895 [19:01<29:20,  2.02it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [19:34<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_27 (50 files)

💽 TQM COPY FLOW:  28%|███████████▎                             | 1348/4895 [19:02<38:14,  1.55it/s]


💽 TQM COPY FLOW:  28%|██████████▋                            | 1349/4895 [19:05<1:23:26,  1.41s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1350/4895 [19:08<2:02:23,  2.07s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1351/4895 [19:09<1:38:00,  1.66s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1352/4895 [19:11<1:47:11,  1.82s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1353/4895 [19:12<1:27:37,  1.48s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1354/4895 [19:13<1:18:37,  1.33s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1355/4895 [19:18<2:28:50,  2.52s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1356/4895 [19:21<2:41:09,  2.73s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1357/4895 [19:22<2:01:14,  2.06s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1358/4895 [19:23<1:48:49,  1.85s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1359/4895 [19:24<1:22:00,  1.39s/it]


💽 TQM COPY FLOW:  28%|██████████▊                            | 1360/4895 [19:24<1:02:23,  1.06s/it]


💽 TQM COPY FLOW:  28%|███████████▍                             | 1361/4895 [19:24<47:09,  1.25it/s]


💽 TQM COPY FLOW:  28%|███████████▍                             | 1362/4895 [19:24<38:57,  1.51it/s]


💽 TQM COPY FLOW:  28%|███████████▍                             | 1363/4895 [19:25<35:10,  1.67it/s]


💽 TQM COPY FLOW:  28%|███████████▍                             | 1364/4895 [19:25<33:46,  1.74it/s]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1365/4895 [19:28<1:07:59,  1.16s/it]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1366/4895 [19:29<1:05:02,  1.11s/it]


💽 TQM COPY FLOW:  28%|███████████▍                             | 1367/4895 [19:30<58:10,  1.01it/s]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1368/4895 [19:32<1:19:08,  1.35s/it]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1369/4895 [19:33<1:20:47,  1.37s/it]


💽 TQM COPY FLOW:  28%|███████████▍                             | 1370/4895 [19:33<58:53,  1.00s/it]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1371/4895 [19:34<1:00:42,  1.03s/it]


💽 TQM COPY FLOW:  28%|███████████▍                             | 1372/4895 [19:35<55:18,  1.06it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1373/4895 [19:36<47:28,  1.24it/s]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1374/4895 [19:42<2:18:12,  2.36s/it]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1375/4895 [19:42<1:38:47,  1.68s/it]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1376/4895 [19:42<1:17:19,  1.32s/it]


💽 TQM COPY FLOW:  28%|██████████▉                            | 1377/4895 [19:43<1:02:14,  1.06s/it]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1378/4895 [19:43<55:20,  1.06it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1379/4895 [19:44<44:11,  1.33it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1380/4895 [19:44<42:38,  1.37it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1382/4895 [19:45<30:23,  1.93it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1383/4895 [19:45<30:46,  1.90it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1384/4895 [19:46<26:31,  2.21it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1385/4895 [19:47<33:40,  1.74it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1386/4895 [19:47<25:54,  2.26it/s]


💽 TQM COPY FLOW:  28%|███████████▌                             | 1387/4895 [19:47<20:21,  2.87it/s]


💽 TQM COPY FLOW:  28%|███████████▋                             | 1388/4895 [19:48<30:36,  1.91it/s]


💽 TQM COPY FLOW:  28%|███████████▋                             | 1390/4895 [19:48<23:43,  2.46it/s]


💽 TQM COPY FLOW:  28%|███████████▋                             | 1391/4895 [19:49<25:19,  2.31it/s]


💽 TQM COPY FLOW:  28%|███████████                            | 1392/4895 [19:52<1:12:14,  1.24s/it]


💽 TQM COPY FLOW:  28%|███████████                            | 1393/4895 [19:53<1:02:21,  1.07s/it]


💽 TQM COPY FLOW:  28%|███████████▋                             | 1394/4895 [19:54<57:47,  1.01it/s]


💽 TQM COPY FLOW:  28%|███████████▋                             | 1395/4895 [19:54<51:21,  1.14it/s]


💽 TQM COPY FLOW:  29%|███████████                            | 1396/4895 [19:59<1:53:19,  1.94s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [26:05<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [20:34<?, ?it/s]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1397/4895 [20:07<3:36:35,  3.72s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [20:41<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_28 (50 files)

💽 TQM COPY FLOW:  29%|███████████▏                           | 1398/4895 [20:10<3:22:51,  3.48s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1399/4895 [20:17<4:23:23,  4.52s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1400/4895 [20:17<3:10:02,  3.26s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1401/4895 [20:18<2:23:56,  2.47s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1402/4895 [20:18<1:50:38,  1.90s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1403/4895 [20:19<1:33:22,  1.60s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1404/4895 [20:20<1:15:53,  1.30s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1405/4895 [20:23<1:48:23,  1.86s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1406/4895 [20:27<2:24:19,  2.48s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1407/4895 [20:31<2:56:09,  3.03s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1408/4895 [20:34<2:59:05,  3.08s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1409/4895 [20:37<2:56:05,  3.03s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1410/4895 [20:45<4:12:42,  4.35s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1411/4895 [20:47<3:39:44,  3.78s/it]


💽 TQM COPY FLOW:  29%|███████████▏                           | 1412/4895 [20:54<4:24:15,  4.55s/it]


💽 TQM COPY FLOW:  29%|███████████▎                           | 1413/4895 [20:54<3:20:19,  3.45s/it]


💽 TQM COPY FLOW:  29%|███████████▎                           | 1414/4895 [20:55<2:31:45,  2.62s/it]


💽 TQM COPY FLOW:  29%|███████████▎                           | 1415/4895 [20:56<1:55:45,  2.00s/it]


💽 TQM COPY FLOW:  29%|███████████▎                           | 1416/4895 [20:58<1:57:12,  2.02s/it]


💽 TQM COPY FLOW:  29%|███████████▎                           | 1418/4895 [20:59<1:15:26,  1.30s/it]


💽 TQM COPY FLOW:  29%|███████████▎                           | 1419/4895 [20:59<1:00:36,  1.05s/it]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1420/4895 [20:59<51:56,  1.12it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1421/4895 [21:00<41:45,  1.39it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1422/4895 [21:00<38:34,  1.50it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1423/4895 [21:02<51:21,  1.13it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1424/4895 [21:02<43:14,  1.34it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1425/4895 [21:03<39:00,  1.48it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1426/4895 [21:03<35:20,  1.64it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1427/4895 [21:03<32:23,  1.78it/s]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1428/4895 [21:04<35:08,  1.64it/s]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1429/4895 [21:08<1:30:26,  1.57s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1430/4895 [21:08<1:10:57,  1.23s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1431/4895 [21:10<1:13:55,  1.28s/it]


💽 TQM COPY FLOW:  29%|███████████▉                             | 1432/4895 [21:10<56:51,  1.02it/s]


💽 TQM COPY FLOW:  29%|████████████                             | 1433/4895 [21:11<51:52,  1.11it/s]


💽 TQM COPY FLOW:  29%|████████████                             | 1434/4895 [21:12<50:14,  1.15it/s]


💽 TQM COPY FLOW:  29%|████████████                             | 1435/4895 [21:12<42:42,  1.35it/s]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1436/4895 [21:16<1:40:54,  1.75s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1437/4895 [21:17<1:19:03,  1.37s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1438/4895 [21:20<1:50:53,  1.92s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1439/4895 [21:21<1:45:32,  1.83s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1440/4895 [21:22<1:23:33,  1.45s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1441/4895 [21:23<1:09:14,  1.20s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1442/4895 [21:32<3:32:05,  3.69s/it]


💽 TQM COPY FLOW:  29%|███████████▍                           | 1443/4895 [21:33<2:35:05,  2.70s/it]


💽 TQM COPY FLOW:  29%|███████████▌                           | 1444/4895 [21:33<1:59:28,  2.08s/it]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1445/4895 [21:34<1:36:59,  1.69s/it]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1446/4895 [21:35<1:19:03,  1.38s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:33<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:02<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1447/4895 [21:35<1:02:57,  1.10s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:09<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_29 (50 files)

💽 TQM COPY FLOW:  30%|███████████▌                           | 1448/4895 [21:38<1:35:17,  1.66s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:06<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1449/4895 [21:39<1:19:53,  1.39s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:06<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1449/4895 [21:39<1:19:53,  1.39s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:06<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1449/4895 [21:39<1:19:53,  1.39s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:06<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1449/4895 [21:39<1:19:53,  1.39s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:06<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1449/4895 [21:39<1:19:53,  1.39s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:06<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1449/4895 [21:39<1:19:53,  1.39s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:06<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1449/4895 [21:39<1:19:53,  1.39s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:13<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_30/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_30 (3 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_31/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_31 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_32/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_32 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_33/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  30%|███████████▌                           | 1450/4895 [21:39<1:07:48,  1.18s/it]


💽 TQM COPY FLOW:  30%|████████████▏                            | 1451/4895 [21:40<58:57,  1.03s/it]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1452/4895 [21:42<1:13:07,  1.27s/it]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1453/4895 [21:44<1:33:10,  1.62s/it]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1454/4895 [21:46<1:26:38,  1.51s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:14<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:15<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:15<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:15<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:15<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:15<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:15<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [27:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:15<?, ?it/s]


💽 TQM COPY FLOW:  30%|███████████▌                           | 1455/4895 [21:47<1:22:58,  1.45s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [22:21<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_33 (7 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_34/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_34 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_35/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_35 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_36/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_36 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_37/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_37 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_38/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_38 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_39/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_39 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_40/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_40 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_41/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  30%|███████████▌                           | 1456/4895 [21:47<1:03:05,  1.10s/it]


💽 TQM COPY FLOW:  30%|████████████▏                            | 1457/4895 [21:48<49:06,  1.17it/s]


💽 TQM COPY FLOW:  30%|████████████▏                            | 1458/4895 [21:48<42:10,  1.36it/s]


💽 TQM COPY FLOW:  30%|████████████▏                            | 1459/4895 [21:48<35:13,  1.63it/s]


💽 TQM COPY FLOW:  30%|████████████▏                            | 1460/4895 [21:49<27:44,  2.06it/s]


💽 TQM COPY FLOW:  30%|████████████▏                            | 1461/4895 [21:49<24:13,  2.36it/s]


💽 TQM COPY FLOW:  30%|████████████▏                            | 1462/4895 [21:49<22:32,  2.54it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1463/4895 [21:49<21:37,  2.65it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1464/4895 [21:50<19:49,  2.89it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1465/4895 [21:50<15:58,  3.58it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1466/4895 [21:50<15:41,  3.64it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1467/4895 [21:50<15:05,  3.79it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1468/4895 [21:51<16:49,  3.40it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1469/4895 [21:52<25:00,  2.28it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1470/4895 [21:52<20:18,  2.81it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1471/4895 [21:52<27:09,  2.10it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1472/4895 [21:53<27:42,  2.06it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1473/4895 [21:54<30:55,  1.84it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1474/4895 [21:55<36:51,  1.55it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1475/4895 [21:55<36:17,  1.57it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1476/4895 [21:56<42:32,  1.34it/s]


💽 TQM COPY FLOW:  30%|████████████▎                            | 1477/4895 [21:57<44:35,  1.28it/s]


💽 TQM COPY FLOW:  30%|████████████▍                            | 1478/4895 [21:58<41:49,  1.36it/s]


💽 TQM COPY FLOW:  30%|████████████▍                            | 1479/4895 [21:58<42:19,  1.35it/s]


💽 TQM COPY FLOW:  30%|████████████▍                            | 1480/4895 [22:00<51:25,  1.11it/s]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1481/4895 [22:07<2:37:34,  2.77s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1482/4895 [22:19<5:18:29,  5.60s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1483/4895 [22:19<3:49:50,  4.04s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1485/4895 [22:22<2:34:56,  2.73s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1486/4895 [22:22<2:04:51,  2.20s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1487/4895 [22:23<1:41:52,  1.79s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1488/4895 [22:24<1:25:03,  1.50s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1489/4895 [22:25<1:15:34,  1.33s/it]


💽 TQM COPY FLOW:  30%|███████████▊                           | 1490/4895 [22:26<1:10:45,  1.25s/it]


💽 TQM COPY FLOW:  30%|███████████▉                           | 1491/4895 [22:26<1:01:00,  1.08s/it]


💽 TQM COPY FLOW:  30%|███████████▉                           | 1492/4895 [22:29<1:28:13,  1.56s/it]


💽 TQM COPY FLOW:  31%|███████████▉                           | 1493/4895 [22:32<1:56:11,  2.05s/it]


💽 TQM COPY FLOW:  31%|███████████▉                           | 1494/4895 [22:33<1:29:27,  1.58s/it]


💽 TQM COPY FLOW:  31%|███████████▉                           | 1495/4895 [22:33<1:13:29,  1.30s/it]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1496/4895 [22:34<57:41,  1.02s/it]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1497/4895 [22:34<49:40,  1.14it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1498/4895 [22:35<46:15,  1.22it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1499/4895 [22:35<37:23,  1.51it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1500/4895 [22:36<33:54,  1.67it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1501/4895 [22:37<51:41,  1.09it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1502/4895 [22:38<42:31,  1.33it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1503/4895 [22:38<35:57,  1.57it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [28:36<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [23:06<?, ?it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1504/4895 [22:38<27:28,  2.06it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [23:12<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_41 (50 files)

💽 TQM COPY FLOW:  31%|████████████▌                            | 1505/4895 [22:38<23:43,  2.38it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1506/4895 [22:39<25:23,  2.22it/s]


💽 TQM COPY FLOW:  31%|████████████▌                            | 1507/4895 [22:39<23:45,  2.38it/s]


💽 TQM COPY FLOW:  31%|████████████                           | 1508/4895 [22:48<2:35:55,  2.76s/it]


💽 TQM COPY FLOW:  31%|████████████                           | 1510/4895 [22:48<1:29:40,  1.59s/it]


💽 TQM COPY FLOW:  31%|████████████                           | 1511/4895 [22:49<1:17:33,  1.38s/it]


💽 TQM COPY FLOW:  31%|████████████                           | 1512/4895 [22:49<1:08:03,  1.21s/it]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1514/4895 [22:50<42:14,  1.33it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1515/4895 [22:50<35:39,  1.58it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1516/4895 [22:50<32:41,  1.72it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1517/4895 [22:51<31:14,  1.80it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1518/4895 [22:51<27:36,  2.04it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1519/4895 [22:52<25:49,  2.18it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1520/4895 [22:52<22:18,  2.52it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1521/4895 [22:52<22:04,  2.55it/s]


💽 TQM COPY FLOW:  31%|████████████▋                            | 1522/4895 [22:53<23:45,  2.37it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1523/4895 [22:53<21:32,  2.61it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1524/4895 [22:53<19:13,  2.92it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1525/4895 [22:54<19:34,  2.87it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1526/4895 [22:54<20:11,  2.78it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1527/4895 [22:54<20:35,  2.73it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1528/4895 [22:55<25:07,  2.23it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1529/4895 [22:55<25:23,  2.21it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1530/4895 [22:56<33:06,  1.69it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1531/4895 [22:57<29:39,  1.89it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1532/4895 [22:57<24:59,  2.24it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1533/4895 [22:58<33:41,  1.66it/s]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1534/4895 [22:59<45:08,  1.24it/s]


💽 TQM COPY FLOW:  31%|████████████▏                          | 1535/4895 [23:02<1:15:05,  1.34s/it]


💽 TQM COPY FLOW:  31%|████████████▏                          | 1536/4895 [23:02<1:01:25,  1.10s/it]


💽 TQM COPY FLOW:  31%|████████████▊                            | 1537/4895 [23:03<51:55,  1.08it/s]


💽 TQM COPY FLOW:  31%|████████████▉                            | 1538/4895 [23:04<46:18,  1.21it/s]


💽 TQM COPY FLOW:  31%|████████████▉                            | 1539/4895 [23:04<38:46,  1.44it/s]


💽 TQM COPY FLOW:  31%|████████████▉                            | 1540/4895 [23:04<36:18,  1.54it/s]


💽 TQM COPY FLOW:  31%|████████████▎                          | 1541/4895 [23:16<3:34:48,  3.84s/it]


💽 TQM COPY FLOW:  32%|████████████▎                          | 1542/4895 [23:21<3:50:36,  4.13s/it]


💽 TQM COPY FLOW:  32%|████████████▎                          | 1543/4895 [23:21<2:52:31,  3.09s/it]


💽 TQM COPY FLOW:  32%|████████████▎                          | 1544/4895 [23:22<2:09:37,  2.32s/it]


💽 TQM COPY FLOW:  32%|████████████▎                          | 1545/4895 [23:22<1:36:55,  1.74s/it]


💽 TQM COPY FLOW:  32%|████████████▎                          | 1546/4895 [23:23<1:23:22,  1.49s/it]


💽 TQM COPY FLOW:  32%|████████████▎                          | 1547/4895 [23:23<1:04:17,  1.15s/it]


💽 TQM COPY FLOW:  32%|████████████▉                            | 1548/4895 [23:24<47:06,  1.18it/s]


💽 TQM COPY FLOW:  32%|████████████▉                            | 1549/4895 [23:24<40:24,  1.38it/s]


💽 TQM COPY FLOW:  32%|████████████▉                            | 1550/4895 [23:24<35:00,  1.59it/s]


💽 TQM COPY FLOW:  32%|████████████▉                            | 1551/4895 [23:25<35:05,  1.59it/s]


💽 TQM COPY FLOW:  32%|████████████▉                            | 1552/4895 [23:26<39:25,  1.41it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1553/4895 [23:26<33:43,  1.65it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [29:25<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [23:54<?, ?it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1554/4895 [23:27<34:26,  1.62it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [24:01<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_42 (50 files)

💽 TQM COPY FLOW:  32%|█████████████                            | 1555/4895 [23:28<43:01,  1.29it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1556/4895 [23:29<40:29,  1.37it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1557/4895 [23:29<39:46,  1.40it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1558/4895 [23:30<36:42,  1.52it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1559/4895 [23:30<29:45,  1.87it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1560/4895 [23:30<23:22,  2.38it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1561/4895 [23:32<44:37,  1.25it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1562/4895 [23:33<43:23,  1.28it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1563/4895 [23:34<47:07,  1.18it/s]


💽 TQM COPY FLOW:  32%|█████████████                            | 1564/4895 [23:34<39:12,  1.42it/s]


💽 TQM COPY FLOW:  32%|████████████▍                          | 1565/4895 [23:37<1:11:18,  1.28s/it]


💽 TQM COPY FLOW:  32%|████████████▍                          | 1566/4895 [23:38<1:02:56,  1.13s/it]


💽 TQM COPY FLOW:  32%|█████████████▏                           | 1567/4895 [23:38<48:30,  1.14it/s]


💽 TQM COPY FLOW:  32%|█████████████▏                           | 1568/4895 [23:38<36:29,  1.52it/s]


💽 TQM COPY FLOW:  32%|█████████████▏                           | 1569/4895 [23:38<27:14,  2.04it/s]


💽 TQM COPY FLOW:  32%|█████████████▏                           | 1570/4895 [23:38<21:20,  2.60it/s]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1571/4895 [23:55<4:53:55,  5.31s/it]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1572/4895 [23:59<4:36:59,  5.00s/it]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1573/4895 [24:04<4:30:15,  4.88s/it]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1574/4895 [24:06<3:46:52,  4.10s/it]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1575/4895 [24:06<2:41:59,  2.93s/it]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1576/4895 [24:06<1:55:47,  2.09s/it]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1577/4895 [24:07<1:23:23,  1.51s/it]


💽 TQM COPY FLOW:  32%|████████████▌                          | 1578/4895 [24:07<1:03:00,  1.14s/it]


💽 TQM COPY FLOW:  32%|█████████████▏                           | 1579/4895 [24:07<47:12,  1.17it/s]


💽 TQM COPY FLOW:  32%|█████████████▏                           | 1580/4895 [24:07<34:47,  1.59it/s]


💽 TQM COPY FLOW:  32%|█████████████▏                           | 1581/4895 [24:08<30:23,  1.82it/s]


💽 TQM COPY FLOW:  32%|█████████████▎                           | 1582/4895 [24:08<24:46,  2.23it/s]


💽 TQM COPY FLOW:  32%|█████████████▎                           | 1583/4895 [24:08<19:14,  2.87it/s]


💽 TQM COPY FLOW:  32%|█████████████▎                           | 1584/4895 [24:08<16:19,  3.38it/s]


💽 TQM COPY FLOW:  32%|█████████████▎                           | 1586/4895 [24:08<11:52,  4.65it/s]


💽 TQM COPY FLOW:  32%|█████████████▎                           | 1587/4895 [24:09<14:31,  3.80it/s]


💽 TQM COPY FLOW:  32%|█████████████▎                           | 1589/4895 [24:09<10:44,  5.13it/s]


💽 TQM COPY FLOW:  32%|█████████████▎                           | 1590/4895 [24:09<11:35,  4.75it/s]


💽 TQM COPY FLOW:  33%|█████████████▎                           | 1591/4895 [24:09<11:08,  4.94it/s]


💽 TQM COPY FLOW:  33%|█████████████▎                           | 1592/4895 [24:10<15:53,  3.47it/s]


💽 TQM COPY FLOW:  33%|█████████████▎                           | 1593/4895 [24:11<29:01,  1.90it/s]


💽 TQM COPY FLOW:  33%|█████████████▎                           | 1594/4895 [24:13<43:47,  1.26it/s]


💽 TQM COPY FLOW:  33%|█████████████▎                           | 1595/4895 [24:13<35:13,  1.56it/s]


💽 TQM COPY FLOW:  33%|█████████████▎                           | 1596/4895 [24:13<30:33,  1.80it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1597/4895 [24:14<29:35,  1.86it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1598/4895 [24:15<44:12,  1.24it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1599/4895 [24:16<41:32,  1.32it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1600/4895 [24:16<31:31,  1.74it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1601/4895 [24:16<29:21,  1.87it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1602/4895 [24:17<38:50,  1.41it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1603/4895 [24:18<42:12,  1.30it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [30:18<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [24:47<?, ?it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1604/4895 [24:20<51:02,  1.07it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [24:53<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_43 (50 files)

💽 TQM COPY FLOW:  33%|████████████▊                          | 1605/4895 [24:28<2:48:33,  3.07s/it]


💽 TQM COPY FLOW:  33%|████████████▊                          | 1606/4895 [24:28<2:05:01,  2.28s/it]


💽 TQM COPY FLOW:  33%|████████████▊                          | 1607/4895 [24:28<1:30:14,  1.65s/it]


💽 TQM COPY FLOW:  33%|████████████▊                          | 1608/4895 [24:29<1:08:14,  1.25s/it]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1610/4895 [24:29<41:05,  1.33it/s]


💽 TQM COPY FLOW:  33%|█████████████▍                           | 1611/4895 [24:29<34:22,  1.59it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1612/4895 [24:29<27:53,  1.96it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1613/4895 [24:30<25:18,  2.16it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1614/4895 [24:30<23:17,  2.35it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1615/4895 [24:30<19:22,  2.82it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1616/4895 [24:30<15:57,  3.42it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1617/4895 [24:30<13:02,  4.19it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1618/4895 [24:31<15:28,  3.53it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1619/4895 [24:31<13:19,  4.10it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1620/4895 [24:32<19:40,  2.77it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1621/4895 [24:32<23:33,  2.32it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1622/4895 [24:32<18:22,  2.97it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1623/4895 [24:33<17:13,  3.17it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1624/4895 [24:33<18:26,  2.96it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1625/4895 [24:33<15:40,  3.48it/s]


💽 TQM COPY FLOW:  33%|█████████████▌                           | 1626/4895 [24:33<15:22,  3.54it/s]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1627/4895 [24:34<14:57,  3.64it/s]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1628/4895 [24:34<19:11,  2.84it/s]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1629/4895 [24:35<21:05,  2.58it/s]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1630/4895 [24:36<36:40,  1.48it/s]


💽 TQM COPY FLOW:  33%|████████████▉                          | 1631/4895 [24:45<2:50:41,  3.14s/it]


💽 TQM COPY FLOW:  33%|█████████████                          | 1632/4895 [24:47<2:25:51,  2.68s/it]


💽 TQM COPY FLOW:  33%|█████████████                          | 1633/4895 [24:47<1:52:09,  2.06s/it]


💽 TQM COPY FLOW:  33%|█████████████                          | 1634/4895 [24:48<1:28:41,  1.63s/it]


💽 TQM COPY FLOW:  33%|█████████████                          | 1635/4895 [24:48<1:09:05,  1.27s/it]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1636/4895 [24:49<55:00,  1.01s/it]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1637/4895 [24:49<44:22,  1.22it/s]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1638/4895 [24:49<35:16,  1.54it/s]


💽 TQM COPY FLOW:  33%|█████████████▋                           | 1639/4895 [24:50<30:36,  1.77it/s]


💽 TQM COPY FLOW:  34%|█████████████▋                           | 1640/4895 [24:50<25:15,  2.15it/s]


💽 TQM COPY FLOW:  34%|█████████████▋                           | 1641/4895 [24:50<23:21,  2.32it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1642/4895 [24:50<20:46,  2.61it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1643/4895 [24:51<18:47,  2.88it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1644/4895 [24:51<20:16,  2.67it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1645/4895 [24:51<18:13,  2.97it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1646/4895 [24:52<17:25,  3.11it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1647/4895 [24:52<15:24,  3.51it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1648/4895 [24:53<22:22,  2.42it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1649/4895 [24:53<25:19,  2.14it/s]


💽 TQM COPY FLOW:  34%|█████████████▏                         | 1650/4895 [24:58<1:40:17,  1.85s/it]


💽 TQM COPY FLOW:  34%|█████████████▏                         | 1651/4895 [24:59<1:14:17,  1.37s/it]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1652/4895 [24:59<56:26,  1.04s/it]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1653/4895 [24:59<46:17,  1.17it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [30:57<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [25:27<?, ?it/s]


💽 TQM COPY FLOW:  34%|█████████████▊                           | 1654/4895 [25:00<37:03,  1.46it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [25:33<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_44 (50 files)

💽 TQM COPY FLOW:  34%|█████████████▏                         | 1655/4895 [25:03<1:15:42,  1.40s/it]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1657/4895 [25:04<58:32,  1.08s/it]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1658/4895 [25:04<49:26,  1.09it/s]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1659/4895 [25:05<45:38,  1.18it/s]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1660/4895 [25:05<35:29,  1.52it/s]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1661/4895 [25:07<49:40,  1.09it/s]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1662/4895 [25:07<42:39,  1.26it/s]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1663/4895 [25:08<35:27,  1.52it/s]


💽 TQM COPY FLOW:  34%|█████████████▉                           | 1664/4895 [25:08<35:51,  1.50it/s]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1665/4895 [25:15<2:15:43,  2.52s/it]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1666/4895 [25:15<1:37:38,  1.81s/it]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1667/4895 [25:16<1:12:22,  1.35s/it]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1668/4895 [25:19<1:43:00,  1.92s/it]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1669/4895 [25:20<1:27:34,  1.63s/it]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1670/4895 [25:20<1:05:29,  1.22s/it]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1671/4895 [25:22<1:10:15,  1.31s/it]


💽 TQM COPY FLOW:  34%|██████████████                           | 1672/4895 [25:22<53:10,  1.01it/s]


💽 TQM COPY FLOW:  34%|██████████████                           | 1673/4895 [25:22<46:21,  1.16it/s]


💽 TQM COPY FLOW:  34%|██████████████                           | 1674/4895 [25:23<40:14,  1.33it/s]


💽 TQM COPY FLOW:  34%|██████████████                           | 1675/4895 [25:24<41:07,  1.31it/s]


💽 TQM COPY FLOW:  34%|██████████████                           | 1676/4895 [25:25<44:23,  1.21it/s]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1677/4895 [25:28<1:27:02,  1.62s/it]


💽 TQM COPY FLOW:  34%|█████████████▎                         | 1678/4895 [25:28<1:03:22,  1.18s/it]


💽 TQM COPY FLOW:  34%|█████████████▍                         | 1679/4895 [25:30<1:10:05,  1.31s/it]


💽 TQM COPY FLOW:  34%|██████████████                           | 1680/4895 [25:31<57:46,  1.08s/it]


💽 TQM COPY FLOW:  34%|██████████████                           | 1681/4895 [25:31<50:32,  1.06it/s]


💽 TQM COPY FLOW:  34%|██████████████                           | 1682/4895 [25:33<59:49,  1.12s/it]


💽 TQM COPY FLOW:  34%|█████████████▍                         | 1683/4895 [25:39<2:20:40,  2.63s/it]


💽 TQM COPY FLOW:  34%|█████████████▍                         | 1684/4895 [25:42<2:29:35,  2.80s/it]


💽 TQM COPY FLOW:  34%|█████████████▍                         | 1685/4895 [25:46<2:43:29,  3.06s/it]


💽 TQM COPY FLOW:  34%|█████████████▍                         | 1686/4895 [25:46<1:59:05,  2.23s/it]


💽 TQM COPY FLOW:  34%|█████████████▍                         | 1687/4895 [25:48<2:01:26,  2.27s/it]


💽 TQM COPY FLOW:  34%|█████████████▍                         | 1688/4895 [25:51<2:15:32,  2.54s/it]


💽 TQM COPY FLOW:  35%|█████████████▍                         | 1689/4895 [25:52<1:43:54,  1.94s/it]


💽 TQM COPY FLOW:  35%|█████████████▍                         | 1690/4895 [25:58<2:53:49,  3.25s/it]


💽 TQM COPY FLOW:  35%|█████████████▍                         | 1691/4895 [26:01<2:37:45,  2.95s/it]


💽 TQM COPY FLOW:  35%|█████████████▍                         | 1692/4895 [26:03<2:35:39,  2.92s/it]


💽 TQM COPY FLOW:  35%|█████████████▍                         | 1693/4895 [26:07<2:41:46,  3.03s/it]


💽 TQM COPY FLOW:  35%|█████████████▍                         | 1694/4895 [26:08<2:05:21,  2.35s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1695/4895 [26:11<2:15:38,  2.54s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1696/4895 [26:14<2:27:52,  2.77s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1697/4895 [26:14<1:51:58,  2.10s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [32:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [26:42<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1698/4895 [26:15<1:27:47,  1.65s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [32:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [26:42<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1698/4895 [26:15<1:27:47,  1.65s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [26:49<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_45/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_45 (45 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [32:15<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [26:44<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1698/4895 [26:17<1:27:47,  1.65s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [26:51<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_46/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  35%|█████████████▌                         | 1699/4895 [26:20<2:23:17,  2.69s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1700/4895 [26:23<2:24:18,  2.71s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1701/4895 [26:26<2:24:41,  2.72s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1702/4895 [26:26<1:46:14,  2.00s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1703/4895 [26:34<3:24:25,  3.84s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1704/4895 [26:38<3:22:12,  3.80s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1705/4895 [26:41<3:11:27,  3.60s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1706/4895 [26:41<2:17:09,  2.58s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [32:39<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:09<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1707/4895 [26:41<1:39:11,  1.87s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [32:39<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:09<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1707/4895 [26:41<1:39:11,  1.87s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:15<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_46 (10 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_47/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  35%|█████████████▌                         | 1708/4895 [26:42<1:25:44,  1.61s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1709/4895 [26:43<1:13:06,  1.38s/it]


💽 TQM COPY FLOW:  35%|█████████████▌                         | 1710/4895 [26:44<1:00:59,  1.15s/it]


💽 TQM COPY FLOW:  35%|██████████████▎                          | 1711/4895 [26:44<46:20,  1.15it/s]


💽 TQM COPY FLOW:  35%|██████████████▎                          | 1712/4895 [26:44<36:08,  1.47it/s]


💽 TQM COPY FLOW:  35%|██████████████▎                          | 1713/4895 [26:46<46:58,  1.13it/s]


💽 TQM COPY FLOW:  35%|██████████████▎                          | 1714/4895 [26:46<45:58,  1.15it/s]


💽 TQM COPY FLOW:  35%|██████████████▎                          | 1715/4895 [26:47<43:05,  1.23it/s]


💽 TQM COPY FLOW:  35%|██████████████▎                          | 1716/4895 [26:47<35:48,  1.48it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1717/4895 [26:48<29:54,  1.77it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1718/4895 [26:49<42:05,  1.26it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1719/4895 [26:50<42:19,  1.25it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1720/4895 [26:50<37:55,  1.40it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1721/4895 [26:51<31:44,  1.67it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1722/4895 [26:51<31:40,  1.67it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1723/4895 [26:52<30:15,  1.75it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1724/4895 [26:52<27:04,  1.95it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1725/4895 [26:53<30:40,  1.72it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1726/4895 [26:53<25:42,  2.05it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1727/4895 [26:54<32:12,  1.64it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1728/4895 [26:54<27:00,  1.95it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1729/4895 [26:55<25:22,  2.08it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1730/4895 [26:55<23:34,  2.24it/s]


💽 TQM COPY FLOW:  35%|██████████████▍                          | 1731/4895 [26:56<23:12,  2.27it/s]


💽 TQM COPY FLOW:  35%|██████████████▌                          | 1732/4895 [26:56<24:56,  2.11it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1733/4895 [27:07<3:16:27,  3.73s/it]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1734/4895 [27:08<2:30:22,  2.85s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:37<?, ?it/s]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1735/4895 [27:09<2:01:05,  2.30s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [27:43<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_47 (29 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_48/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_48 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_49/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_49 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_50/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_50 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_51/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  35%|█████████████▊                         | 1736/4895 [27:13<2:23:19,  2.72s/it]


💽 TQM COPY FLOW:  35%|█████████████▊                         | 1737/4895 [27:16<2:26:42,  2.79s/it]


💽 TQM COPY FLOW:  36%|█████████████▊                         | 1738/4895 [27:21<3:05:16,  3.52s/it]


💽 TQM COPY FLOW:  36%|█████████████▊                         | 1739/4895 [27:23<2:35:14,  2.95s/it]


💽 TQM COPY FLOW:  36%|█████████████▊                         | 1740/4895 [27:30<3:45:59,  4.30s/it]


💽 TQM COPY FLOW:  36%|█████████████▊                         | 1741/4895 [27:34<3:31:53,  4.03s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1742/4895 [27:38<3:38:43,  4.16s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1743/4895 [27:39<2:50:23,  3.24s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1744/4895 [27:48<4:11:34,  4.79s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [33:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:20<?, ?it/s]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1745/4895 [27:52<4:07:44,  4.72s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [28:26<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_51 (11 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_52/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_52 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_53/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_53 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_54/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_54 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_55/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_55 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_56/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  36%|█████████████▉                         | 1746/4895 [27:55<3:34:40,  4.09s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1747/4895 [27:59<3:42:32,  4.24s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1748/4895 [28:00<2:53:20,  3.30s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1749/4895 [28:07<3:37:45,  4.15s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1750/4895 [28:20<6:01:15,  6.89s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1751/4895 [28:27<6:07:38,  7.02s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1752/4895 [28:28<4:29:14,  5.14s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1753/4895 [28:28<3:15:01,  3.72s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1754/4895 [28:29<2:28:10,  2.83s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1755/4895 [28:36<3:36:37,  4.14s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1756/4895 [28:40<3:28:54,  3.99s/it]


💽 TQM COPY FLOW:  36%|█████████████▉                         | 1757/4895 [28:41<2:37:02,  3.00s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1758/4895 [28:44<2:49:03,  3.23s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1759/4895 [28:48<2:59:57,  3.44s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1760/4895 [28:52<3:04:54,  3.54s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1761/4895 [28:56<3:03:11,  3.51s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1762/4895 [28:59<3:08:19,  3.61s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1763/4895 [29:00<2:16:14,  2.61s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1764/4895 [29:05<2:53:09,  3.32s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [35:10<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [29:39<?, ?it/s]


💽 TQM COPY FLOW:  36%|██████████████                         | 1765/4895 [29:12<3:51:33,  4.44s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [29:45<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_56 (21 files)

💽 TQM COPY FLOW:  36%|██████████████                         | 1766/4895 [29:16<3:43:29,  4.29s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1767/4895 [29:16<2:38:44,  3.04s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1769/4895 [29:17<1:35:39,  1.84s/it]


💽 TQM COPY FLOW:  36%|██████████████                         | 1770/4895 [29:17<1:15:04,  1.44s/it]


💽 TQM COPY FLOW:  36%|██████████████▊                          | 1772/4895 [29:18<52:45,  1.01s/it]


💽 TQM COPY FLOW:  36%|██████████████▊                          | 1773/4895 [29:18<47:22,  1.10it/s]


💽 TQM COPY FLOW:  36%|██████████████▊                          | 1774/4895 [29:19<39:51,  1.30it/s]


💽 TQM COPY FLOW:  36%|██████████████▏                        | 1775/4895 [29:22<1:20:14,  1.54s/it]


💽 TQM COPY FLOW:  36%|██████████████▏                        | 1776/4895 [29:23<1:02:34,  1.20s/it]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1777/4895 [29:23<49:16,  1.05it/s]


💽 TQM COPY FLOW:  36%|██████████████▏                        | 1778/4895 [29:25<1:12:30,  1.40s/it]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1779/4895 [29:26<57:29,  1.11s/it]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1780/4895 [29:26<44:59,  1.15it/s]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1781/4895 [29:27<42:16,  1.23it/s]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1782/4895 [29:27<33:42,  1.54it/s]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1783/4895 [29:28<30:17,  1.71it/s]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1784/4895 [29:28<29:23,  1.76it/s]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1785/4895 [29:28<25:52,  2.00it/s]


💽 TQM COPY FLOW:  36%|██████████████▉                          | 1786/4895 [29:29<25:11,  2.06it/s]


💽 TQM COPY FLOW:  37%|██████████████▉                          | 1787/4895 [29:29<24:13,  2.14it/s]


💽 TQM COPY FLOW:  37%|██████████████▉                          | 1788/4895 [29:30<26:42,  1.94it/s]


💽 TQM COPY FLOW:  37%|██████████████▉                          | 1789/4895 [29:30<27:57,  1.85it/s]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1790/4895 [29:35<1:29:16,  1.73s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1791/4895 [29:36<1:18:37,  1.52s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1792/4895 [29:43<2:40:20,  3.10s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1793/4895 [29:44<2:09:29,  2.50s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1794/4895 [29:45<1:42:03,  1.97s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1795/4895 [29:45<1:19:25,  1.54s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1796/4895 [29:46<1:02:10,  1.20s/it]


💽 TQM COPY FLOW:  37%|███████████████                          | 1797/4895 [29:47<58:47,  1.14s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1798/4895 [29:49<1:13:32,  1.42s/it]


💽 TQM COPY FLOW:  37%|███████████████                          | 1799/4895 [29:49<58:14,  1.13s/it]


💽 TQM COPY FLOW:  37%|███████████████                          | 1800/4895 [29:49<44:52,  1.15it/s]


💽 TQM COPY FLOW:  37%|███████████████                          | 1801/4895 [29:50<39:26,  1.31it/s]


💽 TQM COPY FLOW:  37%|███████████████                          | 1802/4895 [29:50<33:39,  1.53it/s]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1803/4895 [29:55<1:34:12,  1.83s/it]


💽 TQM COPY FLOW:  37%|██████████████▎                        | 1804/4895 [29:58<1:50:33,  2.15s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1805/4895 [30:01<2:02:19,  2.38s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1806/4895 [30:01<1:35:57,  1.86s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1807/4895 [30:02<1:16:38,  1.49s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1808/4895 [30:03<1:03:39,  1.24s/it]


💽 TQM COPY FLOW:  37%|███████████████▏                         | 1809/4895 [30:03<51:17,  1.00it/s]


💽 TQM COPY FLOW:  37%|███████████████▏                         | 1810/4895 [30:04<48:18,  1.06it/s]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1811/4895 [30:08<1:41:57,  1.98s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1812/4895 [30:09<1:28:26,  1.72s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [36:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [30:42<?, ?it/s]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1813/4895 [30:15<2:23:31,  2.79s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [30:48<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_57/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [36:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [30:42<?, ?it/s]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1814/4895 [30:15<1:45:24,  2.05s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [30:49<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_57 (50 files)

💽 TQM COPY FLOW:  37%|██████████████▍                        | 1815/4895 [30:18<1:56:20,  2.27s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1816/4895 [30:26<3:32:59,  4.15s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1817/4895 [30:27<2:38:07,  3.08s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1818/4895 [30:31<2:49:43,  3.31s/it]


💽 TQM COPY FLOW:  37%|██████████████▍                        | 1819/4895 [30:34<2:42:18,  3.17s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1820/4895 [30:34<2:03:21,  2.41s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1821/4895 [30:35<1:39:34,  1.94s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1822/4895 [30:37<1:32:47,  1.81s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1823/4895 [30:37<1:16:28,  1.49s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1824/4895 [30:40<1:40:47,  1.97s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1825/4895 [30:43<1:52:19,  2.20s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1826/4895 [30:45<1:53:44,  2.22s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1827/4895 [30:46<1:24:43,  1.66s/it]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1828/4895 [30:46<1:04:52,  1.27s/it]


💽 TQM COPY FLOW:  37%|███████████████▎                         | 1829/4895 [30:46<48:34,  1.05it/s]


💽 TQM COPY FLOW:  37%|███████████████▎                         | 1830/4895 [30:47<37:17,  1.37it/s]


💽 TQM COPY FLOW:  37%|███████████████▎                         | 1831/4895 [30:47<28:02,  1.82it/s]


💽 TQM COPY FLOW:  37%|███████████████▎                         | 1832/4895 [30:47<22:16,  2.29it/s]


💽 TQM COPY FLOW:  37%|███████████████▎                         | 1833/4895 [30:49<50:50,  1.00it/s]


💽 TQM COPY FLOW:  37%|███████████████▎                         | 1834/4895 [30:50<42:15,  1.21it/s]


💽 TQM COPY FLOW:  37%|██████████████▌                        | 1835/4895 [30:54<1:36:42,  1.90s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1836/4895 [30:55<1:25:39,  1.68s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1837/4895 [30:56<1:08:56,  1.35s/it]


💽 TQM COPY FLOW:  38%|███████████████▍                         | 1838/4895 [30:56<53:54,  1.06s/it]


💽 TQM COPY FLOW:  38%|███████████████▍                         | 1839/4895 [30:57<58:26,  1.15s/it]


💽 TQM COPY FLOW:  38%|███████████████▍                         | 1840/4895 [30:59<58:43,  1.15s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1841/4895 [31:03<1:47:31,  2.11s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1842/4895 [31:03<1:22:38,  1.62s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1843/4895 [31:04<1:06:56,  1.32s/it]


💽 TQM COPY FLOW:  38%|███████████████▍                         | 1844/4895 [31:05<54:40,  1.08s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1845/4895 [31:09<1:41:33,  2.00s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1846/4895 [31:10<1:25:19,  1.68s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1847/4895 [31:14<2:12:11,  2.60s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1848/4895 [31:15<1:35:30,  1.88s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1849/4895 [31:16<1:33:04,  1.83s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1850/4895 [31:32<4:59:49,  5.91s/it]


💽 TQM COPY FLOW:  38%|██████████████▋                        | 1851/4895 [31:32<3:35:18,  4.24s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1852/4895 [31:32<2:36:01,  3.08s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [37:34<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:03<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1853/4895 [31:36<2:40:41,  3.17s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:10<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_58/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [37:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:07<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1854/4895 [31:39<2:47:53,  3.31s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:13<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_58 (41 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [37:39<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:09<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1854/4895 [31:41<2:47:53,  3.31s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:15<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_59/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  38%|██████████████▊                        | 1855/4895 [31:45<3:26:26,  4.07s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1856/4895 [31:46<2:34:13,  3.05s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [37:44<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:14<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1857/4895 [31:47<1:57:02,  2.31s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [37:44<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:14<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1857/4895 [31:47<1:57:02,  2.31s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:20<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_59 (4 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_60/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [37:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:18<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1858/4895 [31:51<2:26:53,  2.90s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [37:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:18<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1858/4895 [31:51<2:26:53,  2.90s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:25<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_60 (2 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_61/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  38%|██████████████▊                        | 1859/4895 [31:53<2:21:13,  2.79s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1860/4895 [31:55<2:05:31,  2.48s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1861/4895 [32:00<2:47:50,  3.32s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1862/4895 [32:02<2:25:35,  2.88s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1863/4895 [32:03<1:46:12,  2.10s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1864/4895 [32:06<2:07:32,  2.52s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [38:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:42<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1865/4895 [32:15<3:40:40,  4.37s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [38:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:42<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1865/4895 [32:15<3:40:40,  4.37s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:48<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_61 (8 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_62/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  38%|██████████████▊                        | 1866/4895 [32:15<2:44:58,  3.27s/it]


💽 TQM COPY FLOW:  38%|██████████████▊                        | 1867/4895 [32:16<1:58:54,  2.36s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1868/4895 [32:16<1:30:37,  1.80s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1869/4895 [32:20<2:07:36,  2.53s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [38:22<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:51<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1870/4895 [32:24<2:17:49,  2.73s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [38:22<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:51<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1870/4895 [32:24<2:17:49,  2.73s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:57<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_62 (6 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_63/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  38%|██████████████▉                        | 1871/4895 [32:24<1:42:51,  2.04s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [38:23<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:52<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1872/4895 [32:25<1:24:42,  1.68s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [38:23<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:52<?, ?it/s]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1872/4895 [32:25<1:24:42,  1.68s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [32:59<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_63 (3 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_64/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  38%|██████████████▉                        | 1873/4895 [32:27<1:29:30,  1.78s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1874/4895 [32:32<2:26:22,  2.91s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1875/4895 [32:33<1:51:26,  2.21s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1876/4895 [32:34<1:25:47,  1.71s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1877/4895 [32:35<1:16:35,  1.52s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1878/4895 [32:43<3:04:59,  3.68s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1879/4895 [32:46<2:53:20,  3.45s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1880/4895 [32:49<2:42:59,  3.24s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1881/4895 [32:53<2:49:31,  3.37s/it]


💽 TQM COPY FLOW:  38%|██████████████▉                        | 1882/4895 [32:55<2:39:23,  3.17s/it]


💽 TQM COPY FLOW:  38%|███████████████                        | 1883/4895 [33:00<2:56:35,  3.52s/it]


💽 TQM COPY FLOW:  38%|███████████████                        | 1884/4895 [33:02<2:35:45,  3.10s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1885/4895 [33:05<2:32:23,  3.04s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1886/4895 [33:08<2:33:04,  3.05s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1887/4895 [33:13<3:10:53,  3.81s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1888/4895 [33:17<3:05:25,  3.70s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1889/4895 [33:17<2:14:17,  2.68s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1890/4895 [33:18<1:46:19,  2.12s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1891/4895 [33:22<2:17:20,  2.74s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1892/4895 [33:24<2:09:17,  2.58s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1893/4895 [33:25<1:39:39,  1.99s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1894/4895 [33:25<1:13:26,  1.47s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1895/4895 [33:26<1:08:00,  1.36s/it]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1896/4895 [33:27<57:45,  1.16s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1897/4895 [33:32<1:51:32,  2.23s/it]


💽 TQM COPY FLOW:  39%|███████████████                        | 1898/4895 [33:32<1:27:11,  1.75s/it]


💽 TQM COPY FLOW:  39%|███████████████▏                       | 1899/4895 [33:33<1:06:09,  1.33s/it]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1900/4895 [33:33<50:36,  1.01s/it]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1901/4895 [33:34<42:56,  1.16it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1902/4895 [33:34<35:47,  1.39it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1903/4895 [33:34<29:58,  1.66it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1904/4895 [33:35<26:04,  1.91it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1905/4895 [33:35<24:42,  2.02it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1906/4895 [33:35<24:24,  2.04it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1907/4895 [33:36<22:49,  2.18it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1908/4895 [33:36<22:11,  2.24it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1909/4895 [33:37<23:35,  2.11it/s]


💽 TQM COPY FLOW:  39%|███████████████▉                         | 1910/4895 [33:38<29:09,  1.71it/s]


💽 TQM COPY FLOW:  39%|████████████████                         | 1911/4895 [33:38<24:41,  2.01it/s]


💽 TQM COPY FLOW:  39%|████████████████                         | 1912/4895 [33:39<29:41,  1.67it/s]


💽 TQM COPY FLOW:  39%|███████████████▏                       | 1913/4895 [33:42<1:09:37,  1.40s/it]


💽 TQM COPY FLOW:  39%|████████████████                         | 1914/4895 [33:43<55:25,  1.12s/it]


💽 TQM COPY FLOW:  39%|████████████████                         | 1915/4895 [33:43<51:51,  1.04s/it]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1916/4895 [33:45<1:01:52,  1.25s/it]


💽 TQM COPY FLOW:  39%|████████████████                         | 1917/4895 [33:46<56:51,  1.15s/it]


💽 TQM COPY FLOW:  39%|████████████████                         | 1918/4895 [33:47<53:54,  1.09s/it]


💽 TQM COPY FLOW:  39%|████████████████                         | 1919/4895 [33:48<50:07,  1.01s/it]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1920/4895 [33:52<1:40:04,  2.02s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [39:55<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [34:24<?, ?it/s]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1921/4895 [33:57<2:22:45,  2.88s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [34:31<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_64 (50 files)

💽 TQM COPY FLOW:  39%|███████████████▎                       | 1922/4895 [33:59<2:04:40,  2.52s/it]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1923/4895 [33:59<1:36:56,  1.96s/it]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1924/4895 [34:00<1:18:03,  1.58s/it]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1925/4895 [34:01<1:06:23,  1.34s/it]


💽 TQM COPY FLOW:  39%|████████████████▏                        | 1926/4895 [34:02<57:25,  1.16s/it]


💽 TQM COPY FLOW:  39%|████████████████▏                        | 1927/4895 [34:02<46:53,  1.06it/s]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1928/4895 [34:06<1:29:38,  1.81s/it]


💽 TQM COPY FLOW:  39%|███████████████▎                       | 1929/4895 [34:07<1:13:19,  1.48s/it]


💽 TQM COPY FLOW:  39%|███████████████▍                       | 1930/4895 [34:07<1:03:33,  1.29s/it]


💽 TQM COPY FLOW:  39%|████████████████▏                        | 1931/4895 [34:08<54:29,  1.10s/it]


💽 TQM COPY FLOW:  39%|███████████████▍                       | 1932/4895 [34:13<1:49:44,  2.22s/it]


💽 TQM COPY FLOW:  39%|███████████████▍                       | 1933/4895 [34:13<1:24:23,  1.71s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1934/4895 [34:14<1:10:59,  1.44s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1935/4895 [34:15<1:01:04,  1.24s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1936/4895 [34:17<1:10:54,  1.44s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1937/4895 [34:21<1:50:06,  2.23s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1938/4895 [34:31<3:48:17,  4.63s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1939/4895 [34:32<2:55:00,  3.55s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [40:31<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:00<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1940/4895 [34:33<2:09:33,  2.63s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:06<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_65/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  40%|███████████████▍                       | 1941/4895 [34:34<1:42:23,  2.08s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1942/4895 [34:35<1:26:32,  1.76s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1943/4895 [34:35<1:09:12,  1.41s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1944/4895 [34:40<2:03:49,  2.52s/it]


💽 TQM COPY FLOW:  40%|███████████████▍                       | 1945/4895 [34:41<1:32:59,  1.89s/it]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1946/4895 [34:41<1:10:54,  1.44s/it]


💽 TQM COPY FLOW:  40%|████████████████▎                        | 1947/4895 [34:42<58:51,  1.20s/it]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1948/4895 [34:45<1:24:03,  1.71s/it]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1949/4895 [34:45<1:03:53,  1.30s/it]


💽 TQM COPY FLOW:  40%|████████████████▎                        | 1950/4895 [34:45<52:19,  1.07s/it]


💽 TQM COPY FLOW:  40%|████████████████▎                        | 1951/4895 [34:46<42:29,  1.15it/s]


💽 TQM COPY FLOW:  40%|████████████████▎                        | 1952/4895 [34:46<35:33,  1.38it/s]


💽 TQM COPY FLOW:  40%|████████████████▎                        | 1953/4895 [34:47<30:32,  1.61it/s]


💽 TQM COPY FLOW:  40%|████████████████▎                        | 1954/4895 [34:47<28:59,  1.69it/s]


💽 TQM COPY FLOW:  40%|████████████████▎                        | 1955/4895 [34:49<51:19,  1.05s/it]


💽 TQM COPY FLOW:  40%|████████████████▍                        | 1956/4895 [34:50<39:53,  1.23it/s]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1957/4895 [34:54<1:37:57,  2.00s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [40:53<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:22<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1958/4895 [34:55<1:15:32,  1.54s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:29<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_65 (38 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [40:53<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:23<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1958/4895 [34:55<1:15:32,  1.54s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:29<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_66/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  40%|███████████████▌                       | 1959/4895 [35:02<2:35:08,  3.17s/it]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1960/4895 [35:03<2:06:36,  2.59s/it]


💽 TQM COPY FLOW:  40%|███████████████▌                       | 1961/4895 [35:04<1:39:10,  2.03s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1962/4895 [35:05<1:21:55,  1.68s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1963/4895 [35:09<2:02:05,  2.50s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1964/4895 [35:09<1:31:45,  1.88s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1965/4895 [35:14<2:03:54,  2.54s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:14<1:40:23,  2.06s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:14<1:40:23,  2.06s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:14<1:40:23,  2.06s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:14<1:40:23,  2.06s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:14<1:40:23,  2.06s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:14<1:40:23,  2.06s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:14<1:40:23,  2.06s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [41:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:42<?, ?it/s]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1966/4895 [35:15<1:40:23,  2.06s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [35:48<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_66 (9 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_67/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_67 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_68/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_68 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_69/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_69 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_70/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  40%|███████████████▋                       | 1967/4895 [35:16<1:27:43,  1.80s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1968/4895 [35:21<2:26:30,  3.00s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1969/4895 [35:23<2:01:19,  2.49s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1970/4895 [35:24<1:38:30,  2.02s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1971/4895 [35:29<2:26:59,  3.02s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1972/4895 [35:33<2:37:18,  3.23s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1973/4895 [35:34<2:14:33,  2.76s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1974/4895 [35:37<2:05:12,  2.57s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1975/4895 [35:40<2:11:05,  2.69s/it]


💽 TQM COPY FLOW:  40%|███████████████▋                       | 1976/4895 [35:41<1:59:18,  2.45s/it]


💽 TQM COPY FLOW:  40%|███████████████▊                       | 1977/4895 [35:42<1:32:33,  1.90s/it]


💽 TQM COPY FLOW:  40%|███████████████▊                       | 1978/4895 [35:43<1:12:14,  1.49s/it]


💽 TQM COPY FLOW:  40%|████████████████▌                        | 1979/4895 [35:43<57:52,  1.19s/it]


💽 TQM COPY FLOW:  40%|███████████████▊                       | 1980/4895 [35:47<1:40:08,  2.06s/it]


💽 TQM COPY FLOW:  40%|███████████████▊                       | 1981/4895 [35:50<1:50:54,  2.28s/it]


💽 TQM COPY FLOW:  40%|███████████████▊                       | 1982/4895 [35:55<2:34:16,  3.18s/it]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1983/4895 [35:56<1:57:15,  2.42s/it]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1984/4895 [35:57<1:32:34,  1.91s/it]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1985/4895 [35:58<1:27:46,  1.81s/it]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1986/4895 [36:01<1:43:46,  2.14s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [42:00<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [36:29<?, ?it/s]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1987/4895 [36:02<1:24:52,  1.75s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [36:36<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_70 (22 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [42:04<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [36:34<?, ?it/s]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1987/4895 [36:07<1:24:52,  1.75s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [36:40<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_71/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  41%|███████████████▊                       | 1988/4895 [36:09<2:48:05,  3.47s/it]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1989/4895 [36:11<2:23:55,  2.97s/it]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1990/4895 [36:12<1:45:23,  2.18s/it]


💽 TQM COPY FLOW:  41%|███████████████▊                       | 1991/4895 [36:12<1:17:09,  1.59s/it]


💽 TQM COPY FLOW:  41%|████████████████▋                        | 1992/4895 [36:12<59:03,  1.22s/it]


💽 TQM COPY FLOW:  41%|████████████████▋                        | 1993/4895 [36:13<52:57,  1.09s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 1994/4895 [36:15<1:01:55,  1.28s/it]


💽 TQM COPY FLOW:  41%|████████████████▋                        | 1995/4895 [36:15<49:13,  1.02s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 1996/4895 [36:19<1:28:59,  1.84s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 1997/4895 [36:19<1:08:04,  1.41s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 1998/4895 [36:21<1:13:07,  1.51s/it]


💽 TQM COPY FLOW:  41%|████████████████▋                        | 1999/4895 [36:21<57:12,  1.19s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2000/4895 [36:29<2:28:59,  3.09s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2001/4895 [36:37<3:40:25,  4.57s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2002/4895 [36:45<4:28:31,  5.57s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2003/4895 [36:54<5:22:17,  6.69s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2004/4895 [36:59<5:00:33,  6.24s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2005/4895 [37:11<6:18:29,  7.86s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2006/4895 [37:11<4:30:11,  5.61s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2007/4895 [37:12<3:15:08,  4.05s/it]


💽 TQM COPY FLOW:  41%|███████████████▉                       | 2008/4895 [37:12<2:20:29,  2.92s/it]


💽 TQM COPY FLOW:  41%|████████████████                       | 2009/4895 [37:13<1:46:03,  2.20s/it]


💽 TQM COPY FLOW:  41%|████████████████                       | 2010/4895 [37:14<1:36:52,  2.01s/it]


💽 TQM COPY FLOW:  41%|████████████████                       | 2011/4895 [37:15<1:24:21,  1.76s/it]


💽 TQM COPY FLOW:  41%|████████████████                       | 2012/4895 [37:17<1:19:57,  1.66s/it]


💽 TQM COPY FLOW:  41%|████████████████                       | 2013/4895 [37:18<1:11:01,  1.48s/it]


💽 TQM COPY FLOW:  41%|████████████████                       | 2014/4895 [37:19<1:00:56,  1.27s/it]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2015/4895 [37:19<53:40,  1.12s/it]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2016/4895 [37:20<43:58,  1.09it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2017/4895 [37:21<42:50,  1.12it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2018/4895 [37:21<39:52,  1.20it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2019/4895 [37:23<47:30,  1.01it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:22<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [37:51<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2020/4895 [37:24<49:12,  1.03s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [37:57<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_71 (34 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:25<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [37:55<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2020/4895 [37:27<49:12,  1.03s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:25<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [37:55<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2020/4895 [37:27<49:12,  1.03s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:01<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_72/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_72 (1 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:31<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:00<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2020/4895 [37:33<49:12,  1.03s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:31<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:00<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2020/4895 [37:33<49:12,  1.03s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:06<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_73/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_73 (1 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:31<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:01<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2020/4895 [37:33<49:12,  1.03s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:07<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_74/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  41%|████████████████                       | 2021/4895 [37:40<4:32:04,  5.68s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:39<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:08<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████                       | 2022/4895 [37:41<3:16:02,  4.09s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [43:39<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:08<?, ?it/s]


💽 TQM COPY FLOW:  41%|████████████████                       | 2022/4895 [37:41<3:16:02,  4.09s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [38:14<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_74 (3 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_75/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  41%|████████████████                       | 2023/4895 [37:41<2:21:16,  2.95s/it]


💽 TQM COPY FLOW:  41%|████████████████▏                      | 2024/4895 [37:42<1:52:21,  2.35s/it]


💽 TQM COPY FLOW:  41%|████████████████▏                      | 2025/4895 [37:45<2:06:22,  2.64s/it]


💽 TQM COPY FLOW:  41%|████████████████▏                      | 2026/4895 [37:46<1:33:22,  1.95s/it]


💽 TQM COPY FLOW:  41%|████████████████▏                      | 2027/4895 [37:46<1:13:55,  1.55s/it]


💽 TQM COPY FLOW:  41%|████████████████▉                        | 2028/4895 [37:47<58:34,  1.23s/it]


💽 TQM COPY FLOW:  41%|████████████████▏                      | 2029/4895 [37:51<1:37:34,  2.04s/it]


💽 TQM COPY FLOW:  41%|████████████████▏                      | 2030/4895 [37:56<2:28:27,  3.11s/it]


💽 TQM COPY FLOW:  41%|████████████████▏                      | 2031/4895 [37:57<1:52:46,  2.36s/it]


💽 TQM COPY FLOW:  42%|████████████████▏                      | 2032/4895 [37:57<1:28:06,  1.85s/it]


💽 TQM COPY FLOW:  42%|████████████████▏                      | 2033/4895 [37:59<1:20:40,  1.69s/it]


💽 TQM COPY FLOW:  42%|████████████████▏                      | 2034/4895 [37:59<1:03:38,  1.33s/it]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2035/4895 [38:00<56:32,  1.19s/it]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2036/4895 [38:01<52:12,  1.10s/it]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2037/4895 [38:02<44:27,  1.07it/s]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2038/4895 [38:02<37:43,  1.26it/s]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2039/4895 [38:02<32:48,  1.45it/s]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2040/4895 [38:03<30:58,  1.54it/s]


💽 TQM COPY FLOW:  42%|████████████████▎                      | 2041/4895 [38:07<1:24:18,  1.77s/it]


💽 TQM COPY FLOW:  42%|████████████████▎                      | 2042/4895 [38:08<1:03:38,  1.34s/it]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2043/4895 [38:08<50:02,  1.05s/it]


💽 TQM COPY FLOW:  42%|█████████████████                        | 2044/4895 [38:09<47:57,  1.01s/it]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2045/4895 [38:10<40:57,  1.16it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2046/4895 [38:10<33:10,  1.43it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2047/4895 [38:10<25:53,  1.83it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2048/4895 [38:11<24:26,  1.94it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2049/4895 [38:11<23:58,  1.98it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2050/4895 [38:11<20:47,  2.28it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2051/4895 [38:12<21:55,  2.16it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2052/4895 [38:12<22:03,  2.15it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2053/4895 [38:15<59:02,  1.25s/it]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2054/4895 [38:16<49:38,  1.05s/it]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2055/4895 [38:17<43:37,  1.08it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2056/4895 [38:17<42:47,  1.11it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2057/4895 [38:18<40:26,  1.17it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2058/4895 [38:18<31:22,  1.51it/s]


💽 TQM COPY FLOW:  42%|█████████████████▏                       | 2059/4895 [38:19<33:38,  1.40it/s]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2060/4895 [38:20<29:28,  1.60it/s]


💽 TQM COPY FLOW:  42%|████████████████▍                      | 2061/4895 [38:28<2:22:21,  3.01s/it]


💽 TQM COPY FLOW:  42%|████████████████▍                      | 2062/4895 [38:29<1:53:39,  2.41s/it]


💽 TQM COPY FLOW:  42%|████████████████▍                      | 2063/4895 [38:31<1:42:11,  2.16s/it]


💽 TQM COPY FLOW:  42%|████████████████▍                      | 2064/4895 [38:32<1:23:14,  1.76s/it]


💽 TQM COPY FLOW:  42%|████████████████▍                      | 2065/4895 [38:32<1:05:34,  1.39s/it]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2066/4895 [38:33<57:34,  1.22s/it]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2067/4895 [38:33<45:45,  1.03it/s]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2068/4895 [38:34<42:08,  1.12it/s]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2069/4895 [38:35<36:12,  1.30it/s]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2070/4895 [38:35<34:42,  1.36it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [44:34<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [39:03<?, ?it/s]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2071/4895 [38:36<35:40,  1.32it/s]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [39:10<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_75 (50 files)

💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2072/4895 [38:37<45:19,  1.04it/s]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2073/4895 [38:38<35:43,  1.32it/s]


💽 TQM COPY FLOW:  42%|█████████████████▎                       | 2074/4895 [38:38<32:00,  1.47it/s]


💽 TQM COPY FLOW:  42%|█████████████████▍                       | 2075/4895 [38:39<29:29,  1.59it/s]


💽 TQM COPY FLOW:  42%|█████████████████▍                       | 2076/4895 [38:39<31:02,  1.51it/s]


💽 TQM COPY FLOW:  42%|█████████████████▍                       | 2077/4895 [38:40<29:28,  1.59it/s]


💽 TQM COPY FLOW:  42%|█████████████████▍                       | 2078/4895 [38:41<34:24,  1.36it/s]


💽 TQM COPY FLOW:  42%|█████████████████▍                       | 2079/4895 [38:42<33:49,  1.39it/s]


💽 TQM COPY FLOW:  42%|█████████████████▍                       | 2080/4895 [38:42<32:01,  1.46it/s]


💽 TQM COPY FLOW:  43%|█████████████████▍                       | 2081/4895 [38:43<32:58,  1.42it/s]


💽 TQM COPY FLOW:  43%|█████████████████▍                       | 2082/4895 [38:45<46:41,  1.00it/s]


💽 TQM COPY FLOW:  43%|█████████████████▍                       | 2083/4895 [38:46<57:34,  1.23s/it]


💽 TQM COPY FLOW:  43%|████████████████▌                      | 2084/4895 [38:48<1:05:21,  1.40s/it]


💽 TQM COPY FLOW:  43%|████████████████▌                      | 2085/4895 [38:50<1:03:22,  1.35s/it]


💽 TQM COPY FLOW:  43%|█████████████████▍                       | 2086/4895 [38:50<57:05,  1.22s/it]


💽 TQM COPY FLOW:  43%|█████████████████▍                       | 2087/4895 [38:51<47:23,  1.01s/it]


💽 TQM COPY FLOW:  43%|█████████████████▍                       | 2088/4895 [38:52<43:24,  1.08it/s]


💽 TQM COPY FLOW:  43%|█████████████████▍                       | 2089/4895 [38:52<36:55,  1.27it/s]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2090/4895 [38:56<1:19:32,  1.70s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2091/4895 [38:57<1:05:20,  1.40s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2092/4895 [38:59<1:17:23,  1.66s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2093/4895 [39:00<1:04:12,  1.37s/it]


💽 TQM COPY FLOW:  43%|█████████████████▌                       | 2094/4895 [39:00<49:24,  1.06s/it]


💽 TQM COPY FLOW:  43%|█████████████████▌                       | 2095/4895 [39:01<49:42,  1.07s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2096/4895 [39:04<1:20:52,  1.73s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2097/4895 [39:05<1:01:18,  1.31s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2098/4895 [39:09<1:41:46,  2.18s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2099/4895 [39:12<1:59:29,  2.56s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2100/4895 [39:20<3:03:52,  3.95s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2101/4895 [39:20<2:15:40,  2.91s/it]


💽 TQM COPY FLOW:  43%|████████████████▋                      | 2102/4895 [39:21<1:45:39,  2.27s/it]


💽 TQM COPY FLOW:  43%|████████████████▊                      | 2103/4895 [39:22<1:24:36,  1.82s/it]


💽 TQM COPY FLOW:  43%|████████████████▊                      | 2104/4895 [39:22<1:03:55,  1.37s/it]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2105/4895 [39:22<48:58,  1.05s/it]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2106/4895 [39:23<41:54,  1.11it/s]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2107/4895 [39:23<37:22,  1.24it/s]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2108/4895 [39:24<35:14,  1.32it/s]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2109/4895 [39:25<35:03,  1.32it/s]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2110/4895 [39:26<43:17,  1.07it/s]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2111/4895 [39:27<38:18,  1.21it/s]


💽 TQM COPY FLOW:  43%|████████████████▊                      | 2112/4895 [39:30<1:12:17,  1.56s/it]


💽 TQM COPY FLOW:  43%|████████████████▊                      | 2113/4895 [39:31<1:06:05,  1.43s/it]


💽 TQM COPY FLOW:  43%|████████████████▊                      | 2114/4895 [39:34<1:27:53,  1.90s/it]


💽 TQM COPY FLOW:  43%|████████████████▊                      | 2115/4895 [39:34<1:07:08,  1.45s/it]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2116/4895 [39:35<49:42,  1.07s/it]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2117/4895 [39:35<39:15,  1.18it/s]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2118/4895 [39:35<33:32,  1.38it/s]


💽 TQM COPY FLOW:  43%|█████████████████▋                       | 2119/4895 [39:36<29:51,  1.55it/s]


💽 TQM COPY FLOW:  43%|█████████████████▊                       | 2120/4895 [39:36<25:59,  1.78it/s]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [45:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [40:07<?, ?it/s]


💽 TQM COPY FLOW:  43%|█████████████████▊                       | 2121/4895 [39:39<57:39,  1.25s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [40:13<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_76 (50 files)

💽 TQM COPY FLOW:  43%|████████████████▉                      | 2122/4895 [39:43<1:33:26,  2.02s/it]


💽 TQM COPY FLOW:  43%|████████████████▉                      | 2123/4895 [39:43<1:11:11,  1.54s/it]


💽 TQM COPY FLOW:  43%|█████████████████▊                       | 2124/4895 [39:44<58:02,  1.26s/it]


💽 TQM COPY FLOW:  43%|█████████████████▊                       | 2125/4895 [39:44<47:19,  1.02s/it]


💽 TQM COPY FLOW:  43%|████████████████▉                      | 2126/4895 [39:46<1:00:25,  1.31s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [45:53<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [40:22<?, ?it/s]


💽 TQM COPY FLOW:  43%|████████████████▉                      | 2127/4895 [39:55<2:36:34,  3.39s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [40:28<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_77/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  43%|████████████████▉                      | 2128/4895 [39:58<2:29:18,  3.24s/it]


💽 TQM COPY FLOW:  43%|████████████████▉                      | 2129/4895 [39:58<1:51:01,  2.41s/it]


💽 TQM COPY FLOW:  44%|████████████████▉                      | 2130/4895 [39:58<1:24:34,  1.84s/it]


💽 TQM COPY FLOW:  44%|████████████████▉                      | 2131/4895 [40:00<1:14:16,  1.61s/it]


💽 TQM COPY FLOW:  44%|████████████████▉                      | 2132/4895 [40:04<1:54:34,  2.49s/it]


💽 TQM COPY FLOW:  44%|████████████████▉                      | 2133/4895 [40:05<1:28:43,  1.93s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2134/4895 [40:18<4:08:18,  5.40s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2135/4895 [40:22<3:45:10,  4.89s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2136/4895 [40:27<3:40:49,  4.80s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2137/4895 [40:28<2:54:32,  3.80s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2138/4895 [40:31<2:42:02,  3.53s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2139/4895 [40:33<2:20:48,  3.07s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2140/4895 [40:33<1:45:49,  2.30s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2141/4895 [40:34<1:19:24,  1.73s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2142/4895 [40:39<2:07:49,  2.79s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2143/4895 [40:41<1:59:39,  2.61s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2144/4895 [40:44<2:03:50,  2.70s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2145/4895 [40:53<3:26:01,  4.50s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2146/4895 [40:59<3:51:45,  5.06s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2147/4895 [41:00<2:51:19,  3.74s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2148/4895 [41:05<3:04:59,  4.04s/it]


💽 TQM COPY FLOW:  44%|█████████████████                      | 2149/4895 [41:05<2:15:30,  2.96s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2150/4895 [41:08<2:14:09,  2.93s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2151/4895 [41:09<1:54:12,  2.50s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2152/4895 [41:11<1:36:22,  2.11s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2153/4895 [41:11<1:11:38,  1.57s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2154/4895 [41:13<1:23:05,  1.82s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2155/4895 [41:16<1:30:14,  1.98s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2156/4895 [41:20<2:00:44,  2.65s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2157/4895 [41:23<2:05:28,  2.75s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2158/4895 [41:23<1:32:55,  2.04s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2159/4895 [41:24<1:12:03,  1.58s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2160/4895 [41:25<1:03:52,  1.40s/it]


💽 TQM COPY FLOW:  44%|██████████████████                       | 2161/4895 [41:25<51:37,  1.13s/it]


💽 TQM COPY FLOW:  44%|██████████████████                       | 2162/4895 [41:26<42:45,  1.07it/s]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2163/4895 [41:28<1:03:04,  1.39s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2164/4895 [41:32<1:37:23,  2.14s/it]


💽 TQM COPY FLOW:  44%|█████████████████▏                     | 2165/4895 [41:35<1:45:59,  2.33s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2166/4895 [41:38<2:03:31,  2.72s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2167/4895 [41:39<1:29:18,  1.96s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2168/4895 [41:39<1:06:53,  1.47s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2169/4895 [41:42<1:24:41,  1.86s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [47:46<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [42:16<?, ?it/s]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2170/4895 [41:48<2:28:25,  3.27s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [42:22<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_77 (50 files)

💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2171/4895 [41:53<2:41:50,  3.56s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2172/4895 [41:56<2:37:11,  3.46s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2173/4895 [41:56<1:53:39,  2.51s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2174/4895 [42:00<2:14:05,  2.96s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2175/4895 [42:01<1:49:06,  2.41s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2176/4895 [42:02<1:27:55,  1.94s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2177/4895 [42:08<2:23:40,  3.17s/it]


💽 TQM COPY FLOW:  44%|█████████████████▎                     | 2178/4895 [42:08<1:46:21,  2.35s/it]


💽 TQM COPY FLOW:  45%|█████████████████▎                     | 2179/4895 [42:09<1:18:07,  1.73s/it]


💽 TQM COPY FLOW:  45%|█████████████████▎                     | 2180/4895 [42:14<2:10:17,  2.88s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2181/4895 [42:15<1:35:22,  2.11s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2182/4895 [42:17<1:43:04,  2.28s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2183/4895 [42:18<1:18:29,  1.74s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2184/4895 [42:22<1:58:15,  2.62s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2185/4895 [42:23<1:33:36,  2.07s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2186/4895 [42:24<1:15:37,  1.68s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2187/4895 [42:29<1:58:52,  2.63s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2188/4895 [42:32<2:06:29,  2.80s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2189/4895 [42:37<2:29:44,  3.32s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2190/4895 [42:38<2:06:02,  2.80s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:06<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:06<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:13<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_78/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_78 (22 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:07<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:07<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:07<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:07<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:07<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:07<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]






💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [48:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:07<?, ?it/s]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2191/4895 [42:39<1:37:35,  2.17s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [43:13<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_79/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_79 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_80/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_80 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_81/ | [Errno 2] No such file or directory: ''
📦 Finished chunk: _24_ARCH_rk_81 (1 files)
❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_82/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2192/4895 [42:45<2:31:25,  3.36s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2193/4895 [42:45<1:50:23,  2.45s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2194/4895 [42:48<1:58:32,  2.63s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2195/4895 [42:49<1:27:28,  1.94s/it]


💽 TQM COPY FLOW:  45%|█████████████████▍                     | 2196/4895 [42:50<1:14:14,  1.65s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2197/4895 [42:57<2:31:41,  3.37s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2198/4895 [43:07<3:55:32,  5.24s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2199/4895 [43:08<2:57:24,  3.95s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2200/4895 [43:09<2:17:26,  3.06s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2201/4895 [43:13<2:32:37,  3.40s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2202/4895 [43:16<2:32:42,  3.40s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2203/4895 [43:17<1:53:52,  2.54s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2204/4895 [43:22<2:23:38,  3.20s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2205/4895 [43:27<2:53:49,  3.88s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2206/4895 [43:31<2:50:35,  3.81s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2207/4895 [43:34<2:49:14,  3.78s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2208/4895 [43:38<2:45:50,  3.70s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2209/4895 [43:41<2:44:55,  3.68s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2210/4895 [43:46<2:54:05,  3.89s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2211/4895 [43:58<4:47:29,  6.43s/it]


💽 TQM COPY FLOW:  45%|█████████████████▌                     | 2212/4895 [44:01<3:58:21,  5.33s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2213/4895 [44:05<3:34:15,  4.79s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2214/4895 [44:05<2:38:17,  3.54s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2215/4895 [44:08<2:28:23,  3.32s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2216/4895 [44:10<2:12:24,  2.97s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2217/4895 [44:11<1:50:30,  2.48s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2218/4895 [44:12<1:23:35,  1.87s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2219/4895 [44:14<1:31:55,  2.06s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2220/4895 [44:15<1:09:24,  1.56s/it]


💽 TQM COPY FLOW:  45%|██████████████████▌                      | 2221/4895 [44:16<59:54,  1.34s/it]


💽 TQM COPY FLOW:  45%|██████████████████▌                      | 2222/4895 [44:16<49:04,  1.10s/it]


💽 TQM COPY FLOW:  45%|██████████████████▌                      | 2223/4895 [44:17<44:02,  1.01it/s]


💽 TQM COPY FLOW:  45%|██████████████████▋                      | 2224/4895 [44:17<38:19,  1.16it/s]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2225/4895 [44:24<1:50:14,  2.48s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2226/4895 [44:27<1:56:39,  2.62s/it]


💽 TQM COPY FLOW:  45%|█████████████████▋                     | 2227/4895 [44:27<1:24:58,  1.91s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2228/4895 [44:27<1:04:31,  1.45s/it]


💽 TQM COPY FLOW:  46%|██████████████████▋                      | 2229/4895 [44:28<55:19,  1.25s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2230/4895 [44:30<1:09:48,  1.57s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2231/4895 [44:36<2:03:57,  2.79s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2232/4895 [44:38<1:59:53,  2.70s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2233/4895 [44:39<1:30:32,  2.04s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2234/4895 [44:39<1:07:33,  1.52s/it]


💽 TQM COPY FLOW:  46%|██████████████████▋                      | 2235/4895 [44:40<53:08,  1.20s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2236/4895 [44:43<1:26:00,  1.94s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2237/4895 [44:50<2:24:40,  3.27s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2238/4895 [44:50<1:46:24,  2.40s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [50:50<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [45:20<?, ?it/s]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2239/4895 [44:52<1:42:09,  2.31s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [45:26<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_82 (49 files)

💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2240/4895 [44:55<1:51:00,  2.51s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2241/4895 [44:56<1:26:56,  1.97s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2242/4895 [44:59<1:44:24,  2.36s/it]


💽 TQM COPY FLOW:  46%|█████████████████▊                     | 2243/4895 [45:00<1:25:49,  1.94s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2244/4895 [45:05<2:05:50,  2.85s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2245/4895 [45:06<1:37:09,  2.20s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2246/4895 [45:09<1:51:50,  2.53s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2247/4895 [45:13<2:11:32,  2.98s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2248/4895 [45:14<1:38:14,  2.23s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2249/4895 [45:14<1:17:49,  1.76s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2250/4895 [45:15<1:07:00,  1.52s/it]


💽 TQM COPY FLOW:  46%|██████████████████▊                      | 2251/4895 [45:16<52:04,  1.18s/it]


💽 TQM COPY FLOW:  46%|██████████████████▊                      | 2252/4895 [45:17<49:22,  1.12s/it]


💽 TQM COPY FLOW:  46%|██████████████████▊                      | 2253/4895 [45:18<46:25,  1.05s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2254/4895 [45:21<1:16:02,  1.73s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2255/4895 [45:26<2:07:32,  2.90s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2256/4895 [45:31<2:25:56,  3.32s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2257/4895 [45:42<4:05:31,  5.58s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2258/4895 [45:47<3:57:09,  5.40s/it]


💽 TQM COPY FLOW:  46%|█████████████████▉                     | 2259/4895 [45:47<2:50:52,  3.89s/it]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2260/4895 [45:48<2:09:48,  2.96s/it]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2261/4895 [45:48<1:36:47,  2.20s/it]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2262/4895 [45:49<1:12:41,  1.66s/it]


💽 TQM COPY FLOW:  46%|██████████████████▉                      | 2263/4895 [45:49<57:53,  1.32s/it]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2264/4895 [45:51<1:01:31,  1.40s/it]


💽 TQM COPY FLOW:  46%|██████████████████▉                      | 2265/4895 [45:51<49:56,  1.14s/it]


💽 TQM COPY FLOW:  46%|██████████████████▉                      | 2266/4895 [45:52<41:45,  1.05it/s]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2267/4895 [45:57<1:41:41,  2.32s/it]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2268/4895 [45:58<1:19:31,  1.82s/it]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2269/4895 [45:59<1:06:12,  1.51s/it]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2270/4895 [46:00<1:00:03,  1.37s/it]


💽 TQM COPY FLOW:  46%|███████████████████                      | 2271/4895 [46:01<58:51,  1.35s/it]


💽 TQM COPY FLOW:  46%|███████████████████                      | 2272/4895 [46:01<47:11,  1.08s/it]


💽 TQM COPY FLOW:  46%|███████████████████                      | 2273/4895 [46:02<41:04,  1.06it/s]


💽 TQM COPY FLOW:  46%|██████████████████                     | 2274/4895 [46:06<1:19:04,  1.81s/it]


💽 TQM COPY FLOW:  46%|██████████████████▏                    | 2275/4895 [46:07<1:09:27,  1.59s/it]


💽 TQM COPY FLOW:  46%|██████████████████▏                    | 2276/4895 [46:11<1:46:34,  2.44s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2277/4895 [46:12<1:18:57,  1.81s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2278/4895 [46:14<1:21:51,  1.88s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2279/4895 [46:15<1:07:15,  1.54s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2280/4895 [46:20<2:03:23,  2.83s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2281/4895 [46:22<1:46:36,  2.45s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2282/4895 [46:40<5:03:40,  6.97s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2283/4895 [46:44<4:29:06,  6.18s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2284/4895 [46:49<4:11:12,  5.77s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2285/4895 [46:49<3:00:46,  4.16s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2286/4895 [46:50<2:13:09,  3.06s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2287/4895 [46:52<2:00:42,  2.78s/it]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2288/4895 [46:55<2:11:34,  3.03s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [53:06<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [47:35<?, ?it/s]


💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2289/4895 [47:08<4:15:48,  5.89s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [47:42<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_83 (50 files)

💽 TQM COPY FLOW:  47%|██████████████████▏                    | 2290/4895 [47:09<3:20:14,  4.61s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2291/4895 [47:12<2:56:04,  4.06s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2292/4895 [47:13<2:11:50,  3.04s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2293/4895 [47:13<1:37:28,  2.25s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2294/4895 [47:18<2:11:08,  3.03s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2295/4895 [47:19<1:44:26,  2.41s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2296/4895 [47:20<1:29:06,  2.06s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2297/4895 [47:21<1:06:21,  1.53s/it]


💽 TQM COPY FLOW:  47%|███████████████████▏                     | 2298/4895 [47:21<53:14,  1.23s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2299/4895 [47:24<1:16:55,  1.78s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2300/4895 [47:25<1:09:12,  1.60s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2301/4895 [47:29<1:40:18,  2.32s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2302/4895 [47:32<1:39:26,  2.30s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [53:30<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [48:00<?, ?it/s]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2303/4895 [47:32<1:19:56,  1.85s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [48:06<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_84 (14 files)

💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2304/4895 [47:38<2:05:44,  2.91s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2305/4895 [47:39<1:46:55,  2.48s/it]


💽 TQM COPY FLOW:  47%|██████████████████▎                    | 2306/4895 [47:42<1:55:34,  2.68s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2307/4895 [47:52<3:25:27,  4.76s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2308/4895 [47:55<3:04:00,  4.27s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2309/4895 [47:56<2:16:22,  3.16s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2310/4895 [47:57<1:49:40,  2.55s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2311/4895 [47:58<1:28:46,  2.06s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2312/4895 [48:02<1:55:57,  2.69s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2313/4895 [48:04<1:42:49,  2.39s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2314/4895 [48:05<1:34:33,  2.20s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2315/4895 [48:10<2:07:04,  2.96s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2316/4895 [48:14<2:18:08,  3.21s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2317/4895 [48:15<1:50:12,  2.56s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2318/4895 [48:19<2:09:44,  3.02s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2319/4895 [48:20<1:41:11,  2.36s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2320/4895 [48:20<1:16:36,  1.79s/it]


💽 TQM COPY FLOW:  47%|██████████████████▍                    | 2321/4895 [48:21<1:04:03,  1.49s/it]


💽 TQM COPY FLOW:  47%|███████████████████▍                     | 2322/4895 [48:22<50:58,  1.19s/it]


💽 TQM COPY FLOW:  47%|██████████████████▌                    | 2323/4895 [48:25<1:21:55,  1.91s/it]


💽 TQM COPY FLOW:  47%|██████████████████▌                    | 2324/4895 [48:28<1:36:52,  2.26s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [54:32<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [49:01<?, ?it/s]


💽 TQM COPY FLOW:  47%|██████████████████▌                    | 2325/4895 [48:34<2:18:02,  3.22s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [49:08<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_85 (22 files)

💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2326/4895 [48:41<3:13:27,  4.52s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2327/4895 [48:42<2:18:21,  3.23s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2328/4895 [48:42<1:40:08,  2.34s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2329/4895 [48:54<3:44:06,  5.24s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2330/4895 [49:00<3:56:11,  5.52s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2331/4895 [49:01<2:57:29,  4.15s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2332/4895 [49:05<2:59:42,  4.21s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2333/4895 [49:12<3:28:55,  4.89s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2334/4895 [49:15<3:04:57,  4.33s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2335/4895 [49:22<3:43:45,  5.24s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2336/4895 [49:34<5:10:35,  7.28s/it]


💽 TQM COPY FLOW:  48%|██████████████████▌                    | 2337/4895 [49:36<4:01:00,  5.65s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2338/4895 [49:37<2:54:59,  4.11s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2339/4895 [49:37<2:07:27,  2.99s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2340/4895 [49:42<2:28:31,  3.49s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2341/4895 [49:42<1:48:50,  2.56s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2342/4895 [49:45<1:58:39,  2.79s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2343/4895 [49:46<1:29:09,  2.10s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2344/4895 [49:49<1:37:06,  2.28s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2345/4895 [49:49<1:14:04,  1.74s/it]


💽 TQM COPY FLOW:  48%|███████████████████▋                     | 2346/4895 [49:49<55:24,  1.30s/it]


💽 TQM COPY FLOW:  48%|███████████████████▋                     | 2347/4895 [49:50<41:36,  1.02it/s]


💽 TQM COPY FLOW:  48%|███████████████████▋                     | 2348/4895 [49:50<35:42,  1.19it/s]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2349/4895 [49:56<1:41:42,  2.40s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2350/4895 [50:00<2:00:12,  2.83s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2351/4895 [50:04<2:15:04,  3.19s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2352/4895 [50:09<2:38:09,  3.73s/it]


💽 TQM COPY FLOW:  48%|██████████████████▋                    | 2353/4895 [50:17<3:35:43,  5.09s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2354/4895 [50:18<2:36:06,  3.69s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2355/4895 [50:18<1:57:46,  2.78s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2356/4895 [50:19<1:29:20,  2.11s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2357/4895 [50:19<1:08:29,  1.62s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2358/4895 [50:25<2:03:45,  2.93s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2359/4895 [50:26<1:33:00,  2.20s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2360/4895 [50:26<1:07:43,  1.60s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2361/4895 [50:27<1:01:47,  1.46s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2362/4895 [50:30<1:19:58,  1.89s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2363/4895 [50:34<1:47:25,  2.55s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2364/4895 [50:34<1:16:48,  1.82s/it]


💽 TQM COPY FLOW:  48%|███████████████████▊                     | 2365/4895 [50:35<57:18,  1.36s/it]


💽 TQM COPY FLOW:  48%|███████████████████▊                     | 2366/4895 [50:35<41:48,  1.01it/s]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2367/4895 [50:42<2:05:33,  2.98s/it]


💽 TQM COPY FLOW:  48%|██████████████████▊                    | 2368/4895 [50:44<1:54:15,  2.71s/it]


💽 TQM COPY FLOW:  48%|██████████████████▉                    | 2370/4895 [50:45<1:09:16,  1.65s/it]


💽 TQM COPY FLOW:  48%|██████████████████▉                    | 2371/4895 [50:51<1:47:48,  2.56s/it]


💽 TQM COPY FLOW:  48%|██████████████████▉                    | 2372/4895 [50:55<2:05:49,  2.99s/it]


💽 TQM COPY FLOW:  48%|██████████████████▉                    | 2373/4895 [50:56<1:43:36,  2.46s/it]


💽 TQM COPY FLOW:  48%|██████████████████▉                    | 2374/4895 [50:57<1:29:12,  2.12s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [56:59<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [51:28<?, ?it/s]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2375/4895 [51:01<1:48:45,  2.59s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [51:34<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_86 (50 files)

💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2376/4895 [51:04<2:00:10,  2.86s/it]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2377/4895 [51:08<2:06:11,  3.01s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [57:11<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [51:41<?, ?it/s]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2378/4895 [51:13<2:39:14,  3.80s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [51:47<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_87/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2379/4895 [51:17<2:36:58,  3.74s/it]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2380/4895 [51:22<2:54:12,  4.16s/it]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2381/4895 [51:27<3:07:08,  4.47s/it]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2382/4895 [51:32<3:10:45,  4.55s/it]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2383/4895 [51:37<3:14:01,  4.63s/it]


💽 TQM COPY FLOW:  49%|██████████████████▉                    | 2384/4895 [51:40<2:54:09,  4.16s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2385/4895 [51:45<3:11:07,  4.57s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2386/4895 [51:47<2:30:02,  3.59s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2387/4895 [51:47<1:51:12,  2.66s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2388/4895 [51:48<1:28:32,  2.12s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2389/4895 [51:50<1:23:53,  2.01s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2390/4895 [51:54<1:57:01,  2.80s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2391/4895 [51:59<2:22:19,  3.41s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2392/4895 [52:03<2:30:31,  3.61s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2393/4895 [52:06<2:20:49,  3.38s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2395/4895 [52:06<1:18:06,  1.87s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2396/4895 [52:07<1:01:20,  1.47s/it]


💽 TQM COPY FLOW:  49%|████████████████████                     | 2398/4895 [52:07<36:45,  1.13it/s]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2399/4895 [52:14<1:34:32,  2.27s/it]


💽 TQM COPY FLOW:  49%|███████████████████                    | 2400/4895 [52:22<2:39:09,  3.83s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2401/4895 [52:29<3:05:17,  4.46s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2402/4895 [52:29<2:19:29,  3.36s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2403/4895 [52:33<2:22:18,  3.43s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2404/4895 [52:33<1:46:30,  2.57s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2405/4895 [52:38<2:11:42,  3.17s/it]








💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [58:38<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [53:07<?, ?it/s]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2406/4895 [52:40<1:58:12,  2.85s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [53:13<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_87 (32 files)

💽 TQM COPY FLOW:   2%|▊                                          | 93/4895 [58:38<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [53:08<?, ?it/s]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2406/4895 [52:40<1:58:12,  2.85s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [53:14<?, ?it/s]

❌ ERROR copying  → /Volumes/MY1TB/_24_ARCH_SONGS/_24_ARCH_rk_88/ | [Errno 2] No such file or directory: ''

💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2407/4895 [52:45<2:30:51,  3.64s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2408/4895 [52:50<2:40:52,  3.88s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2409/4895 [52:57<3:28:23,  5.03s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2410/4895 [53:02<3:23:03,  4.90s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2411/4895 [53:08<3:30:58,  5.10s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2412/4895 [53:08<2:32:06,  3.68s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2413/4895 [53:10<2:17:17,  3.32s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2414/4895 [53:12<1:49:17,  2.64s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2415/4895 [53:12<1:23:13,  2.01s/it]


💽 TQM COPY FLOW:  49%|███████████████████▏                   | 2416/4895 [53:15<1:35:26,  2.31s/it]


💽 TQM COPY FLOW:  49%|███████████████████▎                   | 2417/4895 [53:15<1:11:53,  1.74s/it]


💽 TQM COPY FLOW:  49%|███████████████████▎                   | 2418/4895 [53:17<1:09:25,  1.68s/it]


💽 TQM COPY FLOW:  49%|███████████████████▎                   | 2419/4895 [53:20<1:23:14,  2.02s/it]


💽 TQM COPY FLOW:  49%|███████████████████▎                   | 2420/4895 [53:20<1:05:20,  1.58s/it]


💽 TQM COPY FLOW:  49%|███████████████████▎                   | 2421/4895 [53:29<2:33:37,  3.73s/it]


💽 TQM COPY FLOW:  49%|███████████████████▎                   | 2422/4895 [53:33<2:33:48,  3.73s/it]


💽 TQM COPY FLOW:  49%|███████████████████▎                   | 2423/4895 [53:34<1:55:59,  2.82s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2424/4895 [53:36<1:57:14,  2.85s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2425/4895 [53:37<1:29:48,  2.18s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2426/4895 [53:41<1:48:27,  2.64s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2427/4895 [53:42<1:30:28,  2.20s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2428/4895 [53:43<1:11:32,  1.74s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2429/4895 [53:45<1:23:45,  2.04s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2430/4895 [53:49<1:42:52,  2.50s/it]


💽 TQM COPY FLOW:  50%|███████████████████▎                   | 2431/4895 [53:51<1:37:16,  2.37s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2432/4895 [53:51<1:13:38,  1.79s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2433/4895 [53:52<1:01:47,  1.51s/it]


💽 TQM COPY FLOW:  50%|████████████████████▍                    | 2434/4895 [53:52<44:45,  1.09s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2435/4895 [53:56<1:09:52,  1.70s/it]


💽 TQM COPY FLOW:  50%|████████████████████▍                    | 2436/4895 [53:56<51:05,  1.25s/it]


💽 TQM COPY FLOW:  50%|████████████████████▍                    | 2437/4895 [53:56<38:42,  1.06it/s]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2438/4895 [54:03<1:49:37,  2.68s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2439/4895 [54:06<2:03:03,  3.01s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2440/4895 [54:09<1:55:45,  2.83s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2441/4895 [54:21<3:54:19,  5.73s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2442/4895 [54:26<3:44:12,  5.48s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2443/4895 [54:29<3:14:47,  4.77s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2444/4895 [54:33<2:59:41,  4.40s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2445/4895 [54:36<2:42:49,  3.99s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2446/4895 [54:39<2:29:53,  3.67s/it]


💽 TQM COPY FLOW:  50%|███████████████████▍                   | 2447/4895 [54:41<2:11:32,  3.22s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2448/4895 [54:44<2:10:24,  3.20s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2449/4895 [54:48<2:13:06,  3.27s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2450/4895 [54:48<1:39:41,  2.45s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2451/4895 [54:51<1:43:18,  2.54s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2452/4895 [54:54<1:44:32,  2.57s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2453/4895 [54:56<1:44:14,  2.56s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2454/4895 [54:57<1:20:13,  1.97s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:01:00<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [55:29<?, ?it/s]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2455/4895 [55:02<1:59:21,  2.94s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [55:36<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_88 (50 files)

💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2456/4895 [55:03<1:42:49,  2.53s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2457/4895 [55:09<2:24:01,  3.54s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2458/4895 [55:11<2:03:10,  3.03s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2459/4895 [55:12<1:41:04,  2.49s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2460/4895 [55:15<1:35:51,  2.36s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2461/4895 [55:17<1:37:03,  2.39s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2462/4895 [55:20<1:50:14,  2.72s/it]


💽 TQM COPY FLOW:  50%|███████████████████▌                   | 2463/4895 [55:24<1:55:02,  2.84s/it]


💽 TQM COPY FLOW:  50%|███████████████████▋                   | 2464/4895 [55:24<1:26:53,  2.14s/it]


💽 TQM COPY FLOW:  50%|███████████████████▋                   | 2465/4895 [55:28<1:50:32,  2.73s/it]


💽 TQM COPY FLOW:  50%|███████████████████▋                   | 2466/4895 [55:28<1:18:37,  1.94s/it]


💽 TQM COPY FLOW:  50%|███████████████████▋                   | 2467/4895 [55:29<1:03:34,  1.57s/it]


💽 TQM COPY FLOW:  50%|████████████████████▋                    | 2468/4895 [55:30<50:26,  1.25s/it]


💽 TQM COPY FLOW:  50%|████████████████████▋                    | 2469/4895 [55:30<37:12,  1.09it/s]


💽 TQM COPY FLOW:  50%|████████████████████▋                    | 2470/4895 [55:30<34:39,  1.17it/s]


💽 TQM COPY FLOW:  50%|████████████████████▋                    | 2471/4895 [55:32<38:13,  1.06it/s]


💽 TQM COPY FLOW:  51%|████████████████████▋                    | 2472/4895 [55:34<51:14,  1.27s/it]


💽 TQM COPY FLOW:  51%|███████████████████▋                   | 2473/4895 [55:38<1:28:05,  2.18s/it]


💽 TQM COPY FLOW:  51%|███████████████████▋                   | 2474/4895 [55:45<2:30:49,  3.74s/it]


💽 TQM COPY FLOW:  51%|███████████████████▋                   | 2475/4895 [55:51<2:53:09,  4.29s/it]


💽 TQM COPY FLOW:  51%|███████████████████▋                   | 2476/4895 [55:56<3:09:26,  4.70s/it]


💽 TQM COPY FLOW:  51%|███████████████████▋                   | 2477/4895 [56:02<3:15:46,  4.86s/it]


💽 TQM COPY FLOW:  51%|███████████████████▋                   | 2478/4895 [56:02<2:21:28,  3.51s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2479/4895 [56:03<1:48:53,  2.70s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2480/4895 [56:04<1:28:48,  2.21s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2481/4895 [56:04<1:08:12,  1.70s/it]


💽 TQM COPY FLOW:  51%|████████████████████▊                    | 2482/4895 [56:05<57:39,  1.43s/it]


💽 TQM COPY FLOW:  51%|████████████████████▊                    | 2483/4895 [56:06<46:40,  1.16s/it]


💽 TQM COPY FLOW:  51%|████████████████████▊                    | 2484/4895 [56:06<39:33,  1.02it/s]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2485/4895 [56:17<2:32:05,  3.79s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2486/4895 [56:18<2:01:11,  3.02s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2487/4895 [56:19<1:33:43,  2.34s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2488/4895 [56:20<1:24:04,  2.10s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2489/4895 [56:21<1:06:02,  1.65s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2490/4895 [56:42<5:05:51,  7.63s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2491/4895 [56:45<4:00:26,  6.00s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2492/4895 [56:46<3:02:25,  4.55s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2493/4895 [56:54<3:49:28,  5.73s/it]


💽 TQM COPY FLOW:  51%|███████████████████▊                   | 2494/4895 [56:59<3:32:19,  5.31s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2495/4895 [57:01<2:59:18,  4.48s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2496/4895 [57:12<4:14:05,  6.36s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2497/4895 [57:16<3:53:33,  5.84s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2498/4895 [57:23<3:58:22,  5.97s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2499/4895 [57:23<2:51:55,  4.31s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2500/4895 [57:31<3:33:36,  5.35s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2501/4895 [57:32<2:42:12,  4.07s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2502/4895 [57:35<2:33:00,  3.84s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2503/4895 [57:36<1:57:18,  2.94s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2504/4895 [57:38<1:46:11,  2.66s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:03:46<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [58:15<?, ?it/s]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2505/4895 [57:48<3:12:13,  4.83s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [58:22<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_89 (50 files)

💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2506/4895 [57:56<3:46:39,  5.69s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2507/4895 [57:56<2:40:43,  4.04s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2508/4895 [57:57<1:59:27,  3.00s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2509/4895 [57:59<1:50:46,  2.79s/it]


💽 TQM COPY FLOW:  51%|███████████████████▉                   | 2510/4895 [57:59<1:22:51,  2.08s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2511/4895 [58:03<1:36:59,  2.44s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2512/4895 [58:07<1:55:47,  2.92s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2513/4895 [58:30<5:57:24,  9.00s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2514/4895 [58:30<4:18:46,  6.52s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2515/4895 [58:37<4:14:50,  6.42s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2516/4895 [58:41<3:44:57,  5.67s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2517/4895 [58:42<2:48:39,  4.26s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2518/4895 [58:46<2:45:28,  4.18s/it]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2519/4895 [58:50<2:46:24,  4.20s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:04:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [59:18<?, ?it/s]


💽 TQM COPY FLOW:  51%|████████████████████                   | 2520/4895 [58:51<2:08:06,  3.24s/it]
💽 TQM COPY FLOW:   0%|                                                    | 0/4895 [59:25<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_90 (15 files)

💽 TQM COPY FLOW:  52%|████████████████████                   | 2521/4895 [58:54<2:03:13,  3.11s/it]


💽 TQM COPY FLOW:  52%|████████████████████                   | 2522/4895 [59:00<2:44:11,  4.15s/it]


💽 TQM COPY FLOW:  52%|████████████████████                   | 2523/4895 [59:06<3:06:37,  4.72s/it]


💽 TQM COPY FLOW:  52%|████████████████████                   | 2524/4895 [59:07<2:21:19,  3.58s/it]


💽 TQM COPY FLOW:  52%|████████████████████                   | 2525/4895 [59:07<1:42:53,  2.60s/it]


💽 TQM COPY FLOW:  52%|████████████████████▏                  | 2526/4895 [59:08<1:15:46,  1.92s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2527/4895 [59:08<56:45,  1.44s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2528/4895 [59:09<44:04,  1.12s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2529/4895 [59:09<39:13,  1.01it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2530/4895 [59:10<34:09,  1.15it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2531/4895 [59:11<33:13,  1.19it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2532/4895 [59:11<31:04,  1.27it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2533/4895 [59:12<34:06,  1.15it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2534/4895 [59:14<45:35,  1.16s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2535/4895 [59:15<36:26,  1.08it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2536/4895 [59:15<28:15,  1.39it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▏                   | 2537/4895 [59:15<24:41,  1.59it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2538/4895 [59:16<22:28,  1.75it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2539/4895 [59:16<23:49,  1.65it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2540/4895 [59:17<28:50,  1.36it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2541/4895 [59:18<24:33,  1.60it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2542/4895 [59:18<22:28,  1.74it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2543/4895 [59:19<20:58,  1.87it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2544/4895 [59:19<19:14,  2.04it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2545/4895 [59:20<21:02,  1.86it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2546/4895 [59:21<25:35,  1.53it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2547/4895 [59:21<24:17,  1.61it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2548/4895 [59:21<20:31,  1.91it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2549/4895 [59:22<21:10,  1.85it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2550/4895 [59:22<20:10,  1.94it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▎                   | 2551/4895 [59:23<19:08,  2.04it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▍                   | 2552/4895 [59:26<46:04,  1.18s/it]


💽 TQM COPY FLOW:  52%|████████████████████▎                  | 2553/4895 [59:28<1:05:10,  1.67s/it]


💽 TQM COPY FLOW:  52%|████████████████████▎                  | 2554/4895 [59:30<1:08:53,  1.77s/it]


💽 TQM COPY FLOW:  52%|████████████████████▎                  | 2555/4895 [59:38<2:13:36,  3.43s/it]


💽 TQM COPY FLOW:  52%|████████████████████▎                  | 2556/4895 [59:39<1:44:42,  2.69s/it]


💽 TQM COPY FLOW:  52%|████████████████████▎                  | 2557/4895 [59:41<1:44:51,  2.69s/it]


💽 TQM COPY FLOW:  52%|████████████████████▍                  | 2558/4895 [59:43<1:30:08,  2.31s/it]


💽 TQM COPY FLOW:  52%|████████████████████▍                  | 2559/4895 [59:47<1:56:54,  3.00s/it]


💽 TQM COPY FLOW:  52%|████████████████████▍                  | 2560/4895 [59:48<1:27:26,  2.25s/it]


💽 TQM COPY FLOW:  52%|████████████████████▍                  | 2561/4895 [59:48<1:03:54,  1.64s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▍                   | 2562/4895 [59:49<54:15,  1.40s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▍                   | 2563/4895 [59:50<47:04,  1.21s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▍                   | 2564/4895 [59:50<41:14,  1.06s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▍                   | 2565/4895 [59:51<40:32,  1.04s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▍                   | 2566/4895 [59:53<40:17,  1.04s/it]


💽 TQM COPY FLOW:  52%|█████████████████████▌                   | 2567/4895 [59:53<36:44,  1.06it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▌                   | 2568/4895 [59:54<33:07,  1.17it/s]


💽 TQM COPY FLOW:  52%|█████████████████████▌                   | 2569/4895 [59:54<29:46,  1.30it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:05:53<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:00:23<?, ?it/s]


💽 TQM COPY FLOW:  53%|█████████████████████▌                   | 2570/4895 [59:55<29:55,  1.29it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:00:29<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_91 (50 files)

💽 TQM COPY FLOW:  53%|█████████████████████▌                   | 2571/4895 [59:58<48:10,  1.24s/it]


💽 TQM COPY FLOW:  53%|█████████████████████▌                   | 2572/4895 [59:58<41:58,  1.08s/it]


💽 TQM COPY FLOW:  53%|█████████████████████▌                   | 2573/4895 [59:59<36:11,  1.07it/s]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2574/4895 [1:00:00<33:47,  1.14it/s]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2575/4895 [1:00:00<29:12,  1.32it/s]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2576/4895 [1:00:01<29:40,  1.30it/s]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2577/4895 [1:00:02<30:55,  1.25it/s]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2578/4895 [1:00:02<30:07,  1.28it/s]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2579/4895 [1:00:03<29:44,  1.30it/s]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2580/4895 [1:00:07<1:00:59,  1.58s/it]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2581/4895 [1:00:09<1:09:50,  1.81s/it]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2582/4895 [1:00:12<1:25:16,  2.21s/it]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2583/4895 [1:00:16<1:37:54,  2.54s/it]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2584/4895 [1:00:16<1:12:07,  1.87s/it]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2585/4895 [1:00:16<53:07,  1.38s/it]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2586/4895 [1:00:19<1:06:08,  1.72s/it]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2587/4895 [1:00:21<1:10:13,  1.83s/it]


💽 TQM COPY FLOW:  53%|████████████████████▌                  | 2588/4895 [1:00:21<54:06,  1.41s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:06:24<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:00:53<?, ?it/s]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2589/4895 [1:00:26<1:30:39,  2.36s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:00:59<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_92 (19 files)

💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2590/4895 [1:00:29<1:46:36,  2.78s/it]


💽 TQM COPY FLOW:  53%|███████████████████▌                 | 2591/4895 [1:00:30<1:18:53,  2.05s/it]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2592/4895 [1:00:30<59:26,  1.55s/it]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2593/4895 [1:00:31<48:45,  1.27s/it]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2594/4895 [1:00:31<40:01,  1.04s/it]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2595/4895 [1:00:32<33:37,  1.14it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2596/4895 [1:00:32<31:12,  1.23it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2597/4895 [1:00:33<29:05,  1.32it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2598/4895 [1:00:34<28:58,  1.32it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2599/4895 [1:00:35<32:01,  1.19it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2600/4895 [1:00:36<31:29,  1.21it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2601/4895 [1:00:36<27:58,  1.37it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2602/4895 [1:00:37<25:19,  1.51it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2603/4895 [1:00:37<26:09,  1.46it/s]


💽 TQM COPY FLOW:  53%|████████████████████▋                  | 2604/4895 [1:00:38<24:12,  1.58it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2605/4895 [1:00:38<21:15,  1.79it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2606/4895 [1:00:39<19:47,  1.93it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2607/4895 [1:00:39<20:11,  1.89it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2608/4895 [1:00:40<21:43,  1.75it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2609/4895 [1:00:40<18:34,  2.05it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2610/4895 [1:00:40<15:52,  2.40it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2611/4895 [1:00:41<13:47,  2.76it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2612/4895 [1:00:42<20:10,  1.89it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2613/4895 [1:00:42<21:32,  1.77it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2614/4895 [1:00:43<21:06,  1.80it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2615/4895 [1:00:43<18:21,  2.07it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2616/4895 [1:00:44<22:24,  1.70it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2617/4895 [1:00:44<20:33,  1.85it/s]


💽 TQM COPY FLOW:  53%|████████████████████▊                  | 2618/4895 [1:00:45<23:07,  1.64it/s]


💽 TQM COPY FLOW:  54%|████████████████████▊                  | 2619/4895 [1:00:46<20:37,  1.84it/s]


💽 TQM COPY FLOW:  54%|████████████████████▊                  | 2620/4895 [1:00:46<20:18,  1.87it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2621/4895 [1:00:46<18:54,  2.00it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2622/4895 [1:00:47<17:23,  2.18it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2623/4895 [1:00:47<19:12,  1.97it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2624/4895 [1:00:48<18:24,  2.06it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2625/4895 [1:00:48<18:21,  2.06it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2626/4895 [1:00:49<16:05,  2.35it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2627/4895 [1:00:49<19:36,  1.93it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2628/4895 [1:00:50<17:31,  2.15it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2629/4895 [1:00:50<19:25,  1.94it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2630/4895 [1:00:51<18:27,  2.05it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2631/4895 [1:00:52<22:18,  1.69it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2632/4895 [1:00:52<23:45,  1.59it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2633/4895 [1:00:53<19:23,  1.94it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2634/4895 [1:00:53<17:37,  2.14it/s]


💽 TQM COPY FLOW:  54%|████████████████████▉                  | 2635/4895 [1:00:53<17:17,  2.18it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2636/4895 [1:00:54<15:47,  2.38it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:06:52<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:01:22<?, ?it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2637/4895 [1:00:55<20:05,  1.87it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:01:28<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_93 (48 files)

💽 TQM COPY FLOW:  54%|█████████████████████                  | 2638/4895 [1:00:55<24:20,  1.55it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2639/4895 [1:00:56<23:05,  1.63it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2640/4895 [1:00:57<27:50,  1.35it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2641/4895 [1:00:58<26:36,  1.41it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2642/4895 [1:00:59<36:25,  1.03it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2643/4895 [1:01:00<32:26,  1.16it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2644/4895 [1:01:00<28:39,  1.31it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2645/4895 [1:01:01<23:41,  1.58it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2646/4895 [1:01:01<24:51,  1.51it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2647/4895 [1:01:02<21:26,  1.75it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2648/4895 [1:01:02<20:21,  1.84it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2649/4895 [1:01:03<19:39,  1.90it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2650/4895 [1:01:03<20:13,  1.85it/s]


💽 TQM COPY FLOW:  54%|█████████████████████                  | 2651/4895 [1:01:04<23:43,  1.58it/s]


💽 TQM COPY FLOW:  54%|█████████████████████▏                 | 2652/4895 [1:01:05<29:39,  1.26it/s]


💽 TQM COPY FLOW:  54%|█████████████████████▏                 | 2653/4895 [1:01:06<33:36,  1.11it/s]


💽 TQM COPY FLOW:  54%|█████████████████████▏                 | 2654/4895 [1:01:07<29:51,  1.25it/s]


💽 TQM COPY FLOW:  54%|█████████████████████▏                 | 2655/4895 [1:01:10<57:24,  1.54s/it]


💽 TQM COPY FLOW:  54%|████████████████████                 | 2656/4895 [1:01:13<1:14:03,  1.98s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:07:14<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:01:43<?, ?it/s]


💽 TQM COPY FLOW:  54%|████████████████████                 | 2657/4895 [1:01:16<1:21:35,  2.19s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:01:50<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_94 (20 files)

💽 TQM COPY FLOW:  54%|████████████████████                 | 2658/4895 [1:01:19<1:26:27,  2.32s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:07:18<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:01:48<?, ?it/s]


💽 TQM COPY FLOW:  54%|████████████████████                 | 2659/4895 [1:01:21<1:21:51,  2.20s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:01:54<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_95 (2 files)

💽 TQM COPY FLOW:  54%|████████████████████                 | 2660/4895 [1:01:23<1:23:49,  2.25s/it]


💽 TQM COPY FLOW:  54%|████████████████████                 | 2661/4895 [1:01:24<1:05:43,  1.77s/it]


💽 TQM COPY FLOW:  54%|█████████████████████▏                 | 2662/4895 [1:01:24<53:38,  1.44s/it]


💽 TQM COPY FLOW:  54%|█████████████████████▏                 | 2663/4895 [1:01:24<39:57,  1.07s/it]


💽 TQM COPY FLOW:  54%|████████████████████▏                | 2664/4895 [1:01:28<1:10:45,  1.90s/it]


💽 TQM COPY FLOW:  54%|█████████████████████▏                 | 2665/4895 [1:01:29<55:08,  1.48s/it]


💽 TQM COPY FLOW:  54%|████████████████████▏                | 2666/4895 [1:01:33<1:23:35,  2.25s/it]


💽 TQM COPY FLOW:  54%|████████████████████▏                | 2667/4895 [1:01:34<1:12:33,  1.95s/it]


💽 TQM COPY FLOW:  55%|████████████████████▏                | 2668/4895 [1:01:37<1:20:33,  2.17s/it]


💽 TQM COPY FLOW:  55%|████████████████████▏                | 2669/4895 [1:01:37<1:04:23,  1.74s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:07:36<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:02:05<?, ?it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2670/4895 [1:01:38<50:32,  1.36s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:02:12<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_96 (11 files)

💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2671/4895 [1:01:39<42:38,  1.15s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2672/4895 [1:01:39<33:05,  1.12it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2673/4895 [1:01:39<26:00,  1.42it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2674/4895 [1:01:40<22:10,  1.67it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2675/4895 [1:01:40<21:05,  1.75it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2676/4895 [1:01:41<21:57,  1.68it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2677/4895 [1:01:41<20:34,  1.80it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2678/4895 [1:01:41<17:02,  2.17it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:07:40<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:02:10<?, ?it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2679/4895 [1:01:42<19:41,  1.88it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:02:16<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_97 (9 files)

💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2680/4895 [1:01:42<16:52,  2.19it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2681/4895 [1:01:43<15:51,  2.33it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▎                 | 2682/4895 [1:01:43<16:36,  2.22it/s]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2683/4895 [1:01:48<1:03:26,  1.72s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2684/4895 [1:01:52<1:24:52,  2.30s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2685/4895 [1:01:54<1:29:37,  2.43s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2686/4895 [1:02:04<2:51:26,  4.66s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2687/4895 [1:02:05<2:04:40,  3.39s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2688/4895 [1:02:08<2:01:24,  3.30s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2689/4895 [1:02:11<1:55:57,  3.15s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2690/4895 [1:02:12<1:40:33,  2.74s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2691/4895 [1:02:15<1:39:53,  2.72s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2692/4895 [1:02:16<1:18:30,  2.14s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▍                 | 2693/4895 [1:02:16<59:17,  1.62s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2694/4895 [1:02:18<1:04:31,  1.76s/it]


💽 TQM COPY FLOW:  55%|████████████████████▎                | 2695/4895 [1:02:20<1:03:09,  1.72s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▍                 | 2696/4895 [1:02:20<48:13,  1.32s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▍                 | 2697/4895 [1:02:21<39:44,  1.08s/it]


💽 TQM COPY FLOW:  55%|████████████████████▍                | 2698/4895 [1:02:25<1:18:26,  2.14s/it]


💽 TQM COPY FLOW:  55%|████████████████████▍                | 2699/4895 [1:02:26<1:04:33,  1.76s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2700/4895 [1:02:27<52:03,  1.42s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2701/4895 [1:02:27<42:33,  1.16s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2702/4895 [1:02:29<46:58,  1.29s/it]


💽 TQM COPY FLOW:  55%|████████████████████▍                | 2703/4895 [1:02:32<1:04:25,  1.76s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2704/4895 [1:02:33<52:32,  1.44s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2705/4895 [1:02:33<42:30,  1.16s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2706/4895 [1:02:34<35:29,  1.03it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2707/4895 [1:02:34<29:20,  1.24it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2708/4895 [1:02:35<26:33,  1.37it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2709/4895 [1:02:36<30:30,  1.19it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2710/4895 [1:02:37<35:55,  1.01it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2711/4895 [1:02:39<42:53,  1.18s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2712/4895 [1:02:39<38:33,  1.06s/it]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2713/4895 [1:02:40<32:39,  1.11it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▌                 | 2714/4895 [1:02:41<32:11,  1.13it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:08:40<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:03:09<?, ?it/s]


💽 TQM COPY FLOW:  55%|█████████████████████▋                 | 2715/4895 [1:02:42<31:46,  1.14it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:03:15<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_98 (36 files)

💽 TQM COPY FLOW:  55%|█████████████████████▋                 | 2716/4895 [1:02:44<44:47,  1.23s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2717/4895 [1:02:45<44:22,  1.22s/it]


💽 TQM COPY FLOW:  56%|████████████████████▌                | 2718/4895 [1:02:51<1:40:27,  2.77s/it]


💽 TQM COPY FLOW:  56%|████████████████████▌                | 2719/4895 [1:02:52<1:19:21,  2.19s/it]


💽 TQM COPY FLOW:  56%|████████████████████▌                | 2720/4895 [1:02:53<1:04:41,  1.78s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2721/4895 [1:02:54<50:59,  1.41s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2722/4895 [1:02:54<44:09,  1.22s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2723/4895 [1:02:55<41:03,  1.13s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2724/4895 [1:02:56<39:57,  1.10s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2725/4895 [1:02:58<42:48,  1.18s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2726/4895 [1:02:59<47:28,  1.31s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2727/4895 [1:03:00<46:29,  1.29s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2728/4895 [1:03:01<40:30,  1.12s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▋                 | 2729/4895 [1:03:02<39:03,  1.08s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2730/4895 [1:03:04<49:15,  1.37s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2731/4895 [1:03:05<45:43,  1.27s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2732/4895 [1:03:07<54:59,  1.53s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2733/4895 [1:03:09<53:56,  1.50s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2734/4895 [1:03:10<48:38,  1.35s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2735/4895 [1:03:11<42:37,  1.18s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2736/4895 [1:03:12<39:58,  1.11s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2737/4895 [1:03:13<38:28,  1.07s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▊                 | 2738/4895 [1:03:13<36:21,  1.01s/it]


💽 TQM COPY FLOW:  56%|████████████████████▋                | 2739/4895 [1:03:18<1:14:56,  2.09s/it]


💽 TQM COPY FLOW:  56%|████████████████████▋                | 2740/4895 [1:03:21<1:27:34,  2.44s/it]


💽 TQM COPY FLOW:  56%|████████████████████▋                | 2741/4895 [1:03:25<1:39:17,  2.77s/it]


💽 TQM COPY FLOW:  56%|████████████████████▋                | 2742/4895 [1:03:28<1:40:49,  2.81s/it]


💽 TQM COPY FLOW:  56%|████████████████████▋                | 2743/4895 [1:03:32<1:56:21,  3.24s/it]


💽 TQM COPY FLOW:  56%|████████████████████▋                | 2744/4895 [1:03:35<1:58:57,  3.32s/it]


💽 TQM COPY FLOW:  56%|████████████████████▋                | 2745/4895 [1:03:41<2:23:39,  4.01s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2746/4895 [1:03:45<2:25:33,  4.06s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2747/4895 [1:03:49<2:20:15,  3.92s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2748/4895 [1:03:52<2:11:39,  3.68s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2749/4895 [1:03:53<1:39:58,  2.80s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2750/4895 [1:03:57<1:53:50,  3.18s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2751/4895 [1:03:58<1:36:26,  2.70s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2752/4895 [1:04:01<1:39:10,  2.78s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2753/4895 [1:04:02<1:15:58,  2.13s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2754/4895 [1:04:06<1:33:40,  2.63s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2755/4895 [1:04:10<1:48:19,  3.04s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2756/4895 [1:04:13<1:46:11,  2.98s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2757/4895 [1:04:13<1:18:55,  2.22s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2758/4895 [1:04:15<1:18:17,  2.20s/it]


💽 TQM COPY FLOW:  56%|████████████████████▊                | 2759/4895 [1:04:16<1:01:27,  1.73s/it]


💽 TQM COPY FLOW:  56%|█████████████████████▉                 | 2760/4895 [1:04:16<49:55,  1.40s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:10:15<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:04:44<?, ?it/s]


💽 TQM COPY FLOW:  56%|█████████████████████▉                 | 2761/4895 [1:04:17<40:14,  1.13s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:04:51<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_99 (46 files)

💽 TQM COPY FLOW:  56%|██████████████████████                 | 2762/4895 [1:04:19<48:44,  1.37s/it]


💽 TQM COPY FLOW:  56%|██████████████████████                 | 2763/4895 [1:04:20<42:17,  1.19s/it]


💽 TQM COPY FLOW:  56%|████████████████████▉                | 2764/4895 [1:04:23<1:03:56,  1.80s/it]


💽 TQM COPY FLOW:  56%|██████████████████████                 | 2765/4895 [1:04:23<51:04,  1.44s/it]


💽 TQM COPY FLOW:  57%|██████████████████████                 | 2766/4895 [1:04:24<45:48,  1.29s/it]


💽 TQM COPY FLOW:  57%|██████████████████████                 | 2767/4895 [1:04:25<39:22,  1.11s/it]


💽 TQM COPY FLOW:  57%|██████████████████████                 | 2768/4895 [1:04:26<35:11,  1.01it/s]


💽 TQM COPY FLOW:  57%|████████████████████▉                | 2769/4895 [1:04:32<1:29:17,  2.52s/it]


💽 TQM COPY FLOW:  57%|████████████████████▉                | 2770/4895 [1:04:33<1:10:48,  2.00s/it]


💽 TQM COPY FLOW:  57%|████████████████████▉                | 2771/4895 [1:04:34<1:02:00,  1.75s/it]


💽 TQM COPY FLOW:  57%|██████████████████████                 | 2772/4895 [1:04:35<51:26,  1.45s/it]


💽 TQM COPY FLOW:  57%|██████████████████████                 | 2773/4895 [1:04:36<45:50,  1.30s/it]


💽 TQM COPY FLOW:  57%|██████████████████████                 | 2774/4895 [1:04:36<40:17,  1.14s/it]


💽 TQM COPY FLOW:  57%|████████████████████▉                | 2775/4895 [1:04:40<1:05:14,  1.85s/it]


💽 TQM COPY FLOW:  57%|██████████████████████                 | 2776/4895 [1:04:40<51:49,  1.47s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2777/4895 [1:04:41<40:44,  1.15s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2778/4895 [1:04:41<31:33,  1.12it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2779/4895 [1:04:42<27:15,  1.29it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2780/4895 [1:04:42<28:08,  1.25it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2781/4895 [1:04:46<57:22,  1.63s/it]


💽 TQM COPY FLOW:  57%|█████████████████████                | 2782/4895 [1:04:48<1:03:35,  1.81s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2783/4895 [1:04:49<50:05,  1.42s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2784/4895 [1:04:49<40:40,  1.16s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2785/4895 [1:04:50<32:59,  1.07it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2786/4895 [1:04:50<30:38,  1.15it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2787/4895 [1:04:51<26:40,  1.32it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2788/4895 [1:04:51<21:51,  1.61it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2789/4895 [1:04:51<17:30,  2.00it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2790/4895 [1:04:52<19:23,  1.81it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2791/4895 [1:04:53<18:26,  1.90it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▏                | 2792/4895 [1:04:54<23:37,  1.48it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2793/4895 [1:04:54<21:11,  1.65it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2794/4895 [1:04:55<19:35,  1.79it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2795/4895 [1:04:55<18:58,  1.85it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2796/4895 [1:04:56<19:00,  1.84it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2797/4895 [1:04:56<22:03,  1.59it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2798/4895 [1:04:57<25:34,  1.37it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2799/4895 [1:04:58<25:47,  1.35it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2800/4895 [1:04:59<26:09,  1.33it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2801/4895 [1:05:00<29:23,  1.19it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2802/4895 [1:05:01<35:06,  1.01s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2803/4895 [1:05:02<33:12,  1.05it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2804/4895 [1:05:03<29:27,  1.18it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2805/4895 [1:05:03<23:28,  1.48it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2806/4895 [1:05:03<19:42,  1.77it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2807/4895 [1:05:04<16:38,  2.09it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▎                | 2808/4895 [1:05:04<13:51,  2.51it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▍                | 2809/4895 [1:05:04<13:00,  2.67it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▍                | 2810/4895 [1:05:06<24:15,  1.43it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:11:04<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:05:34<?, ?it/s]


💽 TQM COPY FLOW:  57%|██████████████████████▍                | 2811/4895 [1:05:06<22:45,  1.53it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:05:40<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_100 (50 files)

💽 TQM COPY FLOW:  57%|█████████████████████▎               | 2812/4895 [1:05:11<1:02:08,  1.79s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▍                | 2813/4895 [1:05:11<51:13,  1.48s/it]


💽 TQM COPY FLOW:  57%|██████████████████████▍                | 2814/4895 [1:05:13<48:13,  1.39s/it]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2815/4895 [1:05:13<41:39,  1.20s/it]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2816/4895 [1:05:14<32:07,  1.08it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2817/4895 [1:05:15<32:31,  1.06it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2818/4895 [1:05:15<26:43,  1.30it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2819/4895 [1:05:15<24:19,  1.42it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2820/4895 [1:05:16<21:44,  1.59it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2821/4895 [1:05:16<18:12,  1.90it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2822/4895 [1:05:18<26:34,  1.30it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2823/4895 [1:05:18<26:10,  1.32it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▍                | 2824/4895 [1:05:19<21:19,  1.62it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2825/4895 [1:05:19<20:43,  1.67it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2826/4895 [1:05:19<17:49,  1.93it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2827/4895 [1:05:21<24:27,  1.41it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2828/4895 [1:05:21<22:25,  1.54it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2829/4895 [1:05:22<21:47,  1.58it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2830/4895 [1:05:22<19:09,  1.80it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2831/4895 [1:05:23<19:00,  1.81it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2832/4895 [1:05:23<15:16,  2.25it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2833/4895 [1:05:24<18:21,  1.87it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2834/4895 [1:05:24<16:05,  2.13it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2835/4895 [1:05:25<17:54,  1.92it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2836/4895 [1:05:25<17:43,  1.94it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2837/4895 [1:05:26<18:12,  1.88it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2838/4895 [1:05:26<15:37,  2.19it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▌                | 2839/4895 [1:05:26<15:33,  2.20it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2840/4895 [1:05:27<21:56,  1.56it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2841/4895 [1:05:28<21:30,  1.59it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2842/4895 [1:05:29<22:41,  1.51it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2843/4895 [1:05:29<19:27,  1.76it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2844/4895 [1:05:30<22:14,  1.54it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2845/4895 [1:05:30<18:49,  1.82it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2846/4895 [1:05:31<20:02,  1.70it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2847/4895 [1:05:31<17:29,  1.95it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2848/4895 [1:05:32<16:31,  2.06it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2849/4895 [1:05:32<14:34,  2.34it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2850/4895 [1:05:32<14:03,  2.43it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2851/4895 [1:05:33<15:13,  2.24it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2852/4895 [1:05:33<15:27,  2.20it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2853/4895 [1:05:34<14:18,  2.38it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2854/4895 [1:05:34<16:16,  2.09it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▋                | 2855/4895 [1:05:35<17:01,  2.00it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2856/4895 [1:05:35<16:58,  2.00it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2857/4895 [1:05:36<16:54,  2.01it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2858/4895 [1:05:36<17:38,  1.93it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2859/4895 [1:05:37<15:51,  2.14it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2860/4895 [1:05:37<15:36,  2.17it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:11:36<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:06:06<?, ?it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2861/4895 [1:05:38<21:15,  1.59it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:06:12<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_101 (50 files)

💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2862/4895 [1:05:39<21:12,  1.60it/s]


💽 TQM COPY FLOW:  58%|██████████████████████▊                | 2863/4895 [1:05:39<21:09,  1.60it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2864/4895 [1:05:40<22:21,  1.51it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2865/4895 [1:05:41<21:57,  1.54it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2866/4895 [1:05:42<24:40,  1.37it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2867/4895 [1:05:44<39:48,  1.18s/it]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2868/4895 [1:05:44<30:46,  1.10it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2869/4895 [1:05:45<24:10,  1.40it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2870/4895 [1:05:46<35:18,  1.05s/it]


💽 TQM COPY FLOW:  59%|██████████████████████▊                | 2871/4895 [1:05:47<28:55,  1.17it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2872/4895 [1:05:47<23:59,  1.40it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2873/4895 [1:05:48<29:15,  1.15it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2874/4895 [1:05:49<25:10,  1.34it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2875/4895 [1:05:49<21:44,  1.55it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2876/4895 [1:05:50<18:55,  1.78it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2877/4895 [1:05:50<16:34,  2.03it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2878/4895 [1:05:50<15:15,  2.20it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2879/4895 [1:05:51<14:38,  2.30it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2880/4895 [1:05:51<15:20,  2.19it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2881/4895 [1:05:52<14:11,  2.37it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2882/4895 [1:05:52<15:11,  2.21it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2883/4895 [1:05:53<15:12,  2.20it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2884/4895 [1:05:53<17:40,  1.90it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2885/4895 [1:05:54<22:39,  1.48it/s]


💽 TQM COPY FLOW:  59%|██████████████████████▉                | 2886/4895 [1:05:55<21:51,  1.53it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2887/4895 [1:05:56<30:28,  1.10it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2888/4895 [1:05:57<24:50,  1.35it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2889/4895 [1:05:57<20:20,  1.64it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2890/4895 [1:05:57<18:43,  1.79it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2891/4895 [1:05:58<18:23,  1.82it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2892/4895 [1:05:58<16:53,  1.98it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2893/4895 [1:05:59<15:59,  2.09it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2894/4895 [1:05:59<13:48,  2.41it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2895/4895 [1:06:00<15:43,  2.12it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2896/4895 [1:06:00<15:44,  2.12it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2897/4895 [1:06:01<16:20,  2.04it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2898/4895 [1:06:02<23:32,  1.41it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2899/4895 [1:06:02<21:44,  1.53it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2900/4895 [1:06:03<17:53,  1.86it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2901/4895 [1:06:03<18:04,  1.84it/s]


💽 TQM COPY FLOW:  59%|███████████████████████                | 2902/4895 [1:06:04<18:45,  1.77it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2903/4895 [1:06:05<21:12,  1.57it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2904/4895 [1:06:05<17:33,  1.89it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2905/4895 [1:06:05<16:57,  1.96it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2906/4895 [1:06:06<17:19,  1.91it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2907/4895 [1:06:06<17:02,  1.94it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2908/4895 [1:06:07<17:28,  1.90it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2909/4895 [1:06:08<20:45,  1.59it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2910/4895 [1:06:08<20:20,  1.63it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:12:07<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:06:37<?, ?it/s]


💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2911/4895 [1:06:09<20:59,  1.57it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:06:43<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_102 (50 files)

💽 TQM COPY FLOW:  59%|███████████████████████▏               | 2912/4895 [1:06:10<20:00,  1.65it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▏               | 2913/4895 [1:06:10<18:49,  1.76it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▏               | 2914/4895 [1:06:11<17:00,  1.94it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▏               | 2915/4895 [1:06:11<15:45,  2.09it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▏               | 2916/4895 [1:06:12<19:14,  1.71it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▏               | 2917/4895 [1:06:12<19:14,  1.71it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▏               | 2918/4895 [1:06:13<20:49,  1.58it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2919/4895 [1:06:14<25:13,  1.31it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2920/4895 [1:06:15<25:30,  1.29it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2921/4895 [1:06:16<25:03,  1.31it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2922/4895 [1:06:16<23:40,  1.39it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2923/4895 [1:06:17<20:21,  1.61it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2924/4895 [1:06:17<21:08,  1.55it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2925/4895 [1:06:18<24:05,  1.36it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2926/4895 [1:06:19<22:58,  1.43it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2927/4895 [1:06:19<19:31,  1.68it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2928/4895 [1:06:20<18:00,  1.82it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2929/4895 [1:06:20<18:13,  1.80it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2930/4895 [1:06:21<16:37,  1.97it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2931/4895 [1:06:21<17:22,  1.88it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2932/4895 [1:06:22<17:14,  1.90it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▎               | 2933/4895 [1:06:22<17:32,  1.86it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2934/4895 [1:06:24<23:10,  1.41it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2935/4895 [1:06:24<22:11,  1.47it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2936/4895 [1:06:25<25:47,  1.27it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2937/4895 [1:06:26<22:59,  1.42it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2938/4895 [1:06:28<41:21,  1.27s/it]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2939/4895 [1:06:30<42:22,  1.30s/it]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2940/4895 [1:06:30<35:29,  1.09s/it]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2941/4895 [1:06:31<30:55,  1.05it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2942/4895 [1:06:31<25:44,  1.26it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2943/4895 [1:06:32<22:09,  1.47it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2944/4895 [1:06:32<20:28,  1.59it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2945/4895 [1:06:33<18:32,  1.75it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2946/4895 [1:06:33<18:02,  1.80it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2947/4895 [1:06:34<16:50,  1.93it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2948/4895 [1:06:34<15:47,  2.05it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▍               | 2949/4895 [1:06:35<18:30,  1.75it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2950/4895 [1:06:35<18:13,  1.78it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2951/4895 [1:06:36<17:28,  1.85it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2952/4895 [1:06:37<24:04,  1.35it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2953/4895 [1:06:38<23:20,  1.39it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2954/4895 [1:06:38<19:42,  1.64it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2955/4895 [1:06:39<18:40,  1.73it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2956/4895 [1:06:39<17:40,  1.83it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2957/4895 [1:06:40<19:39,  1.64it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2958/4895 [1:06:40<19:08,  1.69it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2959/4895 [1:06:41<18:45,  1.72it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2960/4895 [1:06:41<16:34,  1.95it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:12:41<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:07:10<?, ?it/s]


💽 TQM COPY FLOW:  60%|███████████████████████▌               | 2961/4895 [1:06:43<25:02,  1.29it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:07:16<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_103 (50 files)

💽 TQM COPY FLOW:  61%|███████████████████████▌               | 2962/4895 [1:06:45<43:28,  1.35s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▌               | 2963/4895 [1:06:46<35:01,  1.09s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▌               | 2964/4895 [1:06:47<32:33,  1.01s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▌               | 2965/4895 [1:06:47<28:08,  1.14it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2966/4895 [1:06:48<25:53,  1.24it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2967/4895 [1:06:48<22:20,  1.44it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2968/4895 [1:06:49<19:54,  1.61it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2969/4895 [1:06:49<20:11,  1.59it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2970/4895 [1:06:50<17:58,  1.78it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2971/4895 [1:06:50<16:06,  1.99it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2972/4895 [1:06:51<15:42,  2.04it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2973/4895 [1:06:53<33:57,  1.06s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2974/4895 [1:06:55<43:13,  1.35s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2975/4895 [1:06:57<54:00,  1.69s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2976/4895 [1:06:58<40:45,  1.27s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2977/4895 [1:06:58<31:38,  1.01it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2978/4895 [1:06:58<24:46,  1.29it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2979/4895 [1:06:59<20:16,  1.58it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▋               | 2980/4895 [1:06:59<16:38,  1.92it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2981/4895 [1:07:03<54:17,  1.70s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2982/4895 [1:07:04<46:47,  1.47s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2983/4895 [1:07:05<37:37,  1.18s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2984/4895 [1:07:05<32:10,  1.01s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2985/4895 [1:07:06<28:15,  1.13it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2986/4895 [1:07:10<56:19,  1.77s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:13:09<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:07:38<?, ?it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2987/4895 [1:07:11<49:32,  1.56s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:07:45<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_104 (26 files)

💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2988/4895 [1:07:12<46:38,  1.47s/it]


💽 TQM COPY FLOW:  61%|██████████████████████▌              | 2989/4895 [1:07:16<1:08:34,  2.16s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2990/4895 [1:07:17<58:59,  1.86s/it]


💽 TQM COPY FLOW:  61%|██████████████████████▌              | 2991/4895 [1:07:20<1:10:04,  2.21s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2992/4895 [1:07:21<56:12,  1.77s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2993/4895 [1:07:22<49:03,  1.55s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2994/4895 [1:07:23<40:32,  1.28s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2995/4895 [1:07:24<38:30,  1.22s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▊               | 2996/4895 [1:07:25<37:18,  1.18s/it]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 2997/4895 [1:07:25<29:38,  1.07it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 2998/4895 [1:07:25<23:39,  1.34it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 2999/4895 [1:07:26<19:54,  1.59it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3000/4895 [1:07:26<18:08,  1.74it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3001/4895 [1:07:27<17:27,  1.81it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3002/4895 [1:07:27<16:24,  1.92it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:13:26<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:07:55<?, ?it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3003/4895 [1:07:28<15:42,  2.01it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:08:01<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_105 (16 files)

💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3004/4895 [1:07:28<15:27,  2.04it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3005/4895 [1:07:29<20:39,  1.53it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3006/4895 [1:07:30<20:35,  1.53it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3007/4895 [1:07:30<19:32,  1.61it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3008/4895 [1:07:31<24:20,  1.29it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3009/4895 [1:07:32<22:51,  1.38it/s]


💽 TQM COPY FLOW:  61%|███████████████████████▉               | 3010/4895 [1:07:32<19:56,  1.58it/s]


💽 TQM COPY FLOW:  62%|███████████████████████▉               | 3011/4895 [1:07:33<18:57,  1.66it/s]


💽 TQM COPY FLOW:  62%|███████████████████████▉               | 3012/4895 [1:07:33<17:10,  1.83it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3013/4895 [1:07:34<16:38,  1.88it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3014/4895 [1:07:35<20:46,  1.51it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3015/4895 [1:07:36<25:40,  1.22it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3016/4895 [1:07:37<30:09,  1.04it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3017/4895 [1:07:39<40:19,  1.29s/it]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3018/4895 [1:07:41<42:48,  1.37s/it]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3019/4895 [1:07:42<36:18,  1.16s/it]


💽 TQM COPY FLOW:  62%|██████████████████████▊              | 3020/4895 [1:07:45<1:01:10,  1.96s/it]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3021/4895 [1:07:46<51:03,  1.63s/it]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3022/4895 [1:07:47<40:22,  1.29s/it]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3023/4895 [1:07:47<31:08,  1.00it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3024/4895 [1:07:48<27:41,  1.13it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3025/4895 [1:07:48<22:51,  1.36it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3026/4895 [1:07:49<20:01,  1.56it/s]


💽 TQM COPY FLOW:  62%|████████████████████████               | 3027/4895 [1:07:50<23:31,  1.32it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3028/4895 [1:07:50<21:39,  1.44it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3029/4895 [1:07:51<22:33,  1.38it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3030/4895 [1:07:52<24:16,  1.28it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3031/4895 [1:07:52<20:06,  1.55it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3032/4895 [1:07:53<16:49,  1.85it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3033/4895 [1:07:54<25:24,  1.22it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3034/4895 [1:07:54<22:16,  1.39it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3035/4895 [1:07:55<22:20,  1.39it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3036/4895 [1:07:56<26:03,  1.19it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3037/4895 [1:07:58<30:27,  1.02it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3038/4895 [1:07:59<35:02,  1.13s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3039/4895 [1:08:00<30:42,  1.01it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3040/4895 [1:08:00<24:00,  1.29it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3041/4895 [1:08:01<23:01,  1.34it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3042/4895 [1:08:02<24:43,  1.25it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▏              | 3043/4895 [1:08:03<27:10,  1.14it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3044/4895 [1:08:04<34:08,  1.11s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3045/4895 [1:08:06<43:26,  1.41s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3046/4895 [1:08:08<47:14,  1.53s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3047/4895 [1:08:09<35:58,  1.17s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3048/4895 [1:08:09<29:49,  1.03it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3049/4895 [1:08:10<28:59,  1.06it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3050/4895 [1:08:11<26:00,  1.18it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3051/4895 [1:08:11<24:20,  1.26it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3052/4895 [1:08:12<22:02,  1.39it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:14:10<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:08:40<?, ?it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3053/4895 [1:08:12<19:10,  1.60it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:08:46<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_106 (50 files)

💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3054/4895 [1:08:14<29:52,  1.03it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3055/4895 [1:08:15<28:18,  1.08it/s]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3056/4895 [1:08:16<34:23,  1.12s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3057/4895 [1:08:17<31:50,  1.04s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3058/4895 [1:08:19<38:01,  1.24s/it]


💽 TQM COPY FLOW:  62%|████████████████████████▎              | 3059/4895 [1:08:20<34:44,  1.14s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3060/4895 [1:08:20<27:04,  1.13it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3061/4895 [1:08:21<24:05,  1.27it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3062/4895 [1:08:22<29:00,  1.05it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3063/4895 [1:08:23<29:42,  1.03it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3064/4895 [1:08:24<31:22,  1.03s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3065/4895 [1:08:25<31:07,  1.02s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3066/4895 [1:08:26<31:10,  1.02s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3067/4895 [1:08:27<27:27,  1.11it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3068/4895 [1:08:27<23:58,  1.27it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3069/4895 [1:08:28<24:03,  1.26it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3070/4895 [1:08:29<24:53,  1.22it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3071/4895 [1:08:30<21:34,  1.41it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3072/4895 [1:08:30<19:29,  1.56it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3073/4895 [1:08:31<18:07,  1.67it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3074/4895 [1:08:34<40:04,  1.32s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▍              | 3075/4895 [1:08:37<58:31,  1.93s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3076/4895 [1:08:37<44:36,  1.47s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3077/4895 [1:08:38<37:49,  1.25s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3078/4895 [1:08:40<40:09,  1.33s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3079/4895 [1:08:40<36:45,  1.21s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▎             | 3080/4895 [1:08:48<1:34:03,  3.11s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▎             | 3081/4895 [1:08:49<1:10:31,  2.33s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3082/4895 [1:08:49<53:11,  1.76s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3083/4895 [1:08:49<41:45,  1.38s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3084/4895 [1:08:50<34:24,  1.14s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3085/4895 [1:08:53<52:58,  1.76s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3086/4895 [1:08:53<39:36,  1.31s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3087/4895 [1:08:54<29:32,  1.02it/s]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3088/4895 [1:08:57<46:14,  1.54s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3089/4895 [1:08:59<50:20,  1.67s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▌              | 3090/4895 [1:09:01<58:23,  1.94s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▎             | 3091/4895 [1:09:03<1:01:49,  2.06s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▎             | 3092/4895 [1:09:07<1:18:40,  2.62s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▋              | 3093/4895 [1:09:08<59:06,  1.97s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3094/4895 [1:09:11<1:14:05,  2.47s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3095/4895 [1:09:16<1:29:05,  2.97s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3096/4895 [1:09:19<1:29:14,  2.98s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3097/4895 [1:09:19<1:05:59,  2.20s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3098/4895 [1:09:21<1:00:33,  2.02s/it]


💽 TQM COPY FLOW:  63%|████████████████████████▋              | 3099/4895 [1:09:22<53:57,  1.80s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3100/4895 [1:09:25<1:06:59,  2.24s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3101/4895 [1:09:27<1:03:49,  2.13s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3102/4895 [1:09:30<1:14:50,  2.50s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:15:30<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:10:00<?, ?it/s]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3103/4895 [1:09:32<1:11:17,  2.39s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:10:06<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_107 (50 files)

💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3104/4895 [1:09:35<1:09:49,  2.34s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3105/4895 [1:09:40<1:32:28,  3.10s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3106/4895 [1:09:42<1:23:03,  2.79s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3107/4895 [1:09:44<1:20:08,  2.69s/it]


💽 TQM COPY FLOW:  63%|███████████████████████▍             | 3108/4895 [1:09:51<2:02:08,  4.10s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3109/4895 [1:09:52<1:34:13,  3.17s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3110/4895 [1:09:53<1:09:58,  2.35s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3111/4895 [1:09:59<1:39:07,  3.33s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3112/4895 [1:09:59<1:15:46,  2.55s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3113/4895 [1:10:02<1:13:25,  2.47s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3114/4895 [1:10:05<1:18:35,  2.65s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3115/4895 [1:10:07<1:16:04,  2.56s/it]


💽 TQM COPY FLOW:  64%|████████████████████████▊              | 3116/4895 [1:10:08<59:54,  2.02s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3117/4895 [1:10:12<1:22:35,  2.79s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3118/4895 [1:10:15<1:19:22,  2.68s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3119/4895 [1:10:18<1:27:14,  2.95s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3120/4895 [1:10:19<1:06:21,  2.24s/it]


💽 TQM COPY FLOW:  64%|████████████████████████▊              | 3121/4895 [1:10:20<52:37,  1.78s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3122/4895 [1:10:24<1:15:14,  2.55s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3123/4895 [1:10:27<1:15:55,  2.57s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3124/4895 [1:10:30<1:23:43,  2.84s/it]


💽 TQM COPY FLOW:  64%|███████████████████████▌             | 3125/4895 [1:10:30<1:02:06,  2.11s/it]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3126/4895 [1:10:31<47:40,  1.62s/it]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3127/4895 [1:10:31<36:04,  1.22s/it]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3128/4895 [1:10:31<27:15,  1.08it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3129/4895 [1:10:32<22:45,  1.29it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3130/4895 [1:10:32<19:20,  1.52it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3131/4895 [1:10:33<18:20,  1.60it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3132/4895 [1:10:33<16:08,  1.82it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3133/4895 [1:10:34<15:41,  1.87it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3134/4895 [1:10:34<15:12,  1.93it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3135/4895 [1:10:34<13:33,  2.16it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3136/4895 [1:10:35<14:09,  2.07it/s]


💽 TQM COPY FLOW:  64%|████████████████████████▉              | 3137/4895 [1:10:35<12:58,  2.26it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3138/4895 [1:10:36<11:22,  2.57it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3139/4895 [1:10:36<11:09,  2.62it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3140/4895 [1:10:36<11:38,  2.51it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3141/4895 [1:10:39<30:40,  1.05s/it]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3142/4895 [1:10:41<34:47,  1.19s/it]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3143/4895 [1:10:41<27:25,  1.06it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3144/4895 [1:10:41<22:58,  1.27it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3145/4895 [1:10:43<33:11,  1.14s/it]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3146/4895 [1:10:44<27:19,  1.07it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3147/4895 [1:10:44<23:24,  1.24it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3148/4895 [1:10:45<20:10,  1.44it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3149/4895 [1:10:45<21:25,  1.36it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3150/4895 [1:10:46<20:03,  1.45it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3151/4895 [1:10:49<37:39,  1.30s/it]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3152/4895 [1:10:49<31:08,  1.07s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:16:48<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:11:17<?, ?it/s]


💽 TQM COPY FLOW:  64%|█████████████████████████              | 3153/4895 [1:10:50<24:52,  1.17it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:11:23<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_108 (50 files)

💽 TQM COPY FLOW:  64%|█████████████████████████▏             | 3154/4895 [1:10:51<31:31,  1.09s/it]


💽 TQM COPY FLOW:  64%|█████████████████████████▏             | 3155/4895 [1:10:55<57:18,  1.98s/it]


💽 TQM COPY FLOW:  64%|█████████████████████████▏             | 3156/4895 [1:10:56<49:23,  1.70s/it]


💽 TQM COPY FLOW:  64%|█████████████████████████▏             | 3157/4895 [1:10:58<44:46,  1.55s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3158/4895 [1:10:58<36:06,  1.25s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3159/4895 [1:10:59<30:42,  1.06s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3160/4895 [1:10:59<25:22,  1.14it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3161/4895 [1:11:00<23:46,  1.22it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3162/4895 [1:11:00<21:04,  1.37it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3163/4895 [1:11:02<25:19,  1.14it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3164/4895 [1:11:05<45:35,  1.58s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3165/4895 [1:11:06<37:49,  1.31s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▏             | 3166/4895 [1:11:09<54:13,  1.88s/it]


💽 TQM COPY FLOW:  65%|███████████████████████▉             | 3167/4895 [1:11:12<1:01:30,  2.14s/it]


💽 TQM COPY FLOW:  65%|███████████████████████▉             | 3168/4895 [1:11:16<1:19:59,  2.78s/it]


💽 TQM COPY FLOW:  65%|███████████████████████▉             | 3169/4895 [1:11:17<1:03:04,  2.19s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3170/4895 [1:11:17<49:12,  1.71s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3171/4895 [1:11:17<36:00,  1.25s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3172/4895 [1:11:18<29:59,  1.04s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3173/4895 [1:11:18<23:01,  1.25it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3174/4895 [1:11:19<20:16,  1.41it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3175/4895 [1:11:19<17:46,  1.61it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3176/4895 [1:11:19<14:58,  1.91it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3177/4895 [1:11:20<12:55,  2.22it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3178/4895 [1:11:20<11:23,  2.51it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3179/4895 [1:11:22<21:58,  1.30it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3180/4895 [1:11:23<25:14,  1.13it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3181/4895 [1:11:23<19:07,  1.49it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3182/4895 [1:11:23<16:28,  1.73it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3183/4895 [1:11:24<16:41,  1.71it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▎             | 3184/4895 [1:11:25<17:47,  1.60it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3185/4895 [1:11:25<16:11,  1.76it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3186/4895 [1:11:26<22:42,  1.25it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3187/4895 [1:11:27<21:35,  1.32it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3188/4895 [1:11:28<22:37,  1.26it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3189/4895 [1:11:28<20:09,  1.41it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3190/4895 [1:11:29<17:48,  1.60it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3191/4895 [1:11:29<17:46,  1.60it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3192/4895 [1:11:30<18:55,  1.50it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3193/4895 [1:11:33<35:50,  1.26s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3194/4895 [1:11:34<38:52,  1.37s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3195/4895 [1:11:38<54:28,  1.92s/it]


💽 TQM COPY FLOW:  65%|████████████████████████▏            | 3196/4895 [1:11:41<1:10:13,  2.48s/it]


💽 TQM COPY FLOW:  65%|████████████████████████▏            | 3197/4895 [1:11:44<1:06:51,  2.36s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3198/4895 [1:11:45<54:58,  1.94s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3199/4895 [1:11:45<43:15,  1.53s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▍             | 3200/4895 [1:11:46<34:42,  1.23s/it]


💽 TQM COPY FLOW:  65%|█████████████████████████▌             | 3201/4895 [1:11:46<28:03,  1.01it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▌             | 3202/4895 [1:11:46<22:53,  1.23it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:17:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:12:14<?, ?it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▌             | 3203/4895 [1:11:47<18:31,  1.52it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:12:20<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_109 (50 files)

💽 TQM COPY FLOW:  65%|█████████████████████████▌             | 3204/4895 [1:11:47<19:08,  1.47it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▌             | 3205/4895 [1:11:49<23:42,  1.19it/s]


💽 TQM COPY FLOW:  65%|█████████████████████████▌             | 3206/4895 [1:11:49<21:06,  1.33it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3207/4895 [1:11:50<20:40,  1.36it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3208/4895 [1:11:51<19:35,  1.44it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3209/4895 [1:11:51<18:46,  1.50it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3210/4895 [1:11:52<20:14,  1.39it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3211/4895 [1:11:54<32:22,  1.15s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3212/4895 [1:11:54<24:14,  1.16it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3213/4895 [1:11:56<33:33,  1.20s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3214/4895 [1:11:57<27:42,  1.01it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3215/4895 [1:11:59<38:24,  1.37s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▌             | 3216/4895 [1:12:00<32:18,  1.15s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3217/4895 [1:12:02<38:22,  1.37s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3218/4895 [1:12:04<46:41,  1.67s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3219/4895 [1:12:05<38:02,  1.36s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:18:06<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:12:35<?, ?it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3220/4895 [1:12:08<54:44,  1.96s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:12:42<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_110 (17 files)

💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3221/4895 [1:12:10<56:14,  2.02s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3222/4895 [1:12:11<44:02,  1.58s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3223/4895 [1:12:11<34:39,  1.24s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3224/4895 [1:12:12<27:59,  1.01s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3225/4895 [1:12:15<45:26,  1.63s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3226/4895 [1:12:15<36:48,  1.32s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3227/4895 [1:12:16<30:00,  1.08s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3228/4895 [1:12:20<56:33,  2.04s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3229/4895 [1:12:21<50:06,  1.80s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3230/4895 [1:12:23<45:17,  1.63s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▋             | 3231/4895 [1:12:23<37:13,  1.34s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3232/4895 [1:12:24<33:56,  1.22s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3233/4895 [1:12:25<29:56,  1.08s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3234/4895 [1:12:26<27:28,  1.01it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3235/4895 [1:12:27<27:38,  1.00it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3236/4895 [1:12:28<27:53,  1.01s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3237/4895 [1:12:29<29:05,  1.05s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3238/4895 [1:12:31<40:25,  1.46s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3239/4895 [1:12:33<41:29,  1.50s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3240/4895 [1:12:33<33:17,  1.21s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3241/4895 [1:12:34<28:38,  1.04s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3242/4895 [1:12:35<23:22,  1.18it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3243/4895 [1:12:35<24:17,  1.13it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3244/4895 [1:12:36<22:08,  1.24it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3245/4895 [1:12:39<40:20,  1.47s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3246/4895 [1:12:42<48:55,  1.78s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▊             | 3247/4895 [1:12:42<36:41,  1.34s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3248/4895 [1:12:43<30:50,  1.12s/it]


💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3249/4895 [1:12:43<27:06,  1.01it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3250/4895 [1:12:44<25:36,  1.07it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3251/4895 [1:12:45<23:09,  1.18it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3252/4895 [1:12:45<21:46,  1.26it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3253/4895 [1:12:49<45:35,  1.67s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:18:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:13:19<?, ?it/s]


💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3254/4895 [1:12:52<52:30,  1.92s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:13:25<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_111 (34 files)

💽 TQM COPY FLOW:  66%|█████████████████████████▉             | 3255/4895 [1:12:54<53:43,  1.97s/it]


💽 TQM COPY FLOW:  67%|█████████████████████████▉             | 3256/4895 [1:12:55<45:05,  1.65s/it]


💽 TQM COPY FLOW:  67%|█████████████████████████▉             | 3257/4895 [1:12:55<37:47,  1.38s/it]


💽 TQM COPY FLOW:  67%|█████████████████████████▉             | 3258/4895 [1:12:56<32:06,  1.18s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3259/4895 [1:13:03<1:23:15,  3.05s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3260/4895 [1:13:04<1:06:44,  2.45s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3261/4895 [1:13:08<1:15:40,  2.78s/it]


💽 TQM COPY FLOW:  67%|█████████████████████████▉             | 3262/4895 [1:13:09<59:57,  2.20s/it]


💽 TQM COPY FLOW:  67%|█████████████████████████▉             | 3263/4895 [1:13:09<44:52,  1.65s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3264/4895 [1:13:14<1:08:49,  2.53s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3265/4895 [1:13:17<1:11:41,  2.64s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3266/4895 [1:13:19<1:10:20,  2.59s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3267/4895 [1:13:24<1:29:57,  3.32s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:19:23<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:13:52<?, ?it/s]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3268/4895 [1:13:25<1:09:15,  2.55s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:13:59<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_112 (14 files)

💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3269/4895 [1:13:30<1:28:23,  3.26s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3270/4895 [1:13:30<1:03:45,  2.35s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████             | 3271/4895 [1:13:31<49:47,  1.84s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████             | 3272/4895 [1:13:31<37:43,  1.39s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████             | 3273/4895 [1:13:32<30:32,  1.13s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▋            | 3274/4895 [1:13:36<1:00:15,  2.23s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████             | 3275/4895 [1:13:37<45:26,  1.68s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████             | 3276/4895 [1:13:39<49:23,  1.83s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████             | 3277/4895 [1:13:39<37:56,  1.41s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████             | 3278/4895 [1:13:42<49:51,  1.85s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▊            | 3279/4895 [1:13:46<1:01:48,  2.29s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▊            | 3280/4895 [1:13:50<1:17:14,  2.87s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3281/4895 [1:13:50<58:07,  2.16s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▊            | 3282/4895 [1:13:56<1:22:19,  3.06s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▊            | 3283/4895 [1:14:00<1:30:21,  3.36s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▊            | 3284/4895 [1:14:02<1:22:49,  3.08s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▊            | 3285/4895 [1:14:03<1:03:30,  2.37s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3286/4895 [1:14:04<51:10,  1.91s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3287/4895 [1:14:04<40:18,  1.50s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3288/4895 [1:14:05<34:11,  1.28s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3289/4895 [1:14:06<29:09,  1.09s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3290/4895 [1:14:07<28:30,  1.07s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3291/4895 [1:14:10<49:27,  1.85s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▉            | 3292/4895 [1:14:15<1:13:48,  2.76s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▏            | 3293/4895 [1:14:16<57:03,  2.14s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▉            | 3294/4895 [1:14:22<1:29:41,  3.36s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▉            | 3295/4895 [1:14:23<1:12:13,  2.71s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3296/4895 [1:14:24<57:17,  2.15s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3297/4895 [1:14:25<48:28,  1.82s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3298/4895 [1:14:26<44:46,  1.68s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3299/4895 [1:14:27<36:30,  1.37s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3300/4895 [1:14:28<34:16,  1.29s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3301/4895 [1:14:32<58:04,  2.19s/it]


💽 TQM COPY FLOW:  67%|████████████████████████▉            | 3302/4895 [1:14:36<1:09:44,  2.63s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3303/4895 [1:14:37<57:54,  2.18s/it]


💽 TQM COPY FLOW:  67%|██████████████████████████▎            | 3304/4895 [1:14:38<45:48,  1.73s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▎            | 3305/4895 [1:14:39<41:40,  1.57s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▎            | 3306/4895 [1:14:40<35:33,  1.34s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▎            | 3307/4895 [1:14:41<33:49,  1.28s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▎            | 3308/4895 [1:14:45<52:12,  1.97s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▎            | 3309/4895 [1:14:45<42:03,  1.59s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▎            | 3310/4895 [1:14:47<43:44,  1.66s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████            | 3311/4895 [1:14:54<1:24:37,  3.21s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████            | 3312/4895 [1:14:56<1:17:17,  2.93s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████            | 3313/4895 [1:14:59<1:19:16,  3.01s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████            | 3314/4895 [1:15:03<1:22:20,  3.12s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████            | 3315/4895 [1:15:03<1:01:12,  2.32s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3316/4895 [1:15:04<48:58,  1.86s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3317/4895 [1:15:05<40:04,  1.52s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:21:03<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:15:33<?, ?it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3318/4895 [1:15:06<33:29,  1.27s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:15:39<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_113 (50 files)

💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3319/4895 [1:15:10<55:55,  2.13s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3320/4895 [1:15:10<42:53,  1.63s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3321/4895 [1:15:13<54:50,  2.09s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3322/4895 [1:15:14<43:30,  1.66s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3323/4895 [1:15:17<51:15,  1.96s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3324/4895 [1:15:17<40:10,  1.53s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3325/4895 [1:15:18<31:56,  1.22s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▍            | 3326/4895 [1:15:18<25:47,  1.01it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3327/4895 [1:15:19<23:22,  1.12it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3328/4895 [1:15:19<20:24,  1.28it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3329/4895 [1:15:19<15:08,  1.72it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3330/4895 [1:15:20<12:46,  2.04it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3331/4895 [1:15:20<14:29,  1.80it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3332/4895 [1:15:21<12:13,  2.13it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3333/4895 [1:15:21<15:07,  1.72it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3334/4895 [1:15:23<18:47,  1.38it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3335/4895 [1:15:23<18:50,  1.38it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3336/4895 [1:15:24<22:29,  1.16it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3337/4895 [1:15:25<23:06,  1.12it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3338/4895 [1:15:29<41:27,  1.60s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3339/4895 [1:15:32<53:46,  2.07s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▌            | 3340/4895 [1:15:32<41:27,  1.60s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████▎           | 3341/4895 [1:15:40<1:28:50,  3.43s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████▎           | 3342/4895 [1:15:41<1:05:47,  2.54s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████▎           | 3343/4895 [1:15:44<1:11:50,  2.78s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████▎           | 3344/4895 [1:15:46<1:10:55,  2.74s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████▎           | 3345/4895 [1:15:49<1:08:28,  2.65s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▋            | 3346/4895 [1:15:50<52:38,  2.04s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:21:48<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:16:18<?, ?it/s]


💽 TQM COPY FLOW:  68%|██████████████████████████▋            | 3347/4895 [1:15:50<43:10,  1.67s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:16:24<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_114 (29 files)

💽 TQM COPY FLOW:  68%|█████████████████████████▎           | 3348/4895 [1:15:56<1:16:56,  2.98s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▋            | 3349/4895 [1:15:57<58:54,  2.29s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▋            | 3350/4895 [1:15:58<45:01,  1.75s/it]


💽 TQM COPY FLOW:  68%|█████████████████████████▎           | 3351/4895 [1:16:03<1:10:26,  2.74s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▋            | 3352/4895 [1:16:03<54:02,  2.10s/it]


💽 TQM COPY FLOW:  68%|██████████████████████████▋            | 3353/4895 [1:16:04<42:24,  1.65s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▎           | 3354/4895 [1:16:09<1:12:25,  2.82s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▎           | 3355/4895 [1:16:13<1:16:15,  2.97s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▎           | 3356/4895 [1:16:17<1:26:10,  3.36s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▎           | 3357/4895 [1:16:21<1:32:44,  3.62s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3358/4895 [1:16:28<1:53:37,  4.44s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3359/4895 [1:16:29<1:27:09,  3.40s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3360/4895 [1:16:29<1:06:41,  2.61s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3361/4895 [1:16:34<1:22:34,  3.23s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3362/4895 [1:16:38<1:25:33,  3.35s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3363/4895 [1:16:39<1:08:30,  2.68s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3364/4895 [1:16:44<1:25:12,  3.34s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3365/4895 [1:16:44<1:04:53,  2.55s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3366/4895 [1:16:49<1:23:58,  3.30s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3367/4895 [1:16:55<1:39:16,  3.90s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3368/4895 [1:16:55<1:15:39,  2.97s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3369/4895 [1:16:58<1:15:35,  2.97s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▊            | 3370/4895 [1:16:59<58:48,  2.31s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3371/4895 [1:17:03<1:09:14,  2.73s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▍           | 3372/4895 [1:17:06<1:10:16,  2.77s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▊            | 3373/4895 [1:17:06<54:49,  2.16s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▌           | 3374/4895 [1:17:11<1:15:37,  2.98s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▌           | 3375/4895 [1:17:13<1:01:37,  2.43s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3376/4895 [1:17:14<51:27,  2.03s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3377/4895 [1:17:15<46:32,  1.84s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:23:15<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:17:44<?, ?it/s]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3378/4895 [1:17:17<46:55,  1.86s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:17:51<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_115 (31 files)

💽 TQM COPY FLOW:  69%|█████████████████████████▌           | 3379/4895 [1:17:25<1:32:06,  3.65s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▌           | 3380/4895 [1:17:26<1:13:03,  2.89s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3381/4895 [1:17:27<56:11,  2.23s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▌           | 3382/4895 [1:17:32<1:20:27,  3.19s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▌           | 3383/4895 [1:17:33<1:02:08,  2.47s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3384/4895 [1:17:33<46:27,  1.84s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3385/4895 [1:17:35<45:45,  1.82s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3386/4895 [1:17:36<37:25,  1.49s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3387/4895 [1:17:36<28:59,  1.15s/it]


💽 TQM COPY FLOW:  69%|██████████████████████████▉            | 3388/4895 [1:17:37<26:23,  1.05s/it]


💽 TQM COPY FLOW:  69%|███████████████████████████            | 3389/4895 [1:17:40<40:22,  1.61s/it]


💽 TQM COPY FLOW:  69%|███████████████████████████            | 3390/4895 [1:17:40<29:09,  1.16s/it]


💽 TQM COPY FLOW:  69%|███████████████████████████            | 3391/4895 [1:17:43<41:22,  1.65s/it]


💽 TQM COPY FLOW:  69%|███████████████████████████            | 3392/4895 [1:17:47<58:24,  2.33s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3393/4895 [1:17:49<1:01:50,  2.47s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3394/4895 [1:17:55<1:26:58,  3.48s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3395/4895 [1:17:56<1:09:02,  2.76s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:23:59<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:18:29<?, ?it/s]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3396/4895 [1:18:02<1:27:56,  3.52s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:18:35<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_116 (18 files)

💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3397/4895 [1:18:05<1:29:50,  3.60s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3398/4895 [1:18:11<1:44:08,  4.17s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3399/4895 [1:18:15<1:40:15,  4.02s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3400/4895 [1:18:19<1:45:00,  4.21s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3401/4895 [1:18:23<1:41:49,  4.09s/it]


💽 TQM COPY FLOW:  69%|█████████████████████████▋           | 3402/4895 [1:18:26<1:33:13,  3.75s/it]


💽 TQM COPY FLOW:  70%|█████████████████████████▋           | 3403/4895 [1:18:27<1:10:50,  2.85s/it]


💽 TQM COPY FLOW:  70%|█████████████████████████▋           | 3404/4895 [1:18:30<1:11:01,  2.86s/it]


💽 TQM COPY FLOW:  70%|█████████████████████████▋           | 3405/4895 [1:18:32<1:11:29,  2.88s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3406/4895 [1:18:33<55:09,  2.22s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3407/4895 [1:18:33<40:36,  1.64s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3408/4895 [1:18:34<30:40,  1.24s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3409/4895 [1:18:35<34:25,  1.39s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3410/4895 [1:18:39<49:06,  1.98s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3411/4895 [1:18:41<48:02,  1.94s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3412/4895 [1:18:42<39:37,  1.60s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3413/4895 [1:18:43<41:38,  1.69s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3414/4895 [1:18:45<42:31,  1.72s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:24:47<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:19:17<?, ?it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▏           | 3415/4895 [1:18:49<59:57,  2.43s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:19:23<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_117 (19 files)

💽 TQM COPY FLOW:  70%|█████████████████████████▊           | 3416/4895 [1:18:52<1:05:30,  2.66s/it]


💽 TQM COPY FLOW:  70%|█████████████████████████▊           | 3417/4895 [1:18:54<1:00:23,  2.45s/it]


💽 TQM COPY FLOW:  70%|█████████████████████████▊           | 3418/4895 [1:18:59<1:14:02,  3.01s/it]


💽 TQM COPY FLOW:  70%|█████████████████████████▊           | 3419/4895 [1:19:01<1:06:16,  2.69s/it]


💽 TQM COPY FLOW:  70%|█████████████████████████▊           | 3420/4895 [1:19:03<1:01:57,  2.52s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:25:01<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:19:31<?, ?it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3421/4895 [1:19:03<47:34,  1.94s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:19:37<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_118 (6 files)

💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3422/4895 [1:19:04<39:00,  1.59s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3423/4895 [1:19:07<51:38,  2.10s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3424/4895 [1:19:08<39:19,  1.60s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3425/4895 [1:19:09<31:50,  1.30s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3426/4895 [1:19:09<26:56,  1.10s/it]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3427/4895 [1:19:10<23:16,  1.05it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3428/4895 [1:19:10<19:50,  1.23it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3429/4895 [1:19:11<16:20,  1.49it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3430/4895 [1:19:11<13:13,  1.85it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3431/4895 [1:19:11<10:49,  2.25it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3432/4895 [1:19:12<11:38,  2.09it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3433/4895 [1:19:12<11:08,  2.19it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3434/4895 [1:19:12<10:37,  2.29it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▎           | 3435/4895 [1:19:13<11:23,  2.14it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3436/4895 [1:19:14<12:12,  1.99it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3437/4895 [1:19:14<11:25,  2.13it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3438/4895 [1:19:14<11:52,  2.04it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3439/4895 [1:19:15<11:54,  2.04it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3440/4895 [1:19:15<12:20,  1.96it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3441/4895 [1:19:17<16:03,  1.51it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3442/4895 [1:19:18<18:47,  1.29it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3443/4895 [1:19:18<16:15,  1.49it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3444/4895 [1:19:18<15:05,  1.60it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3445/4895 [1:19:19<12:14,  1.98it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3446/4895 [1:19:19<13:06,  1.84it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3447/4895 [1:19:20<14:02,  1.72it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3448/4895 [1:19:20<12:57,  1.86it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3449/4895 [1:19:21<10:52,  2.22it/s]


💽 TQM COPY FLOW:  70%|███████████████████████████▍           | 3450/4895 [1:19:23<22:06,  1.09it/s]


💽 TQM COPY FLOW:  71%|███████████████████████████▍           | 3451/4895 [1:19:27<47:27,  1.97s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████           | 3452/4895 [1:19:34<1:21:55,  3.41s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████           | 3453/4895 [1:19:38<1:23:41,  3.48s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████           | 3454/4895 [1:19:41<1:20:13,  3.34s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████           | 3455/4895 [1:19:44<1:19:58,  3.33s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▌           | 3456/4895 [1:19:44<59:58,  2.50s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▌           | 3457/4895 [1:19:45<46:52,  1.96s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▌           | 3458/4895 [1:19:46<37:16,  1.56s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▌           | 3459/4895 [1:19:49<46:48,  1.96s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▌           | 3460/4895 [1:19:52<59:48,  2.50s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3461/4895 [1:19:57<1:15:20,  3.15s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3462/4895 [1:19:59<1:09:13,  2.90s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3463/4895 [1:20:02<1:09:03,  2.89s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3464/4895 [1:20:06<1:17:02,  3.23s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:26:05<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:20:35<?, ?it/s]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3465/4895 [1:20:07<1:01:38,  2.59s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:20:41<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_119 (44 files)

💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3466/4895 [1:20:13<1:21:16,  3.41s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3467/4895 [1:20:18<1:33:03,  3.91s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3468/4895 [1:20:23<1:40:02,  4.21s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3469/4895 [1:20:27<1:43:03,  4.34s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3470/4895 [1:20:32<1:46:45,  4.49s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3471/4895 [1:20:37<1:48:08,  4.56s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▏          | 3472/4895 [1:20:42<1:51:08,  4.69s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3473/4895 [1:20:46<1:50:08,  4.65s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3474/4895 [1:20:48<1:25:08,  3.59s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:26:48<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:21:17<?, ?it/s]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3475/4895 [1:20:50<1:15:09,  3.18s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:21:23<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_120 (10 files)

💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3476/4895 [1:20:53<1:14:03,  3.13s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3477/4895 [1:20:55<1:05:58,  2.79s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:26:58<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:21:28<?, ?it/s]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3478/4895 [1:21:00<1:25:38,  3.63s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:21:34<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_121 (3 files)

💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3479/4895 [1:21:07<1:43:40,  4.39s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3480/4895 [1:21:08<1:24:38,  3.59s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:27:09<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:21:38<?, ?it/s]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3481/4895 [1:21:11<1:15:45,  3.21s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:21:44<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_122 (3 files)

💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3482/4895 [1:21:12<1:05:03,  2.76s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3483/4895 [1:21:17<1:17:36,  3.30s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▊           | 3484/4895 [1:21:18<59:26,  2.53s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3485/4895 [1:21:21<1:03:16,  2.69s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3486/4895 [1:21:25<1:16:16,  3.25s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▊           | 3487/4895 [1:21:26<57:25,  2.45s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3488/4895 [1:21:31<1:16:31,  3.26s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▎          | 3489/4895 [1:21:36<1:29:26,  3.82s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▍          | 3490/4895 [1:21:37<1:09:20,  2.96s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▊           | 3491/4895 [1:21:38<54:45,  2.34s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▊           | 3492/4895 [1:21:39<43:13,  1.85s/it]


💽 TQM COPY FLOW:  71%|███████████████████████████▊           | 3493/4895 [1:21:43<59:54,  2.56s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▍          | 3494/4895 [1:21:49<1:21:45,  3.50s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:27:47<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:22:17<?, ?it/s]


💽 TQM COPY FLOW:  71%|██████████████████████████▍          | 3495/4895 [1:21:49<1:01:53,  2.65s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:22:23<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_123 (14 files)

💽 TQM COPY FLOW:  71%|██████████████████████████▍          | 3496/4895 [1:21:55<1:26:23,  3.71s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▍          | 3497/4895 [1:22:00<1:30:37,  3.89s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▍          | 3498/4895 [1:22:04<1:30:40,  3.89s/it]


💽 TQM COPY FLOW:  71%|██████████████████████████▍          | 3499/4895 [1:22:07<1:29:30,  3.85s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▍          | 3500/4895 [1:22:11<1:27:03,  3.74s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:28:13<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:22:42<?, ?it/s]


💽 TQM COPY FLOW:  72%|██████████████████████████▍          | 3501/4895 [1:22:15<1:27:54,  3.78s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:22:48<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_124 (6 files)

💽 TQM COPY FLOW:  72%|██████████████████████████▍          | 3502/4895 [1:22:19<1:29:22,  3.85s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▍          | 3503/4895 [1:22:24<1:36:31,  4.16s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▍          | 3504/4895 [1:22:28<1:35:16,  4.11s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▍          | 3505/4895 [1:22:30<1:23:08,  3.59s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▌          | 3506/4895 [1:22:30<1:01:30,  2.66s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▌          | 3507/4895 [1:22:34<1:05:26,  2.83s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▌          | 3508/4895 [1:22:37<1:07:22,  2.91s/it]


💽 TQM COPY FLOW:  72%|███████████████████████████▉           | 3509/4895 [1:22:37<48:57,  2.12s/it]


💽 TQM COPY FLOW:  72%|███████████████████████████▉           | 3510/4895 [1:22:38<42:33,  1.84s/it]


💽 TQM COPY FLOW:  72%|███████████████████████████▉           | 3511/4895 [1:22:41<50:48,  2.20s/it]


💽 TQM COPY FLOW:  72%|███████████████████████████▉           | 3512/4895 [1:22:42<40:14,  1.75s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:28:42<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:23:11<?, ?it/s]


💽 TQM COPY FLOW:  72%|███████████████████████████▉           | 3513/4895 [1:22:44<41:25,  1.80s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:23:18<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_125 (12 files)

💽 TQM COPY FLOW:  72%|███████████████████████████▉           | 3514/4895 [1:22:44<30:56,  1.34s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3515/4895 [1:22:45<29:44,  1.29s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3516/4895 [1:22:46<26:45,  1.16s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3517/4895 [1:22:50<41:35,  1.81s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3518/4895 [1:22:54<57:58,  2.53s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:28:52<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:23:22<?, ?it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3519/4895 [1:22:54<43:28,  1.90s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:23:28<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_126 (6 files)

💽 TQM COPY FLOW:  72%|████████████████████████████           | 3520/4895 [1:22:55<34:36,  1.51s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3521/4895 [1:22:56<34:55,  1.52s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3522/4895 [1:23:00<47:28,  2.07s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3523/4895 [1:23:02<51:08,  2.24s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▋          | 3524/4895 [1:23:06<1:02:47,  2.75s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▋          | 3525/4895 [1:23:12<1:22:46,  3.62s/it]


💽 TQM COPY FLOW:  72%|██████████████████████████▋          | 3526/4895 [1:23:13<1:03:42,  2.79s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3527/4895 [1:23:14<53:32,  2.35s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3528/4895 [1:23:15<45:31,  2.00s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3529/4895 [1:23:16<40:03,  1.76s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████           | 3530/4895 [1:23:18<37:34,  1.65s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3531/4895 [1:23:19<31:08,  1.37s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3532/4895 [1:23:20<29:44,  1.31s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3533/4895 [1:23:21<26:30,  1.17s/it]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3534/4895 [1:23:21<21:40,  1.05it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3535/4895 [1:23:22<20:39,  1.10it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3536/4895 [1:23:22<18:41,  1.21it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3537/4895 [1:23:23<15:12,  1.49it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3538/4895 [1:23:23<14:40,  1.54it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3539/4895 [1:23:24<13:03,  1.73it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3540/4895 [1:23:24<10:07,  2.23it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3541/4895 [1:23:24<10:26,  2.16it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3542/4895 [1:23:25<10:34,  2.13it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3543/4895 [1:23:26<16:51,  1.34it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3544/4895 [1:23:28<21:47,  1.03it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▏          | 3545/4895 [1:23:28<17:12,  1.31it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▎          | 3546/4895 [1:23:28<14:37,  1.54it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▎          | 3547/4895 [1:23:29<15:08,  1.48it/s]


💽 TQM COPY FLOW:  72%|████████████████████████████▎          | 3548/4895 [1:23:30<13:18,  1.69it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3549/4895 [1:23:30<13:45,  1.63it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3550/4895 [1:23:31<13:38,  1.64it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3551/4895 [1:23:31<13:28,  1.66it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3552/4895 [1:23:32<12:33,  1.78it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3553/4895 [1:23:33<13:14,  1.69it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3554/4895 [1:23:33<14:34,  1.53it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3555/4895 [1:23:34<13:45,  1.62it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3556/4895 [1:23:35<14:06,  1.58it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3557/4895 [1:23:35<13:56,  1.60it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3558/4895 [1:23:36<12:52,  1.73it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3559/4895 [1:23:36<13:55,  1.60it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3560/4895 [1:23:37<13:17,  1.67it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▎          | 3561/4895 [1:23:38<13:52,  1.60it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3562/4895 [1:23:38<13:58,  1.59it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3563/4895 [1:23:39<13:36,  1.63it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3564/4895 [1:23:39<13:53,  1.60it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3565/4895 [1:23:40<14:46,  1.50it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3566/4895 [1:23:41<13:36,  1.63it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3567/4895 [1:23:41<12:50,  1.72it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3568/4895 [1:23:42<14:49,  1.49it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:29:41<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:10<?, ?it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3569/4895 [1:23:43<15:59,  1.38it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:17<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_127 (50 files)

💽 TQM COPY FLOW:  73%|██████████████████████████▉          | 3570/4895 [1:23:52<1:10:51,  3.21s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3571/4895 [1:23:52<52:35,  2.38s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3572/4895 [1:23:53<40:52,  1.85s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3573/4895 [1:23:53<30:41,  1.39s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3574/4895 [1:23:54<23:42,  1.08s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3575/4895 [1:23:54<19:31,  1.13it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3576/4895 [1:23:55<16:44,  1.31it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▍          | 3577/4895 [1:23:55<13:50,  1.59it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:29:55<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:25<?, ?it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3578/4895 [1:23:58<27:01,  1.23s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:31<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_128 (9 files)

💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3579/4895 [1:24:00<32:54,  1.50s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3580/4895 [1:24:02<36:27,  1.66s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3581/4895 [1:24:02<28:31,  1.30s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:30:01<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:30<?, ?it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3582/4895 [1:24:03<23:24,  1.07s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:36<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_129 (4 files)

💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3583/4895 [1:24:06<38:13,  1.75s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:30:05<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:35<?, ?it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3584/4895 [1:24:07<35:31,  1.63s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:24:41<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_130 (2 files)

💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3585/4895 [1:24:12<53:53,  2.47s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3586/4895 [1:24:12<41:08,  1.89s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3587/4895 [1:24:13<34:56,  1.60s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3588/4895 [1:24:14<28:03,  1.29s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3589/4895 [1:24:14<22:14,  1.02s/it]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3590/4895 [1:24:15<18:50,  1.15it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3591/4895 [1:24:15<17:33,  1.24it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▌          | 3592/4895 [1:24:16<16:15,  1.34it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▋          | 3593/4895 [1:24:17<16:26,  1.32it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▋          | 3594/4895 [1:24:17<13:29,  1.61it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▋          | 3595/4895 [1:24:18<12:26,  1.74it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▋          | 3596/4895 [1:24:19<14:49,  1.46it/s]


💽 TQM COPY FLOW:  73%|████████████████████████████▋          | 3597/4895 [1:24:19<12:56,  1.67it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3598/4895 [1:24:20<13:40,  1.58it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3599/4895 [1:24:20<11:57,  1.81it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3600/4895 [1:24:21<12:03,  1.79it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3601/4895 [1:24:21<10:52,  1.98it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3602/4895 [1:24:23<19:51,  1.09it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3603/4895 [1:24:24<20:04,  1.07it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3604/4895 [1:24:25<23:21,  1.09s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3605/4895 [1:24:26<20:26,  1.05it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3606/4895 [1:24:27<23:00,  1.07s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3607/4895 [1:24:28<20:17,  1.06it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▋          | 3608/4895 [1:24:30<24:52,  1.16s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3609/4895 [1:24:30<21:53,  1.02s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3610/4895 [1:24:31<20:08,  1.06it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3611/4895 [1:24:32<17:16,  1.24it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3612/4895 [1:24:32<15:01,  1.42it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3613/4895 [1:24:33<14:40,  1.46it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3614/4895 [1:24:34<16:21,  1.30it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3615/4895 [1:24:34<15:09,  1.41it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3616/4895 [1:24:34<12:18,  1.73it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3617/4895 [1:24:35<13:47,  1.54it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3618/4895 [1:24:36<12:00,  1.77it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3619/4895 [1:24:37<15:14,  1.40it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3620/4895 [1:24:38<17:37,  1.21it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3621/4895 [1:24:39<18:12,  1.17it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3622/4895 [1:24:39<16:02,  1.32it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3623/4895 [1:24:40<16:27,  1.29it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▊          | 3624/4895 [1:24:41<20:35,  1.03it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3625/4895 [1:24:43<23:14,  1.10s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3626/4895 [1:24:44<20:57,  1.01it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3627/4895 [1:24:45<24:11,  1.15s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3628/4895 [1:24:46<24:41,  1.17s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3629/4895 [1:24:47<24:36,  1.17s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3630/4895 [1:24:48<18:58,  1.11it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3631/4895 [1:24:49<18:31,  1.14it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3632/4895 [1:24:49<15:41,  1.34it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3633/4895 [1:24:50<14:39,  1.44it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:30:48<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:25:17<?, ?it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3634/4895 [1:24:50<12:24,  1.69it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:25:24<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_131 (50 files)

💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3635/4895 [1:24:52<22:58,  1.09s/it]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3636/4895 [1:24:53<17:57,  1.17it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3637/4895 [1:24:53<14:24,  1.46it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3638/4895 [1:24:53<13:48,  1.52it/s]


💽 TQM COPY FLOW:  74%|████████████████████████████▉          | 3639/4895 [1:24:54<11:23,  1.84it/s]


💽 TQM COPY FLOW:  74%|█████████████████████████████          | 3640/4895 [1:24:54<11:09,  1.87it/s]


💽 TQM COPY FLOW:  74%|█████████████████████████████          | 3641/4895 [1:24:55<11:58,  1.75it/s]


💽 TQM COPY FLOW:  74%|█████████████████████████████          | 3642/4895 [1:24:55<12:02,  1.73it/s]


💽 TQM COPY FLOW:  74%|█████████████████████████████          | 3643/4895 [1:24:56<11:46,  1.77it/s]


💽 TQM COPY FLOW:  74%|█████████████████████████████          | 3644/4895 [1:24:57<11:54,  1.75it/s]


💽 TQM COPY FLOW:  74%|█████████████████████████████          | 3645/4895 [1:24:58<18:35,  1.12it/s]


💽 TQM COPY FLOW:  74%|█████████████████████████████          | 3646/4895 [1:24:59<20:45,  1.00it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3647/4895 [1:25:00<16:39,  1.25it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3648/4895 [1:25:01<19:56,  1.04it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3649/4895 [1:25:02<19:05,  1.09it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3650/4895 [1:25:03<17:30,  1.18it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3651/4895 [1:25:03<14:26,  1.44it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3652/4895 [1:25:03<12:53,  1.61it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3653/4895 [1:25:04<12:43,  1.63it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3654/4895 [1:25:05<12:57,  1.60it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████          | 3655/4895 [1:25:05<12:07,  1.71it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3656/4895 [1:25:06<13:31,  1.53it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3657/4895 [1:25:07<17:24,  1.19it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3658/4895 [1:25:09<22:35,  1.10s/it]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3659/4895 [1:25:09<18:45,  1.10it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3660/4895 [1:25:10<14:18,  1.44it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3661/4895 [1:25:10<15:20,  1.34it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3662/4895 [1:25:11<14:17,  1.44it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3663/4895 [1:25:12<13:20,  1.54it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3664/4895 [1:25:12<12:42,  1.61it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3665/4895 [1:25:13<12:35,  1.63it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3666/4895 [1:25:13<10:27,  1.96it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3667/4895 [1:25:13<08:54,  2.30it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3668/4895 [1:25:14<08:59,  2.27it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3669/4895 [1:25:14<09:59,  2.04it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3670/4895 [1:25:15<10:52,  1.88it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▏         | 3671/4895 [1:25:15<09:15,  2.20it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3672/4895 [1:25:16<10:38,  1.92it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3673/4895 [1:25:17<11:26,  1.78it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3674/4895 [1:25:17<11:25,  1.78it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3675/4895 [1:25:18<15:13,  1.34it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3676/4895 [1:25:19<16:31,  1.23it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3677/4895 [1:25:20<14:17,  1.42it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3678/4895 [1:25:20<12:40,  1.60it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3679/4895 [1:25:21<10:58,  1.85it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3680/4895 [1:25:21<11:03,  1.83it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3681/4895 [1:25:22<11:51,  1.71it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3682/4895 [1:25:22<10:43,  1.88it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3683/4895 [1:25:23<10:17,  1.96it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:31:21<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:25:50<?, ?it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3684/4895 [1:25:23<09:05,  2.22it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:25:57<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_132 (50 files)

💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3685/4895 [1:25:24<14:21,  1.40it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▎         | 3686/4895 [1:25:25<13:19,  1.51it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3687/4895 [1:25:25<11:39,  1.73it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3688/4895 [1:25:27<17:06,  1.18it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3689/4895 [1:25:28<17:03,  1.18it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3690/4895 [1:25:29<20:03,  1.00it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3691/4895 [1:25:29<17:01,  1.18it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3692/4895 [1:25:30<14:31,  1.38it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3693/4895 [1:25:30<11:54,  1.68it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3694/4895 [1:25:31<11:22,  1.76it/s]


💽 TQM COPY FLOW:  75%|█████████████████████████████▍         | 3695/4895 [1:25:31<10:59,  1.82it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▍         | 3696/4895 [1:25:32<11:52,  1.68it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▍         | 3697/4895 [1:25:32<11:01,  1.81it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▍         | 3698/4895 [1:25:33<11:19,  1.76it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▍         | 3699/4895 [1:25:34<12:15,  1.63it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▍         | 3700/4895 [1:25:34<13:32,  1.47it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▍         | 3701/4895 [1:25:35<13:00,  1.53it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▍         | 3702/4895 [1:25:35<11:15,  1.77it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3703/4895 [1:25:36<12:29,  1.59it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3704/4895 [1:25:36<10:02,  1.98it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3705/4895 [1:25:37<09:52,  2.01it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3706/4895 [1:25:37<10:24,  1.90it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3707/4895 [1:25:38<09:39,  2.05it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3708/4895 [1:25:38<09:59,  1.98it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3709/4895 [1:25:39<09:49,  2.01it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3710/4895 [1:25:39<08:47,  2.25it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3711/4895 [1:25:40<09:41,  2.03it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3712/4895 [1:25:40<10:36,  1.86it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3713/4895 [1:25:41<10:54,  1.81it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3714/4895 [1:25:42<10:37,  1.85it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3715/4895 [1:25:42<09:20,  2.10it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3716/4895 [1:25:42<08:58,  2.19it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3717/4895 [1:25:43<08:21,  2.35it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▌         | 3718/4895 [1:25:43<08:46,  2.24it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3719/4895 [1:25:44<10:56,  1.79it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3720/4895 [1:25:45<11:30,  1.70it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3721/4895 [1:25:45<10:03,  1.94it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3722/4895 [1:25:46<15:43,  1.24it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3723/4895 [1:25:47<15:17,  1.28it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3724/4895 [1:25:48<13:44,  1.42it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3725/4895 [1:25:48<13:05,  1.49it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3726/4895 [1:25:49<14:12,  1.37it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3727/4895 [1:25:50<16:27,  1.18it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3728/4895 [1:25:51<15:44,  1.24it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3729/4895 [1:25:51<13:18,  1.46it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3730/4895 [1:25:52<11:39,  1.67it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3731/4895 [1:25:54<19:52,  1.02s/it]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3732/4895 [1:25:58<38:28,  1.99s/it]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3733/4895 [1:25:59<31:41,  1.64s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:31:57<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:26:27<?, ?it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▋         | 3734/4895 [1:25:59<25:36,  1.32s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:26:33<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_133 (50 files)

💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3735/4895 [1:26:01<27:25,  1.42s/it]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3736/4895 [1:26:02<22:34,  1.17s/it]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3737/4895 [1:26:02<18:47,  1.03it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3738/4895 [1:26:02<15:04,  1.28it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3739/4895 [1:26:03<14:03,  1.37it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3740/4895 [1:26:04<12:24,  1.55it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3741/4895 [1:26:04<11:46,  1.63it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3742/4895 [1:26:05<10:56,  1.76it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3743/4895 [1:26:05<09:58,  1.93it/s]


💽 TQM COPY FLOW:  76%|█████████████████████████████▊         | 3744/4895 [1:26:05<09:57,  1.93it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▊         | 3745/4895 [1:26:06<09:58,  1.92it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▊         | 3746/4895 [1:26:06<08:35,  2.23it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▊         | 3747/4895 [1:26:07<11:43,  1.63it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▊         | 3748/4895 [1:26:08<10:20,  1.85it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▊         | 3749/4895 [1:26:08<08:51,  2.16it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3750/4895 [1:26:08<08:49,  2.16it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3751/4895 [1:26:09<07:32,  2.53it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3752/4895 [1:26:09<08:00,  2.38it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3753/4895 [1:26:10<08:31,  2.23it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3754/4895 [1:26:10<07:36,  2.50it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3755/4895 [1:26:10<06:54,  2.75it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3756/4895 [1:26:11<10:01,  1.89it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3757/4895 [1:26:11<08:33,  2.21it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3758/4895 [1:26:12<07:47,  2.43it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3759/4895 [1:26:12<07:31,  2.51it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3760/4895 [1:26:13<08:23,  2.25it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3761/4895 [1:26:14<10:58,  1.72it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3762/4895 [1:26:15<15:15,  1.24it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3763/4895 [1:26:15<14:10,  1.33it/s]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3764/4895 [1:26:18<22:26,  1.19s/it]


💽 TQM COPY FLOW:  77%|█████████████████████████████▉         | 3765/4895 [1:26:18<20:18,  1.08s/it]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3766/4895 [1:26:19<17:14,  1.09it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3767/4895 [1:26:19<14:32,  1.29it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3768/4895 [1:26:20<13:42,  1.37it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3769/4895 [1:26:21<11:54,  1.58it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3770/4895 [1:26:22<14:26,  1.30it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3771/4895 [1:26:24<22:50,  1.22s/it]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3772/4895 [1:26:24<18:01,  1.04it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3773/4895 [1:26:25<15:47,  1.18it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3774/4895 [1:26:25<11:40,  1.60it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3775/4895 [1:26:26<14:15,  1.31it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3776/4895 [1:26:26<12:19,  1.51it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3777/4895 [1:26:28<15:58,  1.17it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3778/4895 [1:26:30<22:16,  1.20s/it]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3779/4895 [1:26:30<18:52,  1.02s/it]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3780/4895 [1:26:31<16:54,  1.10it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████         | 3781/4895 [1:26:31<13:57,  1.33it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3782/4895 [1:26:32<11:49,  1.57it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3783/4895 [1:26:32<11:04,  1.67it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:32:31<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:27:00<?, ?it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3784/4895 [1:26:33<10:02,  1.84it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:27:06<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_134 (50 files)

💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3785/4895 [1:26:35<22:39,  1.22s/it]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3786/4895 [1:26:36<19:24,  1.05s/it]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3787/4895 [1:26:37<16:09,  1.14it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3788/4895 [1:26:37<12:44,  1.45it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3789/4895 [1:26:37<11:19,  1.63it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3790/4895 [1:26:38<09:48,  1.88it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3791/4895 [1:26:38<08:28,  2.17it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3792/4895 [1:26:38<07:22,  2.49it/s]


💽 TQM COPY FLOW:  77%|██████████████████████████████▏        | 3793/4895 [1:26:39<08:40,  2.12it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▏        | 3794/4895 [1:26:39<08:40,  2.12it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▏        | 3795/4895 [1:26:40<08:32,  2.15it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▏        | 3796/4895 [1:26:40<07:21,  2.49it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3797/4895 [1:26:41<12:38,  1.45it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3798/4895 [1:26:43<16:04,  1.14it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3799/4895 [1:26:43<12:46,  1.43it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3800/4895 [1:26:44<16:25,  1.11it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3801/4895 [1:26:45<12:39,  1.44it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3802/4895 [1:26:45<10:34,  1.72it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3803/4895 [1:26:46<12:10,  1.49it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3804/4895 [1:26:46<09:22,  1.94it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3805/4895 [1:26:46<09:35,  1.89it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3806/4895 [1:26:47<09:24,  1.93it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3807/4895 [1:26:47<08:55,  2.03it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3808/4895 [1:26:48<09:27,  1.91it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3809/4895 [1:26:49<11:00,  1.65it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3810/4895 [1:26:50<13:42,  1.32it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3811/4895 [1:26:50<12:23,  1.46it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▎        | 3812/4895 [1:26:51<14:04,  1.28it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3813/4895 [1:26:53<17:59,  1.00it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3814/4895 [1:26:54<17:03,  1.06it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3815/4895 [1:26:54<14:56,  1.20it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3816/4895 [1:26:55<12:33,  1.43it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3817/4895 [1:26:56<15:13,  1.18it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3818/4895 [1:26:56<13:57,  1.29it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3819/4895 [1:26:57<11:54,  1.51it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3820/4895 [1:26:58<11:58,  1.50it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3821/4895 [1:26:58<12:13,  1.46it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3822/4895 [1:26:59<11:27,  1.56it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3823/4895 [1:27:00<12:54,  1.38it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3824/4895 [1:27:00<12:45,  1.40it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3825/4895 [1:27:01<11:11,  1.59it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3826/4895 [1:27:01<10:44,  1.66it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3827/4895 [1:27:02<09:50,  1.81it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▍        | 3828/4895 [1:27:03<10:34,  1.68it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3829/4895 [1:27:03<09:59,  1.78it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3830/4895 [1:27:03<09:21,  1.90it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3831/4895 [1:27:04<08:12,  2.16it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3832/4895 [1:27:04<08:40,  2.04it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3833/4895 [1:27:05<09:04,  1.95it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:33:03<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:27:33<?, ?it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3834/4895 [1:27:05<07:33,  2.34it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:27:39<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_135 (50 files)

💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3835/4895 [1:27:06<07:32,  2.34it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3836/4895 [1:27:06<09:36,  1.84it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3837/4895 [1:27:07<09:45,  1.81it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3838/4895 [1:27:07<08:18,  2.12it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3839/4895 [1:27:07<07:13,  2.44it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3840/4895 [1:27:08<08:42,  2.02it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3841/4895 [1:27:08<07:24,  2.37it/s]


💽 TQM COPY FLOW:  78%|██████████████████████████████▌        | 3842/4895 [1:27:09<09:49,  1.79it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▌        | 3843/4895 [1:27:09<07:50,  2.24it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3844/4895 [1:27:11<10:57,  1.60it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3845/4895 [1:27:12<12:44,  1.37it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3846/4895 [1:27:13<14:33,  1.20it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3847/4895 [1:27:14<15:43,  1.11it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3848/4895 [1:27:14<13:34,  1.28it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3849/4895 [1:27:15<16:28,  1.06it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3850/4895 [1:27:16<13:28,  1.29it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3851/4895 [1:27:17<13:21,  1.30it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3852/4895 [1:27:17<11:16,  1.54it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3853/4895 [1:27:17<10:38,  1.63it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3854/4895 [1:27:18<09:25,  1.84it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3855/4895 [1:27:18<09:13,  1.88it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3856/4895 [1:27:19<11:25,  1.52it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3857/4895 [1:27:20<10:59,  1.57it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3858/4895 [1:27:20<10:28,  1.65it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▋        | 3859/4895 [1:27:21<12:05,  1.43it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3860/4895 [1:27:22<10:39,  1.62it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3861/4895 [1:27:22<09:48,  1.76it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3862/4895 [1:27:22<07:57,  2.16it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3863/4895 [1:27:23<10:00,  1.72it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3864/4895 [1:27:24<11:41,  1.47it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3865/4895 [1:27:25<10:59,  1.56it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3866/4895 [1:27:26<13:34,  1.26it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3867/4895 [1:27:27<13:07,  1.31it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3868/4895 [1:27:27<12:23,  1.38it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3869/4895 [1:27:28<13:54,  1.23it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3870/4895 [1:27:29<12:32,  1.36it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3871/4895 [1:27:29<10:33,  1.62it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3872/4895 [1:27:30<09:14,  1.85it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3873/4895 [1:27:30<07:58,  2.14it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3874/4895 [1:27:30<07:38,  2.22it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▊        | 3875/4895 [1:27:31<08:08,  2.09it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3876/4895 [1:27:31<08:14,  2.06it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3877/4895 [1:27:32<07:10,  2.36it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3878/4895 [1:27:32<06:10,  2.75it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3879/4895 [1:27:32<05:06,  3.32it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3880/4895 [1:27:33<07:37,  2.22it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3881/4895 [1:27:34<10:36,  1.59it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3882/4895 [1:27:34<10:46,  1.57it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3883/4895 [1:27:35<12:01,  1.40it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:33:34<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:28:04<?, ?it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3884/4895 [1:27:36<13:32,  1.24it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:28:10<?, ?it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3885/4895 [1:27:37<10:31,  1.60it/s]

📦 Finished chunk: _24_ARCH_rk_136 (50 files)

💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3886/4895 [1:27:38<13:33,  1.24it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3887/4895 [1:27:38<10:57,  1.53it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3888/4895 [1:27:39<10:54,  1.54it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3889/4895 [1:27:39<10:40,  1.57it/s]


💽 TQM COPY FLOW:  79%|██████████████████████████████▉        | 3890/4895 [1:27:40<13:00,  1.29it/s]


💽 TQM COPY FLOW:  79%|███████████████████████████████        | 3891/4895 [1:27:41<12:12,  1.37it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3892/4895 [1:27:41<10:33,  1.58it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3893/4895 [1:27:42<08:48,  1.90it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3894/4895 [1:27:42<08:34,  1.95it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3895/4895 [1:27:43<07:24,  2.25it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3896/4895 [1:27:43<06:01,  2.76it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3897/4895 [1:27:43<05:45,  2.89it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3898/4895 [1:27:43<05:30,  3.01it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3899/4895 [1:27:44<05:42,  2.90it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3900/4895 [1:27:44<06:48,  2.44it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3901/4895 [1:27:45<06:25,  2.58it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3902/4895 [1:27:45<07:14,  2.28it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3903/4895 [1:27:46<07:05,  2.33it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3904/4895 [1:27:46<08:29,  1.95it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3905/4895 [1:27:47<10:55,  1.51it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████        | 3906/4895 [1:27:48<10:40,  1.54it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3907/4895 [1:27:49<13:33,  1.21it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3908/4895 [1:27:50<14:39,  1.12it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3909/4895 [1:27:50<11:18,  1.45it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3910/4895 [1:27:51<09:23,  1.75it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3911/4895 [1:27:51<09:20,  1.76it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3912/4895 [1:27:53<13:34,  1.21it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3913/4895 [1:27:53<10:44,  1.52it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3914/4895 [1:27:55<15:25,  1.06it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3915/4895 [1:27:55<14:13,  1.15it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3916/4895 [1:27:57<17:40,  1.08s/it]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3917/4895 [1:27:58<15:52,  1.03it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3918/4895 [1:27:58<15:23,  1.06it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3919/4895 [1:27:59<13:21,  1.22it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3920/4895 [1:27:59<12:00,  1.35it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3921/4895 [1:28:00<09:55,  1.63it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▏       | 3922/4895 [1:28:01<10:54,  1.49it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3923/4895 [1:28:01<09:21,  1.73it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3924/4895 [1:28:01<07:48,  2.07it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3925/4895 [1:28:02<07:11,  2.25it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3926/4895 [1:28:02<06:45,  2.39it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3927/4895 [1:28:02<07:23,  2.18it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3928/4895 [1:28:03<09:43,  1.66it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3929/4895 [1:28:05<12:00,  1.34it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3930/4895 [1:28:06<14:10,  1.13it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3931/4895 [1:28:06<12:27,  1.29it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3932/4895 [1:28:07<11:19,  1.42it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3933/4895 [1:28:09<17:09,  1.07s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:34:08<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:28:37<?, ?it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3934/4895 [1:28:10<17:32,  1.10s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:28:44<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_137 (50 files)

💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3935/4895 [1:28:11<19:20,  1.21s/it]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3936/4895 [1:28:12<14:50,  1.08it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▎       | 3937/4895 [1:28:12<12:46,  1.25it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▍       | 3938/4895 [1:28:13<11:48,  1.35it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▍       | 3939/4895 [1:28:13<11:14,  1.42it/s]


💽 TQM COPY FLOW:  80%|███████████████████████████████▍       | 3940/4895 [1:28:14<10:49,  1.47it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3941/4895 [1:28:16<14:59,  1.06it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3942/4895 [1:28:16<12:59,  1.22it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3943/4895 [1:28:17<12:27,  1.27it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3944/4895 [1:28:17<12:18,  1.29it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3945/4895 [1:28:18<11:49,  1.34it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3946/4895 [1:28:19<11:17,  1.40it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3947/4895 [1:28:20<11:10,  1.41it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3948/4895 [1:28:20<12:07,  1.30it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3949/4895 [1:28:21<11:45,  1.34it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3950/4895 [1:28:22<12:08,  1.30it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3951/4895 [1:28:23<13:16,  1.19it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3952/4895 [1:28:24<13:43,  1.14it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▍       | 3953/4895 [1:28:25<15:07,  1.04it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3954/4895 [1:28:26<12:55,  1.21it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3955/4895 [1:28:26<11:28,  1.37it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3956/4895 [1:28:27<10:41,  1.46it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3957/4895 [1:28:28<13:39,  1.14it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3958/4895 [1:28:29<12:27,  1.25it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3959/4895 [1:28:29<10:37,  1.47it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3960/4895 [1:28:29<09:33,  1.63it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3961/4895 [1:28:30<11:03,  1.41it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3962/4895 [1:28:31<10:00,  1.55it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3963/4895 [1:28:32<10:11,  1.53it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3964/4895 [1:28:32<09:30,  1.63it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3965/4895 [1:28:33<09:14,  1.68it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3966/4895 [1:28:33<08:51,  1.75it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3967/4895 [1:28:35<12:59,  1.19it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3968/4895 [1:28:35<12:05,  1.28it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▌       | 3969/4895 [1:28:36<10:43,  1.44it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3970/4895 [1:28:37<14:21,  1.07it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3971/4895 [1:28:39<16:14,  1.05s/it]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3972/4895 [1:28:40<16:51,  1.10s/it]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3973/4895 [1:28:40<13:58,  1.10it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3974/4895 [1:28:41<14:25,  1.06it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3975/4895 [1:28:42<12:15,  1.25it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3976/4895 [1:28:42<12:03,  1.27it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3977/4895 [1:28:43<12:50,  1.19it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3978/4895 [1:28:44<10:55,  1.40it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3979/4895 [1:28:44<09:23,  1.62it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3980/4895 [1:28:45<10:06,  1.51it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3981/4895 [1:28:46<10:37,  1.43it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3982/4895 [1:28:46<09:49,  1.55it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3983/4895 [1:28:47<09:15,  1.64it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:34:45<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:29:15<?, ?it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3984/4895 [1:28:47<07:51,  1.93it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:29:21<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_138 (50 files)

💽 TQM COPY FLOW:  81%|███████████████████████████████▋       | 3985/4895 [1:28:51<23:01,  1.52s/it]


💽 TQM COPY FLOW:  81%|███████████████████████████████▊       | 3986/4895 [1:28:51<18:07,  1.20s/it]


💽 TQM COPY FLOW:  81%|███████████████████████████████▊       | 3987/4895 [1:28:52<14:31,  1.04it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▊       | 3988/4895 [1:28:52<12:42,  1.19it/s]


💽 TQM COPY FLOW:  81%|███████████████████████████████▊       | 3989/4895 [1:28:53<10:36,  1.42it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3990/4895 [1:28:54<13:46,  1.10it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3991/4895 [1:28:55<12:32,  1.20it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3992/4895 [1:28:55<10:24,  1.45it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3993/4895 [1:28:56<10:22,  1.45it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3994/4895 [1:28:57<10:15,  1.46it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3995/4895 [1:28:57<08:06,  1.85it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3996/4895 [1:28:58<09:01,  1.66it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3997/4895 [1:28:58<09:30,  1.57it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3998/4895 [1:28:59<08:23,  1.78it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 3999/4895 [1:29:00<10:05,  1.48it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▊       | 4000/4895 [1:29:00<09:41,  1.54it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4001/4895 [1:29:01<09:16,  1.61it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4002/4895 [1:29:01<09:04,  1.64it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4003/4895 [1:29:03<11:46,  1.26it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4004/4895 [1:29:04<14:13,  1.04it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4005/4895 [1:29:05<14:46,  1.00it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4006/4895 [1:29:06<15:24,  1.04s/it]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4007/4895 [1:29:07<12:35,  1.17it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4008/4895 [1:29:07<10:48,  1.37it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4009/4895 [1:29:07<09:02,  1.63it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4010/4895 [1:29:08<08:01,  1.84it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4012/4895 [1:29:08<06:06,  2.41it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4013/4895 [1:29:09<05:52,  2.50it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4014/4895 [1:29:09<07:00,  2.10it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4015/4895 [1:29:10<08:39,  1.69it/s]


💽 TQM COPY FLOW:  82%|███████████████████████████████▉       | 4016/4895 [1:29:11<07:42,  1.90it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4017/4895 [1:29:11<06:34,  2.23it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4018/4895 [1:29:11<06:06,  2.39it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4019/4895 [1:29:12<06:06,  2.39it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4020/4895 [1:29:14<13:23,  1.09it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4021/4895 [1:29:15<14:24,  1.01it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4022/4895 [1:29:17<18:18,  1.26s/it]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4023/4895 [1:29:18<16:32,  1.14s/it]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4024/4895 [1:29:20<20:44,  1.43s/it]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4025/4895 [1:29:22<22:35,  1.56s/it]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4026/4895 [1:29:22<17:33,  1.21s/it]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4027/4895 [1:29:23<17:03,  1.18s/it]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4028/4895 [1:29:23<12:50,  1.12it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4029/4895 [1:29:24<10:38,  1.36it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4030/4895 [1:29:24<08:50,  1.63it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4031/4895 [1:29:24<07:22,  1.95it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████       | 4032/4895 [1:29:25<06:41,  2.15it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████▏      | 4033/4895 [1:29:25<06:19,  2.27it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:35:23<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:29:53<?, ?it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████▏      | 4034/4895 [1:29:25<06:22,  2.25it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:29:59<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_139 (50 files)

💽 TQM COPY FLOW:  82%|████████████████████████████████▏      | 4035/4895 [1:29:26<05:58,  2.40it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████▏      | 4036/4895 [1:29:32<30:06,  2.10s/it]


💽 TQM COPY FLOW:  82%|████████████████████████████████▏      | 4037/4895 [1:29:32<22:38,  1.58s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:35:32<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:30:02<?, ?it/s]


💽 TQM COPY FLOW:  82%|████████████████████████████████▏      | 4038/4895 [1:29:35<26:09,  1.83s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:30:08<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_140 (4 files)

💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4039/4895 [1:29:37<27:43,  1.94s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4040/4895 [1:29:41<35:17,  2.48s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4041/4895 [1:29:41<28:06,  1.97s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:35:40<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:30:10<?, ?it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4042/4895 [1:29:42<23:00,  1.62s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:30:16<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_141 (4 files)

💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4043/4895 [1:29:43<19:16,  1.36s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4044/4895 [1:29:43<15:40,  1.10s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4045/4895 [1:29:44<14:24,  1.02s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▏      | 4047/4895 [1:29:44<08:33,  1.65it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4048/4895 [1:29:45<08:29,  1.66it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4049/4895 [1:29:45<07:25,  1.90it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4050/4895 [1:29:46<06:18,  2.23it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4051/4895 [1:29:46<05:57,  2.36it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4052/4895 [1:29:47<06:52,  2.04it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4053/4895 [1:29:47<06:18,  2.22it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4054/4895 [1:29:47<06:09,  2.28it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4055/4895 [1:29:48<05:43,  2.45it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4056/4895 [1:29:49<07:32,  1.85it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4057/4895 [1:29:49<06:35,  2.12it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4058/4895 [1:29:49<06:30,  2.15it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4059/4895 [1:29:49<05:17,  2.63it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4060/4895 [1:29:50<04:59,  2.78it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4061/4895 [1:29:50<04:23,  3.17it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4062/4895 [1:29:50<04:09,  3.34it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▎      | 4063/4895 [1:29:50<03:36,  3.84it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4064/4895 [1:29:52<07:48,  1.78it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4065/4895 [1:29:54<15:02,  1.09s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4066/4895 [1:29:56<18:33,  1.34s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4067/4895 [1:29:56<15:11,  1.10s/it]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4068/4895 [1:29:57<11:29,  1.20it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4069/4895 [1:29:57<09:43,  1.42it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4070/4895 [1:29:58<09:05,  1.51it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4071/4895 [1:29:58<09:38,  1.42it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4072/4895 [1:29:59<07:48,  1.76it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4073/4895 [1:29:59<08:02,  1.70it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4074/4895 [1:30:00<08:42,  1.57it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4075/4895 [1:30:00<07:23,  1.85it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4076/4895 [1:30:01<07:13,  1.89it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4077/4895 [1:30:01<06:05,  2.24it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4078/4895 [1:30:02<05:58,  2.28it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▍      | 4079/4895 [1:30:02<06:12,  2.19it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4080/4895 [1:30:02<05:36,  2.42it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4081/4895 [1:30:03<06:08,  2.21it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4082/4895 [1:30:03<05:30,  2.46it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4083/4895 [1:30:04<05:03,  2.68it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4084/4895 [1:30:04<05:22,  2.52it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4085/4895 [1:30:04<04:50,  2.79it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4086/4895 [1:30:05<04:40,  2.88it/s]


💽 TQM COPY FLOW:  83%|████████████████████████████████▌      | 4087/4895 [1:30:05<05:22,  2.50it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▌      | 4088/4895 [1:30:06<05:50,  2.31it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▌      | 4089/4895 [1:30:06<06:00,  2.23it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▌      | 4090/4895 [1:30:07<05:55,  2.26it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▌      | 4091/4895 [1:30:07<06:58,  1.92it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:36:06<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:30:35<?, ?it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▌      | 4092/4895 [1:30:08<06:46,  1.97it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:30:41<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_142 (50 files)

💽 TQM COPY FLOW:  84%|████████████████████████████████▌      | 4093/4895 [1:30:08<05:51,  2.28it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▌      | 4094/4895 [1:30:08<04:33,  2.93it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4095/4895 [1:30:09<05:35,  2.38it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4096/4895 [1:30:09<05:08,  2.59it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4097/4895 [1:30:10<05:56,  2.24it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4098/4895 [1:30:10<06:00,  2.21it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4099/4895 [1:30:11<06:20,  2.09it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4100/4895 [1:30:12<08:01,  1.65it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4101/4895 [1:30:13<10:14,  1.29it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4102/4895 [1:30:14<13:24,  1.01s/it]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4103/4895 [1:30:15<11:13,  1.18it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4104/4895 [1:30:15<09:17,  1.42it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4105/4895 [1:30:16<08:21,  1.58it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4106/4895 [1:30:16<08:19,  1.58it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4107/4895 [1:30:17<08:32,  1.54it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4108/4895 [1:30:18<09:36,  1.37it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4109/4895 [1:30:18<07:30,  1.74it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▋      | 4110/4895 [1:30:19<09:00,  1.45it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4111/4895 [1:30:19<06:49,  1.91it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4112/4895 [1:30:22<14:15,  1.09s/it]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4113/4895 [1:30:22<11:56,  1.09it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4114/4895 [1:30:22<09:31,  1.37it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4115/4895 [1:30:23<08:31,  1.53it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4116/4895 [1:30:23<07:01,  1.85it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4117/4895 [1:30:24<07:25,  1.74it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4118/4895 [1:30:24<07:57,  1.63it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4119/4895 [1:30:26<10:17,  1.26it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4120/4895 [1:30:27<11:25,  1.13it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4121/4895 [1:30:27<09:33,  1.35it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4122/4895 [1:30:28<09:31,  1.35it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4123/4895 [1:30:28<07:55,  1.62it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4124/4895 [1:30:29<07:59,  1.61it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4125/4895 [1:30:30<09:09,  1.40it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▊      | 4126/4895 [1:30:31<10:33,  1.21it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4127/4895 [1:30:31<09:26,  1.36it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4128/4895 [1:30:32<07:43,  1.66it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4129/4895 [1:30:33<08:41,  1.47it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4130/4895 [1:30:34<12:15,  1.04it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4131/4895 [1:30:34<09:49,  1.30it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4132/4895 [1:30:35<09:29,  1.34it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4133/4895 [1:30:36<09:28,  1.34it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4134/4895 [1:30:36<08:24,  1.51it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4135/4895 [1:30:37<07:01,  1.80it/s]


💽 TQM COPY FLOW:  84%|████████████████████████████████▉      | 4136/4895 [1:30:37<06:05,  2.08it/s]


💽 TQM COPY FLOW:  85%|████████████████████████████████▉      | 4137/4895 [1:30:37<05:33,  2.27it/s]


💽 TQM COPY FLOW:  85%|████████████████████████████████▉      | 4138/4895 [1:30:37<04:20,  2.91it/s]


💽 TQM COPY FLOW:  85%|████████████████████████████████▉      | 4139/4895 [1:30:38<04:29,  2.80it/s]


💽 TQM COPY FLOW:  85%|████████████████████████████████▉      | 4140/4895 [1:30:38<04:49,  2.61it/s]


💽 TQM COPY FLOW:  85%|████████████████████████████████▉      | 4141/4895 [1:30:39<05:06,  2.46it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:36:37<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:31:06<?, ?it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4142/4895 [1:30:39<04:15,  2.95it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:31:13<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_143 (50 files)

💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4143/4895 [1:30:39<04:15,  2.94it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4144/4895 [1:30:40<04:04,  3.08it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4145/4895 [1:30:40<05:12,  2.40it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4146/4895 [1:30:40<04:44,  2.64it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4147/4895 [1:30:43<13:03,  1.05s/it]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4148/4895 [1:30:44<12:54,  1.04s/it]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4149/4895 [1:30:45<11:29,  1.08it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4150/4895 [1:30:45<09:18,  1.33it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4151/4895 [1:30:46<08:49,  1.41it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4152/4895 [1:30:46<08:08,  1.52it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4153/4895 [1:30:47<06:42,  1.85it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4154/4895 [1:30:47<05:42,  2.17it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4155/4895 [1:30:48<08:02,  1.53it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4156/4895 [1:30:48<07:44,  1.59it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████      | 4157/4895 [1:30:49<08:29,  1.45it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4158/4895 [1:30:50<08:40,  1.41it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4160/4895 [1:30:51<05:54,  2.07it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4161/4895 [1:30:51<06:59,  1.75it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4162/4895 [1:30:52<05:58,  2.05it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4163/4895 [1:30:52<05:15,  2.32it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4164/4895 [1:30:53<06:36,  1.84it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4165/4895 [1:30:53<06:16,  1.94it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4166/4895 [1:30:54<06:19,  1.92it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4167/4895 [1:30:55<09:02,  1.34it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4168/4895 [1:30:56<10:30,  1.15it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4169/4895 [1:30:57<09:28,  1.28it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4170/4895 [1:30:57<07:22,  1.64it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4171/4895 [1:30:57<06:59,  1.72it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▏     | 4172/4895 [1:30:58<06:58,  1.73it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4174/4895 [1:30:59<05:27,  2.20it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4175/4895 [1:30:59<06:38,  1.81it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4176/4895 [1:31:00<07:31,  1.59it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4177/4895 [1:31:01<06:51,  1.74it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4178/4895 [1:31:01<06:25,  1.86it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4179/4895 [1:31:01<05:13,  2.29it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4180/4895 [1:31:02<04:50,  2.46it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4181/4895 [1:31:04<10:04,  1.18it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4182/4895 [1:31:05<10:11,  1.17it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4183/4895 [1:31:06<11:23,  1.04it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4184/4895 [1:31:06<09:30,  1.25it/s]


💽 TQM COPY FLOW:  85%|█████████████████████████████████▎     | 4185/4895 [1:31:07<08:32,  1.39it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▎     | 4186/4895 [1:31:07<07:29,  1.58it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▎     | 4187/4895 [1:31:08<07:10,  1.64it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▎     | 4188/4895 [1:31:08<07:16,  1.62it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4189/4895 [1:31:09<06:05,  1.93it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4190/4895 [1:31:09<05:42,  2.06it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4191/4895 [1:31:09<05:12,  2.25it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:37:08<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:31:37<?, ?it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4192/4895 [1:31:10<04:36,  2.55it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:31:43<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_144 (50 files)

💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4193/4895 [1:31:12<10:59,  1.06it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4194/4895 [1:31:14<15:33,  1.33s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4195/4895 [1:31:15<14:06,  1.21s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4196/4895 [1:31:16<12:06,  1.04s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4197/4895 [1:31:16<10:47,  1.08it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4198/4895 [1:31:17<09:56,  1.17it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4199/4895 [1:31:18<09:25,  1.23it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4200/4895 [1:31:18<07:34,  1.53it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4201/4895 [1:31:19<10:20,  1.12it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4202/4895 [1:31:21<11:33,  1.00s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4203/4895 [1:31:21<10:39,  1.08it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▍     | 4204/4895 [1:31:22<09:29,  1.21it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4205/4895 [1:31:23<09:06,  1.26it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4206/4895 [1:31:24<09:17,  1.24it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4207/4895 [1:31:24<07:49,  1.47it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4208/4895 [1:31:29<21:38,  1.89s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4209/4895 [1:31:35<35:50,  3.14s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4210/4895 [1:31:35<27:12,  2.38s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4211/4895 [1:31:36<21:19,  1.87s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4212/4895 [1:31:36<15:53,  1.40s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4213/4895 [1:31:37<11:54,  1.05s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4214/4895 [1:31:39<15:16,  1.35s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4215/4895 [1:31:39<11:59,  1.06s/it]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4216/4895 [1:31:39<09:21,  1.21it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4217/4895 [1:31:40<07:56,  1.42it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4218/4895 [1:31:40<07:54,  1.43it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4219/4895 [1:31:41<06:21,  1.77it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▌     | 4220/4895 [1:31:41<06:16,  1.79it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4221/4895 [1:31:42<06:50,  1.64it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4222/4895 [1:31:42<06:48,  1.65it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4223/4895 [1:31:43<06:44,  1.66it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4224/4895 [1:31:44<06:36,  1.69it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4225/4895 [1:31:44<06:39,  1.68it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4226/4895 [1:31:45<08:10,  1.36it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4227/4895 [1:31:46<06:37,  1.68it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4228/4895 [1:31:47<09:40,  1.15it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4229/4895 [1:31:48<08:14,  1.35it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4230/4895 [1:31:48<06:54,  1.60it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4231/4895 [1:31:48<06:10,  1.79it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4232/4895 [1:31:49<05:09,  2.14it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4233/4895 [1:31:49<06:19,  1.74it/s]


💽 TQM COPY FLOW:  86%|█████████████████████████████████▋     | 4234/4895 [1:31:51<09:26,  1.17it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▋     | 4235/4895 [1:31:51<07:25,  1.48it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▋     | 4236/4895 [1:31:52<08:49,  1.24it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4237/4895 [1:31:54<10:54,  1.01it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4238/4895 [1:32:01<31:53,  2.91s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4239/4895 [1:32:01<22:55,  2.10s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4240/4895 [1:32:02<20:03,  1.84s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4241/4895 [1:32:03<15:35,  1.43s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:38:01<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:32:31<?, ?it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4242/4895 [1:32:03<12:05,  1.11s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:32:37<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_145 (50 files)

💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4243/4895 [1:32:07<21:17,  1.96s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4244/4895 [1:32:16<42:38,  3.93s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4245/4895 [1:32:16<31:13,  2.88s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4246/4895 [1:32:17<23:31,  2.17s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4247/4895 [1:32:17<17:44,  1.64s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4248/4895 [1:32:18<14:26,  1.34s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4249/4895 [1:32:18<11:15,  1.05s/it]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4250/4895 [1:32:19<09:02,  1.19it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▊     | 4251/4895 [1:32:19<07:58,  1.35it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4252/4895 [1:32:19<06:27,  1.66it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4253/4895 [1:32:20<06:32,  1.63it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4254/4895 [1:32:20<06:08,  1.74it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4255/4895 [1:32:21<05:15,  2.03it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4256/4895 [1:32:21<05:45,  1.85it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4257/4895 [1:32:22<05:16,  2.02it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4258/4895 [1:32:22<05:26,  1.95it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4259/4895 [1:32:24<07:55,  1.34it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4260/4895 [1:32:24<07:32,  1.40it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4261/4895 [1:32:24<05:45,  1.83it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4262/4895 [1:32:25<05:28,  1.93it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4263/4895 [1:32:25<04:35,  2.30it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4264/4895 [1:32:25<04:14,  2.48it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4265/4895 [1:32:26<04:00,  2.62it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4266/4895 [1:32:26<04:19,  2.43it/s]


💽 TQM COPY FLOW:  87%|█████████████████████████████████▉     | 4267/4895 [1:32:27<05:22,  1.95it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4268/4895 [1:32:27<05:08,  2.03it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4269/4895 [1:32:28<04:16,  2.44it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4270/4895 [1:32:28<03:59,  2.61it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4271/4895 [1:32:28<03:21,  3.09it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4272/4895 [1:32:29<03:28,  2.99it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4273/4895 [1:32:29<04:02,  2.56it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4274/4895 [1:32:30<04:31,  2.29it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4275/4895 [1:32:30<04:20,  2.38it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4276/4895 [1:32:30<04:29,  2.30it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4277/4895 [1:32:31<04:45,  2.17it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4278/4895 [1:32:31<04:12,  2.45it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4279/4895 [1:32:31<03:34,  2.88it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4280/4895 [1:32:32<05:36,  1.83it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4281/4895 [1:32:33<04:42,  2.17it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4282/4895 [1:32:34<06:09,  1.66it/s]


💽 TQM COPY FLOW:  87%|██████████████████████████████████     | 4283/4895 [1:32:35<08:05,  1.26it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4284/4895 [1:32:37<11:07,  1.09s/it]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4285/4895 [1:32:37<09:53,  1.03it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4286/4895 [1:32:38<08:24,  1.21it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4287/4895 [1:32:38<07:19,  1.38it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4288/4895 [1:32:39<06:38,  1.52it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4289/4895 [1:32:39<06:04,  1.66it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4290/4895 [1:32:40<04:47,  2.10it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4291/4895 [1:32:40<04:31,  2.22it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:38:38<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:33:08<?, ?it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4292/4895 [1:32:40<04:11,  2.40it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:33:14<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_146 (50 files)

💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4293/4895 [1:32:41<03:51,  2.60it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4294/4895 [1:32:41<04:00,  2.50it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4295/4895 [1:32:42<05:40,  1.76it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4296/4895 [1:32:43<06:34,  1.52it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4297/4895 [1:32:44<08:43,  1.14it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▏    | 4298/4895 [1:32:44<06:34,  1.51it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4299/4895 [1:32:45<05:30,  1.81it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4300/4895 [1:32:45<05:10,  1.92it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4301/4895 [1:32:46<05:31,  1.79it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4302/4895 [1:32:46<05:44,  1.72it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4303/4895 [1:32:47<05:30,  1.79it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4304/4895 [1:32:49<09:10,  1.07it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4305/4895 [1:32:49<06:48,  1.44it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4306/4895 [1:32:51<09:55,  1.01s/it]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4307/4895 [1:32:52<09:37,  1.02it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4308/4895 [1:32:54<12:39,  1.29s/it]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4309/4895 [1:32:56<15:19,  1.57s/it]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4310/4895 [1:32:56<12:46,  1.31s/it]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4311/4895 [1:32:57<09:36,  1.01it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4312/4895 [1:32:58<09:30,  1.02it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4313/4895 [1:32:58<08:15,  1.17it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▎    | 4314/4895 [1:32:59<07:27,  1.30it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4315/4895 [1:32:59<07:00,  1.38it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4316/4895 [1:33:00<06:44,  1.43it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4317/4895 [1:33:00<05:19,  1.81it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4318/4895 [1:33:01<05:37,  1.71it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4319/4895 [1:33:01<04:23,  2.18it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4320/4895 [1:33:01<03:34,  2.68it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4321/4895 [1:33:02<03:43,  2.57it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4322/4895 [1:33:02<04:05,  2.34it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4323/4895 [1:33:02<03:30,  2.71it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4324/4895 [1:33:03<04:24,  2.16it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4325/4895 [1:33:03<03:45,  2.53it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4326/4895 [1:33:04<04:01,  2.36it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4327/4895 [1:33:04<04:15,  2.23it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4328/4895 [1:33:05<04:52,  1.94it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4329/4895 [1:33:05<04:41,  2.01it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▍    | 4330/4895 [1:33:06<04:20,  2.17it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▌    | 4331/4895 [1:33:06<04:30,  2.08it/s]


💽 TQM COPY FLOW:  88%|██████████████████████████████████▌    | 4332/4895 [1:33:07<04:19,  2.17it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4333/4895 [1:33:07<04:08,  2.26it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4334/4895 [1:33:08<05:05,  1.84it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4335/4895 [1:33:08<04:19,  2.16it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4336/4895 [1:33:09<03:59,  2.33it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4337/4895 [1:33:09<04:23,  2.12it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4338/4895 [1:33:10<04:32,  2.05it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4339/4895 [1:33:10<04:34,  2.03it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4340/4895 [1:33:11<05:06,  1.81it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4341/4895 [1:33:12<06:56,  1.33it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:39:11<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:33:40<?, ?it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4342/4895 [1:33:13<07:18,  1.26it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:33:47<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_147 (50 files)

💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4343/4895 [1:33:16<14:17,  1.55s/it]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4344/4895 [1:33:17<11:25,  1.24s/it]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▌    | 4345/4895 [1:33:17<09:10,  1.00s/it]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4346/4895 [1:33:18<07:25,  1.23it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4347/4895 [1:33:18<06:17,  1.45it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4348/4895 [1:33:19<06:54,  1.32it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4349/4895 [1:33:20<06:32,  1.39it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4350/4895 [1:33:21<07:10,  1.27it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4351/4895 [1:33:21<07:13,  1.25it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4352/4895 [1:33:22<07:49,  1.16it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4353/4895 [1:33:23<07:44,  1.17it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4354/4895 [1:33:24<07:03,  1.28it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4355/4895 [1:33:25<08:51,  1.02it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4356/4895 [1:33:26<09:02,  1.01s/it]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4357/4895 [1:33:27<06:58,  1.28it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4358/4895 [1:33:27<06:48,  1.31it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4359/4895 [1:33:28<05:45,  1.55it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4360/4895 [1:33:29<08:31,  1.05it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▋    | 4361/4895 [1:33:30<07:33,  1.18it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4362/4895 [1:33:31<07:28,  1.19it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4363/4895 [1:33:32<07:35,  1.17it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4364/4895 [1:33:32<06:10,  1.43it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4365/4895 [1:33:32<04:55,  1.79it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4366/4895 [1:33:33<04:39,  1.89it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4367/4895 [1:33:33<04:41,  1.88it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4368/4895 [1:33:34<04:34,  1.92it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4369/4895 [1:33:34<04:53,  1.79it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4370/4895 [1:33:35<04:17,  2.04it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4371/4895 [1:33:35<04:21,  2.01it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4372/4895 [1:33:36<04:07,  2.11it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4373/4895 [1:33:36<04:21,  1.99it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4374/4895 [1:33:37<04:28,  1.94it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4375/4895 [1:33:38<05:22,  1.61it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4376/4895 [1:33:38<04:39,  1.86it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▊    | 4377/4895 [1:33:38<04:02,  2.13it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▉    | 4378/4895 [1:33:39<04:28,  1.92it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▉    | 4379/4895 [1:33:39<04:30,  1.90it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▉    | 4380/4895 [1:33:40<04:32,  1.89it/s]


💽 TQM COPY FLOW:  89%|██████████████████████████████████▉    | 4381/4895 [1:33:40<04:27,  1.92it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4382/4895 [1:33:41<04:15,  2.01it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4383/4895 [1:33:42<04:52,  1.75it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4384/4895 [1:33:42<04:39,  1.83it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4385/4895 [1:33:43<04:42,  1.80it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4386/4895 [1:33:43<04:22,  1.94it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4387/4895 [1:33:44<04:39,  1.82it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4388/4895 [1:33:44<04:54,  1.72it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4389/4895 [1:33:45<05:42,  1.48it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4390/4895 [1:33:46<06:35,  1.28it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4391/4895 [1:33:47<06:01,  1.39it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:39:46<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:34:15<?, ?it/s]


💽 TQM COPY FLOW:  90%|██████████████████████████████████▉    | 4392/4895 [1:33:48<06:29,  1.29it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:34:22<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_148 (50 files)

💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4393/4895 [1:33:53<17:09,  2.05s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4394/4895 [1:33:53<13:29,  1.62s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4395/4895 [1:33:54<11:30,  1.38s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4396/4895 [1:33:55<09:53,  1.19s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4397/4895 [1:33:56<08:59,  1.08s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4398/4895 [1:33:57<08:06,  1.02it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4399/4895 [1:33:57<07:19,  1.13it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4400/4895 [1:33:58<07:47,  1.06it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4401/4895 [1:33:59<07:11,  1.14it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4402/4895 [1:34:00<07:31,  1.09it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4403/4895 [1:34:01<06:50,  1.20it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4404/4895 [1:34:02<08:39,  1.06s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4405/4895 [1:34:03<07:59,  1.02it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4406/4895 [1:34:04<07:18,  1.11it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4407/4895 [1:34:05<07:30,  1.08it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████    | 4408/4895 [1:34:06<07:23,  1.10it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4409/4895 [1:34:07<07:18,  1.11it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4410/4895 [1:34:07<06:45,  1.20it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4411/4895 [1:34:08<06:19,  1.28it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4412/4895 [1:34:09<05:51,  1.37it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4413/4895 [1:34:09<06:25,  1.25it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4414/4895 [1:34:10<05:28,  1.46it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4415/4895 [1:34:11<05:33,  1.44it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4416/4895 [1:34:11<04:53,  1.63it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4417/4895 [1:34:12<04:39,  1.71it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4418/4895 [1:34:12<04:55,  1.61it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4419/4895 [1:34:13<05:18,  1.49it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4420/4895 [1:34:14<05:40,  1.39it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4421/4895 [1:34:15<07:06,  1.11it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4422/4895 [1:34:16<07:04,  1.12it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4423/4895 [1:34:17<06:46,  1.16it/s]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▏   | 4424/4895 [1:34:18<08:26,  1.08s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▎   | 4425/4895 [1:34:20<09:01,  1.15s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▎   | 4426/4895 [1:34:21<09:04,  1.16s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▎   | 4427/4895 [1:34:23<10:20,  1.33s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▎   | 4428/4895 [1:34:24<11:00,  1.42s/it]


💽 TQM COPY FLOW:  90%|███████████████████████████████████▎   | 4429/4895 [1:34:25<09:22,  1.21s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4430/4895 [1:34:26<07:43,  1.00it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4431/4895 [1:34:26<07:07,  1.09it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4432/4895 [1:34:27<06:14,  1.24it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4433/4895 [1:34:27<05:25,  1.42it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4434/4895 [1:34:28<05:21,  1.43it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4435/4895 [1:34:29<05:11,  1.48it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4436/4895 [1:34:29<04:39,  1.64it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4437/4895 [1:34:33<11:26,  1.50s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4438/4895 [1:34:33<09:09,  1.20s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4439/4895 [1:34:35<10:45,  1.41s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▎   | 4440/4895 [1:34:36<08:57,  1.18s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4441/4895 [1:34:37<08:32,  1.13s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:40:35<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:35:05<?, ?it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4442/4895 [1:34:37<07:21,  1.03it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:35:11<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_149 (50 files)

💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4443/4895 [1:34:43<18:28,  2.45s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4444/4895 [1:34:44<14:59,  2.00s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4445/4895 [1:34:45<12:19,  1.64s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4446/4895 [1:34:46<10:20,  1.38s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4447/4895 [1:34:47<09:23,  1.26s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4448/4895 [1:34:48<09:38,  1.29s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4449/4895 [1:34:49<09:00,  1.21s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4450/4895 [1:34:50<07:57,  1.07s/it]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4451/4895 [1:34:50<06:56,  1.07it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4452/4895 [1:34:51<05:45,  1.28it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4453/4895 [1:34:52<06:48,  1.08it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4454/4895 [1:34:53<05:56,  1.24it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▍   | 4455/4895 [1:34:53<05:24,  1.36it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4456/4895 [1:34:54<05:37,  1.30it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4457/4895 [1:34:55<05:05,  1.44it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4458/4895 [1:34:55<05:06,  1.43it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4459/4895 [1:34:56<04:37,  1.57it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4460/4895 [1:34:56<04:28,  1.62it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4461/4895 [1:34:57<04:58,  1.45it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4462/4895 [1:34:58<04:51,  1.48it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4463/4895 [1:34:59<05:03,  1.42it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4464/4895 [1:34:59<05:01,  1.43it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4465/4895 [1:35:00<05:24,  1.33it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4466/4895 [1:35:01<05:13,  1.37it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4467/4895 [1:35:01<04:51,  1.47it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4468/4895 [1:35:02<04:40,  1.52it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4469/4895 [1:35:03<06:15,  1.13it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4470/4895 [1:35:04<06:11,  1.14it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▌   | 4471/4895 [1:35:05<05:58,  1.18it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▋   | 4472/4895 [1:35:06<05:52,  1.20it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▋   | 4473/4895 [1:35:07<05:52,  1.20it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▋   | 4474/4895 [1:35:07<05:29,  1.28it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▋   | 4475/4895 [1:35:08<05:27,  1.28it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▋   | 4476/4895 [1:35:09<05:45,  1.21it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▋   | 4477/4895 [1:35:10<05:08,  1.36it/s]


💽 TQM COPY FLOW:  91%|███████████████████████████████████▋   | 4478/4895 [1:35:10<05:08,  1.35it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4479/4895 [1:35:11<05:48,  1.19it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4480/4895 [1:35:12<05:40,  1.22it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4481/4895 [1:35:13<05:26,  1.27it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4482/4895 [1:35:14<05:29,  1.25it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4483/4895 [1:35:14<04:36,  1.49it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4484/4895 [1:35:15<04:27,  1.54it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4485/4895 [1:35:16<04:57,  1.38it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4486/4895 [1:35:16<04:42,  1.45it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▋   | 4487/4895 [1:35:17<05:38,  1.21it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4488/4895 [1:35:18<05:12,  1.30it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4489/4895 [1:35:19<06:35,  1.03it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4490/4895 [1:35:21<08:39,  1.28s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4491/4895 [1:35:27<16:15,  2.42s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:41:25<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:35:55<?, ?it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4492/4895 [1:35:27<12:52,  1.92s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:36:01<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_150 (50 files)

💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4493/4895 [1:35:30<14:16,  2.13s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4494/4895 [1:35:30<11:00,  1.65s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4495/4895 [1:35:31<08:56,  1.34s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4496/4895 [1:35:33<10:56,  1.65s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4497/4895 [1:35:35<10:18,  1.55s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4498/4895 [1:35:36<09:26,  1.43s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4499/4895 [1:35:36<07:36,  1.15s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4500/4895 [1:35:37<07:01,  1.07s/it]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4501/4895 [1:35:38<06:26,  1.02it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▊   | 4502/4895 [1:35:38<05:23,  1.21it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4503/4895 [1:35:40<06:10,  1.06it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4504/4895 [1:35:41<06:03,  1.08it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4505/4895 [1:35:42<06:06,  1.06it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4506/4895 [1:35:43<06:23,  1.01it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4507/4895 [1:35:43<05:19,  1.21it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4508/4895 [1:35:44<05:29,  1.17it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4509/4895 [1:35:45<05:37,  1.14it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4510/4895 [1:35:46<05:37,  1.14it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4511/4895 [1:35:47<05:20,  1.20it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4512/4895 [1:35:47<05:11,  1.23it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4513/4895 [1:35:48<04:46,  1.34it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4514/4895 [1:35:49<04:47,  1.33it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4515/4895 [1:35:50<05:13,  1.21it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4516/4895 [1:35:50<04:43,  1.34it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4517/4895 [1:35:52<05:39,  1.11it/s]


💽 TQM COPY FLOW:  92%|███████████████████████████████████▉   | 4518/4895 [1:35:53<06:13,  1.01it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4519/4895 [1:35:54<06:19,  1.01s/it]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4520/4895 [1:35:55<05:46,  1.08it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4521/4895 [1:35:55<05:28,  1.14it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4522/4895 [1:35:56<05:57,  1.04it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4523/4895 [1:35:57<05:01,  1.23it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4524/4895 [1:35:58<04:56,  1.25it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4525/4895 [1:35:59<05:42,  1.08it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4526/4895 [1:35:59<04:58,  1.24it/s]


💽 TQM COPY FLOW:  92%|████████████████████████████████████   | 4527/4895 [1:36:00<04:57,  1.24it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████   | 4528/4895 [1:36:02<06:15,  1.02s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████   | 4529/4895 [1:36:03<06:25,  1.05s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████   | 4530/4895 [1:36:04<06:05,  1.00s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████   | 4531/4895 [1:36:05<06:16,  1.04s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████   | 4532/4895 [1:36:06<05:54,  1.02it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████   | 4533/4895 [1:36:07<06:30,  1.08s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████   | 4534/4895 [1:36:08<06:52,  1.14s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4535/4895 [1:36:09<05:59,  1.00it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4536/4895 [1:36:10<05:37,  1.06it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4537/4895 [1:36:11<05:31,  1.08it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4538/4895 [1:36:11<04:59,  1.19it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4539/4895 [1:36:12<04:48,  1.23it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4540/4895 [1:36:13<04:19,  1.37it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4541/4895 [1:36:14<04:45,  1.24it/s]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:42:12<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:36:42<?, ?it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4542/4895 [1:36:14<04:40,  1.26it/s]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:36:48<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_151 (50 files)

💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4543/4895 [1:36:17<07:20,  1.25s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4544/4895 [1:36:17<06:22,  1.09s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4545/4895 [1:36:18<04:58,  1.17it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4546/4895 [1:36:18<04:17,  1.35it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4547/4895 [1:36:19<03:46,  1.54it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4548/4895 [1:36:19<03:53,  1.49it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▏  | 4549/4895 [1:36:20<03:36,  1.60it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4550/4895 [1:36:21<03:53,  1.48it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4551/4895 [1:36:21<03:55,  1.46it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4552/4895 [1:36:22<04:09,  1.37it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4553/4895 [1:36:23<04:51,  1.17it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4554/4895 [1:36:24<04:54,  1.16it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4555/4895 [1:36:25<04:53,  1.16it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4556/4895 [1:36:26<04:35,  1.23it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4557/4895 [1:36:27<04:38,  1.22it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4558/4895 [1:36:27<04:03,  1.38it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4559/4895 [1:36:28<03:37,  1.54it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4560/4895 [1:36:29<04:07,  1.35it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4561/4895 [1:36:29<03:16,  1.70it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4562/4895 [1:36:29<03:10,  1.75it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4563/4895 [1:36:30<03:14,  1.71it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4564/4895 [1:36:30<02:43,  2.03it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▎  | 4565/4895 [1:36:31<03:08,  1.75it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4566/4895 [1:36:32<03:25,  1.60it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4567/4895 [1:36:33<03:55,  1.39it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4568/4895 [1:36:34<04:54,  1.11it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4569/4895 [1:36:35<05:55,  1.09s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4570/4895 [1:36:36<05:12,  1.04it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4571/4895 [1:36:38<07:25,  1.37s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4572/4895 [1:36:40<07:08,  1.33s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4573/4895 [1:36:40<06:06,  1.14s/it]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4574/4895 [1:36:41<05:15,  1.02it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4575/4895 [1:36:42<04:38,  1.15it/s]


💽 TQM COPY FLOW:  93%|████████████████████████████████████▍  | 4576/4895 [1:36:42<03:36,  1.48it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▍  | 4577/4895 [1:36:42<02:56,  1.80it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▍  | 4578/4895 [1:36:42<02:17,  2.31it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▍  | 4579/4895 [1:36:43<02:01,  2.61it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▍  | 4580/4895 [1:36:43<02:15,  2.33it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▍  | 4581/4895 [1:36:44<02:42,  1.93it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4582/4895 [1:36:44<02:53,  1.80it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4583/4895 [1:36:45<02:32,  2.04it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4584/4895 [1:36:45<02:40,  1.94it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4585/4895 [1:36:46<02:38,  1.96it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4586/4895 [1:36:48<05:17,  1.03s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:42:51<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:37:20<?, ?it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4587/4895 [1:36:53<10:55,  2.13s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:37:26<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_152 (45 files)

💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4588/4895 [1:37:00<18:08,  3.55s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4589/4895 [1:37:01<14:33,  2.85s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4590/4895 [1:37:02<11:17,  2.22s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4591/4895 [1:37:02<08:21,  1.65s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:43:01<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:37:30<?, ?it/s]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4592/4895 [1:37:03<06:59,  1.38s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:37:36<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_153 (5 files)

💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4593/4895 [1:37:03<05:43,  1.14s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4594/4895 [1:37:04<05:39,  1.13s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4595/4895 [1:37:06<06:01,  1.21s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▌  | 4596/4895 [1:37:16<19:17,  3.87s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4597/4895 [1:37:26<28:46,  5.79s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4598/4895 [1:37:33<29:43,  6.01s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4599/4895 [1:37:40<31:03,  6.30s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4600/4895 [1:37:41<23:17,  4.74s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4601/4895 [1:37:42<17:41,  3.61s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4602/4895 [1:37:43<14:11,  2.91s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4603/4895 [1:37:44<11:48,  2.43s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4604/4895 [1:37:46<10:49,  2.23s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4605/4895 [1:37:47<09:19,  1.93s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4606/4895 [1:37:48<08:06,  1.68s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4607/4895 [1:37:49<07:08,  1.49s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4608/4895 [1:37:50<06:13,  1.30s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4609/4895 [1:37:51<05:46,  1.21s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4610/4895 [1:37:52<05:19,  1.12s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4611/4895 [1:37:54<06:55,  1.46s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▋  | 4612/4895 [1:38:02<16:14,  3.44s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4613/4895 [1:38:03<12:34,  2.67s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4614/4895 [1:38:05<11:08,  2.38s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4615/4895 [1:38:10<14:27,  3.10s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4616/4895 [1:38:14<16:30,  3.55s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4617/4895 [1:38:23<23:14,  5.02s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4618/4895 [1:38:30<25:54,  5.61s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4619/4895 [1:38:31<19:09,  4.16s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4620/4895 [1:38:31<14:25,  3.15s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4621/4895 [1:38:38<18:56,  4.15s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4622/4895 [1:38:46<23:53,  5.25s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4623/4895 [1:38:47<18:01,  3.98s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4624/4895 [1:38:48<13:55,  3.08s/it]


💽 TQM COPY FLOW:  94%|████████████████████████████████████▊  | 4625/4895 [1:38:53<16:41,  3.71s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▊  | 4626/4895 [1:39:02<23:37,  5.27s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▊  | 4627/4895 [1:39:08<25:06,  5.62s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▊  | 4628/4895 [1:39:09<18:57,  4.26s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4629/4895 [1:39:13<18:01,  4.07s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4630/4895 [1:39:14<13:33,  3.07s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4631/4895 [1:39:19<16:12,  3.68s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4632/4895 [1:39:21<14:26,  3.29s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4633/4895 [1:39:23<12:02,  2.76s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4634/4895 [1:39:25<11:27,  2.64s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4635/4895 [1:39:27<10:45,  2.48s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4636/4895 [1:39:28<08:58,  2.08s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4637/4895 [1:39:30<07:48,  1.82s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4638/4895 [1:39:30<06:32,  1.53s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4639/4895 [1:39:32<06:18,  1.48s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4640/4895 [1:39:32<05:13,  1.23s/it]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4641/4895 [1:39:33<04:43,  1.11s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:45:32<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:40:02<?, ?it/s]


💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4642/4895 [1:39:34<04:36,  1.09s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:40:08<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_154 (50 files)

💽 TQM COPY FLOW:  95%|████████████████████████████████████▉  | 4643/4895 [1:39:37<06:38,  1.58s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4644/4895 [1:39:38<06:21,  1.52s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4645/4895 [1:39:46<13:21,  3.21s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4646/4895 [1:39:47<11:19,  2.73s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4647/4895 [1:39:49<10:11,  2.47s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4648/4895 [1:39:50<08:56,  2.17s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4649/4895 [1:39:52<08:13,  2.01s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4650/4895 [1:39:57<12:00,  2.94s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4651/4895 [1:40:09<22:50,  5.62s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4652/4895 [1:40:11<18:32,  4.58s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4653/4895 [1:40:13<15:15,  3.78s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4654/4895 [1:40:15<12:25,  3.09s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4655/4895 [1:40:20<15:26,  3.86s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4656/4895 [1:40:22<13:02,  3.27s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4657/4895 [1:40:29<16:45,  4.23s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:46:29<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:40:58<?, ?it/s]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4658/4895 [1:40:31<13:59,  3.54s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:41:04<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_155 (16 files)

💽 TQM COPY FLOW:  95%|█████████████████████████████████████  | 4659/4895 [1:40:32<11:43,  2.98s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4660/4895 [1:40:34<10:02,  2.56s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4661/4895 [1:40:36<09:10,  2.35s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4662/4895 [1:40:37<07:52,  2.03s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4663/4895 [1:40:39<08:05,  2.09s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4664/4895 [1:40:41<07:22,  1.91s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4665/4895 [1:40:42<06:24,  1.67s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4666/4895 [1:40:43<06:06,  1.60s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4667/4895 [1:40:44<05:07,  1.35s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4668/4895 [1:40:45<04:56,  1.31s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4669/4895 [1:40:47<04:58,  1.32s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4670/4895 [1:40:48<04:41,  1.25s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4671/4895 [1:40:49<04:42,  1.26s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4672/4895 [1:40:51<04:59,  1.34s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4673/4895 [1:40:52<05:13,  1.41s/it]


💽 TQM COPY FLOW:  95%|█████████████████████████████████████▏ | 4674/4895 [1:40:54<05:19,  1.45s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▏ | 4675/4895 [1:40:55<04:47,  1.31s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4676/4895 [1:40:57<05:55,  1.62s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4677/4895 [1:40:59<05:48,  1.60s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4678/4895 [1:40:59<04:55,  1.36s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4679/4895 [1:41:01<04:59,  1.39s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4680/4895 [1:41:01<04:03,  1.13s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4681/4895 [1:41:03<04:24,  1.24s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4682/4895 [1:41:07<08:00,  2.25s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4683/4895 [1:41:08<06:30,  1.84s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4684/4895 [1:41:09<05:08,  1.46s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4685/4895 [1:41:11<05:31,  1.58s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4686/4895 [1:41:13<05:58,  1.72s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4687/4895 [1:41:15<06:17,  1.81s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4688/4895 [1:41:17<06:13,  1.81s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4689/4895 [1:41:18<06:08,  1.79s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4690/4895 [1:41:24<10:32,  3.09s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▎ | 4691/4895 [1:41:26<08:43,  2.57s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4692/4895 [1:41:27<07:33,  2.24s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4693/4895 [1:41:29<06:33,  1.95s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4694/4895 [1:41:30<06:07,  1.83s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4695/4895 [1:41:32<06:24,  1.92s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4696/4895 [1:41:35<06:45,  2.04s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4697/4895 [1:41:36<06:13,  1.89s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4698/4895 [1:41:37<05:27,  1.66s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4699/4895 [1:41:38<04:47,  1.47s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4700/4895 [1:41:40<04:36,  1.42s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4701/4895 [1:41:41<04:09,  1.29s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4702/4895 [1:41:42<04:14,  1.32s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4703/4895 [1:41:43<03:58,  1.24s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4704/4895 [1:41:49<08:07,  2.55s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:47:49<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:42:18<?, ?it/s]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4705/4895 [1:41:51<07:50,  2.47s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:42:25<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_156 (47 files)

💽 TQM COPY FLOW:  96%|█████████████████████████████████████▍ | 4706/4895 [1:42:00<13:53,  4.41s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4707/4895 [1:42:01<10:37,  3.39s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4708/4895 [1:42:06<12:41,  4.07s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4709/4895 [1:42:15<16:31,  5.33s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4710/4895 [1:42:16<12:54,  4.18s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4711/4895 [1:42:22<13:57,  4.55s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4712/4895 [1:42:23<10:41,  3.51s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4713/4895 [1:42:27<11:08,  3.67s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4714/4895 [1:42:35<15:17,  5.07s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4715/4895 [1:42:40<15:08,  5.05s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4716/4895 [1:42:41<11:05,  3.72s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4717/4895 [1:42:48<14:34,  4.91s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4718/4895 [1:42:49<11:04,  3.75s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4719/4895 [1:42:51<08:44,  2.98s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4720/4895 [1:42:57<12:04,  4.14s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4721/4895 [1:42:59<09:47,  3.38s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▌ | 4722/4895 [1:43:06<12:59,  4.51s/it]


💽 TQM COPY FLOW:  96%|█████████████████████████████████████▋ | 4723/4895 [1:43:07<09:50,  3.43s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4724/4895 [1:43:09<08:20,  2.92s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4725/4895 [1:43:14<10:14,  3.62s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4726/4895 [1:43:20<12:07,  4.31s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4727/4895 [1:43:21<09:14,  3.30s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4728/4895 [1:43:23<07:50,  2.82s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4729/4895 [1:43:30<11:48,  4.27s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4730/4895 [1:43:41<16:37,  6.04s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4731/4895 [1:43:48<17:33,  6.42s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4732/4895 [1:43:49<13:15,  4.88s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4733/4895 [1:43:54<13:13,  4.90s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4734/4895 [1:43:58<12:16,  4.57s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4735/4895 [1:44:11<18:57,  7.11s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4736/4895 [1:44:12<14:11,  5.36s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4737/4895 [1:44:19<15:33,  5.91s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▋ | 4738/4895 [1:44:25<15:35,  5.96s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4739/4895 [1:44:26<11:31,  4.43s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4740/4895 [1:44:28<08:56,  3.46s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4741/4895 [1:44:28<06:48,  2.66s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:50:36<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:45:06<?, ?it/s]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4742/4895 [1:44:38<12:23,  4.86s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:45:12<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_157 (37 files)

💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4743/4895 [1:44:42<11:44,  4.64s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4744/4895 [1:44:48<12:29,  4.96s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4745/4895 [1:44:49<09:28,  3.79s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4746/4895 [1:44:50<07:25,  2.99s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4747/4895 [1:44:51<05:45,  2.33s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4748/4895 [1:44:52<04:58,  2.03s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4749/4895 [1:45:02<10:20,  4.25s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4750/4895 [1:45:03<08:07,  3.36s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4751/4895 [1:45:10<10:50,  4.52s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4752/4895 [1:45:15<10:33,  4.43s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▊ | 4753/4895 [1:45:17<09:02,  3.82s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4754/4895 [1:45:18<06:45,  2.87s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4755/4895 [1:45:19<05:32,  2.37s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4756/4895 [1:45:25<08:24,  3.63s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4757/4895 [1:45:27<07:01,  3.05s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:51:32<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:46:01<?, ?it/s]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4758/4895 [1:45:34<09:19,  4.08s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:46:07<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_158 (16 files)

💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4759/4895 [1:45:36<08:12,  3.62s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4760/4895 [1:45:37<06:02,  2.69s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4761/4895 [1:45:37<04:30,  2.02s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4762/4895 [1:45:38<03:31,  1.59s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4763/4895 [1:45:38<02:52,  1.31s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4764/4895 [1:45:40<02:57,  1.36s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4765/4895 [1:45:42<03:45,  1.73s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4766/4895 [1:45:43<02:53,  1.34s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4767/4895 [1:45:43<02:23,  1.12s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4768/4895 [1:45:44<02:08,  1.01s/it]


💽 TQM COPY FLOW:  97%|█████████████████████████████████████▉ | 4769/4895 [1:45:46<02:45,  1.32s/it]


💽 TQM COPY FLOW:  97%|██████████████████████████████████████ | 4770/4895 [1:45:47<02:36,  1.25s/it]


💽 TQM COPY FLOW:  97%|██████████████████████████████████████ | 4771/4895 [1:45:52<04:48,  2.33s/it]


💽 TQM COPY FLOW:  97%|██████████████████████████████████████ | 4772/4895 [1:45:53<03:41,  1.80s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4773/4895 [1:45:54<03:11,  1.57s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4774/4895 [1:45:54<02:29,  1.24s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4775/4895 [1:45:55<02:00,  1.00s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4776/4895 [1:45:56<02:00,  1.01s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4777/4895 [1:45:57<01:50,  1.06it/s]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4778/4895 [1:45:58<02:01,  1.04s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4779/4895 [1:45:59<02:14,  1.16s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4780/4895 [1:46:01<02:23,  1.25s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4781/4895 [1:46:02<02:32,  1.34s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4782/4895 [1:46:04<02:53,  1.54s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4783/4895 [1:46:10<05:17,  2.83s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4784/4895 [1:46:10<03:50,  2.08s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████ | 4785/4895 [1:46:14<04:41,  2.56s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4786/4895 [1:46:18<05:27,  3.00s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4787/4895 [1:46:19<04:06,  2.28s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4788/4895 [1:46:19<03:09,  1.77s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4789/4895 [1:46:20<02:37,  1.49s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4790/4895 [1:46:21<02:24,  1.38s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4791/4895 [1:46:23<02:21,  1.36s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4792/4895 [1:46:24<02:16,  1.32s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4793/4895 [1:46:25<02:16,  1.34s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4794/4895 [1:46:27<02:23,  1.43s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4795/4895 [1:46:32<04:02,  2.42s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4796/4895 [1:46:33<03:24,  2.07s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4797/4895 [1:46:34<02:55,  1.79s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4798/4895 [1:46:35<02:42,  1.68s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4799/4895 [1:46:37<02:26,  1.53s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▏| 4800/4895 [1:46:37<01:59,  1.26s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4801/4895 [1:46:38<01:58,  1.26s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4802/4895 [1:46:39<01:36,  1.04s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4803/4895 [1:46:40<01:32,  1.00s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4804/4895 [1:46:40<01:20,  1.13it/s]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4805/4895 [1:46:42<01:40,  1.11s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4806/4895 [1:46:44<01:52,  1.27s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4807/4895 [1:46:45<01:43,  1.18s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:52:43<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:47:13<?, ?it/s]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4808/4895 [1:46:45<01:29,  1.03s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:47:19<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_159 (50 files)

💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4809/4895 [1:46:49<02:28,  1.73s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4810/4895 [1:46:49<02:00,  1.42s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4811/4895 [1:46:50<01:28,  1.05s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4812/4895 [1:46:51<01:33,  1.13s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4813/4895 [1:46:52<01:29,  1.09s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4814/4895 [1:46:54<01:45,  1.30s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4815/4895 [1:46:55<01:41,  1.26s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▎| 4816/4895 [1:46:56<01:31,  1.16s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▍| 4817/4895 [1:46:57<01:27,  1.12s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▍| 4818/4895 [1:46:58<01:23,  1.08s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:52:57<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:47:26<?, ?it/s]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▍| 4819/4895 [1:46:59<01:20,  1.05s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:47:33<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_160 (11 files)

💽 TQM COPY FLOW:  98%|██████████████████████████████████████▍| 4820/4895 [1:47:00<01:21,  1.08s/it]


💽 TQM COPY FLOW:  98%|██████████████████████████████████████▍| 4821/4895 [1:47:01<01:13,  1.00it/s]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4822/4895 [1:47:02<01:16,  1.05s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4823/4895 [1:47:03<01:24,  1.17s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4824/4895 [1:47:05<01:26,  1.22s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4825/4895 [1:47:07<01:40,  1.44s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:53:06<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:47:35<?, ?it/s]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4826/4895 [1:47:08<01:32,  1.33s/it]
💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:47:42<?, ?it/s]

📦 Finished chunk: _24_ARCH_rk_161 (7 files)

💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4827/4895 [1:47:09<01:33,  1.38s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4828/4895 [1:47:11<01:31,  1.37s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4829/4895 [1:47:12<01:31,  1.38s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4830/4895 [1:47:14<01:32,  1.42s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4831/4895 [1:47:14<01:20,  1.26s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▍| 4832/4895 [1:47:15<01:11,  1.14s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4833/4895 [1:47:16<01:08,  1.10s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4834/4895 [1:47:17<01:07,  1.11s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4835/4895 [1:47:19<01:20,  1.34s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4836/4895 [1:47:21<01:21,  1.38s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4837/4895 [1:47:22<01:10,  1.22s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4838/4895 [1:47:23<01:08,  1.21s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4839/4895 [1:47:24<01:13,  1.31s/it]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4840/4895 [1:47:27<01:25,  1.56s/it]








💽 TQM COPY FLOW:   2%|▊                                        | 93/4895 [1:53:26<31:39,  2.53it/s]

💽 TQM COPY FLOW:   0%|                                                  | 0/4895 [1:47:56<?, ?it/s]


💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4841/4895 [1:47:28<01:28,  1.64s/it]
💽 TQM COPY FLOW:  99%|██████████████████████████████████████▌| 4841/4895 [1:47:28<01:11,  1.33s/it]

📦 Final chunk: _24_ARCH_rk_162 (15 files)

✅ Done. Log saved at: /Volumes/MY1TB/_24_ARCH_SONGS/copied_log.csv

In [29]:
50*162

8100