# start

In [1]:
# attn USE this for new ADDS

f"NA-TRkw_{title}_ARkw_{artist_val}_MXkw_{remix}_KYkw_{key}_"
            f"BPkw_{bpm}_GNkw_{genre_val}_LBkw_{label_val}_RYkw_{release_date_val}_"
            f"PYkw_{purchase_date_val}{ext}"

IndentationError: unexpected indent (4271792928.py, line 4)

In [1]:
# -----######-----###### RENAME FINAL: FULL CONTROL + PUkw CORRECTED -----######-----######
import os
import pandas as pd
from tqdm import tqdm
from datetime import datetime

def _rename_2304_kwtagging_GET_renamed_files_from_txt(
    txt_path,
    custom_artist="DJ_Selphi",
    custom_genre="Salsa",
    custom_label="Bachata",
    custom_release_date="",
    custom_purchase_date=""
):
    """
    Rename files using a kw-tag structure with optional custom overrides.
    Pulls from TXT if any override is left blank.

    Args:
        txt_path (str): Path to UTF-16 tab-separated metadata file
        custom_artist (str): Optional override for artist (max 25 chars)
        custom_genre (str): Optional override for genre
        custom_label (str): Optional override for label
        custom_release_date (str): Optional override in YYYY_MM_DD format
        custom_purchase_date (str): Optional override in YYYY_MM_DD format

    Returns:
        pd.DataFrame: Original DataFrame + 'Renamed_Path' column
    """
    tqdm.pandas()

    df = pd.read_csv(
        txt_path,
        sep="\t",
        encoding='utf-16',
        engine='python',
        on_bad_lines='skip'
    )
    
    df.columns = df.columns.str.strip()

    def clean(s):
        return (
            str(s)
            .replace(" ", "_").replace("/", "___").replace(",", "_")
            .replace("(", "").replace(")", "").replace("!", "")
            .replace("&", "and").replace("’", "").replace("'", "")
            .replace("¿", "").replace("¡", "").replace(":", "")
            .replace(";", "").strip()
        )

    def extract_mix(title):
        title_lower = title.lower()
        if "remix" in title_lower or "mix" in title_lower:
            return clean(title)
        return "original"

    def format_filename(row):
        title = clean(row.get('Track Title', ''))[:25]
        remix = extract_mix(row.get('Track Title', ''))

        artist_val = clean(custom_artist)[:25] if custom_artist else clean(row.get('Artist', ''))[:25]
        genre_val = clean(custom_genre) if custom_genre else clean(row.get('Genre', ''))
        label_val = clean(custom_label) if custom_label else clean(row.get('Label', ''))

        # ✅ FIXED: Use Release Date column if custom_release_date not passed
        release_date_val = (
            custom_release_date if custom_release_date
            else pd.to_datetime(row.get('Release Date', ''), errors='coerce').strftime('%Y_%m_%d')
            if pd.notna(row.get('Release Date', '')) else 'NA'
        )

        key = clean(row.get('Key', 'NA')) if pd.notna(row.get('Key', '')) else 'NA'
        bpm = str(int(round(float(row.get('BPM', 0))))) if pd.notna(row.get('BPM', 0)) else 'NA'

        date_added = pd.to_datetime(row.get('Date Added', datetime.today()), errors='coerce').strftime('%Y_%m_%d')
        purchase_date_val = (
            custom_purchase_date if custom_purchase_date
            else pd.to_datetime(row.get('Purchased', datetime.today()), errors='coerce').strftime('%Y_%m_%d')
        )

        ext = os.path.splitext(row.get('Location', ''))[1]

        new_name = (
            f"TRkw_{title}_ARkw_{artist_val}_MXkw_{remix}_KYkw_{key}_"
            f"BPkw_{bpm}_GNkw_{genre_val}_LBkw_{label_val}_RYkw_{release_date_val}_"
            f"PYkw_{purchase_date_val}{ext}"
        )

        if len(new_name) > 240:
            new_name = new_name[:230] + ext

        return new_name

    new_paths = []
    log_long_names = []

    for i, row in tqdm(df.iterrows(), total=len(df), desc="Renaming files"):
        original_path = str(row.get('Location', '')).strip()

        if not os.path.isfile(original_path):
            print(f"❌ File not found (Row {i}): {original_path}")
            new_paths.append(None)
            continue

        new_filename = format_filename(row)
        new_path = os.path.join(os.path.dirname(original_path), new_filename)

        try:
            os.rename(original_path, new_path)
            new_paths.append(new_path)
        except Exception as e:
            print(f"❌ Error renaming (Row {i}): {e}")
            new_paths.append(None)
            log_long_names.append({
                "Index": i,
                "OriginalPath": original_path,
                "IntendedFilename": new_filename,
                "Error": str(e)
            })

    df['Renamed_Path'] = new_paths

    if log_long_names:
        pd.DataFrame(log_long_names).to_csv("long_name_errors_log.csv", index=False)
        print("📁 Saved log of failed renames to: long_name_errors_log.csv")

    return df

In [2]:
txt_path ='/Users/yerik/Desktop/MARCH_pl.txt'

In [3]:
#!#!#!#!#! RUNNING STATEMENTS #!#!#!#!#!



df = _rename_2304_kwtagging_GET_renamed_files_from_txt(
    txt_path,
    custom_artist="",           # ✅ or "" for TXT
    custom_genre="",                # ✅ or "" for TXT
    custom_label="",      # ✅ or "" for TXT
    custom_release_date="",    # ✅ or "" for fallback
    custom_purchase_date="2026_03_06"              # ✅ "" uses 'Purchased' column
)

Renaming files: 100%|█████████████████████████████████████████████████████| 182/182 [00:00<00:00, 3968.60it/s]

❌ File not found (Row 106): None
❌ File not found (Row 107): None
❌ File not found (Row 108): None
❌ File not found (Row 109): None
❌ File not found (Row 110): None
❌ File not found (Row 151): None
❌ File not found (Row 152): None
❌ File not found (Row 153): None
❌ File not found (Row 154): None
❌ File not found (Row 155): None

In [23]:
#3+17+19+13+3 #= 
8+10+15+22

55

# check

In [14]:
import pandas as pd

txt_path = txt_path

# 🚀 FAST & FORGIVING READ
df = pd.read_csv(txt_path, sep="\t", encoding='latin1', engine='python', on_bad_lines='skip')
df.columns = df.columns.str.strip()  # 🧼 Clean whitespaces

# 🎯 SHOW COLUMNS
print("\n🔎 COLUMN NAMES:")
for i, col in enumerate(df.columns):
    print(f"{i:>2}: '{col}'")

df#.head(3)

🔎 COLUMN NAMES:
 0: 'ÿþ# '
 1: ' K e y '
 2: ' F i l e   T y p e '
 3: ' D J   P l a y   C o u n t '
 4: ' A r t i s t '
 5: ' A r t w o r k '
 6: ' A l b u m '
 7: ' B P M '
 8: ' C o m m e n t s '
 9: ' T r a c k   T i t l e '
10: ' R e l e a s e   D a t e '
11: ' Y e a r '
12: ' L a b e l '
13: ' G e n r e '
14: ' R e m i x e r '
15: ' M i x   N a m e '
16: ' T i m e '
17: ' R a t i n g '
18: ' D a t e   A d d e d '
19: ' S i z e '
20: ' F i l e   N a m e '
21: ' B i t r a t e '
22: ' L o c a t i o n '
23: ' B i t d e p t h '

,ÿþ# , K e y , F i l e   T y p e , D J   P l a y   C o u n t , A r t i s t , A r t w o r k , A l b u m , B P M , C o m m e n t s , T r a c k   T i t l e ,..., R e m i x e r , M i x   N a m e , T i m e , R a t i n g , D a t e   A d d e d , S i z e , F i l e   N a m e , B i t r a t e , L o c a t i o n , B i t d e p t h 
0, 1 , 1 0 A , A I F F , 0 , Á n g e l e s   A z u l e s , , E l   B a ú l   I l e g a l , 9 0 . 0 0 , V i s i t   h t t p s : / / e d m o o n r e c..., C ó m o   T e   V o y   A   O l v i d a r   (...,..., L a s c i v i o   B o h e m i a , R e m i x , 0 3 : 3 8 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 5 . 3   M B , A n g e l e s   A z u l e s   -   C ó m o   T..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
1, 2 , 6 A , A I F F , 0 , D e n g u e   D e n g u e   D e n g u e , , L a   A l i a n z a   P r o f a n a , 9 5 . 0 0 , V i s i t   h t t p s : / / d e n g u e d e n..., A l p h a   &   O m e g a ,..., , O r i g i n a l   M i x , 0 3 : 2 5 ,           , 2 0 2 5 - 0 8 - 0 1 , 3 4 . 9   M B , D e n g u e   D e n g u e   D e n g u e   -  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
2, 3 , 1 2 B , A I F F , 0 , D e n g u e   D e n g u e   D e n g u e , , H u m o s   E P   V o l . 3 , 1 0 3 . 0 0 , V i s i t   h t t p s : / / d e n g u e d e n..., B a r r a b a s s ,..., , O r i g i n a l   M i x , 0 4 : 4 1 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 7 . 4   M B , D e n g u e   D e n g u e   D e n g u e   -  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
3, 4 , 1 2 A , A I F F , 0 , D e n g u e   D e n g u e   D e n g u e ! , , S o u n d s   a n d   C o l o u r s   P e r u , 9 4 . 0 0 , V i s i t   h t t p s : / / s o u n d s a n d..., D o n   M a r c i a l ,..., , O r i g i n a l   M i x , 0 4 : 2 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 5 . 4   M B , D e n g u e   D e n g u e   D e n g u e !   -..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
4, 5 , 7 A , A I F F , 0 , D J   N i r s o , , , 1 1 4 . 0 0 , V i s i t   h t t p s : / / d j n i r s o . b..., E l   B u g a   -   M i n i   C o n g a   ( N...,..., N i r s o , R e m i x , 0 4 : 1 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 3 . 3   M B , D J   N i r s o   -   E l   B u g a   -   M i..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
5, 6 , 6 A , A I F F , 0 , E x z a k t , , , 1 3 2 . 0 0 , V i s i t   h t t p s : / / e x z a k t . b a..., R Ü F Ü S   D U   S O L   -   I n n e r b l o...,..., E X Z , R e m i x , 0 5 : 2 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 5 . 5   M B , E x z a k t   -   R Ü F Ü S   D U   S O L   -..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
6, 7 , 7 A , A I F F , 0 , F é r t i l   D i s c o s , , I s l a .   E d i t s   p a r a   l a   V i c..., 8 8 . 0 0 , V i s i t   h t t p s : / / f e r t i l d i s..., A n d r e s   L a n d e r o   -   D e j a m e...,..., E l   B ú h o , E d i t , 0 5 : 1 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 4   M B , F é r t i l   D i s c o s   -   A n d r e s  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
7, 8 , 8 A , A I F F , 0 , F L A K O   S T I K , , P A R T Y   S T A R T E R S   V O L .   2 , 1 2 7 . 0 0 , V i s i t   h t t p s : / / f l a k o s t i k..., J a r a b e   d e   P a l o   -   L A   F L A...,..., F L A K O   S T I K , E d i t , 0 5 : 3 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 6   M B , F L A K O   S T I K   -   J a r a b e   d e  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
8, 9 , 7 A , A I F F , 0 , F u n k S u p p l y , , , 1 1 2 . 0 0 , V i s i t   h t t p s : / / f u n k s u p p l...," I ' v e   g o t   a n   a t t i t u d e ,   b...",..., , O r i g i n a l   M i x , 0 6 : 5 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 1 0 4 . 1   M B , F u n k S u p p l y   -   I ' v e   g o t   a..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
9, 1 0 , 7 A , A I F F , 0 , K l i k   &   F r i k , , B o t a n a s   ( S h i k a   S h i k a ) , 9 2 . 0 0 , V i s i t   h t t p s : / / k l i k a n d f r..., G r u p o   B a h i a   -   R u m b a   C h o...,..., K l i k   &   F r i k , R e m i x , 0 4 : 3 3 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 6 . 1   M B , K l i k   &   F r i k   -   G r u p o   B a h..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
10, 1 1 , 7 A , A I F F , 0 , K O N N   R E C O R D I N G S , , L a t i n o a m é r i c a   E d i t - b y   M..., 1 3 2 . 5 1 , V i s i t   h t t p s : / / k o n n r e c o r..., M o s a i c o   D e   B u n d e   - G r u p o...,..., M r .   T o é   E d i t , E d i t , 0 6 : 0 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 1 . 8   M B , K O N N   R E C O R D I N G S   -   M o s a i..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
11, 1 2 , 3 A , A I F F , 0 , L o s   H e r m a n o s   B a l a n t a   ( B..., , , 7 8 . 0 0 , V i s i t   h t t p s : / / b i o m i g r a n..., M u c h o   H i j u e p u t a ,..., B i o m i g r a n t   E d i t , E d i t , 0 3 : 1 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 9 . 8   M B , L o s   H e r m a n o s   B a l a n t a   ( B..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
12, 1 3 , 8 A , A I F F , 0 , M y s t i c   C r o c k , , B e y o n d   H o r i z o n s   [ 2 4   b i t ] , 1 0 4 . 0 0 , V i s i t   h t t p s : / / m y s t i c c r o..., L o s t   I n   L o v e ,..., , O r i g i n a l   M i x , 0 9 : 1 1 ,           , 2 0 2 5 - 0 8 - 0 1 , 1 3 9 . 3   M B , M y s t i c   C r o c k   -   L o s t   I n  ..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
13, 1 4 , 1 2 A , A I F F , 0 , N a n o s p h e r e , , N i g h t   V i s i o n s   4   -   D e s e r..., 1 4 0 . 0 0 , V i s i t   h t t p s : / / d e s e r t d w e..., H o m e w o r l d   ( D e s e r t   D w e l l...,..., D e s e r t   D w e l l e r s   , R e m i x , 0 4 : 0 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 1 . 6   M B , N a n o s p h e r e   -   H o m e w o r l d  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
14, 1 5 , 4 A , A I F F , 0 , N i c k   L e ó n , , X t a s i s , 1 4 0 . 0 0 , V i s i t   h t t p s : / / n i c k n o e x i..., X t a s i s   F e a t .   D J   B a b a t r ,..., f e a t .   D J   B a b a t r , R e m i x , 0 4 : 5 5 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 9 . 9   M B , N i c k   L e ó n   -   X t a s i s   F e a t..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
15, 1 6 , 9 A , A I F F , 0 , O v n i m o o n   R e c o r d s , , A t m o s p h e r i k a   -   V i d a   ( o v..., 9 5 . 0 0 , V i s i t   h t t p s : / / o v n i m o o n r..., C i c l o   d e   V i d a ,..., , O r i g i n a l   M i x , 0 6 : 1 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 4   M B , O v n i m o o n   R e c o r d s   -   C i c l..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
16, 1 7 , 1 1 A , A I F F , 0 , P i g m a l i ã o , , S o u n d s   a n d   C o l o u r s   P e r u , 8 9 . 0 0 , V i s i t   h t t p s : / / s o u n d s a n d..., E n   E l   C a m i n o   P a r a   Z a ñ a ,..., , O r i g i n a l   M i x , 0 4 : 4 0 ,           , 2 0 2 5 - 0 8 - 0 1 , 7 0 . 9   M B , P i g m a l i ã o   -   E n   E l   C a m i n..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
17, 1 8 , 3 A , A I F F , 0 , T h e   H a l l u c i   N a t i o n , , A   T r i b e   C a l l e d   R e d , 1 3 3 . 3 3 , V i s i t   h t t p s : / / t h e h a l l u c..., E l e c t r i c   P o w   W o w   D r u m ,..., , O r i g i n a l   M i x , 0 3 : 3 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 3 7 . 1   M B , T h e   H a l l u c i   N a t i o n   -   E l..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
18, 1 9 , 4 A , A I F F , 0 , u j i , , A l b o r a d a , 8 8 . 0 0 , V i s i t   h t t p s : / / u j i t i m e b e..., A l b o r a d a   f e a t .   A n i c c a ,..., , O r i g i n a l   M i x , 0 6 : 3 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 9 9 . 2   M B , u j i   -   A l b o r a d a   f e a t .   A n..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
19, 2 0 , 6 A , A I F F , 0 , H e a t t r a x x , , H T 0 1 9   -   H u x l e y , 1 2 5 . 0 0 , V i s i t   h t t p s : / / h e a t t r a x x..., M o n i e ,..., , O r i g i n a l   M i x , 0 6 : 1 4 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 3 . 1   M B , H e a t t r a x x   -   H T 0 1 9   -   H u x..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
20, 2 1 , 2 A , A I F F , 0 , H e a t t r a x x , , H T 0 1 9   -   H u x l e y , 1 2 3 . 0 0 , V i s i t   h t t p s : / / h e a t t r a x x..., O b s e s s e d ,..., , O r i g i n a l   M i x , 0 6 : 3 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 6 . 1   M B , H e a t t r a x x   -   H T 0 1 9   -   H u x..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
21, 2 2 , 4 A , A I F F , 0 , H e a t t r a x x , , H T 0 1 9   -   H u x l e y , 1 2 9 . 0 0 , V i s i t   h t t p s : / / h e a t t r a x x..., R h y t h m ,..., , O r i g i n a l   M i x , 0 5 : 0 1 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 0 . 8   M B , H e a t t r a x x   -   H T 0 1 9   -   H u x..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
22, ,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [15]:
df

,ÿþ# , K e y , F i l e   T y p e , D J   P l a y   C o u n t , A r t i s t , A r t w o r k , A l b u m , B P M , C o m m e n t s , T r a c k   T i t l e ,..., R e m i x e r , M i x   N a m e , T i m e , R a t i n g , D a t e   A d d e d , S i z e , F i l e   N a m e , B i t r a t e , L o c a t i o n , B i t d e p t h 
0, 1 , 1 0 A , A I F F , 0 , Á n g e l e s   A z u l e s , , E l   B a ú l   I l e g a l , 9 0 . 0 0 , V i s i t   h t t p s : / / e d m o o n r e c..., C ó m o   T e   V o y   A   O l v i d a r   (...,..., L a s c i v i o   B o h e m i a , R e m i x , 0 3 : 3 8 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 5 . 3   M B , A n g e l e s   A z u l e s   -   C ó m o   T..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
1, 2 , 6 A , A I F F , 0 , D e n g u e   D e n g u e   D e n g u e , , L a   A l i a n z a   P r o f a n a , 9 5 . 0 0 , V i s i t   h t t p s : / / d e n g u e d e n..., A l p h a   &   O m e g a ,..., , O r i g i n a l   M i x , 0 3 : 2 5 ,           , 2 0 2 5 - 0 8 - 0 1 , 3 4 . 9   M B , D e n g u e   D e n g u e   D e n g u e   -  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
2, 3 , 1 2 B , A I F F , 0 , D e n g u e   D e n g u e   D e n g u e , , H u m o s   E P   V o l . 3 , 1 0 3 . 0 0 , V i s i t   h t t p s : / / d e n g u e d e n..., B a r r a b a s s ,..., , O r i g i n a l   M i x , 0 4 : 4 1 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 7 . 4   M B , D e n g u e   D e n g u e   D e n g u e   -  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
3, 4 , 1 2 A , A I F F , 0 , D e n g u e   D e n g u e   D e n g u e ! , , S o u n d s   a n d   C o l o u r s   P e r u , 9 4 . 0 0 , V i s i t   h t t p s : / / s o u n d s a n d..., D o n   M a r c i a l ,..., , O r i g i n a l   M i x , 0 4 : 2 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 5 . 4   M B , D e n g u e   D e n g u e   D e n g u e !   -..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
4, 5 , 7 A , A I F F , 0 , D J   N i r s o , , , 1 1 4 . 0 0 , V i s i t   h t t p s : / / d j n i r s o . b..., E l   B u g a   -   M i n i   C o n g a   ( N...,..., N i r s o , R e m i x , 0 4 : 1 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 3 . 3   M B , D J   N i r s o   -   E l   B u g a   -   M i..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
5, 6 , 6 A , A I F F , 0 , E x z a k t , , , 1 3 2 . 0 0 , V i s i t   h t t p s : / / e x z a k t . b a..., R Ü F Ü S   D U   S O L   -   I n n e r b l o...,..., E X Z , R e m i x , 0 5 : 2 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 5 . 5   M B , E x z a k t   -   R Ü F Ü S   D U   S O L   -..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
6, 7 , 7 A , A I F F , 0 , F é r t i l   D i s c o s , , I s l a .   E d i t s   p a r a   l a   V i c..., 8 8 . 0 0 , V i s i t   h t t p s : / / f e r t i l d i s..., A n d r e s   L a n d e r o   -   D e j a m e...,..., E l   B ú h o , E d i t , 0 5 : 1 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 4   M B , F é r t i l   D i s c o s   -   A n d r e s  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
7, 8 , 8 A , A I F F , 0 , F L A K O   S T I K , , P A R T Y   S T A R T E R S   V O L .   2 , 1 2 7 . 0 0 , V i s i t   h t t p s : / / f l a k o s t i k..., J a r a b e   d e   P a l o   -   L A   F L A...,..., F L A K O   S T I K , E d i t , 0 5 : 3 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 6   M B , F L A K O   S T I K   -   J a r a b e   d e  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
8, 9 , 7 A , A I F F , 0 , F u n k S u p p l y , , , 1 1 2 . 0 0 , V i s i t   h t t p s : / / f u n k s u p p l...," I ' v e   g o t   a n   a t t i t u d e ,   b...",..., , O r i g i n a l   M i x , 0 6 : 5 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 1 0 4 . 1   M B , F u n k S u p p l y   -   I ' v e   g o t   a..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
9, 1 0 , 7 A , A I F F , 0 , K l i k   &   F r i k , , B o t a n a s   ( S h i k a   S h i k a ) , 9 2 . 0 0 , V i s i t   h t t p s : / / k l i k a n d f r..., G r u p o   B a h i a   -   R u m b a   C h o...,..., K l i k   &   F r i k , R e m i x , 0 4 : 3 3 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 6 . 1   M B , K l i k   &   F r i k   -   G r u p o   B a h..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
10, 1 1 , 7 A , A I F F , 0 , K O N N   R E C O R D I N G S , , L a t i n o a m é r i c a   E d i t - b y   M..., 1 3 2 . 5 1 , V i s i t   h t t p s : / / k o n n r e c o r..., M o s a i c o   D e   B u n d e   - G r u p o...,..., M r .   T o é   E d i t , E d i t , 0 6 : 0 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 1 . 8   M B , K O N N   R E C O R D I N G S   -   M o s a i..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
11, 1 2 , 3 A , A I F F , 0 , L o s   H e r m a n o s   B a l a n t a   ( B..., , , 7 8 . 0 0 , V i s i t   h t t p s : / / b i o m i g r a n..., M u c h o   H i j u e p u t a ,..., B i o m i g r a n t   E d i t , E d i t , 0 3 : 1 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 9 . 8   M B , L o s   H e r m a n o s   B a l a n t a   ( B..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
12, 1 3 , 8 A , A I F F , 0 , M y s t i c   C r o c k , , B e y o n d   H o r i z o n s   [ 2 4   b i t ] , 1 0 4 . 0 0 , V i s i t   h t t p s : / / m y s t i c c r o..., L o s t   I n   L o v e ,..., , O r i g i n a l   M i x , 0 9 : 1 1 ,           , 2 0 2 5 - 0 8 - 0 1 , 1 3 9 . 3   M B , M y s t i c   C r o c k   -   L o s t   I n  ..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
13, 1 4 , 1 2 A , A I F F , 0 , N a n o s p h e r e , , N i g h t   V i s i o n s   4   -   D e s e r..., 1 4 0 . 0 0 , V i s i t   h t t p s : / / d e s e r t d w e..., H o m e w o r l d   ( D e s e r t   D w e l l...,..., D e s e r t   D w e l l e r s   , R e m i x , 0 4 : 0 6 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 1 . 6   M B , N a n o s p h e r e   -   H o m e w o r l d  ..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
14, 1 5 , 4 A , A I F F , 0 , N i c k   L e ó n , , X t a s i s , 1 4 0 . 0 0 , V i s i t   h t t p s : / / n i c k n o e x i..., X t a s i s   F e a t .   D J   B a b a t r ,..., f e a t .   D J   B a b a t r , R e m i x , 0 4 : 5 5 ,           , 2 0 2 5 - 0 8 - 0 1 , 4 9 . 9   M B , N i c k   L e ó n   -   X t a s i s   F e a t..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
15, 1 6 , 9 A , A I F F , 0 , O v n i m o o n   R e c o r d s , , A t m o s p h e r i k a   -   V i d a   ( o v..., 9 5 . 0 0 , V i s i t   h t t p s : / / o v n i m o o n r..., C i c l o   d e   V i d a ,..., , O r i g i n a l   M i x , 0 6 : 1 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 4   M B , O v n i m o o n   R e c o r d s   -   C i c l..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
16, 1 7 , 1 1 A , A I F F , 0 , P i g m a l i ã o , , S o u n d s   a n d   C o l o u r s   P e r u , 8 9 . 0 0 , V i s i t   h t t p s : / / s o u n d s a n d..., E n   E l   C a m i n o   P a r a   Z a ñ a ,..., , O r i g i n a l   M i x , 0 4 : 4 0 ,           , 2 0 2 5 - 0 8 - 0 1 , 7 0 . 9   M B , P i g m a l i ã o   -   E n   E l   C a m i n..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
17, 1 8 , 3 A , A I F F , 0 , T h e   H a l l u c i   N a t i o n , , A   T r i b e   C a l l e d   R e d , 1 3 3 . 3 3 , V i s i t   h t t p s : / / t h e h a l l u c..., E l e c t r i c   P o w   W o w   D r u m ,..., , O r i g i n a l   M i x , 0 3 : 3 9 ,           , 2 0 2 5 - 0 8 - 0 1 , 3 7 . 1   M B , T h e   H a l l u c i   N a t i o n   -   E l..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
18, 1 9 , 4 A , A I F F , 0 , u j i , , A l b o r a d a , 8 8 . 0 0 , V i s i t   h t t p s : / / u j i t i m e b e..., A l b o r a d a   f e a t .   A n i c c a ,..., , O r i g i n a l   M i x , 0 6 : 3 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 9 9 . 2   M B , u j i   -   A l b o r a d a   f e a t .   A n..., 2 1 1 6   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 2 4 
19, 2 0 , 6 A , A I F F , 0 , H e a t t r a x x , , H T 0 1 9   -   H u x l e y , 1 2 5 . 0 0 , V i s i t   h t t p s : / / h e a t t r a x x..., M o n i e ,..., , O r i g i n a l   M i x , 0 6 : 1 4 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 3 . 1   M B , H e a t t r a x x   -   H T 0 1 9   -   H u x..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
20, 2 1 , 2 A , A I F F , 0 , H e a t t r a x x , , H T 0 1 9   -   H u x l e y , 1 2 3 . 0 0 , V i s i t   h t t p s : / / h e a t t r a x x..., O b s e s s e d ,..., , O r i g i n a l   M i x , 0 6 : 3 2 ,           , 2 0 2 5 - 0 8 - 0 1 , 6 6 . 1   M B , H e a t t r a x x   -   H T 0 1 9   -   H u x..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
21, 2 2 , 4 A , A I F F , 0 , H e a t t r a x x , , H T 0 1 9   -   H u x l e y , 1 2 9 . 0 0 , V i s i t   h t t p s : / / h e a t t r a x x..., R h y t h m ,..., , O r i g i n a l   M i x , 0 5 : 0 1 ,           , 2 0 2 5 - 0 8 - 0 1 , 5 0 . 8   M B , H e a t t r a x x   -   H T 0 1 9   -   H u x..., 1 4 1 1   k b p s , / U s e r s / y e r i k / D o w n l o a d s /..., 1 6 
22, ,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [17]:
print(df['Year'].unique())

KeyError: 'Year'