In [16]:
import pandas as pd
# Adjust settings to display all rows and columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)  # Set a wide display width to fit the content
pd.set_option('display.max_colwidth', None)  # Show full column content without truncation

folder_list = ['/Users/yerik/Desktop/try']

In [17]:
counter = 0

for path in folder_list:
    try:
        print(f"\n🔁 Processing: {path}")
        my_aiff = path
        direc_jpg = "images/"
        direc_tables = "tables/"

        # Execute external script
        exec(open("run.py", encoding="utf-8").read())

        # Save first row of df using custom file name format
        pkl_name = f"df_{counter:03d}_.pkl"
        df.to_pickle(pkl_name)
        print(f"✅ Saved: {pkl_name}")
        [shutil.rmtree(f, ignore_errors=True) or os.makedirs(f, exist_ok=True) for f in ['images/', 'tables/']]
        print('images and tables folders erased')
        counter += 1

    except Exception as e:
        print(f"❌ Error in {path}: {e}")
        continue
# -----######-----######-----######-----######-----######-----#
# 0_FNS: _folderreplace_1704_i1_REPLACE_dir_with_backup
# -----######-----######-----######-----######-----######-----#

# import os
# import shutil

# def _folderreplace_1704_i1_REPLACE_dir_with_backup(test_dir, test_bu_dir):
#     """
#     Replaces the folder `test_dir` with the contents of `test_bu_dir`.
#     Prompts user to hit ENTER before proceeding with deletion and replacement.
#     """
#     if not os.path.isdir(test_dir):
#         print(f"❌ ERROR: Folder not found: {test_dir}")
#         return
#     if not os.path.isdir(test_bu_dir):
#         print(f"❌ ERROR: Backup folder not found: {test_bu_dir}")
#         return

#     print(f"\n⚠️  WARNING: This will completely delete and replace:\n'{test_dir}' ⬅️ with contents from '{test_bu_dir}'")
#     input("Press [ENTER] to continue or [CTRL+C] to cancel...")

#     shutil.rmtree(test_dir)
#     shutil.copytree(test_bu_dir, test_dir)
    
#     print(f"✅ Replaced '{test_dir}' with contents from '{test_bu_dir}'")
    
# test_dir = "/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/test"
# test_bu_dir = "/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/test_bu"

# _folderreplace_1704_i1_REPLACE_dir_with_backup(test_dir, test_bu_dir)

🔁 Processing: /Users/yerik/Desktop/try

ALL AIFF in correct format -> if something changes go erase the already downsized

Searching for Files: 100%|██████████████████████████████████████████████| 11/11 [00:00<00:00, 14820.86files/s]

ATTN ::: <E>  AFTER making sure that you have assigned the DIRECTORY PATH to ::: var ::: /Users/yerik/Desktop/try
***df*** will be returned having ::: 10  rows, write df in next cell to see your DATA FRAME

second part FREQUENCIES OF df :::

Grand Total Size in MB: 27.790
Grand Total Size in Bytes: 29139824.000
Grand Total Size in GB: 0.027

 FREQUENCY TABLE:::

  Extension  frequency  total_size_in_mb
0     .aiff         10         27.789902

Audio file Attributes: 100%|████████████████████████████████████████████████| 10/10 [00:00<00:00, 2485.66it/s]
Computing LUFS: 100%|███████████████████████████████████████████████████████| 10/10 [00:01<00:00,  8.24file/s]
100%|█████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 128266.18it/s]

                                                                                                                                                                        Path                                                                                                                                      temp_id                                                                                                                                         file_name Extension dur_seconds   dur_min     sr bit_depth bit_rate channels file_size file_size_human num_frames error  ms_lufs ms_LUFS_code id_cat_lufs
0    /Users/yerik/Desktop/try/TRkw__704_ms_a_004_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff    TRkw__704_ms_a_004_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01    TRkw__704_ms_a_004_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff     .aiff   29.261383   0.48769  44100        16     None        2   5162838         4.92 MB    1290427  None  -40.000          LuA           A
1  /Users/yerik/Desktop/try/TRkw__698_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_120_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff  TRkw__698_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_120_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01  TRkw__698_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_120_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff     .aiff         6.0       0.1  44100        16     None        2   1059532         1.01 MB     264600  None  -28.542          LuA           A
2   /Users/yerik/Desktop/try/TRkw__706_need_this_loop_002_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_95_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff   TRkw__706_need_this_loop_002_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_95_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01   TRkw__706_need_this_loop_002_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_95_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff     .aiff    7.619025  0.126984  44100        16     None        2   1345128         1.28 MB     335999  None  -34.930          LuA           A
3   /Users/yerik/Desktop/try/TRkw__702_ms_a_002_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_82_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff   TRkw__702_ms_a_002_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_82_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01   TRkw__702_ms_a_002_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_82_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff     .aiff   29.261383   0.48769  44100        16     None        2   5162838         4.92 MB    1290427  None  -17.819          LuB           K
4    /Users/yerik/Desktop/try/TRkw__701_ms_a_001_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff    TRkw__701_ms_a_001_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01    TRkw__701_ms_a_001_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff     .aiff   29.261383   0.48769  44100        16     None        2   5162838         4.92 MB    1290427  None  -40.000          LuA           A

BPM per file:   0%|                                                                    | 0/10 [00:00<?, ?it/s]<string>:774: UserWarning: ⚠️ Skipping TRkw__704_ms_a_004_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: No BPM values detected
<string>:774: UserWarning: ⚠️ Skipping TRkw__698_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_120_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: Too short for one BPM window
<string>:774: UserWarning: ⚠️ Skipping TRkw__706_need_this_loop_002_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_95_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: Too short for one BPM window
BPM per file:  30%|██████████████████                                          | 3/10 [00:00<00:00, 28.75it/s]<string>:760: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
<string>:774: UserWarning: ⚠️ Skipping TRkw__701_ms_a_001_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: No BPM values detected
<string>:774: UserWarning: ⚠️ Skipping TRkw__707_vocal_loos_Kiss_001__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_87_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: No BPM values detected
BPM per file:  60%|████████████████████████████████████                        | 6/10 [00:00<00:00, 20.55it/s]<string>:774: UserWarning: ⚠️ Skipping TRkw__705_need_this_loop_001_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_92_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: No BPM values detected
<string>:774: UserWarning: ⚠️ Skipping TRkw__699_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: Too short for one BPM window
<string>:774: UserWarning: ⚠️ Skipping TRkw__700_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff: Too short for one BPM window
BPM per file: 100%|███████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 25.32it/s]
Extracting ID3 Titles: 100%|████████████████████████████████████████████████| 10/10 [00:00<00:00, 2306.97it/s]

DONE with getting 1_title
title_file
ID3TAGS    10
Name: count, dtype: int64

Writing AIFF files for title: 100%|██████████████████████████████████████████| 10/10 [00:00<00:00, 650.27it/s]

Total files processed for title: 10

Extracting ID3 Artists: 100%|███████████████████████████████████████████████| 10/10 [00:00<00:00, 1168.10it/s]

DONE with getting 2_artist
artist_file
ID3TAGS    10
Name: count, dtype: int64

Writing AIFF files for artist: 100%|████████████████████████████████████████| 10/10 [00:00<00:00, 1237.48it/s]

Total files processed for artist: 10

Extracting ID3 Labels: 100%|████████████████████████████████████████████████| 10/10 [00:00<00:00, 1907.02it/s]

DONE with getting 3_LABEL
label_file
ID3TAGS    10
Name: count, dtype: int64

Extracting ID3 Genres: 100%|████████████████████████████████████████████████| 10/10 [00:00<00:00, 1931.52it/s]

DONE with getting 4_genre
genre_file
ID3TAGS    10
Name: count, dtype: int64

Extracting ID3 Release Year: 100%|██████████████████████████████████████████| 10/10 [00:00<00:00, 1758.69it/s]

DONE with getting 5_release_year
rel_year_file
FILE_NAME    10
Name: count, dtype: int64

Extracting ID3 Key: 100%|███████████████████████████████████████████████████| 10/10 [00:00<00:00, 1796.66it/s]

DONE with getting 6_KEY
key_file
ID3TAGS      8
FILE_NAME    2
Name: count, dtype: int64
DONE with getting 7_mix_name & 8_remixer

  0%|          | 0/10 [00:00<?, ?it/s]

DONE with getting 9_date_purchased

Writtng AIFF files for : remixer:   0%|          | 0/10 [00:00<?, ?it/s]

DONE with WRITTING 7_mix_name & 8_remixer : to ID3TAG remixer

Writtng AIFF files for : genre: 0it [00:00, ?it/s]

Total files processed: 0
DONE with WRITTING 4_genre : to ID3TAG genre

Writtng AIFF files for : label: 0it [00:00, ?it/s]

Total files processed for label: 0
DONE with WRITTING 3_LABEL : to ID3TAG LABEL

Extracting ID3 Release Date:   0%|          | 0/10 [00:00<?, ?it/s]

Writing AIFF files for: release date:   0%|          | 0/10 [00:00<?, ?it/s]

Total files processed for release date: 10

  0%|          | 0/10 [00:00<?, ?it/s]

/Users/yerik/_apple_lib/_b_envs/2ms_env/lib/python3.11/site-packages/librosa/core/pitch.py:103: UserWarning: Trying to estimate tuning from empty frequency set.
  return pitch_tuning(

Processing keys:   0%|          | 0/10 [00:00<?, ?it/s]

Processing keys:   0%|          | 0/10 [00:00<?, ?it/s]

Writing AIFF files for comment:   0%|          | 0/10 [00:00<?, ?it/s]

Total files processed for comment: 10

❌ Error in /Users/yerik/Desktop/try: 'NoneType' object is not subscriptable

In [18]:
df

,Path,temp_id,file_name,Extension,dur_seconds,dur_min,sr,bit_depth,bit_rate,channels,file_size,file_size_human,num_frames,error,ms_lufs,ms_LUFS_code,id_cat_lufs,mean_bpm,std_bpm,min_bpm,max_bpm,variation_percentage,dominant_bpm,bpm_consistency,bpm_consistency_cat,title,title_file,artist,artist_file,LABEL,label_file,genre,genre_file,rel_year,rel_year_file,KEY,key_file,mix_name,remixer,remix,date_purchased,rel_date,rel_date_file,key_dj,key_music,status,Relative_Key,Key_Up,Key_Down,Jaw_s_Mix,Mood_Shifter,ID,comment
0,/Users/yerik/Desktop/try/TRkw__704_ms_a_004_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__704_ms_a_004_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__704_ms_a_004_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,29.261383,0.48769,44100,16,None,2,5162838,4.92 MB,1290427,None,-40.000,LuA,A,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,704 ms a 004 Scene 1 G,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,No energy detected in the main section,FILE_NAME,original,original,U,2025-01-01,2015-01-01,ID3TAGS,1A,NaN,Skipped: No key_dj value,None,None,None,None,None,idy_9Aa_7Y38,idy_9Aa_7Y38_No energy detected in the main section
1,/Users/yerik/Desktop/try/TRkw__698_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_120_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__698_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_120_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__698_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_120_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,6.0,0.1,44100,16,None,2,1059532,1.01 MB,264600,None,-28.542,LuA,A,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,698 loops YODJ sep asian,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,Gmin,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,6A,Gmin,Success: TKEY updated,6B,7A,5A,1A,9B,idy_9Aa_6Y32,idy_9Aa_6Y32_Gmin
2,/Users/yerik/Desktop/try/TRkw__706_need_this_loop_002_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_95_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__706_need_this_loop_002_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_95_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__706_need_this_loop_002_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_95_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,7.619025,0.126984,44100,16,None,2,1345128,1.28 MB,335999,None,-34.930,LuA,A,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,706 need this loop 002 S,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,G#min,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,1A,G#min,Success: TKEY updated,1B,2A,12A,8A,4B,idy_9Aa_7Y28,idy_9Aa_7Y28_G#min
3,/Users/yerik/Desktop/try/TRkw__702_ms_a_002_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_82_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__702_ms_a_002_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_82_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__702_ms_a_002_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_82_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,29.261383,0.48769,44100,16,None,2,5162838,4.92 MB,1290427,None,-17.819,LuB,K,123.046875,0.000000,123.046875,123.046875,0.000000,123,1.000000,D_9,702 ms a 002 Scene 1 G,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,Cmin,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,5A,Cmin,Success: TKEY updated,5B,6A,4A,12A,8B,idy_9Bk_7Y38,idy_9Bk_7Y38_Cmin
4,/Users/yerik/Desktop/try/TRkw__701_ms_a_001_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__701_ms_a_001_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__701_ms_a_001_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,29.261383,0.48769,44100,16,None,2,5162838,4.92 MB,1290427,None,-40.000,LuA,A,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,701 ms a 001 Scene 1 G,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,No energy detected in the main section,FILE_NAME,original,original,U,2025-01-01,2015-01-01,ID3TAGS,1A,NaN,Skipped: No key_dj value,None,None,None,None,None,idy_9Aa_7Y38,idy_9Aa_7Y38_No energy detected in the main section
5,/Users/yerik/Desktop/try/TRkw__707_vocal_loos_Kiss_001__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_87_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__707_vocal_loos_Kiss_001__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_87_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__707_vocal_loos_Kiss_001__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_87_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,11.03449,0.183908,44100,16,None,2,1947616,1.86 MB,486621,None,-19.596,LuA,C,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,707 vocal loos Kiss 001,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,Dmin,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,7A,Dmin,Success: TKEY updated,7B,8A,6A,2A,10B,idy_9Ac_7Y16,idy_9Ac_7Y16_Dmin
6,/Users/yerik/Desktop/try/TRkw__705_need_this_loop_001_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_92_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__705_need_this_loop_001_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_92_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__705_need_this_loop_001_S_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_92_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,11.428571,0.190476,44100,16,None,2,2017132,1.92 MB,504000,None,-30.672,LuA,A,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,705 need this loop 001 S,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,G#min,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,1A,G#min,Success: TKEY updated,1B,2A,12A,8A,4B,idy_9Aa_7Y32,idy_9Aa_7Y32_G#min
7,/Users/yerik/Desktop/try/TRkw__699_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__699_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__699_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,6.0,0.1,44100,16,None,2,1059532,1.01 MB,264600,None,-27.014,LuA,A,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,699 loops YODJ sep asian,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,Fmaj,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,7B,Fmaj,Success: TKEY updated,7A,8B,6B,2B,4A,idy_9Aa_6Y32,idy_9Aa_6Y32_Fmaj
8,/Users/yerik/Desktop/try/TRkw__700_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__700_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__700_loops_YODJ_sep_asian_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,6.0,0.1,44100,16,None,2,1059532,1.01 MB,264600,None,-24.202,LuA,A,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,D_9,700 loops YODJ sep asian,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,Cmin,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,5A,Cmin,Success: TKEY updated,5B,6A,4A,12A,8B,idy_9Aa_7Y32,idy_9Aa_7Y32_Cmin
9,/Users/yerik/Desktop/try/TRkw__703_ms_a_003_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,TRkw__703_ms_a_003_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01,TRkw__703_ms_a_003_Scene_1_-_G_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_0_GNkw_M-Plus-Export_LBkw_YODJ-M-Plus_RYkw_2015_01_01_PYkw_2025_01_01.aiff,.aiff,29.261383,0.48769,44100,16,None,2,5162838,4.92 MB,1290427,None,-25.893,LuA,A,138.395217,18.209897,120.185320,156.605114,13.157895,120,0.883721,D_9,703 ms a 003 Scene 1 G,ID3TAGS,YODJ,ID3TAGS,YODJ-M-Plus,ID3TAGS,sample,ID3TAGS,2025,FILE_NAME,Dmin,ID3TAGS,original,original,U,2025-01-01,2015-01-01,ID3TAGS,7A,Dmin,Success: TKEY updated,7B,8A,6A,2A,10B,idy_9Aa_7Y38,idy_9Aa_7Y38_Dmin

In [3]:
import shutil
import os
[shutil.rmtree(f, ignore_errors=True) or os.makedirs(f, exist_ok=True) for f in ['images/', 'tables/']]

[None, None]

In [4]:
df[['dominant_bpm']]

   dominant_bpm
0    120.185320
1      0.000000
2    123.046875
3    120.185320
4      0.000000
5      0.000000
6    120.185320
7    107.666016

In [1]:
# -----######-----######-----######-----######-----######-----#
# FUNCTION: _fs_1704_listsubdirs_GET_list_all
# -----######-----######-----######-----######-----######-----#

import os
from tqdm import tqdm

def _fs_1704_listsubdirs_GET_list_all(root_folder):
    """
    Returns a list of full paths to all immediate subfolders inside the given folder.
    
    Parameters:
        root_folder (str): Path to the root directory

    Returns:
        List of full paths to subdirectories only
    """
    print(f"🔍 Scanning for subfolders in:\n{root_folder}")
    subfolders = [
        os.path.join(root_folder, d)
        for d in os.listdir(root_folder)
        if os.path.isdir(os.path.join(root_folder, d))
    ]
    print(f"✅ Found {len(subfolders)} subfolders.")
    return subfolders
folder_list_23 = _fs_1704_listsubdirs_GET_list_all("/Users/yerik/Music/_1_NEW_SOURCE/_2023_this")
folder_list_24 = _fs_1704_listsubdirs_GET_list_all("/Users/yerik/Music/_1_NEW_SOURCE/_2024_this")
folder_list_25 = _fs_1704_listsubdirs_GET_list_all("/Users/yerik/Music/_1_NEW_SOURCE/_2025_this")

folder_list = folder_list_23 + folder_list_24 + folder_list_25
#print(folder_list)
folder_list

🔍 Scanning for subfolders in:
/Users/yerik/Music/_1_NEW_SOURCE/_2023_this
✅ Found 12 subfolders.
🔍 Scanning for subfolders in:
/Users/yerik/Music/_1_NEW_SOURCE/_2024_this
✅ Found 20 subfolders.
🔍 Scanning for subfolders in:
/Users/yerik/Music/_1_NEW_SOURCE/_2025_this
✅ Found 8 subfolders.

['/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_04_NEW_LODGE',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_06_ttt_SPKRBOX',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_12_Tangent_Debout',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_11_AN_SpotLite',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_02_AN_LA_VENTANA',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_10_Detroit_Hou_Tech',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_04_Foundation_Hotel',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_08_SL_ACAPELLAS',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_08_Barefoot',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_03_Love_Lang',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_05_AN_bigPINK',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/___YODJ_N0Supervisi0n',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_06_Metroplex_2_and_RNDMgood',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_04_BBssBBssBBs_BandCamp',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_11_11_albm_LordECHO_JAZZ',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/___DJ_friends_Nun',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_07_Puma_BurningMan_indian',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_11_Dinner_Materia_Puma_Jazzy',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_11_11_albm_MimSuleiman_TRIBAL',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_12_fixed_and_added',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_04_NorthL_BadBunny_LatinFast',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_05_MVMNT_block_is_HOT',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_12_Dinner_HipHop_Indian_Puma',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_11_11_N0_Supervisi0n_SPKRbox',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_09_Ghettotech_HiTECH_stu',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_08_Barefoot_and_FREE',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_06_Metroplex_1_and_RNDMgood',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_06_Detroit_Brazil_Funky',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_12_NYE_25',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_09_Eagle_SPKR_Techno',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__24_08_Xime_13_Memorial',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_04_BP_Rapharazzi_BDAY',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_04_BCAL_SalsaEstrellasPa',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_04_BCAL_TerapiaLatina',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_04_BP_ximMAYBDAY_HOUSY_PARTY_LATIN',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_02_DETROIT_PUMA_SPKR',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_04_BP_LATIN_HOUSE',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_02_CDMX_SecretoRoom',
 '/Users/yerik/Music/_1_NEW_SOURCE/_2025_this/__25_03_CAPSULE_House_Latin']