In [65]:
copy_fns()

1. __nonzero__()
2. _hash_0912_df_ITERATE_APPEND_hash()
3. mediainfo()
4. analyze_and_downsize_aiff()
5. downsize_aiff()
6. _write_comment_2712_id3_SET_tag_bulk()
7. process_date_column()
8. _hash_bulk_2812_audio_GET_df_hashes()
9. compute_lufs_for_paths_AIFF()
10. _audio_attr_extract_11_INFO_AIFF()
11. process_metadata_optimized_AIFF()
12. _df_GET_rework_type_AIFF()
13. _filefinder_by_EXT_GET_df()
14. _audio_attr_all_audio_formats_extract_11_INFO()
15. _all_au_ext_GET_12_LUFS_values()
16. _all_values_CREATE_12_LUFS_categories()
17. process_metadata_optimized_mp3()
18. _rename_reorder_GET_df()
19. add_country_column_based_on_isrc()
20. _df_GET_mp3_rework_type()
21. extract_and_convert_key()
22. extract_and_convert_key_AIFF()
23. display_missing_data_by_extension()
24. _file_extract_from_file_name_()
25. _write_tags_2712_id3_SET_tag_bulk()

Pick the function number:  13

Function '_filefinder_by_EXT_GET_df()' with its docstring has been successfully copied to the clipboard.

# START

In [2]:
%run AIFF_fns.py

AIFF fns imported

# IMPORTS

In [3]:
import pandas as pd

# Adjust settings to display all rows and columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)  # Set a wide display width to fit the content
pd.set_option('display.max_colwidth', None)  # Show full column content without truncation

#exec(open(f"/Users/yerik/_apple_source/_0_fns_MANAGER.py",encoding="utf-8").read()) # copy_fns()
#%%writefile /Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/_song_attr_mapping.py
exec(open("/Users/yerik/_apple_source/pd2.py",encoding="utf-8").read())
#
print(" \n\nget_fns()#;copy_fns()#get_fns() FNS_FNS_FNS") 
#
my_aiff = "/Users/yerik/Music/_1_NEW_SOURCE"
#"/Volumes/HD_back_UP/2025_ALL_AIFF_raw/_2023_this/_23_02_AN_LA_VENTANA"
#
import sys;sys.path.append('/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms')
#
### ALL AUDIO TYPES ^<<< _***_0_***_ >>>^
#
from df_AIFF_new import compute_lufs_for_paths_AIFF,_audio_attr_extract_11_INFO_AIFF,process_metadata_optimized_AIFF,_df_GET_rework_type_AIFF
#
from df_read import _filefinder_by_EXT_GET_df
#
from _MSG_GET_song_attributes import _audio_attr_all_audio_formats_extract_11_INFO
from _MSG_GET_song_attributes import _all_au_ext_GET_12_LUFS_values,_all_values_CREATE_12_LUFS_categories

#
### MP3 id tags    ^<<< _***_1_***_ >>>^
#
from mp3_tags import process_metadata_optimized_mp3
#
from df_modif import _rename_reorder_GET_df
#
from _song_attributes_mapping import add_country_column_based_on_isrc, _df_GET_mp3_rework_type
from _song_attributes_mapping import extract_and_convert_key,extract_and_convert_key_AIFF ,display_missing_data_by_extension
#
# GENERAL
from tqdm import tqdm

Running garbage collection to free up unused memory.
Memory Usage: 122.34 MB
CPU Usage: 13.0%
Memory Usage: 122.34 MB
CPU Usage: 10.5%
ATTN - > TO start coding in this NOTEBOOK & following FNS :::  run ::: hi_jupy()
ATTN at the end RUN > py and cleans py ready to be copied >  runpy()
ATTN - > TO get all GLOBAL, libs and functions & ALL_DATA inputs, stats, temp, tables files info > db_paths()
ATTN - > TO move files from input to curr_direc > move_files(input_folder_path, curr_direc)
ATTN - > TO COPY program > copy_files_and_subdirectories(path_2_copy, dest_direc) --- respects original copied
ATTN - > TO get all GAME PLANS TO EXPORT ALPHA and BETA programs  > game_plan()
define program_folder_name before running runpy()


get_fns()#;copy_fns()#get_fns() FNS_FNS_FNS

# BEFORE here , Preprocess for AIFF file.

In [3]:
# # Running the function with corrected folder path
results_df = analyze_and_downsize_aiff(my_aiff)

# # Display results
results_df.head()

   Sample Rate (Hz)  Bit Depth  Count
0             44100         16   1108

# make sure you have all AIFF correct format and RENAMED at this step

In [4]:
###############################################         PREPARE VARIABLES / ausio_extension and loc -> directory variables
#
### -------------------------------------------- >>> FILTER by AIFF
code = 'all_AIFF'
audio_extensions = [ '.AIFF', '.aif', '.aiff'];file_extensions = audio_extensions 
# 
my_folder_path = my_aiff
#my_folder_path_mp3 = f'/Users/yerik/Downloads/{folder_name_new}_mp3'
#my_folder_path = {folder_name_new}'
table_name = f"temp_now_{code}.pkl"
#
###############################################          READ by Audio Ext & RETREIVE GENERAL Audio Info 
#^<<< _***_0_***_ >>>^
#
####
### -------------------------------------------- >>> FILTER by AIFF --------- here below ::: audio_extensions
#
df, fre_tab = _filefinder_by_EXT_GET_df(my_folder_path, file_extensions = audio_extensions)#file_extensions = None-> 4 none ext
df = df[~df['Name'].str.startswith('._')].copy();df = df[~df['Name'].str.startswith('.DS')].copy() # omit not wanted
df = df.rename(columns={'Name': 'temp_id'}).drop(columns=['Size (MB)',])                           # KEEP & RENAME
#df = df[df['Extension'].isin(['.mp3', '.MP3'])].copy() # KEEP ONLY extension type 
#
####
#input('')
if not df.empty:
    #
    #_1_ MSG_AUDIO general ATTRIBUTES
    #
    df = _audio_attr_extract_11_INFO_AIFF(df, audio_extensions)#;input('')
    #
    #_2_ MSG_LUFS
    #
    df['ms_lufs'] = compute_lufs_for_paths_AIFF(df['Path'])
    df['ms_LUFS_code'] = df['ms_lufs'].apply(_all_values_CREATE_12_LUFS_categories); lufs_cols =['ms_lufs','ms_LUFS_code']
    #
    #_3_ MSG_BPM
    #
    #df['BPM']
    #
    ## -> KEEP COLS_0 :::
    #
cols_0 = ['temp_id', 'Path', 'Extension', 'dur_seconds', 'dur_min', 'sr', 'bit_rate', 'bit_depth', 
              'channels', 'file_size', 'file_size_human', 'num_frames', 'error']  + lufs_cols
###
###############################################            RETREIVE       MP3 ID TAGS
#^<<< _***_1_***_ >>>^
#
#input('')
if not df.empty:
    df = process_metadata_optimized_AIFF(df, file_column='Path');print('DONE with getting ID3 tags')

    df = _rename_reorder_GET_df(df);print('DONE with renaming ID3 tags')
    df = process_date_column(df);print('DONE with processing ID3 tags for DATES');df['isrc'] = ''
    df = add_country_column_based_on_isrc(df);print('DONE with processing ID3 tags for isrc rel_COUNTRY_code')
    df =  _df_GET_rework_type_AIFF(df, col='Path');print('DONE with processing ID3 tags for REWORK type')
    df['KEY'] = '';df['BPM'] = '';df['LABEL'] = ''
    df = extract_and_convert_key_AIFF(df);print('DONE with conversion Camelot ID3 KEYS')
    #
    ## -> KEEP COLS_1 :::
    #
    cols_1 = [ 'title','artist','rework','album','track_#','genre','LABEL','isrc','rel_country',
               'rel_date',  'year','rel_year', 'rel_month', 'rel_day', 'rel_weekday',
               'audio_offset', 'decoder','comment','BPM', 'KEY', 'KEYC', 'KEY_code' ]     


# after id3 TAG abstractions
df = df[cols_0 + cols_1];
display_missing_data_by_extension(df) #display Freq table of attributes by extension and list of vars

Searching for Files: 100%|██████████████████████████████████████████| 1120/1120 [00:00<00:00, 58118.73files/s]

ATTN ::: <E>  AFTER making sure that you have assigned the DIRECTORY PATH to ::: var ::: /Users/yerik/Music/_1_NEW_SOURCE
***df*** will be returned having ::: 1108  rows, write df in next cell to see your DATA FRAME

second part FREQUENCIES OF df :::

Grand Total Size in MB: 67413.981
Grand Total Size in Bytes: 70688682582.000
Grand Total Size in GB: 65.834

 FREQUENCY TABLE:::

  Extension  frequency  total_size_in_mb
0     .aiff       1108      67413.981039

Processing Audio Files: 100%|███████████████████████████████████████████| 1108/1108 [00:00<00:00, 3569.95it/s]
Computing LUFS: 100%|███████████████████████████████████████████████████| 1108/1108 [13:27<00:00,  1.37file/s]
Processing AIFF Files:   9%|████▍                                          | 104/1108 [00:08<01:24, 11.89it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  10%|████▍                                          | 106/1108 [00:08<01:23, 12.07it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  10%|████▌                                          | 108/1108 [00:09<01:25, 11.73it/s]

TinyTag extraction error (AIFF): 'utf-8' codec can't decode byte 0xc2 in position 19: invalid continuation byte

/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  10%|████▋                                          | 110/1108 [00:09<01:24, 11.76it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  10%|████▊                                          | 112/1108 [00:09<01:26, 11.51it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  10%|████▊                                          | 114/1108 [00:09<01:24, 11.80it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  10%|████▉                                          | 116/1108 [00:09<01:22, 11.96it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  11%|█████                                          | 118/1108 [00:09<01:24, 11.77it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  11%|█████                                          | 120/1108 [00:10<01:23, 11.83it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  11%|█████▏                                         | 122/1108 [00:10<01:22, 11.92it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  11%|█████▎                                         | 124/1108 [00:10<01:23, 11.76it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  11%|█████▎                                         | 126/1108 [00:10<01:22, 11.86it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  12%|█████▍                                         | 128/1108 [00:10<01:22, 11.86it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  12%|█████▌                                         | 130/1108 [00:10<01:22, 11.86it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  12%|█████▌                                         | 132/1108 [00:11<01:21, 11.93it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  12%|█████▋                                         | 134/1108 [00:11<01:21, 11.95it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  12%|█████▊                                         | 136/1108 [00:11<01:20, 12.04it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  12%|█████▊                                         | 138/1108 [00:11<01:20, 12.04it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  13%|█████▉                                         | 140/1108 [00:11<01:20, 12.00it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  13%|██████                                         | 142/1108 [00:11<01:26, 11.14it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  13%|██████                                         | 144/1108 [00:12<01:26, 11.15it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  13%|██████▏                                        | 146/1108 [00:12<01:25, 11.31it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  13%|██████▎                                        | 148/1108 [00:12<01:26, 11.08it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  14%|██████▎                                        | 150/1108 [00:12<01:25, 11.22it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value
Processing AIFF Files:  14%|██████▍                                        | 152/1108 [00:12<01:26, 11.08it/s]/Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/df_AIFF_new.py:223: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe.at[index, key] = value

DONE with getting ID3 tags
DONE with renaming ID3 tags
DONE with processing ID3 tags for DATES
DONE with processing ID3 tags for isrc rel_COUNTRY_code
Error reading TRkw_Deeper_Into_Blue_ARkw_Waajeed_MXkw_Instrumental_KYkw_D_Major_BPkw_126_GNkw_Tech_House_RMkw__LBkw_Dirt_Tech_Reck_RYkw_2019_07_26_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Rojo,_Sangre_Y_Fuego_(Original)_ARkw_More_Lotion_MXkw_Original_KYkw_E_Minor_BPkw_126_GNkw_House_RMkw__LBkw_Jolly_Jams_RYkw_2023_03_31_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Tamo_Loco_ARkw_Lorna,_Hugel,_Jenn_Morel_MXkw_Original_Mix_KYkw_F_Major_BPkw_126_GNkw_Dance___Pop_RMkw__LBkw_Insomniac_Records_RYkw_2022_07_01_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Octave_One_ARkw_Drez_(HU)_MXkw_Original_Mix_KYkw_A_Minor_BPkw_128_GNkw_Minimal___Deep_Tech_RMkw__LBkw_Rawsome_Ltd_RYkw_2021_07_12_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Dirty_Dancing_ARkw_Harvard_Bass_MXkw_Bontan_&_Melé_Remix_KYkw_C_Minor_BPkw_124_GNkw_House_RMkw_Bontan,_Mele_LBkw_Bump_City_Records_RYkw_2021_09_17_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_We_Give_Thee_Honor_ARkw_Floorplan_MXkw_Extended_Mix_KYkw_C_Minor_BPkw_125_GNkw_House_RMkw__LBkw_Classic_Music_Company_RYkw_2023_02_10_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Brave_ARkw_Anushka_MXkw_Original_Mix_KYkw_Db_Minor_BPkw_112_GNkw_Electronica_RMkw__LBkw_Tru_Thoughts_RYkw_2021_04_13_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Cape_Cod_ARkw_Marma_Boog_MXkw_Original_Mix_KYkw_A_Minor_BPkw_117_GNkw_House_RMkw__LBkw_Paper_Disco_RYkw_2018_05_10_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_The_Dub_ARkw_Waajeed_MXkw_Original_Mix_KYkw_A_Minor_BPkw_125_GNkw_Dance___Pop_RMkw__LBkw_BMG_Rights_Management_(UK)_Ltd_RYkw_2022_11_25_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Into_Deeper_ARkw_Twilite_MXkw_Original_Mix_KYkw_F_Minor_BPkw_111_GNkw_Deep_House_RMkw__LBkw_Scenic_Music_RYkw_2013_03_18_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Tio_Rico_ARkw_Marcos_Cabral_MXkw_Original_Mix_KYkw_Ab_Minor_BPkw_105_GNkw_House_RMkw__LBkw_L.I.E.S._Records_RYkw_2013_12_03_PYkw_2023_05_10.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Mr_Dry_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_E_Minor_BPkw_125_GNkw_House_RMkw__LBkw_For_A_Memory_RYkw_2009_08_01_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Ain_t_No_Other_Man_ARkw_Murphy_s_Law_(UK)_MXkw_Rework_-_Extended_Mix_KYkw_Gb_Minor_BPkw_128_GNkw_Funky_House_RMkw__LBkw_RCA_Legacy_RYkw_2023_05_19_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Get_Busy_ARkw_Kevin_McKay_MXkw_Extended_Mix_KYkw_F_Minor_BPkw_126_GNkw_Tech_House_RMkw__LBkw_Glasgow_Underground_RYkw_2023_04_21_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Set_It_Off_ARkw_Strafe_MXkw_Justin_Martin_Remix_KYkw_A_Minor_BPkw_120_GNkw_Breaks___Breakbeat___UK_Bass_RMkw_Justin_Martin_LBkw_DIRTYBIRD_RYkw_2018_10_12_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Wave_feat._ZENSOFLY_&_Maxville_ARkw_Catz__n_Dogz,_ZENSOFLY,_Maxville_MXkw_Justin_Martin_Remix_KYkw_F_Major_BPkw_124_GNkw_Tech_House_RMkw_Justin_Martin_LBkw_Pets_Recordings_RYkw_2020_01_03_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Back_To_The_Jungle_ARkw_Justin_Martin,_Will_Clarke_MXkw_Chris_Lorenzo_Remix_KYkw_A_Minor_BPkw_124_GNkw_Tech_House_RMkw_Chris_Lorenzo_LBkw_DIRTYBIRD_RYkw_2017_09_29_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Hail_Mary_ARkw_Justin_Martin,_Ardalan_MXkw_Original_Mix_KYkw_A_Minor_BPkw_122_GNkw_Breaks___Breakbeat___UK_Bass_RMkw__LBkw_Trippy_Ass_Technologies_RYkw_2019_02_08_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Mushrooms_ARkw_Marshall_Jefferson_MXkw_Justin_Martin_Remix_KYkw_A_Major_BPkw_125_GNkw_Tech_House_RMkw_Justin_Martin_LBkw_Freakin909_RYkw_2018_12_28_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Can_You_Pass_That__ARkw_Walker_&_Royce,_Mr._JPatt_MXkw_Justin_Martin_&_Ardalan_Dub_KYkw_B_Major_BPkw_126_GNkw_Tech_House_RMkw_Justin_Martin,_Ardalan_LBkw_DIRTYBIRD_RYkw_2018_08_24_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Defrost_My_Heart_(feat._Victoria_Rae)_ARkw_Justin_Martin_MXkw_Original_Mix_KYkw_C_Minor_BPkw_126_GNkw_Bass_House_RMkw__LBkw_What_To_Do_RYkw_2023_05_26_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Flowcito_ARkw_VLTRA_(IT),_Francis_De_Simone_MXkw_Loco_Dice_Remix_KYkw_B_Minor_BPkw_129_GNkw_Tech_House_RMkw_Loco_Dice_LBkw_SB_Recordings_RYkw_2023_05_19_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Set_It_Off_ARkw_Strafe_MXkw_Justin_Martin_Party_Starter_Remix_KYkw_A_Minor_BPkw_92_GNkw_Tech_House_RMkw_Justin_Martin_LBkw_DIRTYBIRD_RYkw_2018_10_12_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Rhyme_Dust_ARkw_MK,_Dom_Dolla_MXkw_Extended_KYkw_G_Major_BPkw_128_GNkw_Tech_House_RMkw__LBkw_Columbia_(Sony)_RYkw_2023_02_24_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Ruff_Stuff_ARkw_Justin_Martin_MXkw_Walker_&_Royce_Remix_KYkw_Gb_Minor_BPkw_128_GNkw_Bass_House_RMkw_Walker_&_Royce_LBkw_What_To_Do_RYkw_2022_10_14_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_The_Feels_ARkw_Justin_Martin_MXkw_Low_Steppa_Remix_KYkw_Eb_Minor_BPkw_123_GNkw_Tech_House_RMkw_Low_Steppa_LBkw_DIRTYBIRD_RYkw_2017_02_24_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Sweat_ARkw_ESSEL_MXkw_Extended_Mix_KYkw_Eb_Minor_BPkw_127_GNkw_Tech_House_RMkw__LBkw_Toolroom_RYkw_2023_04_21_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Belter_ARkw_Justin_Martin,_Christian_Martin_MXkw_Original_Mix_KYkw_F_Minor_BPkw_126_GNkw_Techno_(Peak_Time___Driving)_RMkw__LBkw_Trippy_Ass_Technologies_RYkw_2020_03_10_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Stay_(feat._Dalilah)_ARkw_Justin_Martin,_Dalilah_MXkw_Original_Mix_KYkw_C#_Minor_BPkw_122_GNkw_Tech_House_RMkw__LBkw_What_To_Do_RYkw_2020_04_27_PYkw_2023_06_02.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Could_Heaven_Ever_Be_Like_This_ARkw_Idris_Muhammad_MXkw_Walker_&_Royce_and_Chris_Lorenzo_Extended_Mix_KYkw_D_Minor_BPkw_127_GNkw_House_RMkw_Walker_&_Royce,_Chris_Lorenzo_LBkw_Ultra_RYkw_2022_08_12_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_MAMI_(feat._COBRAH)_ARkw_Chris_Lorenzo_MXkw_AC_Slater_Extended_Remix_KYkw_Eb_Minor_BPkw_128_GNkw_Bass_House_RMkw_AC_Slater_LBkw_Late_Checkout_RYkw_2022_10_14_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_MAMI_ARkw_Chris_Lorenzo,_COBRAH_MXkw_Extended_Mix_KYkw_Bb_Major_BPkw_126_GNkw_Bass_House_RMkw__LBkw_Late_Checkout_RYkw_2022_07_22_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Esa_Nena_ARkw_Chuwe_MXkw_Original_Mix_KYkw_B_Minor_BPkw_125_GNkw_Tech_House_RMkw__LBkw_DistroKid_RYkw_2022_03_18_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_In_Da_Getto_ARkw_Skrillex,_J_Balvin_MXkw_Chris_Lorenzo_Remix_KYkw_E_Major_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_Sueños_Globales,_LLC_RYkw_2021_12_15_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_TURMA_ARkw_Twogangs_MXkw_Original_Mix_KYkw_A#_Minor_BPkw_128_GNkw_Bass___Club_RMkw__LBkw_Good_Times_Bad_Times_Records_RYkw_2020_05_22_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Back_Seat_ARkw_Anna_Lunoe,_Genesis_Owusu_MXkw_Chris_Lorenzo_Remix_KYkw_G_Minor_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_NLV_Records_RYkw_2022_01_13_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Disco_Maghreb_ARkw_DJ_Snake_MXkw_Original_Mix_KYkw_Ab_Major_BPkw_100_GNkw_Dance___Pop_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_05_31_PYkw_2023_03_29.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Work_It_ARkw_Kevin_McKay,_Milos_Pesovic_MXkw_Extended_Club_Mix_KYkw_C_Major_BPkw_125_GNkw_Tech_House_RMkw__LBkw_Glasgow_Underground_RYkw_2020_10_23_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_London_Grammar_ARkw_Tube_&_Velvet_MXkw_Original_Mix_KYkw_C_Minor_BPkw_120_GNkw_Tech_House_RMkw_Weekend_Mode_LBkw_PRYZMA_RYkw_2021_11_22_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Tesseract_ARkw_Pablo_Fierro_MXkw_Original_Mix_KYkw_Bb_Major_BPkw_123_GNkw_Melodic_House_&_Techno_RMkw__LBkw_WE_RE_HERE_RYkw_2022_06_10_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Never_Sleep_Again_ARkw_Solomun_MXkw_Keinemusik_Remix_KYkw_G_Minor_BPkw_120_GNkw_Melodic_House_&_Techno_RMkw_&ME,_Rampa,_Adam_Port,_Keinemusik_LBkw_NINL_RYkw_2022_06_10_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Booom_Shak_ARkw_Rene_Amesz_MXkw_Extended_Mix_KYkw_F_Major_BPkw_123_GNkw_House_RMkw__LBkw_Armada_Subjekt_RYkw_2017_12_04_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Ta_Que_Tiembla_ARkw_Buscabulla_MXkw_Original_Mix_KYkw_G#_Minor_BPkw_88_GNkw_House_RMkw__LBkw_Ribbon_Music_RYkw_2020_05_08_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Dancing_To_ARkw_Kurd_Maverick_MXkw_Extended_Mix_KYkw_A#_Minor_BPkw_123_GNkw_House_RMkw__LBkw_Toolroom_RYkw_2020_12_18_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Camaleon_ARkw_Pablo_Fierro_MXkw_Original_Mix_KYkw_F_Major_BPkw_123_GNkw_Afro_House_RMkw__LBkw_WE_RE_HERE_RYkw_2022_06_24_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Reincarnation_ARkw_Pablo_Fierro_MXkw_Original_Mix_KYkw_A_Minor_BPkw_124_GNkw_Afro_House_RMkw__LBkw_Watergate_Records_RYkw_2020_11_30_PYkw_2023_05_07.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Everyday_ARkw_Nils_Hunerfurst_MXkw_Original_Mix_KYkw_E_Minor_BPkw__GNkw_Electronica_RMkw__LBkw_recordJet_RYkw_2019_10_19_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Another_Brick_In_The_Wall_ARkw_Pink_Coffee_MXkw_Original_Mix_KYkw_D_Major_BPkw_125_GNkw_Funky_House_RMkw__LBkw_Pacha_Recordings_RYkw_2012_12_17_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Explosions_in_a_Four_Chambered_Heart_ARkw_Moon_Ate_the_Dark_MXkw_Original_Mix_KYkw_A_Minor_BPkw_135_GNkw_Electronica_RMkw__LBkw_Sonic_Pieces_RYkw_2012_06_08_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Estación_Esperanza_feat._Manu_Chao_ARkw_Manu_Chao,_Sofia_Kourtesis_MXkw_Original_Mix_KYkw_A_Minor_BPkw_122_GNkw_Afro_House_RMkw__LBkw_Ninja_Tune_RYkw_2022_01_17_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Apaga_La_Luz_ARkw_Tony_Touch_MXkw_Pablo_Fierro_Raw_Mix_KYkw_E_Minor_BPkw_124_GNkw_Afro_House_RMkw_Pablo_Fierro_LBkw_Vega_Records_RYkw_2022_11_25_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Ojos_Verdes_ARkw_Jamek_Ortega,_JUNO_(DE)_MXkw_Original_Mix_KYkw_C_Minor_BPkw_121_GNkw_Afro_House_RMkw__LBkw_MoBlack_Records_RYkw_2023_03_17_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Kuar_ARkw_Henrik_Schwarz,_Emmanuel_Jal_MXkw_Henrik_Schwarz_Remix_KYkw_D#_Minor_BPkw_125_GNkw_Afro_House_RMkw_Henrik_Schwarz_LBkw_Innervisions_RYkw_2020_01_17_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Joys_ARkw_Roberto_Surace_MXkw_Extended_Mix_KYkw_G_Major_BPkw_125_GNkw_House_RMkw__LBkw_Defected_RYkw_2019_07_19_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Algo_Cabrón_ARkw_Andres_Losada_MXkw_Original_Mix_KYkw_Bb_Minor_BPkw_127_GNkw_Minimal___Deep_Tech_RMkw__LBkw_Duff_Music_RYkw_2022_08_31_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Prospect_(feat._ÄTNA)_ARkw_Solomun,_Atna_MXkw_Carl_Craig_Late_Island_Mix_KYkw_A_Minor_BPkw_127_GNkw_Melodic_House_&_Techno_RMkw_Carl_Craig_LBkw_NINL_RYkw_2022_10_14_PYkw_2023_08_03.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Vayu_ARkw_Kora_(CA)_MXkw_Original_Mix_KYkw_G_Major_BPkw_119_GNkw_Organic_House___Downtempo_RMkw__LBkw_Earthly_Delights_RYkw_2017_01_16_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Guddi_Riddim_ARkw_DJ_Snake,_Wade,_Nooran_Sisters_MXkw_Extended_Mix_KYkw_Ab_Minor_BPkw_128_GNkw_Tech_House_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_12_20_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Yeva_ARkw_Nicola_Cruz_MXkw_Original_Mix_KYkw_D#_Minor_BPkw_107_GNkw_Indie_Dance_RMkw__LBkw_Optimo_Music_Digital_Danceforce_RYkw_2020_03_27_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Tiniri_ARkw_Sabo,_Satori_(NL),_Amine_K_(Moroko_Loko)_MXkw_Satori_Re_Imagined_Mix_KYkw_G_Major_BPkw_107_GNkw_Organic_House___Downtempo_RMkw__LBkw_Sol_Selectas_RYkw_2020_10_09_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_La_Luna_Perdida_ARkw_Joseph_Paul_DeFaria,_J.Pool_MXkw_Original_Mix_KYkw_D_Minor_BPkw_109_GNkw_Electronica_RMkw__LBkw_Numa_RYkw_2018_11_23_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_WYWD_ARkw_Girl_Unit,_Kelela_MXkw_Remix_KYkw_Ab_Minor_BPkw_124_GNkw_Bass___Club_RMkw__LBkw_Night_Slugs._RYkw_2018_06_14_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_All_Comes_ARkw_GRY,_Christian_Löffler_MXkw_Original_Mix_KYkw_Eb_Minor_BPkw_120_GNkw_Deep_House_RMkw_Mind_Against_LBkw_Young_Alaska_RYkw_2014_08_29_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Camino_en_Llamas_ARkw_Lagartijeando_MXkw_Uji_Remix_KYkw_A_Minor_BPkw_135_GNkw_Electronica_RMkw_Uji_LBkw_Wonderwheel_Recordings_RYkw_2022_09_16_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Yeke_Yeke_ARkw_Stylo,_Space_Motion_MXkw_Original_Mix_KYkw_C_Major_BPkw_122_GNkw_Afro_House_RMkw__LBkw_Space_Motion_Records_RYkw_2021_05_10_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Sayha_ARkw_Space_Motion,_Zanjma_MXkw_Original_Mix_KYkw_Eb_Major_BPkw_125_GNkw_Progressive_House_RMkw__LBkw_Space_Motion_Records_RYkw_2019_10_14_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Lazos_ARkw_Simon_Vuarambon_MXkw_Original_Mix_KYkw_A_Minor_BPkw_120_GNkw_Organic_House___Downtempo_RMkw__LBkw_Peace_Symphonies_RYkw_2021_05_06_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Nahimana_ARkw_Rey&Kjavik_MXkw_Original_Mix_KYkw_D_Minor_BPkw_102_GNkw_Electronica_RMkw__LBkw_RKJVK_RYkw_2018_12_14_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Cause_Away_ARkw_Loquace_MXkw_Original_Mix_KYkw_F_Minor_BPkw_92_GNkw_Tech_House_RMkw__LBkw_Kiara_Records_RYkw_2013_05_20_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Muyè_ARkw_&ME,_Rampa,_Adam_Port_MXkw_Black_Coffee_Remix_KYkw_A_Minor_BPkw_120_GNkw_Melodic_House_&_Techno_RMkw_Black_Coffee_LBkw_Keinemusik_RYkw_2018_04_06_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Lost_Memories_ARkw_Rey&Kjavik,_Mazefive_MXkw_Original_Mix_KYkw_C_Major_BPkw_118_GNkw_Organic_House___Downtempo_RMkw__LBkw_RKJVK_RYkw_2021_02_26_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Kids_of_Hula_ARkw_Rodriguez_Jr._MXkw_Original_Mix_KYkw_G_Minor_BPkw_127_GNkw_Tech_House_RMkw__LBkw_Leena_Music_RYkw_2009_07_13_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Kaboo_ARkw_DJ_Diass_MXkw_Original_Mix_KYkw_Bb_Minor_BPkw_123_GNkw_Tech_House_RMkw__LBkw_NastyFunk_Records_RYkw_2017_03_06_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Caparica_ARkw_Populous_MXkw_Original_Mix_KYkw_Bb_Major_BPkw_108_GNkw_House_RMkw__LBkw_Wonderwheel_Recordings_RYkw_2022_09_16_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Roomers_ARkw_Derek_Marin,_Juliet_Fox_MXkw_Alexander_Aurel_Remix_KYkw_F_Major_BPkw_125_GNkw_Tech_House_RMkw_Alexander_Aurel_LBkw_My_Favourite_Freaks_Music_RYkw_2016_12_09_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Sayha_ARkw_Erhan_Yilmaz_MXkw_Original_Mix_KYkw_C_Minor_BPkw_105_GNkw_Organic_House___Downtempo_RMkw__LBkw_Shango_Records_RYkw_2022_02_18_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_El_Colapso_Suena_ARkw_Uji_MXkw_Original_Mix_KYkw_A_Minor_BPkw_108_GNkw_Electronica_RMkw__LBkw_ZZK_Records_RYkw_2018_06_08_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_The_Messenger_ARkw_Nicola_Cruz_MXkw_Original_Mix_KYkw_Ab_Major_BPkw_115_GNkw_Techno_(Raw___Deep___Hypnotic)_RMkw__LBkw_Highlife_RYkw_2023_01_13_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Cuando_Canto_Grito_ARkw_Cerrero,_Lucia_Pulido,_Diego_Gómez_MXkw_Original_Mix_KYkw_A#_Minor_BPkw_86_GNkw_Electronica_RMkw__LBkw_BBE_Music_RYkw_2019_06_07_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Run_Again_ARkw_Space_Motion_MXkw_Original_Mix_KYkw_G_Major_BPkw_125_GNkw_Melodic_House_&_Techno_RMkw__LBkw_Space_Motion_Records_RYkw_2021_11_01_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Undefeated_Warrior_ARkw_Moshiana_MXkw_Shaka_Zulu_KYkw_C_Minor_BPkw_124_GNkw_House_RMkw__LBkw_StreetWise_Records_RYkw_2014_03_17_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Palang_Kuh_ARkw_Birds_of_Mind_MXkw_Original_Mix_KYkw_D_Minor_BPkw_97_GNkw_Electronica_RMkw__LBkw_Underyourskin_Records_RYkw_2016_07_21_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Maloka_ARkw_Uji_MXkw_Original_Mix_KYkw_A_Major_BPkw_101_GNkw_Electronica_RMkw__LBkw_ZZK_Records_RYkw_2018_06_08_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Moan_ARkw_Trentemoller_MXkw_Trentemoller_Remix_KYkw_C_Minor_BPkw_120_GNkw_Tech_House_RMkw_Trentemoller_LBkw_Poker_Flat_Recordings_RYkw_2007_03_05_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Haunted_House_ARkw_Raz_Ohara,_Acid_Pauli,_Nu,_FEATHERED_SUN,_Jo.Ke,_Chris_Schwarzwalder_MXkw_Original_Mix_KYkw_A_Minor_BPkw_78_GNkw_Electronica_RMkw__LBkw_Denature_Records_RYkw_2017_04_28_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Telemenet_ARkw_Stae_MXkw_Original_Mix_KYkw_C_Minor_BPkw_120_GNkw_Organic_House___Downtempo_RMkw__LBkw_The_Soundgarden_RYkw_2023_04_07_PYkw_2023_04_15.aiff: argument of type 'NoneType' is not iterable
Error reading TRkw_Before_ARkw_Pablo_Fierro_MXkw_Original_Mix_KYkw_Bb_Minor_BPkw_120_GNkw_Afro_House_RMkw__LBkw_WE_RE_HERE_RYkw_2021_10_22_PYkw_2023_05_22.aiff: argument of type 'NoneType' is not iterable

In [63]:
display_missing_data_by_extension(df) #display Freq table of attributes by extension and list of vars

######################## EXTENSION: .aiff ########################

Column               Missing Values       Percentage Missing
------------------------------------------------------------
temp_id              0                    0.00%
Path                 0                    0.00%
Extension            0                    0.00%
dur_seconds          0                    0.00%
dur_min              0                    0.00%
sr                   0                    0.00%
bit_rate             1108                 100.00%
bit_depth            0                    0.00%
channels             0                    0.00%
file_size            0                    0.00%
file_size_human      0                    0.00%
num_frames           0                    0.00%
error                1108                 100.00%
ms_lufs              0                    0.00%
ms_LUFS_code         0                    0.00%
title                0                    0.00%
artist               0                    0.00%
rework               1                    0.09%
album                178                  16.06%
track_#              178                  16.06%
genre                2                    0.18%
LABEL                2                    0.18%
isrc                 0                    0.00%
rel_country          1108                 100.00%
rel_date             2                    0.18%
year                 168                  15.16%
rel_year             1108                 100.00%
rel_month            1108                 100.00%
rel_day              1108                 100.00%
rel_weekday          1108                 100.00%
audio_offset         1                    0.09%
decoder              0                    0.00%
comment              0                    0.00%
BPM                  2                    0.18%
KEY                  0                    0.00%
KEYC                 309                  27.89%
KEY_code             309                  27.89%
audio_hash           0                    0.00%
remix                2                    0.18%
status               0                    0.00%
################################################################################

 >>> NAMES 40 of columns

col_names =  ['temp_id', 'Path', 'Extension', 'dur_seconds', 'dur_min', 'sr', 'bit_rate', 'bit_depth', 'channels', 'file_size', 'file_size_human', 'num_frames', 'error', 'ms_lufs', 'ms_LUFS_code', 'title', 'artist', 'rework', 'album', 'track_#', 'genre', 'LABEL', 'isrc', 'rel_country', 'rel_date', 'year', 'rel_year', 'rel_month', 'rel_day', 'rel_weekday', 'audio_offset', 'decoder', 'comment', 'BPM', 'KEY', 'KEYC', 'KEY_code', 'audio_hash', 'remix', 'status']

In [6]:
### HASH VALUE
#df = _hash_bulk_2812_audio_GET_df_hashes(df)
#df

## CHECK POINT

In [7]:
#### get all the values trhough words

In [53]:
df.head()

                                                                                                                                                                            temp_id                                                                                                                                                                                                                                                 Path Extension dur_seconds   dur_min     sr bit_rate bit_depth channels file_size file_size_human num_frames error  ms_lufs ms_LUFS_code                                       title           artist                    rework                                        album track_#                genre                            LABEL isrc rel_country      rel_date  year rel_year rel_month rel_day rel_weekday  audio_offset decoder comment    BPM    KEY     KEYC KEY_code                                                        audio_hash         remix                 status
0                                  TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_Db_Major_BPkw_124_GNkw_Minimal___Deep_Tech_RMkw__LBkw_DIRTYBIRD_RYkw_2008_05_14_PYkw_2023_09_05                                  /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_Db_Major_BPkw_124_GNkw_Minimal___Deep_Tech_RMkw__LBkw_DIRTYBIRD_RYkw_2008_05_14_PYkw_2023_09_05.aiff     .aiff  412.810884  6.880181  44100     None        16        2  72851124        69.48 MB   18204960  None  -12.494          LuD                        Revox (Original Mix)        Tim Green                   Ori_Mix                                        Revox       1  Minimal / Deep Tech                      _DIRTYBIRD_          Unknown  _2008_05_14_  2008     None      None    None        None          46.0    none     LuD  _124_  Dbmaj  Unknown  Unknown  c6af9d8d3896b26ced0bdfd81b1fe343479e6b70a236622129cf909f5bc05ded            __  Success: Tags updated
1              TRkw_Baby_Wants_To_Ride_ARkw_Jamie_Principle_MXkw_James_Curd_Remix_KYkw_D_Minor_BPkw_126_GNkw_House_RMkw_James_Curd_LBkw_S&S_Records_RYkw_2022_02_25_PYkw_2023_09_05              /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Baby_Wants_To_Ride_ARkw_Jamie_Principle_MXkw_James_Curd_Remix_KYkw_D_Minor_BPkw_126_GNkw_House_RMkw_James_Curd_LBkw_S&S_Records_RYkw_2022_02_25_PYkw_2023_09_05.aiff     .aiff  433.333333  7.222222  44100     None        16        2  77032764        73.46 MB   19110000  None  -10.212          Lue       Baby Wants To Ride (James Curd Remix)  Jamie Principle          James Curd Remix  S&S Curations Mix Compilation 004 (DJ Slab)       7                House                    _S&S_Records_          Unknown  _2022_02_25_  2022     None      None    None        None          46.0    none     Lue  _126_   Dmin       7A      07A  906c7885737443a493a685e068e3f724a27014c9b4aeca5670acf4c92b18acbc  _James_Curd_  Success: Tags updated
2                        TRkw_Lengua_Ri_Suto_ARkw_Ghetto_Kumbe_MXkw_Cero39_Remix_KYkw_C_Minor_BPkw_80_GNkw_Electronica_RMkw_Cero39_LBkw_ZZK_Records_RYkw_2022_11_09_PYkw_2023_09_05                        /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Lengua_Ri_Suto_ARkw_Ghetto_Kumbe_MXkw_Cero39_Remix_KYkw_C_Minor_BPkw_80_GNkw_Electronica_RMkw_Cero39_LBkw_ZZK_Records_RYkw_2022_11_09_PYkw_2023_09_05.aiff     .aiff  230.692971  3.844883  44100     None        16        2  43705650        41.68 MB   10173560  None   -7.342          LuF               Lengua Ri Suto (Cero39 Remix)     Ghetto Kumbe              Cero39 Remix                Ghetto Kumbé Clubbing Remixes      10          Electronica                    _ZZK_Records_          Unknown  _2022_11_09_  2022     None      None    None        None          46.0    none     LuF   _80_   Cmin       5A      05A  d6bfc8aa5c6980bc16007dd0dbb03ef6e4a296f3c291bc922a301ac2ec96eea1      _Cero39_  Success: Tags updated
3  TRkw_Can_You_Feel_It_ARkw_Chez_Damier_MXkw_MK_New_York_Dub_Extended_KYkw_Eb_Minor_BPkw_124_GNkw_House_RMkw_MK_LBkw_KMS_Records_(BEAT_Music_Fund)_RYkw_1992_01_01_PYkw_2023_09_05  /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Can_You_Feel_It_ARkw_Chez_Damier_MXkw_MK_New_York_Dub_Extended_KYkw_Eb_Minor_BPkw_124_GNkw_House_RMkw_MK_LBkw_KMS_Records_(BEAT_Music_Fund)_RYkw_1992_01_01_PYkw_2023_09_05.aiff     .aiff  328.919773  5.481996  44100     None        16        2  59754958        56.99 MB   14505362  None  -10.596          Lue  Can You Feel It (MK New York Dub Extended)      Chez Damier  MK New York Dub Extended                              Can You Feel It       1                House  _KMS_Records_(BEAT_Music_Fund)_          Unknown  _1992_01_01_  1992     None      None    None        None          46.0    none     Lue  _124_  Ebmin  Unknown  Unknown  6771ba8393efda0aa73bb41c8e068c1244dbd880ea33dc27bd06c87f7b323f47          _MK_  Success: Tags updated
4                               TRkw_Recovery_ARkw_Rival_Consoles_MXkw_Original_Mix_KYkw_F#_Minor_BPkw_155_GNkw_Electronica_RMkw__LBkw_Erased_Tapes_RYkw_2019_02_28_PYkw_2023_09_05                               /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Recovery_ARkw_Rival_Consoles_MXkw_Original_Mix_KYkw_F#_Minor_BPkw_155_GNkw_Electronica_RMkw__LBkw_Erased_Tapes_RYkw_2019_02_28_PYkw_2023_09_05.aiff     .aiff  290.201587  4.836693  44100     None        16        2  51270722        48.90 MB   12797890  None  -11.857          Lue                     Recovery (Original Mix)   Rival Consoles                   Ori_Mix                                        Sonne       6          Electronica                   _Erased_Tapes_          Unknown  _2019_02_28_  2019     None      None    None        None          46.0    none     Lue  _155_  F#min      11A      11A  efdc49a33b7a63d18c90739e23976e49d8c37571f426ed854ba40524a8deb6d7            __  Success: Tags updated

# if not in df get from FILE NAMES

In [10]:
col_names =  ['temp_id', 'Path', 'Extension', 'dur_seconds', 'dur_min', 'sr', 'bit_rate', 'bit_depth', 'channels', 'file_size', 'file_size_human', 'num_frames', 'error', 'ms_lufs', 'ms_LUFS_code', 'title', 'artist', 'rework', 'album', 'track_#', 'genre', 'LABEL', 'isrc', 'rel_country', 'rel_date', 'year', 'rel_year', 'rel_month', 'rel_day', 'rel_weekday', 'audio_offset', 'decoder', 'comment', 'BPM', 'KEY', 'KEYC', 'KEY_code']

In [60]:
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

def _file_extract_from_file_name_(df,var,btw_front, btw_back):
    import pandas as pd

    # Define "empty" values
    empty_values = [None, "", "None", "NAN", "NaN", "nan","Error: argument of type 'NoneType' is not iterable"]
    
    # Identify rows with missing 'title'
    missing_title_idx = df[f'{var}'].isin(empty_values) | df[f'{var}'].isnull()
    
    # Extract title from temp_id using the rule
    def extract_title_from_temp_id(temp_id):
        if isinstance(temp_id, str) and f"{btw_front}" in temp_id and f"{btw_back}"in temp_id:
            start = temp_id.find(f"{btw_front}") + 4  # Start after "TRkw"
            end = temp_id.find(f"{btw_back}", start)  # End before "ARkw"
            return temp_id[start:end].strip()
        return None  # Return None if pattern not found or temp_id is not a string

    # Apply extraction to missing titles
    df.loc[missing_title_idx, f'{var}'] = df.loc[missing_title_idx, 'temp_id'].apply(extract_title_from_temp_id)

    return df

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
# RUNNING STATEMENTS
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

# Title
var = 'title' ; btw_front = 'TRkw' ; btw_back = 'ARkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# Artist 
var = 'artist' ; btw_front = 'ARkw' ; btw_back = 'MXkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# rework
var = 'rework'; btw_front = 'MXkw' ; btw_back = 'KYkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# key 
var = 'KEY'; btw_front = 'KYkw' ; btw_back = 'BPkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# BPM 
var = 'BPM'; btw_front = 'BPkw' ; btw_back = 'GNkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# genre
var = 'genre'; btw_front = 'GNkw' ; btw_back = 'RMkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# remix
df['remix'] = None
var = 'remix'; btw_front = 'RMkw' ; btw_back = 'LBkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# label
var = 'LABEL'; btw_front = 'LBkw' ; btw_back = 'RYkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)

# REL year
var = 'rel_date'; btw_front = 'RYkw' ; btw_back = 'PYkw'
df = _file_extract_from_file_name_(df,var,btw_front, btw_back)


col_names =  ['temp_id', 'Path', 'Extension', 'dur_seconds', 'dur_min', 'sr', 'bit_rate', 'bit_depth', 'channels', 'file_size', 'file_size_human', 'num_frames', 'error', 'ms_lufs', 'ms_LUFS_code', 'title', 'artist', 'rework', 'album', 'track_#', 'genre', 'LABEL', 'isrc', 'rel_country', 'rel_date', 'year', 'rel_year', 'rel_month', 'rel_day', 'rel_weekday', 'audio_offset', 'decoder', 'comment', 'BPM', 'KEY', 'KEYC', 'KEY_code'] 
col_imp =[ 'ms_lufs', 'ms_LUFS_code', 'title', 'artist', 'rework', 'album', 'genre', 'LABEL', 'isrc', 'rel_country', 'rel_date', 'year', 'audio_offset', 'decoder', 'comment', 'BPM', 'KEY', 'KEYC', 'KEY_code'] 

df_1 = df[['ms_lufs', 'ms_LUFS_code',  'title','artist','rework','KEY','BPM', 'genre','remix','LABEL', 'rel_date',
          'audio_hash','Path', 'comment']].copy()

In [61]:
df.head(2)

                                                                                                                                                                temp_id                                                                                                                                                                                                                                     Path Extension dur_seconds   dur_min     sr bit_rate bit_depth channels file_size file_size_human num_frames error  ms_lufs ms_LUFS_code                                  title           artist            rework                                        album track_#                genre          LABEL isrc rel_country      rel_date  year rel_year rel_month rel_day rel_weekday  audio_offset decoder comment    BPM    KEY     KEYC KEY_code                                                        audio_hash         remix                 status
0                      TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_Db_Major_BPkw_124_GNkw_Minimal___Deep_Tech_RMkw__LBkw_DIRTYBIRD_RYkw_2008_05_14_PYkw_2023_09_05                      /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_Db_Major_BPkw_124_GNkw_Minimal___Deep_Tech_RMkw__LBkw_DIRTYBIRD_RYkw_2008_05_14_PYkw_2023_09_05.aiff     .aiff  412.810884  6.880181  44100     None        16        2  72851124        69.48 MB   18204960  None  -12.494          LuD                   Revox (Original Mix)        Tim Green           Ori_Mix                                        Revox       1  Minimal / Deep Tech    _DIRTYBIRD_          Unknown  _2008_05_14_  2008     None      None    None        None          46.0    none     LuD  _124_  Dbmaj  Unknown  Unknown  c6af9d8d3896b26ced0bdfd81b1fe343479e6b70a236622129cf909f5bc05ded            __  Success: Tags updated
1  TRkw_Baby_Wants_To_Ride_ARkw_Jamie_Principle_MXkw_James_Curd_Remix_KYkw_D_Minor_BPkw_126_GNkw_House_RMkw_James_Curd_LBkw_S&S_Records_RYkw_2022_02_25_PYkw_2023_09_05  /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Baby_Wants_To_Ride_ARkw_Jamie_Principle_MXkw_James_Curd_Remix_KYkw_D_Minor_BPkw_126_GNkw_House_RMkw_James_Curd_LBkw_S&S_Records_RYkw_2022_02_25_PYkw_2023_09_05.aiff     .aiff  433.333333  7.222222  44100     None        16        2  77032764        73.46 MB   19110000  None  -10.212          Lue  Baby Wants To Ride (James Curd Remix)  Jamie Principle  James Curd Remix  S&S Curations Mix Compilation 004 (DJ Slab)       7                House  _S&S_Records_          Unknown  _2022_02_25_  2022     None      None    None        None          46.0    none     Lue  _126_   Dmin       7A      07A  906c7885737443a493a685e068e3f724a27014c9b4aeca5670acf4c92b18acbc  _James_Curd_  Success: Tags updated

In [62]:
display_missing_data_by_extension(df_1)

######################## EXTENSION: .aiff ########################

Column               Missing Values       Percentage Missing
------------------------------------------------------------
ms_lufs              0                    0.00%
ms_LUFS_code         0                    0.00%
title                0                    0.00%
artist               0                    0.00%
rework               1                    0.09%
KEY                  0                    0.00%
BPM                  2                    0.18%
genre                2                    0.18%
remix                2                    0.18%
LABEL                2                    0.18%
rel_date             2                    0.18%
audio_hash           0                    0.00%
Path                 0                    0.00%
comment              0                    0.00%
Extension            0                    0.00%
################################################################################

 >>> NAMES 15 of columns

col_names =  ['ms_lufs', 'ms_LUFS_code', 'title', 'artist', 'rework', 'KEY', 'BPM', 'genre', 'remix', 'LABEL', 'rel_date', 'audio_hash', 'Path', 'comment', 'Extension']

In [ ]:
# analyze the columns 
column = 
# Calculate the total count from value_counts
value_counts_sum = df['tag_key'].value_counts().sum()

# Calculate the total rows in the column
total_rows = len(df['tag_key'])
print(total_rows )

df['tag_key'].value_counts()

In [52]:
# Your important columns
col_imp = [ 'rel_country']
# 'ms_LUFS_code', 'title', 'artist', 'rework', 'album', 'genre', 'LABEL', 
#    'isrc', 'rel_country', 'rel_date', 'year', 'audio_offset', 'decoder', 'comment', 
#    'BPM', 'KEY', 'KEYC', 'KEY_code'
#]

# -----######-----######-----######-----######-----######-----######-----
# FULL LABEL PRINT + MISSING REPORT LOOP
# -----######-----######-----######-----######-----######-----######-----

for column in col_imp:
    if column not in df.columns:
        print(f"\n⚠️ Column missing from DataFrame: {column}")
        continue

    print(f"\n{'='*100}")
    print(f"🔍 COLUMN: {column}")
    print('-'*100)

    # Full label list with value counts
    full_counts = df[column].value_counts(dropna=False)
    for label, count in full_counts.items():
        print(f"{repr(label):<50} -> {count}x")

    # Summary stats
    total = len(df[column])
    missing = df[column].isna().sum()
    percent_missing = (missing / total) * 100
    non_missing_count = df[column].notna().sum()

    print(f"\n✅ Total Rows: {total}")
    print(f"🧮 Non-Null Values: {non_missing_count}")
    print(f"❌ Missing Values: {missing} ({percent_missing:.2f}%)")

====================================================================================================
🔍 COLUMN: rel_country
----------------------------------------------------------------------------------------------------
'Unknown'                                          -> 1108x

✅ Total Rows: 1108
🧮 Non-Null Values: 1108
❌ Missing Values: 0 (0.00%)

In [32]:
df_1.head()

   ms_lufs ms_LUFS_code                                       title           artist                    rework    KEY    BPM                genre         remix                            LABEL      rel_date                                                        audio_hash                                                                                                                                                                                                                                                 Path                                 comment Extension
0  -12.494          LuD                        Revox (Original Mix)        Tim Green                   Ori_Mix  Dbmaj  _124_  Minimal / Deep Tech            __                      _DIRTYBIRD_  _2008_05_14_  c6af9d8d3896b26ced0bdfd81b1fe343479e6b70a236622129cf909f5bc05ded                                  /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_Db_Major_BPkw_124_GNkw_Minimal___Deep_Tech_RMkw__LBkw_DIRTYBIRD_RYkw_2008_05_14_PYkw_2023_09_05.aiff  engID3v1 Comment Purchased at Beatport     .aiff
1  -10.212          Lue       Baby Wants To Ride (James Curd Remix)  Jamie Principle          James Curd Remix   Dmin  _126_                House  _James_Curd_                    _S&S_Records_  _2022_02_25_  906c7885737443a493a685e068e3f724a27014c9b4aeca5670acf4c92b18acbc              /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Baby_Wants_To_Ride_ARkw_Jamie_Principle_MXkw_James_Curd_Remix_KYkw_D_Minor_BPkw_126_GNkw_House_RMkw_James_Curd_LBkw_S&S_Records_RYkw_2022_02_25_PYkw_2023_09_05.aiff  engID3v1 Comment Purchased at Beatport     .aiff
2   -7.342          LuF               Lengua Ri Suto (Cero39 Remix)     Ghetto Kumbe              Cero39 Remix   Cmin   _80_          Electronica      _Cero39_                    _ZZK_Records_  _2022_11_09_  d6bfc8aa5c6980bc16007dd0dbb03ef6e4a296f3c291bc922a301ac2ec96eea1                        /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Lengua_Ri_Suto_ARkw_Ghetto_Kumbe_MXkw_Cero39_Remix_KYkw_C_Minor_BPkw_80_GNkw_Electronica_RMkw_Cero39_LBkw_ZZK_Records_RYkw_2022_11_09_PYkw_2023_09_05.aiff  engID3v1 Comment Purchased at Beatport     .aiff
3  -10.596          Lue  Can You Feel It (MK New York Dub Extended)      Chez Damier  MK New York Dub Extended  Ebmin  _124_                House          _MK_  _KMS_Records_(BEAT_Music_Fund)_  _1992_01_01_  6771ba8393efda0aa73bb41c8e068c1244dbd880ea33dc27bd06c87f7b323f47  /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Can_You_Feel_It_ARkw_Chez_Damier_MXkw_MK_New_York_Dub_Extended_KYkw_Eb_Minor_BPkw_124_GNkw_House_RMkw_MK_LBkw_KMS_Records_(BEAT_Music_Fund)_RYkw_1992_01_01_PYkw_2023_09_05.aiff  engID3v1 Comment Purchased at Beatport     .aiff
4  -11.857          Lue                     Recovery (Original Mix)   Rival Consoles                   Ori_Mix  F#min  _155_          Electronica            __                   _Erased_Tapes_  _2019_02_28_  efdc49a33b7a63d18c90739e23976e49d8c37571f426ed854ba40524a8deb6d7                               /Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_23_09_AN_ArtPArk/TRkw_Recovery_ARkw_Rival_Consoles_MXkw_Original_Mix_KYkw_F#_Minor_BPkw_155_GNkw_Electronica_RMkw__LBkw_Erased_Tapes_RYkw_2019_02_28_PYkw_2023_09_05.aiff  engID3v1 Comment Purchased at Beatport     .aiff

In [35]:
df['comment'] = df['ms_LUFS_code']
#df.head()

In [36]:
df = _write_comment_2712_id3_SET_tag_bulk(df, "Path", "comment")

In [37]:
# -----######-----######-----###### FUNCTION -----######-----######-----######
def _write_tags_2712_id3_SET_tag_bulk(df, path_col, comment_col, genre_col):
    """
    Writes comments and genres to the ID3 tags of AIFF files based on a DataFrame.

    Parameters:
    - df: DataFrame containing file paths, comments, and genres.
    - path_col: Column name in the DataFrame containing AIFF file paths.
    - comment_col: Column name in the DataFrame containing comments to write.
    - genre_col: Column name in the DataFrame containing genres to write.

    Returns:
    - DataFrame: Updated with a 'status' column indicating success or error messages.
    """
    import mutagen
    from mutagen.aiff import AIFF
    from mutagen.id3 import ID3, COMM, TCON

    results = []

    for index, row in df.iterrows():
        aiff_path = row[path_col]
        comment_text = row[comment_col]
        genre_text = row[genre_col]

        try:
            # Load the AIFF file
            audio = AIFF(aiff_path)

            # Add ID3 tag if not already present
            if not hasattr(audio, "tags") or audio.tags is None:
                audio.add_tags()

            # Remove existing comments and genre tags
            if "COMM" in audio.tags:
                del audio.tags["COMM"]
            if "TCON" in audio.tags:
                del audio.tags["TCON"]

            # Add new comment
            audio.tags.add(COMM(encoding=3, lang='eng', desc='', text=comment_text))

            # Add new genre
            audio.tags.add(TCON(encoding=3, text=genre_text))

            # Save changes
            audio.save()

            results.append("Success: Tags updated")
        except Exception as e:
            results.append(f"Error: {e}")

    # Add results to DataFrame
    df["status"] = results
    return df

df =_write_tags_2712_id3_SET_tag_bulk(df, "Path", "comment","genre")

In [26]:
df['genre'] = "oscios "

In [5]:
display_missing_data_by_extension(df)

######################## EXTENSION: .aiff ########################

Column               Missing Values       Percentage Missing
------------------------------------------------------------
temp_id              0                    0.00%
Path                 0                    0.00%
Extension            0                    0.00%
dur_seconds          0                    0.00%
dur_min              0                    0.00%
sr                   0                    0.00%
bit_rate             5                    100.00%
bit_depth            0                    0.00%
channels             0                    0.00%
file_size            0                    0.00%
file_size_human      0                    0.00%
num_frames           0                    0.00%
error                5                    100.00%
ms_lufs              0                    0.00%
ms_LUFS_code         0                    0.00%
title                0                    0.00%
artist               0                    0.00%
rework               2                    40.00%
album                1                    20.00%
track_#              1                    20.00%
genre                3                    60.00%
LABEL                3                    60.00%
isrc                 2                    40.00%
rel_country          2                    40.00%
rel_date             3                    60.00%
year                 0                    0.00%
rel_year             3                    60.00%
rel_month            3                    60.00%
rel_day              3                    60.00%
rel_weekday          3                    60.00%
audio_offset         0                    0.00%
decoder              0                    0.00%
comment              3                    60.00%
BPM                  3                    60.00%
KEY                  0                    0.00%
KEYC                 3                    60.00%
KEY_code             3                    60.00%
################################################################################

 >>> NAMES 37 of columns

col_names =  ['temp_id', 'Path', 'Extension', 'dur_seconds', 'dur_min', 'sr', 'bit_rate', 'bit_depth', 'channels', 'file_size', 'file_size_human', 'num_frames', 'error', 'ms_lufs', 'ms_LUFS_code', 'title', 'artist', 'rework', 'album', 'track_#', 'genre', 'LABEL', 'isrc', 'rel_country', 'rel_date', 'year', 'rel_year', 'rel_month', 'rel_day', 'rel_weekday', 'audio_offset', 'decoder', 'comment', 'BPM', 'KEY', 'KEYC', 'KEY_code']

In [14]:
df_copy = df.copy()

# check missing fields

In [40]:
df= df_copy.copy()

# NOTES

make sure all metadata its ok, do one by one exeption 
LUFS showing everywhere - remember ENERGY of the song depicted - YEAR of prod as well
Detroit pointer in image as well as new collection 

do one by 

When yuo have the main fields completed to the max, then you have to have this 

#### fields in DF with HAsh of the file, image save somewhere, and with id re build all files with new image.

take hash again and see if they are ok !

# CLEANING

In [42]:
# -----######-----###### MAIN FUNCTION -----######-----###### 

def _replace_missing_1212_robust_GET_df(df, cols_1, default="MISSING"):
    """
    Robustly replaces missing values in specified columns using values from the next column
    or a default value when the next column also has missing data.

    Args:
        df: DataFrame to process.
        cols_1: List of columns to align missing values sequentially.
        default: Default value to use when both the current and next column have missing data (default: 'MISSING').

    Returns:
        Updated DataFrame with consistent missing data indicators.
    """
    import numpy as np
    import pandas as pd

    # Define missing indicators explicitly
    missing_indicators = [None, "NaN", "nan", "none", "NaT", "Unknown", "UNKNOWN", np.nan]

    # Ensure all specified columns exist in the DataFrame
    cols_to_process = [col for col in cols_1 if col in df.columns]

    # Convert all specified columns to string type to standardize processing
    df[cols_to_process] = df[cols_to_process].astype(str).replace(missing_indicators, np.nan)

    # Loop through the columns in sequential order
    for i in range(len(cols_to_process) - 1):
        current_col = cols_to_process[i]
        next_col = cols_to_process[i + 1]

        # Fill missing values in the current column using the next column's values
        df[current_col] = df[current_col].fillna(df[next_col])

    # Replace any remaining missing values with the default value
    for col in cols_to_process:
        df[col] = df[col].fillna(default)

    return df

# Define the columns to process
cols_1 = ['title', 'artist', 'rework', 'album', 'genre', 'LABEL',
          'rel_date', 'year', 'rel_year', 'rel_month', 'rel_day', 'BPM', 'KEY']

# Apply the function
df = _replace_missing_1212_robust_GET_df(df, cols_1)

In [43]:
df.head()

                                                                                                                                                                                                                     temp_id                                                                                                                                                                                                                                                                                                 Path Extension dur_seconds   dur_min     sr bit_rate bit_depth channels file_size file_size_human num_frames error  ms_lufs ms_LUFS_code    title artist rework    album track_#    genre    LABEL isrc rel_country rel_date  year rel_year rel_month rel_day rel_weekday  audio_offset decoder comment                                                 BPM                                                 KEY   KEYC KEY_code
0                                           TRkw_Back_Seat_ARkw_Anna_Lunoe,_Genesis_Owusu_MXkw_Chris_Lorenzo_Remix_KYkw_G_Minor_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_NLV_Records_RYkw_2022_01_13_PYkw_2023_03_29                                           /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Back_Seat_ARkw_Anna_Lunoe,_Genesis_Owusu_MXkw_Chris_Lorenzo_Remix_KYkw_G_Minor_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_NLV_Records_RYkw_2022_01_13_PYkw_2023_03_29.aiff     .aiff  286.875011   4.78125  44100     None        16        2  50604806        48.26 MB   12651188  None   -7.168          LuF  MISSING   None   None  MISSING     NaN  MISSING  MISSING  NaN     Unknown  MISSING  None     None      None    None        None          46.0    none     NaN  Error: argument of type 'NoneType' is not iterable  Error: argument of type 'NoneType' is not iterable  Error    Error
1  TRkw_Could_Heaven_Ever_Be_Like_This_ARkw_Idris_Muhammad_MXkw_Walker_&_Royce_and_Chris_Lorenzo_Extended_Mix_KYkw_D_Minor_BPkw_127_GNkw_House_RMkw_Walker_&_Royce,_Chris_Lorenzo_LBkw_Ultra_RYkw_2022_08_12_PYkw_2023_03_29  /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Could_Heaven_Ever_Be_Like_This_ARkw_Idris_Muhammad_MXkw_Walker_&_Royce_and_Chris_Lorenzo_Extended_Mix_KYkw_D_Minor_BPkw_127_GNkw_House_RMkw_Walker_&_Royce,_Chris_Lorenzo_LBkw_Ultra_RYkw_2022_08_12_PYkw_2023_03_29.aiff     .aiff  363.779546  6.062992  44100     None        16        2  64170766        61.20 MB   16042678  None   -7.305          LuF  MISSING   None   None  MISSING     NaN  MISSING  MISSING  NaN     Unknown  MISSING  None     None      None    None        None          46.0    none     NaN  Error: argument of type 'NoneType' is not iterable  Error: argument of type 'NoneType' is not iterable  Error    Error
2                                                   TRkw_Disco_Maghreb_ARkw_DJ_Snake_MXkw_Original_Mix_KYkw_Ab_Major_BPkw_100_GNkw_Dance___Pop_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_05_31_PYkw_2023_03_29                                                   /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Disco_Maghreb_ARkw_DJ_Snake_MXkw_Original_Mix_KYkw_Ab_Major_BPkw_100_GNkw_Dance___Pop_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_05_31_PYkw_2023_03_29.aiff     .aiff  184.799977      3.08  44100     None        16        2  32598770        31.09 MB    8149679  None   -7.362          LuF  MISSING   None   None  MISSING     NaN  MISSING  MISSING  NaN     Unknown  MISSING  None     None      None    None        None          46.0    none     NaN  Error: argument of type 'NoneType' is not iterable  Error: argument of type 'NoneType' is not iterable  Error    Error
3                                                                                      TRkw_Esa_Nena_ARkw_Chuwe_MXkw_Original_Mix_KYkw_B_Minor_BPkw_125_GNkw_Tech_House_RMkw__LBkw_DistroKid_RYkw_2022_03_18_PYkw_2023_03_29                                                                                      /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Esa_Nena_ARkw_Chuwe_MXkw_Original_Mix_KYkw_B_Minor_BPkw_125_GNkw_Tech_House_RMkw__LBkw_DistroKid_RYkw_2022_03_18_PYkw_2023_03_29.aiff     .aiff       254.0  4.233333  44100     None        16        2  44805654        42.73 MB   11201400  None   -6.471          LuF  MISSING   None   None  MISSING     NaN  MISSING  MISSING  NaN     Unknown  MISSING  None     None      None    None        None          46.0    none     NaN  Error: argument of type 'NoneType' is not iterable  Error: argument of type 'NoneType' is not iterable  Error    Error
4                                      TRkw_In_Da_Getto_ARkw_Skrillex,_J_Balvin_MXkw_Chris_Lorenzo_Remix_KYkw_E_Major_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_Sueños_Globales,_LLC_RYkw_2021_12_15_PYkw_2023_03_29                                      /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_In_Da_Getto_ARkw_Skrillex,_J_Balvin_MXkw_Chris_Lorenzo_Remix_KYkw_E_Major_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_Sueños_Globales,_LLC_RYkw_2021_12_15_PYkw_2023_03_29.aiff     .aiff      257.28     4.288  44100     None        16        2  45384246        43.28 MB   11346048  None   -7.525          LuF  MISSING   None   None  MISSING     NaN  MISSING  MISSING  NaN     Unknown  MISSING  None     None      None    None        None          46.0    none     NaN  Error: argument of type 'NoneType' is not iterable  Error: argument of type 'NoneType' is not iterable  Error    Error

In [ ]:
# notes

# FILL UP FIELDS

In [44]:
# -----######-----###### MAIN FUNCTION -----######-----######

import re
import pandas as pd

def _extract_attrs_1212_DFkw_APPEND_df_results(df, file_col='file_name', missing_keywords=["MISSING", None]):
    """
    Extract attributes from file names in a DataFrame, and fill missing data in specified columns.

    Args:
        df: DataFrame to process.
        file_col: Column containing file names to extract attributes from.
        missing_keywords: List of values considered as missing (default: ["MISSING", None]).

    Returns:
        Updated DataFrame with extracted attributes appended and missing data filled.
    """
    # Define columns to extract
    cols_1 = ['title', 'artist', 'rework', 'album', 'genre', 'LABEL',
              'rel_date', 'year', 'rel_year', 'rel_month', 'rel_day', 'BPM', 'KEY']
    
    # Define regex patterns matching the provided file name structure
    kw_patterns = {
        'title': r'TRkw_(.*?)_ARkw',
        'artist': r'ARkw_(.*?)_MXkw',
        'rework': r'MXkw_(.*?)_KYkw',
        'KEY': r'KYkw_(.*?)_BPkw',
        'BPM': r'BPkw_(\d+)_GNkw',
        'genre': r'GNkw_(.*?)_RMkw',
        'rework': r'RMkw_(.*?)_LBkw',
        'LABEL': r'LBkw_(.*?)_RYkw',
        'album': r'LBkw_(.*?)_RYkw',  # Differentiated from label
        'rel_date': r'RYkw_(\d{4}_\d{2}_\d{2})_PYkw',
        'year': r'RYkw_(\d{4})_\d{2}_\d{2}',
        'rel_year': r'RYkw_(\d{4})_\d{2}_\d{2}',
        'rel_month': r'RYkw_\d{4}_(\d{2})_\d{2}',
        'rel_day': r'RYkw_\d{4}_\d{2}_(\d{2})',
    }
    
    # Process each row to extract attributes
    for index, row in df.iterrows():
        file_name = row[file_col]
        for col in cols_1:
            # Skip if the current value is not missing
            if row[col] not in missing_keywords:
                continue
            
            # Extract attribute using regex pattern
            pattern = kw_patterns.get(col)
            if pattern:
                match = re.search(pattern, file_name)
                if match:
                    # Assign the extracted value to the column
                    df.at[index, col] = match.group(1)
    
    return df

In [46]:
df_results = _extract_attrs_1212_DFkw_APPEND_df_results(df, file_col='temp_id')
df_results

                                                                                                                                                                                                                                                 temp_id                                                                                                                                                                                                                                                                                                                                       Path Extension  dur_seconds    dur_min     sr bit_rate bit_depth channels  file_size file_size_human num_frames error  ms_lufs ms_LUFS_code                                                                                                     title                                                               artist                                                                                       rework  \
0                                                                       TRkw_Back_Seat_ARkw_Anna_Lunoe,_Genesis_Owusu_MXkw_Chris_Lorenzo_Remix_KYkw_G_Minor_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_NLV_Records_RYkw_2022_01_13_PYkw_2023_03_29                                                                                 /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Back_Seat_ARkw_Anna_Lunoe,_Genesis_Owusu_MXkw_Chris_Lorenzo_Remix_KYkw_G_Minor_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_NLV_Records_RYkw_2022_01_13_PYkw_2023_03_29.aiff     .aiff   286.875011    4.78125  44100     None        16        2   50604806        48.26 MB   12651188  None   -7.168          LuF                                                                                                 Back_Seat                                                                 None                                                                                         None
1                              TRkw_Could_Heaven_Ever_Be_Like_This_ARkw_Idris_Muhammad_MXkw_Walker_&_Royce_and_Chris_Lorenzo_Extended_Mix_KYkw_D_Minor_BPkw_127_GNkw_House_RMkw_Walker_&_Royce,_Chris_Lorenzo_LBkw_Ultra_RYkw_2022_08_12_PYkw_2023_03_29                                        /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Could_Heaven_Ever_Be_Like_This_ARkw_Idris_Muhammad_MXkw_Walker_&_Royce_and_Chris_Lorenzo_Extended_Mix_KYkw_D_Minor_BPkw_127_GNkw_House_RMkw_Walker_&_Royce,_Chris_Lorenzo_LBkw_Ultra_RYkw_2022_08_12_PYkw_2023_03_29.aiff     .aiff   363.779546   6.062992  44100     None        16        2   64170766        61.20 MB   16042678  None   -7.305          LuF                                                                            Could_Heaven_Ever_Be_Like_This                                                                 None                                                                                         None
2                                                                               TRkw_Disco_Maghreb_ARkw_DJ_Snake_MXkw_Original_Mix_KYkw_Ab_Major_BPkw_100_GNkw_Dance___Pop_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_05_31_PYkw_2023_03_29                                                                                         /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Disco_Maghreb_ARkw_DJ_Snake_MXkw_Original_Mix_KYkw_Ab_Major_BPkw_100_GNkw_Dance___Pop_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_05_31_PYkw_2023_03_29.aiff     .aiff   184.799977       3.08  44100     None        16        2   32598770        31.09 MB    8149679  None   -7.362          LuF                                                                                             Disco_Maghreb                                                                 None                                                                                         None
3                                                                                                                  TRkw_Esa_Nena_ARkw_Chuwe_MXkw_Original_Mix_KYkw_B_Minor_BPkw_125_GNkw_Tech_House_RMkw__LBkw_DistroKid_RYkw_2022_03_18_PYkw_2023_03_29                                                                                                                            /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_Esa_Nena_ARkw_Chuwe_MXkw_Original_Mix_KYkw_B_Minor_BPkw_125_GNkw_Tech_House_RMkw__LBkw_DistroKid_RYkw_2022_03_18_PYkw_2023_03_29.aiff     .aiff        254.0   4.233333  44100     None        16        2   44805654        42.73 MB   11201400  None   -6.471          LuF                                                                                                  Esa_Nena                                                                 None                                                                                         None
4                                                                  TRkw_In_Da_Getto_ARkw_Skrillex,_J_Balvin_MXkw_Chris_Lorenzo_Remix_KYkw_E_Major_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_Sueños_Globales,_LLC_RYkw_2021_12_15_PYkw_2023_03_29                                                                            /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_In_Da_Getto_ARkw_Skrillex,_J_Balvin_MXkw_Chris_Lorenzo_Remix_KYkw_E_Major_BPkw_128_GNkw_Bass_House_RMkw_Chris_Lorenzo_LBkw_Sueños_Globales,_LLC_RYkw_2021_12_15_PYkw_2023_03_29.aiff     .aiff       257.28      4.288  44100     None        16        2   45384246        43.28 MB   11346048  None   -7.525          LuF                                                                                               In_Da_Getto                                                                 None                                                                                         None
5                                                                     TRkw_MAMI_(feat._COBRAH)_ARkw_Chris_Lorenzo_MXkw_AC_Slater_Extended_Remix_KYkw_Eb_Minor_BPkw_128_GNkw_Bass_House_RMkw_AC_Slater_LBkw_Late_Checkout_RYkw_2022_10_14_PYkw_2023_03_29                                                                               /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_MAMI_(feat._COBRAH)_ARkw_Chris_Lorenzo_MXkw_AC_Slater_Extended_Remix_KYkw_Eb_Minor_BPkw_128_GNkw_Bass_House_RMkw_AC_Slater_LBkw_Late_Checkout_RYkw_2022_10_14_PYkw_2023_03_29.aiff     .aiff   286.901746   4.781696  44100     None        16        2   50609522        48.27 MB   12652367  None   -9.061          LuF                                                                                       MAMI_(feat._COBRAH)                                                                 None                                                                                         None
6                                                                                                 TRkw_MAMI_ARkw_Chris_Lorenzo,_COBRAH_MXkw_Extended_Mix_KYkw_Bb_Major_BPkw_126_GNkw_Bass_House_RMkw__LBkw_Late_Checkout_RYkw_2022_07_22_PYkw_2023_03_29                                                                                                           /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_MAMI_ARkw_Chris_Lorenzo,_COBRAH_MXkw_Extended_Mix_KYkw_Bb_Major_BPkw_126_GNkw_Bass_House_RMkw__LBkw_Late_Checkout_RYkw_2022_07_22_PYkw_2023_03_29.aiff     .aiff   289.787347   4.829789  44100     None        16        2   51118542        48.75 MB   12779622  None   -8.224          LuF                                                                                                      MAMI                                                                 None                                                                                         None
7                                                                                             TRkw_TURMA_ARkw_Twogangs_MXkw_Original_Mix_KYkw_A#_Minor_BPkw_128_GNkw_Bass___Club_RMkw__LBkw_Good_Times_Bad_Times_Records_RYkw_2020_05_22_PYkw_2023_03_29                                                                                                       /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_02_AN_LA_VENTANA/TRkw_TURMA_ARkw_Twogangs_MXkw_Original_Mix_KYkw_A#_Minor_BPkw_128_GNkw_Bass___Club_RMkw__LBkw_Good_Times_Bad_Times_Records_RYkw_2020_05_22_PYkw_2023_03_29.aiff     .aiff        180.0        3.0  44100     None        16        2   31752054        30.28 MB    7938000  None   -6.901          LuF                                                                                                     TURMA                                                                 None                                                                                         None
8                                                                               TRkw_All_Comes_ARkw_GRY,_Christian_Löffler_MXkw_Original_Mix_KYkw_Eb_Minor_BPkw_120_GNkw_Deep_House_RMkw_Mind_Against_LBkw_Young_Alaska_RYkw_2014_08_29_PYkw_2023_04_15                                                                                             /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_All_Comes_ARkw_GRY,_Christian_Löffler_MXkw_Original_Mix_KYkw_Eb_Minor_BPkw_120_GNkw_Deep_House_RMkw_Mind_Against_LBkw_Young_Alaska_RYkw_2014_08_29_PYkw_2023_04_15.aiff     .aiff   489.993288   8.166555  44100     None        16        2   86434870        82.43 MB   21608704  None  -11.430          Lue                                                                                                 All_Comes                                                                 None                                                                                         None
9                                                                                    TRkw_Camino_en_Llamas_ARkw_Lagartijeando_MXkw_Uji_Remix_KYkw_A_Minor_BPkw_135_GNkw_Electronica_RMkw_Uji_LBkw_Wonderwheel_Recordings_RYkw_2022_09_16_PYkw_2023_04_15                                                                                                  /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Camino_en_Llamas_ARkw_Lagartijeando_MXkw_Uji_Remix_KYkw_A_Minor_BPkw_135_GNkw_Electronica_RMkw_Uji_LBkw_Wonderwheel_Recordings_RYkw_2022_09_16_PYkw_2023_04_15.aiff     .aiff        256.0   4.266667  44100     None        16        2   45158454        43.07 MB   11289600  None  -12.167          LuD                                                                                          Camino_en_Llamas                                                                 None                                                                                         None
10                                                                                                     TRkw_Caparica_ARkw_Populous_MXkw_Original_Mix_KYkw_Bb_Major_BPkw_108_GNkw_House_RMkw__LBkw_Wonderwheel_Recordings_RYkw_2022_09_16_PYkw_2023_04_15                                                                                                                    /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Caparica_ARkw_Populous_MXkw_Original_Mix_KYkw_Bb_Major_BPkw_108_GNkw_House_RMkw__LBkw_Wonderwheel_Recordings_RYkw_2022_09_16_PYkw_2023_04_15.aiff     .aiff   216.820045   3.613667  44100     None        16        2   38247110        36.48 MB    9561764  None  -10.683          Lue                                                                                                  Caparica                                                                 None                                                                                         None
11                                                                                                          TRkw_Cause_Away_ARkw_Loquace_MXkw_Original_Mix_KYkw_F_Minor_BPkw_92_GNkw_Tech_House_RMkw__LBkw_Kiara_Records_RYkw_2013_05_20_PYkw_2023_04_15                                                                                                                         /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Cause_Away_ARkw_Loquace_MXkw_Original_Mix_KYkw_F_Minor_BPkw_92_GNkw_Tech_House_RMkw__LBkw_Kiara_Records_RYkw_2013_05_20_PYkw_2023_04_15.aiff     .aiff   437.319501   7.288658  44100     None        16        2   77143214        73.57 MB   19285790  None   -9.858          LuF                                                                                                Cause_Away                                                                 None                                                                                         None
12                                                                        TRkw_Cuando_Canto_Grito_ARkw_Cerrero,_Lucia_Pulido,_Diego_Gómez_MXkw_Original_Mix_KYkw_A#_Minor_BPkw_86_GNkw_Electronica_RMkw__LBkw_BBE_Music_RYkw_2019_06_07_PYkw_2023_04_15                                                                                       /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Cuando_Canto_Grito_ARkw_Cerrero,_Lucia_Pulido,_Diego_Gómez_MXkw_Original_Mix_KYkw_A#_Minor_BPkw_86_GNkw_Electronica_RMkw__LBkw_BBE_Music_RYkw_2019_06_07_PYkw_2023_04_15.aiff     .aiff       341.08   5.684667  44100     None        16        2   60166566        57.38 MB   15041628  None   -9.585          LuF                                                                                        Cuando_Canto_Grito                                                                 None                                                                                         None
13                                                                                                        TRkw_El_Colapso_Suena_ARkw_Uji_MXkw_Original_Mix_KYkw_A_Minor_BPkw_108_GNkw_Electronica_RMkw__LBkw_ZZK_Records_RYkw_2018_06_08_PYkw_2023_04_15                                                                                                                       /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_El_Colapso_Suena_ARkw_Uji_MXkw_Original_Mix_KYkw_A_Minor_BPkw_108_GNkw_Electronica_RMkw__LBkw_ZZK_Records_RYkw_2018_06_08_PYkw_2023_04_15.aiff     .aiff        240.0        4.0  44100     None        16        2   42336054        40.37 MB   10584000  None   -8.923          LuF                                                                                          El_Colapso_Suena                                                                 None                                                                                         None
14                                                          TRkw_Guddi_Riddim_ARkw_DJ_Snake,_Wade,_Nooran_Sisters_MXkw_Extended_Mix_KYkw_Ab_Minor_BPkw_128_GNkw_Tech_House_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_12_20_PYkw_2023_04_15                                                                         /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Guddi_Riddim_ARkw_DJ_Snake,_Wade,_Nooran_Sisters_MXkw_Extended_Mix_KYkw_Ab_Minor_BPkw_128_GNkw_Tech_House_RMkw__LBkw_DJ_Snake_Music_Productions_Limited_RYkw_2022_12_20_PYkw_2023_04_15.aiff     .aiff       258.75     4.3125  44100     None        16        2   45643554        43.53 MB   11410875  None   -6.674          LuF                                                                                              Guddi_Riddim                                                                 None                                                                                         None
15                                      TRkw_Haunted_House_ARkw_Raz_Ohara,_Acid_Pauli,_Nu,_FEATHERED_SUN,_Jo.Ke,_Chris_Schwarzwalder_MXkw_Original_Mix_KYkw_A_Minor_BPkw_78_GNkw_Electronica_RMkw__LBkw_Denature_Records_RYkw_2017_04_28_PYkw_2023_04_15                                                     /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Haunted_House_ARkw_Raz_Ohara,_Acid_Pauli,_Nu,_FEATHERED_SUN,_Jo.Ke,_Chris_Schwarzwalder_MXkw_Original_Mix_KYkw_A_Minor_BPkw_78_GNkw_Electronica_RMkw__LBkw_Denature_Records_RYkw_2017_04_28_PYkw_2023_04_15.aiff     .aiff   363.076939   6.051282  44100     None        16        2   64046826        61.08 MB   16011693  None  -12.469          LuD                                                                                             Haunted_House                                                                 None                                                                                         None
16                                                                                                        TRkw_Kaboo_ARkw_DJ_Diass_MXkw_Original_Mix_KYkw_Bb_Minor_BPkw_123_GNkw_Tech_House_RMkw__LBkw_NastyFunk_Records_RYkw_2017_03_06_PYkw_2023_04_15                                                                                                                       /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Kaboo_ARkw_DJ_Diass_MXkw_Original_Mix_KYkw_Bb_Minor_BPkw_123_GNkw_Tech_House_RMkw__LBkw_NastyFunk_Records_RYkw_2017_03_06_PYkw_2023_04_15.aiff     .aiff   333.737256   5.562288  44100     None        16        2   58871306        56.14 MB   14717813  None   -9.682          LuF                                                                                                     Kaboo                                                                 None                                                                                         None
17                                                                                                   TRkw_Kids_of_Hula_ARkw_Rodriguez_Jr._MXkw_Original_Mix_KYkw_G_Minor_BPkw_127_GNkw_Tech_House_RMkw__LBkw_Leena_Music_RYkw_2009_07_13_PYkw_2023_04_15                                                                                                                  /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_Kids_of_Hula_ARkw_Rodriguez_Jr._MXkw_Original_Mix_KYkw_G_Minor_BPkw_127_GNkw_Tech_House_RMkw__LBkw_Leena_Music_RYkw_2009_07_13_PYkw_2023_04_15.aiff     .aiff   459.413333   7.656889  44100     None        16        2   81040566        77.29 MB   20260128  None   -9.153          LuF                                                                                              Kids_of_Hula                                                                 None                                                                                         None
18                                                                                        TRkw_La_Luna_Perdida_ARkw_Joseph_Paul_DeFaria,_J.Pool_MXkw_Original_Mix_KYkw_D_Minor_BPkw_109_GNkw_Electronica_RMkw__LBkw_Numa_RYkw_2018_11_23_PYkw_2023_04_15                                                                                                       /Volumes/HD_back_UP/try/2025_goodone/_2023_this/_23_03_Love_Lang/TRkw_La_Luna_Perdida_ARkw_Joseph_Paul_DeFaria,_J.Pool_MXkw_Original_Mix_KYkw_D_Minor_BPkw_109_GNkw_Electronica_RMkw__LBkw_Numa_RYkw_2018_11_23_PYkw_2023_04_15.aiff     .aiff   321.467891   5.357798  44100     None        16        2   56706990        54.08 MB   14176734  None  -12.357          LuD                                                                                           La_Luna_Perdida                                                                 None                                                                                         None

# make sure you have all AIFF correct format and RENAMED at this step

In [6]:
import pandas as pd

# Adjust settings to display all rows and columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)  # Set a wide display width to fit the content
pd.set_option('display.max_colwidth', None)  # Show full column content without truncation

df.head(20)

,temp_id,Path,Extension,dur_seconds,dur_min,sr,bit_rate,bit_depth,channels,file_size,file_size_human,num_frames,error,ms_lufs,ms_LUFS_code,title,artist,rework,album,track_#,genre,LABEL,isrc,rel_country,rel_date,year,rel_year,rel_month,rel_day,rel_weekday,audio_offset,decoder,comment,BPM,KEY,KEYC,KEY_code
0,TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_Db_Major_BPkw_124_GNkw_Minimal___Deep_Tech_RMkw__LBkw_DIRTYBIRD_RYkw_2008_05_14_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KYkw_Db_Major_BPkw_124_GNkw_Minimal___Deep_Tech_RMkw__LBkw_DIRTYBIRD_RYkw_2008_05_14_PYkw_2023_09_05.aiff,.aiff,412.810884,6.880181,44100,None,16,2,72851124,69.48 MB,18204960,None,-12.494,LuD,Revox (Original Mix),Tim Green,Ori_Mix,Revox,1,Minimal / Deep Tech,DIRTYBIRD,US75Z0800013,United States,2008-05-14,2008,2008,May,14,Wed,46.0,none,engID3v1 Comment Purchased at Beatport,124,Dbmaj,Unknown,Unknown
1,TRkw_Baby_Wants_To_Ride_ARkw_Jamie_Principle_MXkw_James_Curd_Remix_KYkw_D_Minor_BPkw_126_GNkw_House_RMkw_James_Curd_LBkw_S&S_Records_RYkw_2022_02_25_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Baby_Wants_To_Ride_ARkw_Jamie_Principle_MXkw_James_Curd_Remix_KYkw_D_Minor_BPkw_126_GNkw_House_RMkw_James_Curd_LBkw_S&S_Records_RYkw_2022_02_25_PYkw_2023_09_05.aiff,.aiff,433.333333,7.222222,44100,None,16,2,77032764,73.46 MB,19110000,None,-10.212,Lue,Baby Wants To Ride (James Curd Remix),Jamie Principle,James Curd Remix,S&S Curations Mix Compilation 004 (DJ Slab),7,House,S&S Records,USHWH1900202,United States,2022-02-25,2022,2022,Feb,25,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,126,Dmin,7A,07A
2,TRkw_Lengua_Ri_Suto_ARkw_Ghetto_Kumbe_MXkw_Cero39_Remix_KYkw_C_Minor_BPkw_80_GNkw_Electronica_RMkw_Cero39_LBkw_ZZK_Records_RYkw_2022_11_09_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Lengua_Ri_Suto_ARkw_Ghetto_Kumbe_MXkw_Cero39_Remix_KYkw_C_Minor_BPkw_80_GNkw_Electronica_RMkw_Cero39_LBkw_ZZK_Records_RYkw_2022_11_09_PYkw_2023_09_05.aiff,.aiff,230.692971,3.844883,44100,None,16,2,43705650,41.68 MB,10173560,None,-7.342,LuF,Lengua Ri Suto (Cero39 Remix),Ghetto Kumbe,Cero39 Remix,Ghetto Kumbé Clubbing Remixes,10,Electronica,ZZK Records,QZR422104725,global,2022-11-09,2022,2022,Nov,9,Wed,46.0,none,engID3v1 Comment Purchased at Beatport,80,Cmin,5A,05A
3,TRkw_Can_You_Feel_It_ARkw_Chez_Damier_MXkw_MK_New_York_Dub_Extended_KYkw_Eb_Minor_BPkw_124_GNkw_House_RMkw_MK_LBkw_KMS_Records_(BEAT_Music_Fund)_RYkw_1992_01_01_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Can_You_Feel_It_ARkw_Chez_Damier_MXkw_MK_New_York_Dub_Extended_KYkw_Eb_Minor_BPkw_124_GNkw_House_RMkw_MK_LBkw_KMS_Records_(BEAT_Music_Fund)_RYkw_1992_01_01_PYkw_2023_09_05.aiff,.aiff,328.919773,5.481996,44100,None,16,2,59754958,56.99 MB,14505362,None,-10.596,Lue,Can You Feel It (MK New York Dub Extended),Chez Damier,MK New York Dub Extended,Can You Feel It,1,House,KMS Records (BEAT Music Fund),GBCPZ1105573,United Kingdom,1992-01-01,1992,1992,Jan,1,Wed,46.0,none,engID3v1 Comment Purchased at Beatport,124,Ebmin,Unknown,Unknown
4,TRkw_Recovery_ARkw_Rival_Consoles_MXkw_Original_Mix_KYkw_F#_Minor_BPkw_155_GNkw_Electronica_RMkw__LBkw_Erased_Tapes_RYkw_2019_02_28_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Recovery_ARkw_Rival_Consoles_MXkw_Original_Mix_KYkw_F#_Minor_BPkw_155_GNkw_Electronica_RMkw__LBkw_Erased_Tapes_RYkw_2019_02_28_PYkw_2023_09_05.aiff,.aiff,290.201587,4.836693,44100,None,16,2,51270722,48.90 MB,12797890,None,-11.857,Lue,Recovery (Original Mix),Rival Consoles,Ori_Mix,Sonne,6,Electronica,Erased Tapes,GBWZD1405906,United Kingdom,2019-02-28,2019,2019,Feb,28,Thu,46.0,none,engID3v1 Comment Purchased at Beatport,155,F#min,11A,11A
5,TRkw_Final_Credits_ARkw_Midland_MXkw_Original_Mix_KYkw_F_Minor_BPkw_133_GNkw_House_RMkw__LBkw_Classic_Music_Company_RYkw_2017_02_10_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Final_Credits_ARkw_Midland_MXkw_Original_Mix_KYkw_F_Minor_BPkw_133_GNkw_House_RMkw__LBkw_Classic_Music_Company_RYkw_2017_02_10_PYkw_2023_09_05.aiff,.aiff,439.994082,7.333235,44100,None,16,2,77695690,74.10 MB,19403739,None,-9.840,LuF,Final Credits (Original Mix),Midland,Ori_Mix,Final Credits,1,House,Classic Music Company,GBCPZ1610502,United Kingdom,2017-02-10,2017,2017,Feb,10,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,133,Fmin,4A,04A
6,TRkw_Purple_Drank_ARkw_Axel_Boman_MXkw_Original_Mix_KYkw_B_Minor_BPkw_119_GNkw_Tech_House_RMkw__LBkw_Pampa_Records_RYkw_2010_08_30_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Purple_Drank_ARkw_Axel_Boman_MXkw_Original_Mix_KYkw_B_Minor_BPkw_119_GNkw_Tech_House_RMkw__LBkw_Pampa_Records_RYkw_2010_08_30_PYkw_2023_09_05.aiff,.aiff,438.060431,7.301007,44100,None,16,2,77314128,73.73 MB,19318465,None,-10.227,Lue,Purple Drank (Original Mix),Axel Boman,Ori_Mix,Holy Love,2,Tech House,Pampa Records,DEMM11000008,Germany,2010-08-30,2010,2010,Aug,30,Mon,46.0,none,engID3v1 Comment Purchased at Beatport,119,Bmin,10A,10A
7,TRkw_Let_s_Dream_ARkw_Paco_Osuna_MXkw_Original_Mix_KYkw_A_Major_BPkw_123_GNkw_Tech_House_RMkw__LBkw_Minus_RYkw_2014_10_20_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Let_s_Dream_ARkw_Paco_Osuna_MXkw_Original_Mix_KYkw_A_Major_BPkw_123_GNkw_Tech_House_RMkw__LBkw_Minus_RYkw_2014_10_20_PYkw_2023_09_05.aiff,.aiff,472.195147,7.869919,44100,None,16,2,83335898,79.48 MB,20823806,None,-8.718,LuF,Let's Dream (Original Mix),Paco Osuna,Ori_Mix,Long Play,1,Tech House,Minus,CAM261450551,Canada,2014-10-20,2014,2014,Oct,20,Mon,46.0,none,engID3v1 Comment Purchased at Beatport,123,Amaj,11B,11B
8,TRkw_Feeling_For_You_(Les_Rythmes_Digitales_Dreamix___Short_Remix)_ARkw_Cassius_MXkw_Original_Mix_KYkw_F_Minor_BPkw_128_GNkw_Electronica_RMkw_Les_Rythmes_Digitales_LBkw_Because_Music_RYkw_2016_03_25_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Feeling_For_You_(Les_Rythmes_Digitales_Dreamix___Short_Remix)_ARkw_Cassius_MXkw_Original_Mix_KYkw_F_Minor_BPkw_128_GNkw_Electronica_RMkw_Les_Rythmes_Digitales_LBkw_Because_Music_RYkw_2016_03_25_PYkw_2023_09_05.aiff,.aiff,315.6,5.26,44100,None,16,2,55729204,53.15 MB,13917960,None,-9.891,LuF,Feeling For You (Reveries Digitales Dreamix / Short Remix),Cassius,Reveries Digitales Dreamix / Short Remix,1999 (Deluxe Edition),20,Electronica,Because Music,FR01Q9800034,France,2016-03-25,2016,2016,Mar,25,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,128,Fmin,4A,04A
9,"TRkw_Discow_ARkw_Mr_Oizo,_Handbraekes,_Boysnoize_MXkw_Original_Mix_KYkw_Bb_Minor_BPkw_124_GNkw_Electronica_RMkw__LBkw_Ed_Banger_Records___Because_Music_RYkw_2018_10_26_PYkw_2023_09_05","/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Discow_ARkw_Mr_Oizo,_Handbraekes,_Boysnoize_MXkw_Original_Mix_KYkw_Bb_Minor_BPkw_124_GNkw_Electronica_RMkw__LBkw_Ed_Banger_Records___Because_Music_RYkw_2018_10_26_PYkw_2023_09_05.aiff",.aiff,159.28,2.654667,44100,None,16,2,28135338,26.83 MB,7024248,None,-9.475,LuF,Discow (Original Mix),Handbraekes,Ori_Mix,#3,1,Electronica,Ed Banger Records / Because Music,FR0NT1801253,France,2018-10-26,2018-10-26,2018,Oct,26,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,124,Bbmin,Unknown,Unknown
10,TRkw_Night_Clubbing_ARkw_Johnny_D._MXkw_Marko_Nastic_Remix_KYkw_Eb_Minor_BPkw_126_GNkw_Deep_House_RMkw_Marko_Nastic_LBkw_AMA_Recordings_RYkw_2015_07_15_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Night_Clubbing_ARkw_Johnny_D._MXkw_Marko_Nastic_Remix_KYkw_Eb_Minor_BPkw_126_GNkw_Deep_House_RMkw_Marko_Nastic_LBkw_AMA_Recordings_RYkw_2015_07_15_PYkw_2023_09_05.aiff,.aiff,503.093719,8.384895,44100,None,16,2,88820170,84.71 MB,22186433,None,-8.688,LuF,Night Clubbing (Marko Nastic Remix),Johnny D.,Marko Nastic Remix,Night Clubbing EP,2,Deep House,AMA Recordings,DEKB71438881,Germany,2015-07-15,2015,2015,Jul,15,Wed,46.0,none,engID3v1 Comment Purchased at Beatport,126,Ebmin,Unknown,Unknown
11,TRkw_Momma_s_Groove_ARkw_Osunlade_MXkw_Jimpster_s_Hip_Replacement_Mix_KYkw_A_Minor_BPkw_123_GNkw_House_RMkw_Jimpster_LBkw_Strictly_Rhythm_RYkw_2017_07_05_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Momma_s_Groove_ARkw_Osunlade_MXkw_Jimpster_s_Hip_Replacement_Mix_KYkw_A_Minor_BPkw_123_GNkw_House_RMkw_Jimpster_LBkw_Strictly_Rhythm_RYkw_2017_07_05_PYkw_2023_09_05.aiff,.aiff,453.973333,7.566222,44100,None,16,2,80178422,76.46 MB,20020224,None,-7.639,LuF,Momma's Groove (Jimpster's Hip Replacement Mix),Osunlade,Jimpster's Hip Replacement Mix,Momma's Groove,2,House,Strictly Rhythm,GBDVG0865302,United Kingdom,2008-08-25,2008,2008,Aug,25,Mon,46.0,none,engID3v1 Comment Purchased at Beatport,123,Amin,8A,08A
12,TRkw_Bring_the_Funk_Back_ARkw_Nigel_Hey_MXkw_Original_Mix_KYkw_D_Minor_BPkw_130_GNkw_Tech_House_RMkw__LBkw_TRÈS_BIEN_RYkw_2023_07_29_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Bring_the_Funk_Back_ARkw_Nigel_Hey_MXkw_Original_Mix_KYkw_D_Minor_BPkw_130_GNkw_Tech_House_RMkw__LBkw_TRÈS_BIEN_RYkw_2023_07_29_PYkw_2023_09_05.aiff,.aiff,387.692313,6.461539,44100,None,16,2,69117222,65.92 MB,17097231,None,-9.330,LuF,Bring the Funk Back (Original Mix),Nigel Hey,Ori_Mix,Bring the Funk Back,1,Tech House,TRÈS BIEN,GBLFP2381701,United Kingdom,2023-07-29,2023,2023,Jul,29,Sat,46.0,none,engID3v1 Comment Purchased at Beatport,130,Dmin,7A,07A
13,TRkw_By_Your_Side_ARkw_Sofia_Kourtesis_MXkw_Original_Mix_KYkw_F_Minor_BPkw_122_GNkw_Electronica_RMkw__LBkw_Technicolour_RYkw_2021_03_19_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_By_Your_Side_ARkw_Sofia_Kourtesis_MXkw_Original_Mix_KYkw_F_Minor_BPkw_122_GNkw_Electronica_RMkw__LBkw_Technicolour_RYkw_2021_03_19_PYkw_2023_09_05.aiff,.aiff,367.362902,6.122715,44100,None,16,2,65880384,62.83 MB,16200704,None,-9.697,LuF,By Your Side (Original Mix),Sofia Kourtesis,Ori_Mix,Fresia Magdalena,2,Electronica,Technicolour,GBCFB2000760,United Kingdom,2021-03-19,2021,2021,Mar,19,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,122,Fmin,4A,04A
14,TRkw_Han_Jan_ARkw_Peggy_Gou_MXkw_Edit_KYkw_Bb_Minor_BPkw_123_GNkw_Electronica_RMkw__LBkw_Ninja_Tune_RYkw_2018_02_27_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Han_Jan_ARkw_Peggy_Gou_MXkw_Edit_KYkw_Bb_Minor_BPkw_123_GNkw_Electronica_RMkw__LBkw_Ninja_Tune_RYkw_2018_02_27_PYkw_2023_09_05.aiff,.aiff,242.982585,4.04971,44100,None,16,2,43094454,41.10 MB,10715532,None,-11.762,Lue,Han Jan (Edit),Peggy Gou,Edit,Han Jan,1,Electronica,Ninja Tune,GBCFB1800075,United Kingdom,2018-02-27,2018,2018,Feb,27,Tue,46.0,none,engID3v1 Comment Purchased at Beatport,123,Bbmin,Unknown,Unknown
15,TRkw_Ninos_ARkw_Lexa_Hill_MXkw_Lexah_Remix_2022_KYkw_Gb_Minor_BPkw_124_GNkw_Afro_House_RMkw_LEXAH_LBkw_UNION_RECORDS_(IT)_RYkw_2022_07_01_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Ninos_ARkw_Lexa_Hill_MXkw_Lexah_Remix_2022_KYkw_Gb_Minor_BPkw_124_GNkw_Afro_House_RMkw_LEXAH_LBkw_UNION_RECORDS_(IT)_RYkw_2022_07_01_PYkw_2023_09_05.aiff,.aiff,343.42746,5.723791,44100,None,16,2,61113474,58.28 MB,15145151,None,-8.640,LuF,Ninos (Lexah Remix 2022),Lexa Hill,Lexah Remix 2022,Ninos (Lexah Remix 2022),1,Afro House,UNION RECORDS (IT),ITLCJ2100207,Italy,2022-07-01,2022,2022,Jul,1,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,124,Gbmin,Unknown,Unknown
16,TRkw_Disco_Ballz_ARkw_Mat.Joe_MXkw_Original_Mix_KYkw_C_Major_BPkw_125_GNkw_House_RMkw__LBkw_Mother_Recordings_RYkw_2018_10_05_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Disco_Ballz_ARkw_Mat.Joe_MXkw_Original_Mix_KYkw_C_Major_BPkw_125_GNkw_House_RMkw__LBkw_Mother_Recordings_RYkw_2018_10_05_PYkw_2023_09_05.aiff,.aiff,370.950703,6.182512,44100,None,16,2,65927590,62.87 MB,16358926,None,-9.465,LuF,Disco Ballz (Original Mix),Mat.Joe,Ori_Mix,Disco Ballz,1,House,Mother Recordings,FR96X1814297,France,2018-10-05,2018,2018,Oct,5,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,125,Cmaj,8B,08B
17,TRkw_The_Move_ARkw_Marco_Carola_MXkw_Original_Mix_KYkw_D#_Minor_BPkw_124_GNkw_Techno_(Peak_Time___Driving)_RMkw__LBkw_Minus_RYkw_2009_12_09_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_The_Move_ARkw_Marco_Carola_MXkw_Original_Mix_KYkw_D#_Minor_BPkw_124_GNkw_Techno_(Peak_Time___Driving)_RMkw__LBkw_Minus_RYkw_2009_12_09_PYkw_2023_09_05.aiff,.aiff,470.292834,7.838214,44100,None,16,2,82972496,79.13 MB,20739914,None,-11.773,Lue,The Move (Original Mix),Marco Carola,Ori_Mix,Walking Dog,5,Techno (Peak Time / Driving),Minus,CAM260950090,Canada,2009-12-09,2009,2009,Dec,9,Wed,46.0,none,engID3v1 Comment Purchased at Beatport,124,D#min,2A,02A
18,TRkw_Far_Away_Place_ARkw_Xinobi_MXkw_Rampa_Remix_KYkw_D_Major_BPkw_123_GNkw_Melodic_House_&_Techno_RMkw_Rampa_LBkw_Discotexas_RYkw_2018_11_30_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Far_Away_Place_ARkw_Xinobi_MXkw_Rampa_Remix_KYkw_D_Major_BPkw_123_GNkw_Melodic_House_&_Techno_RMkw_Rampa_LBkw_Discotexas_RYkw_2018_11_30_PYkw_2023_09_05.aiff,.aiff,331.980544,5.533009,44100,None,16,2,58608694,55.89 MB,14640342,None,-10.568,Lue,Far Away Place (Rampa Remix),Xinobi,Rampa Remix,Far Away Place (Rampa Remix),1,Melodic House & Techno,Discotexas,PT6DV1800044,Portugal,2018-11-30,2018,2018,Nov,30,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,123,Dmaj,10B,10B
19,TRkw_Both_Of_Us_ARkw_Jayda_G_MXkw_Edit_KYkw_B_Major_BPkw_124_GNkw_Electronica_RMkw__LBkw_Ninja_Tune_RYkw_2020_06_05_PYkw_2023_09_05,/Users/yerik/Downloads/___-_-_-_MUSIC_towards2025/_2023_this/_23_09_AN_ArtPArk/TRkw_Both_Of_Us_ARkw_Jayda_G_MXkw_Edit_KYkw_B_Major_BPkw_124_GNkw_Electronica_RMkw__LBkw_Ninja_Tune_RYkw_2020_06_05_PYkw_2023_09_05.aiff,.aiff,229.424762,3.823746,44100,None,16,2,40527240,38.65 MB,10117632,None,-13.454,LuD,Both Of Us (Edit),Jayda G,Edit,Both Of Us (Jayda G Sunset Bliss Mix),2,Electronica,Ninja Tune,GBCFB2000297,United Kingdom,2020-06-05,2020,2020,Jun,5,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,124,Bmaj,1B,01B

In [15]:
import pandas as pd
from mutagen.aiff import AIFF

def _extract_key_write_to_df_2111_aiff_GET_df(df):
    """
    Extracts the musical key (TKEY) from AIFF files and writes it into a DataFrame.

    Parameters:
        df: A Pandas DataFrame containing a column 'Path' with AIFF file paths.

    Returns:
        Updated DataFrame with a new column 'KEY' containing the extracted keys.
    """
    # Ensure the 'KEY' column exists
    df['KEY'] = None

    for idx, row in df.iterrows():
        file_path = row['Path']
        try:
            # Load the AIFF file
            audio = AIFF(file_path)
            
            # Extract the TKEY tag
            if 'TKEY' in audio.tags:
                key_tag = audio.tags['TKEY']
                key = key_tag.text[0] if hasattr(key_tag, 'text') else str(key_tag)
                df.at[idx, 'KEY'] = key  # Write the key into the DataFrame
            else:
                df.at[idx, 'KEY'] = "No TKEY"  # Handle missing TKEY tag

        except Exception as e:
            df.at[idx, 'KEY'] = f"Error: {e}"  # Handle file errors

    return df

updated_df = _extract_key_write_to_df_2111_aiff_GET_df(df)
#print(updated_df)
updated_df

,temp_id,Path,Extension,dur_seconds,dur_min,sr,bit_rate,bit_depth,channels,file_size,file_size_human,num_frames,error,ms_lufs,ms_LUFS_code,title,artist,rework,album,track_#,genre,LABEL,isrc,rel_country,rel_date,year,rel_year,rel_month,rel_day,rel_weekday,audio_offset,decoder,comment,BPM,KEY,KEYC,KEY_code
0,"Manda_Island_feat._Boddhi_Satva-BY-Boddhi_Satva,_Afefe_Iku_(Original_Mix)_KEY_F_Major_BPM_83_Deep_House__LBL_ITH_(Defected_In_The_House)-RY_2014_02-DWN_2024_11","/Users/yerik/Downloads/try_py_AIFF/Manda_Island_feat._Boddhi_Satva-BY-Boddhi_Satva,_Afefe_Iku_(Original_Mix)_KEY_F_Major_BPM_83_Deep_House__LBL_ITH_(Defected_In_The_House)-RY_2014_02-DWN_2024_11.aiff",.aiff,438.034127,7.300569,44100,None,16,2,77326878,73.74 MB,19317305,None,-8.389,LuF,Manda Island feat. Boddhi Satva (Original Mix),"Boddhi Satva, Afefe Iku",Ori_Mix,"Sunset Sessions - Cable Beach, Australia",13,Deep House,ITH (Defected In The House),ITK140800010,Italy,2014-02-16,2014,2014,Feb,16,Sun,46.0,none,engID3v1 Comment Purchased at Beatport,83,Fmaj,NaN,"0Error reading file: '/Users/yerik/Downloads/try_py_AIFF/Manda_Island_feat._Boddhi_Satva-BY-Boddhi_Satva,_Afefe_Iku_(Original_Mix)_KEY_F_Major_BPM_83_Deep_House__LBL_ITH_(Defected_In_The_House)-RY_2014_02-DWN_2024_11.aiff' doesn't start with an ID3 tag"
2,The_Wall-BY-Discuji_(Prins_Thomas_Remix)_KEY_A_Minor_BPM_106_Deep_House_Prins_Thomas_LBL_Internasjonal-RY_2024_05-DWN_2024_11,/Users/yerik/Downloads/try_py_AIFF/The_Wall-BY-Discuji_(Prins_Thomas_Remix)_KEY_A_Minor_BPM_106_Deep_House_Prins_Thomas_LBL_Internasjonal-RY_2024_05-DWN_2024_11.aiff,.aiff,430.896236,7.181604,44100,None,16,2,76287932,72.75 MB,19002524,None,-13.286,LuD,The Wall (Prins Thomas Remix),Discuji,Prins Thomas Remix,The Wall,1,Deep House,Internasjonal,DECY52400564,Germany,2024-05-03,2024,2024,May,3,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,106,Amin,NaN,0Error reading file: '/Users/yerik/Downloads/try_py_AIFF/The_Wall-BY-Discuji_(Prins_Thomas_Remix)_KEY_A_Minor_BPM_106_Deep_House_Prins_Thomas_LBL_Internasjonal-RY_2024_05-DWN_2024_11.aiff' doesn't start with an ID3 tag
3,Sure_Thing_(Jullian_Gomes_Remix)-BY-St_Germain_(Original_Mix)_KEY_G_Major_BPM_118_Electronica_Jullian_Gomes_LBL_Parlophone_(France)-RY_2021_04-DWN_2024_11,/Users/yerik/Downloads/try_py_AIFF/Sure_Thing_(Jullian_Gomes_Remix)-BY-St_Germain_(Original_Mix)_KEY_G_Major_BPM_118_Electronica_Jullian_Gomes_LBL_Parlophone_(France)-RY_2021_04-DWN_2024_11.aiff,.aiff,428.644082,7.144068,44100,None,16,2,77259608,73.68 MB,18903204,None,-10.770,Lue,Sure Thing (Jullian Gomes Remix) (Original Mix),St Germain,Jullian Gomes Remix,Sure Thing (Jullian Gomes Remix),2,Electronica,Parlophone (France),FR92S2000011,France,2021-04-30,2021,2021,Apr,30,Fri,46.0,none,engID3v1 Comment Purchased at Beatport,118,Gmaj,NaN,0Error reading file: '/Users/yerik/Downloads/try_py_AIFF/Sure_Thing_(Jullian_Gomes_Remix)-BY-St_Germain_(Original_Mix)_KEY_G_Major_BPM_118_Electronica_Jullian_Gomes_LBL_Parlophone_(France)-RY_2021_04-DWN_2024_11.aiff' doesn't start with an ID3 tag

# BPM

In [4]:
import os
import numpy as np
import pandas as pd
import wave
from tqdm import tqdm
from pydub import AudioSegment
import shutil  # To delete the temp folder after all processing
import aubio
import math

# -----######-----###### CORE FUNCTION FOR CONVERSION WITH EXTRA ATTRIBUTES -----######-----######
def _convert_0110_files_to_wav_LOCATE_get_files(df, temp_wav_folder, audio_extensions):
    """
    Converts audio files to WAV if necessary and saves them in the temp_wav_folder.
    Also extracts sample rate (sr_conv), bit depth (bit_depth_conv), and channels (channels_conv) for the converted WAV files.

    :param df: DataFrame containing 'Path' column
    :param temp_wav_folder: The folder to save converted wav files
    :param audio_extensions: List of valid audio extensions (input as a variable outside the function)
    :return: Updated DataFrame with 'Wav_Path', 'sr_conv', 'bit_depth_conv', and 'channels_conv' columns
    """
    
    if not os.path.exists(temp_wav_folder):
        os.makedirs(temp_wav_folder)

    df.loc[:, 'Wav_Path'] = ""
    df.loc[:, 'sr_conv'] = None
    df.loc[:, 'bit_depth_conv'] = None
    df.loc[:, 'channels_conv'] = None

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Converting files"):
        file_path = row['Path']
        ext = os.path.splitext(file_path)[1].lower()

        if os.path.exists(file_path) and ext in audio_extensions:
            wav_file_name = os.path.basename(os.path.splitext(file_path)[0] + '.wav')
            wav_path = os.path.join(temp_wav_folder, wav_file_name)

            try:
                # Convert non-WAV files to WAV using pydub
                if ext != '.wav':
                    audio = AudioSegment.from_file(file_path)
                    audio.export(wav_path, format="wav")
                else:
                    wav_path = file_path

                # Extract attributes from the WAV file (for converted file)
                with wave.open(wav_path, 'r') as wav_file:
                    sr_conv = wav_file.getframerate()
                    bit_depth_conv = wav_file.getsampwidth() * 8  # sample width in bytes, so multiply by 8 for bits
                    channels_conv = wav_file.getnchannels()

                # Store the attributes of the converted file in the DataFrame
                df.loc[index, 'Wav_Path'] = wav_path
                df.loc[index, 'sr_conv'] = sr_conv
                df.loc[index, 'bit_depth_conv'] = bit_depth_conv
                df.loc[index, 'channels_conv'] = channels_conv

            except Exception as e:
                print(f"Error processing {file_path}: {e}")

    return df

# -----######-----###### BPM FUNCTION USING AUBIO -----######-----######
def compute_bpm(filename):
    """
    Computes BPM from an audio file using the aubio library.

    :param filename: Path to the audio file
    :return: BPM value (float)
    """
    try:
        win_s = 512  # fft size
        hop_s = win_s // 2  # hop size
        samplerate = 0
        s = aubio.source(filename, samplerate, hop_s)
        samplerate = s.samplerate
        o = aubio.tempo("default", win_s, hop_s, samplerate)
        beats = []
        while True:
            samples, read = s()
            is_beat = o(samples)
            if is_beat:
                this_beat = o.get_last_s()
                beats.append(this_beat)
            if read < hop_s:
                break
        bpms = 60. / np.diff(beats)
        return np.median(bpms) if len(bpms) > 0 else None
    except Exception as e:
        print(f"Error processing file {filename}: {str(e)}")
        return None

# -----######-----###### MAIN FUNCTION TO RUN CONVERSION AND BPM CALCULATION WITH TQM AND CLEANUP -----######-----######
def process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=1, save_pkl=False, save_path=None):
    """
    Processes audio files in chunks, converts them to WAV if needed, and computes BPM.
    Cleans up the temp folder by deleting processed WAV files after each chunk.
    Optionally saves the DataFrame after processing each chunk to a pickle file.

    :param df: DataFrame containing file paths in 'Path'
    :param temp_wav_folder: Folder to store WAV files
    :param audio_extensions: List of valid audio extensions (input outside the function)
    :param chunk_size: Number of files to process per chunk
    :param save_pkl: Boolean flag to save the DataFrame as a pickle file (default=False)
    :param save_path: Path where the DataFrame is saved after each chunk if save_pkl is True
    :return: Final processed DataFrame
    """
    n = df.shape[0]
    final_df = pd.DataFrame()

    with tqdm(total=n, leave=True, desc="Processing audio files with TQM") as pbar:
        for i in range(0, n, chunk_size):
            df_chunk = df.iloc[i:i + chunk_size].copy()  # Ensuring we are working on a copy to avoid warnings

            # Convert audio files to WAV if needed, and extract sr_conv, bit_depth_conv, channels_conv
            df_chunk = _convert_0110_files_to_wav_LOCATE_get_files(df_chunk, temp_wav_folder, audio_extensions)

            # Compute BPM for each file in the chunk
            df_chunk['ms_bpm'] = [compute_bpm(x) if x.endswith(tuple(audio_extensions)) else None 
                                  for x in tqdm(df_chunk['Wav_Path'], desc="Computing BPM")]

            # Round up the BPM values and convert to integer
            df_chunk['ms_BPM_code'] = df_chunk['ms_bpm'].apply(lambda x: math.ceil(x) if x is not None else None)

            # Add leading zero if BPM is two digits
            df_chunk['ms_BPM_code'] = df_chunk['ms_BPM_code'].apply(lambda x: f"{x:03d}" if pd.notnull(x) else None)

            # Concatenate the results
            final_df = pd.concat([final_df, df_chunk], ignore_index=True)
            
            # Update the main progress bar
            pbar.update(chunk_size)

            # Save after each chunk if save_pkl is True
            if save_pkl and save_path:
                final_df.to_pickle(save_path)
                print(f"Progress saved to {save_path} after chunk {i // chunk_size + 1}")

            # Cleanup: Remove the WAV files created for this chunk
            for file in os.listdir(temp_wav_folder):
                file_path = os.path.join(temp_wav_folder, file)
                if os.path.isfile(file_path) and file.endswith('.wav'):
                    os.remove(file_path)
                    
        # Optionally: Delete the temp folder after all processing
        if os.path.exists(temp_wav_folder):
            shutil.rmtree(temp_wav_folder)

    return final_df

# -----######-----###### EXAMPLE RUN STATEMENTS -----######-----######
# Example DataFrame with paths
audio_extensions = ['.mp3', '.flac', '.aac', '.ogg', '.wma', '.au', '.aif', '.aiff', '.wav']

# Process the files with a temporary WAV folder and save results to pickle if needed
temp_wav_folder = '/Users/yerik/Desktop/temp_wav'
df = process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=10, save_pkl=False)

df

Processing audio files with TQM:   0%|                                       | 0/13 [00:00<?, ?it/s]
Converting files:   0%|                                                      | 0/10 [00:00<?, ?it/s]
Converting files:  10%|████▌                                         | 1/10 [00:01<00:10,  1.15s/it]
Converting files:  20%|█████████▏                                    | 2/10 [00:02<00:07,  1.02it/s]
Converting files:  30%|█████████████▊                                | 3/10 [00:03<00:07,  1.00s/it]
Converting files:  40%|██████████████████▍                           | 4/10 [00:04<00:05,  1.00it/s]
Converting files:  50%|███████████████████████                       | 5/10 [00:05<00:05,  1.07s/it]
Converting files:  60%|███████████████████████████▌                  | 6/10 [00:06<00:04,  1.04s/it]
Converting files:  70%|████████████████████████████████▏             | 7/10 [00:07<00:03,  1.02s/it]
Converting files:  80%|████████████████████████████████████▊         | 8/10 [00:08<00:01,  1.04it/s]
Converting files:  90%|█████████████████████████████████████████▍    | 9/10 [00:08<00:00,  1.04it/s]
Converting files: 100%|█████████████████████████████████████████████| 10/10 [00:10<00:00,  1.00it/s]

Computing BPM:   0%|                                                         | 0/10 [00:00<?, ?it/s]
Computing BPM:  10%|████▉                                            | 1/10 [00:00<00:08,  1.06it/s]
Computing BPM:  20%|█████████▊                                       | 2/10 [00:01<00:06,  1.24it/s]
Computing BPM:  30%|██████████████▋                                  | 3/10 [00:02<00:05,  1.24it/s]
Computing BPM:  40%|███████████████████▌                             | 4/10 [00:03<00:04,  1.22it/s]
Computing BPM:  50%|████████████████████████▌                        | 5/10 [00:04<00:04,  1.13it/s]
Computing BPM:  60%|█████████████████████████████▍                   | 6/10 [00:05<00:03,  1.19it/s]
Computing BPM:  70%|██████████████████████████████████▎              | 7/10 [00:05<00:02,  1.20it/s]
Computing BPM:  80%|███████████████████████████████████████▏         | 8/10 [00:06<00:01,  1.27it/s]
Computing BPM:  90%|████████████████████████████████████████████     | 9/10 [00:07<00:00,  1.27it/s]
Computing BPM: 100%|████████████████████████████████████████████████| 10/10 [00:08<00:00,  1.22it/s]
Processing audio files with TQM:  77%|███████████████████████       | 10/13 [00:18<00:05,  1.83s/it]
Converting files:   0%|                                                       | 0/3 [00:00<?, ?it/s]
Converting files:  33%|███████████████▋                               | 1/3 [00:01<00:02,  1.09s/it]
Converting files:  67%|███████████████████████████████▎               | 2/3 [00:02<00:01,  1.00s/it]
Converting files: 100%|███████████████████████████████████████████████| 3/3 [00:02<00:00,  1.06it/s]

Computing BPM:   0%|                                                          | 0/3 [00:00<?, ?it/s]
Computing BPM:  33%|████████████████▋                                 | 1/3 [00:00<00:01,  1.11it/s]
Computing BPM:  67%|█████████████████████████████████▎                | 2/3 [00:01<00:00,  1.21it/s]
Computing BPM: 100%|██████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.24it/s]
Processing audio files with TQM: 20it [00:23,  1.18s/it]

,temp_id,Path,Extension,dur_seconds,dur_min,sr,bit_rate,bit_depth,channels,file_size,...,BPM,KEY,KEYC,KEY_code,Wav_Path,sr_conv,bit_depth_conv,channels_conv,ms_bpm,ms_BPM_code
0,Dry_Me-BY-Heiko_Laux_(Original_Mix)_KEY_A#_Min...,/Users/yerik/Downloads/try_py_MP3/Dry_Me-BY-He...,.mp3,502.987755,8.383129,44100,320000,None,2,20263819,...,126,2A,Ebm,02A,/Users/yerik/Desktop/temp_wav/Dry_Me-BY-Heiko_...,44100,16,2,127.056999,128
1,Do_It_Again-BY-Franzfontein_(Original_Mix)_KEY...,/Users/yerik/Downloads/try_py_MP3/Do_It_Again-...,.mp3,378.566531,6.309442,44100,320000,None,2,16470811,...,125,9A,Em,09A,/Users/yerik/Desktop/temp_wav/Do_It_Again-BY-F...,44100,16,2,126.038849,127
2,"La_Cocina_Del_Cabron-BY-Lee_Van_Dowski,_Glimps...",/Users/yerik/Downloads/try_py_MP3/La_Cocina_De...,.mp3,431.777959,7.196299,44100,320000,None,2,17582221,...,127,1A,Abm,01A,/Users/yerik/Desktop/temp_wav/La_Cocina_Del_Ca...,44100,16,2,127.862648,128
3,"Tribal_Sessions_II-BY-Yotam_Avni,_Eloy_Gonzale...",/Users/yerik/Downloads/try_py_MP3/Tribal_Sessi...,.mp3,449.306122,7.488435,44100,320000,None,2,19146720,...,125,4A,Fm,04A,/Users/yerik/Desktop/temp_wav/Tribal_Sessions_...,44100,16,2,125.966171,126
4,"Midnight_Jazz_Journey-BY-Ron_Trent,_Coflo,_Rob...",/Users/yerik/Downloads/try_py_MP3/Midnight_Jaz...,.mp3,539.559184,8.992653,44100,320000,None,2,22641313,...,125,5A,Cm,05A,/Users/yerik/Desktop/temp_wav/Midnight_Jazz_Jo...,44100,16,2,125.938939,126
5,"Don't_Turn_it_Off-BY-40_Thieves,_Qzen,_O-SHiN_...",/Users/yerik/Downloads/try_py_MP3/Don't_Turn_i...,.mp3,407.640816,6.794014,44100,320000,None,2,16763201,...,124,8A,Am,08A,/Users/yerik/Desktop/temp_wav/Don't_Turn_it_Of...,44100,16,2,124.957417,125
6,Fantastic_Diversion-BY-Chris_Fortier_(Maetrik_...,/Users/yerik/Downloads/try_py_MP3/Fantastic_Di...,.mp3,436.166531,7.269442,44100,320000,None,2,17541843,...,124,11A,F#m,11A,/Users/yerik/Desktop/temp_wav/Fantastic_Divers...,44100,16,2,124.846330,125
7,Welcome_2_My_House-BY-Ladymonix_(Original_Mix)...,/Users/yerik/Downloads/try_py_MP3/Welcome_2_My...,.mp3,363.62449,6.060408,44100,320000,None,2,17765829,...,127,11B,A,11B,/Users/yerik/Desktop/temp_wav/Welcome_2_My_Hou...,44100,16,2,127.916721,128
8,Artefacts-BY-Diego_Krause_(Original_Mix)_KEY_A...,/Users/yerik/Downloads/try_py_MP3/Artefacts-BY...,.mp3,420.989388,7.01649,44100,320000,None,2,16896936,...,126,4A,Fm,04A,/Users/yerik/Desktop/temp_wav/Artefacts-BY-Die...,44100,16,2,127.018009,128
9,Keep_It_Real-BY-Silat_Beksi_(Original_Mix)_KEY...,/Users/yerik/Downloads/try_py_MP3/Keep_It_Real...,.mp3,461.557551,7.692626,44100,320000,None,2,18709376,...,125,10A,Bm,10A,/Users/yerik/Desktop/temp_wav/Keep_It_Real-BY-...,44100,16,2,125.945998,126
10,The_Frenchie_Thing-BY-Reboot_(Original_Mix)_KE...,/Users/yerik/Downloads/try_py_MP3/The_Frenchie...,.mp3,483.970612,8.066177,44100,320000,None,2,19492410,...,124,10A,Bm,10A,/Users/yerik/Desktop/temp_wav/The_Frenchie_Thi...,44100,16,2,124.846330,125
11,Tikkun-BY-Yotam_Avni_(Original_Mix)_KEY_B_Mino...,/Users/yerik/Downloads/try_py_MP3/Tikkun-BY-Yo...,.mp3,421.773061,7.029551,44100,320000,None,2,16962089,...,125,10A,Bm,10A,/Users/yerik/Desktop/temp_wav/Tikkun-BY-Yotam_...,44100,16,2,125.950032,126
12,"Better_For_My_Brain-BY-Pele,_Shawnecy_(Origina...",/Users/yerik/Downloads/try_py_MP3/Better_For_M...,.mp3,398.759184,6.645986,44100,320000,None,2,17698547,...,124,8A,Am,08A,/Users/yerik/Desktop/temp_wav/Better_For_My_Br...,44100,16,2,124.870117,125

# FREQ info

In [ ]:
import os
import numpy as np
import pandas as pd
import wave
from tqdm import tqdm
from pydub import AudioSegment
import shutil  # To delete the temp folder after all processing

# -----######-----###### CORE FUNCTION FOR CONVERSION WITH EXTRA ATTRIBUTES -----######-----######
def _convert_0110_files_to_wav_LOCATE_get_files(df, temp_wav_folder, audio_extensions):
    """
    Converts audio files to WAV if necessary and saves them in the temp_wav_folder.
    Also extracts sample rate (sr_conv), bit depth (bit_depth_conv), and channels (channels_conv) for the converted WAV files.

    :param df: DataFrame containing 'Path' column
    :param temp_wav_folder: The folder to save converted wav files
    :param audio_extensions: List of valid audio extensions (input as a variable outside the function)
    :return: Updated DataFrame with 'Wav_Path', 'sr_conv', 'bit_depth_conv', and 'channels_conv' columns
    """
    
    if not os.path.exists(temp_wav_folder):
        os.makedirs(temp_wav_folder)

    df.loc[:, 'Wav_Path'] = ""
    df.loc[:, 'sr_conv'] = None
    df.loc[:, 'bit_depth_conv'] = None
    df.loc[:, 'channels_conv'] = None

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Converting files"):
        file_path = row['Path']
        ext = os.path.splitext(file_path)[1].lower()

        if os.path.exists(file_path) and ext in audio_extensions:
            wav_file_name = os.path.basename(os.path.splitext(file_path)[0] + '.wav')
            wav_path = os.path.join(temp_wav_folder, wav_file_name)

            try:
                # Convert non-WAV files to WAV using pydub
                if ext != '.wav':
                    audio = AudioSegment.from_file(file_path)
                    audio.export(wav_path, format="wav")
                else:
                    wav_path = file_path

                # Extract attributes from the WAV file (for converted file)
                with wave.open(wav_path, 'r') as wav_file:
                    sr_conv = wav_file.getframerate()
                    bit_depth_conv = wav_file.getsampwidth() * 8  # sample width in bytes, so multiply by 8 for bits
                    channels_conv = wav_file.getnchannels()

                # Store the attributes of the converted file in the DataFrame
                df.loc[index, 'Wav_Path'] = wav_path
                df.loc[index, 'sr_conv'] = sr_conv
                df.loc[index, 'bit_depth_conv'] = bit_depth_conv
                df.loc[index, 'channels_conv'] = channels_conv

            except Exception as e:
                print(f"Error processing {file_path}: {e}")

    return df

# -----######-----###### CORE FUNCTION FOR FREQUENCY ANALYSIS -----######-----######
def _analyze_0110_wav_frequencies_LOCATE_get_prominent(df, save_pkl=False):
    """
    Reads WAV files, extracts low, high, and prominent frequencies, and updates the DataFrame.

    :param df: DataFrame with 'Wav_Path' for wav file paths
    :param save_pkl: Boolean flag to save the DataFrame as a pickle file (default=False)
    :return: DataFrame updated with frequency analysis
    """
    low_freqs, high_freqs, prominent_freqs_list = [], [], []

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Analyzing frequencies"):
        file_path = row['Wav_Path']
        if file_path and os.path.exists(file_path):
            low_freq, high_freq, prominent_freqs = read_frequencies_and_prominent_wav(file_path)
            
            low_freqs.append(low_freq)
            high_freqs.append(high_freq)
            prominent_freqs_list.append(list(prominent_freqs) if prominent_freqs is not None else [])

            # Save progress after each file if save_pkl is True
            if save_pkl:
                df.to_pickle(f"{os.path.dirname(file_path)}/processed_freqs_df.pkl")
        else:
            low_freqs.append(None)
            high_freqs.append(None)
            prominent_freqs_list.append([])

    df.loc[:, 'Low_Frequency'] = low_freqs
    df.loc[:, 'High_Frequency'] = high_freqs
    df.loc[:, 'Prominent_Frequencies'] = prominent_freqs_list

    return df

# -----######-----###### SUPPORT FUNCTION FOR FREQUENCY EXTRACTION -----######-----######
def read_frequencies_and_prominent_wav(file_path):
    """
    Extracts frequencies from a WAV file.

    :param file_path: Path to the WAV file
    :return: low_freq, high_freq, prominent_freqs
    """
    with wave.open(file_path, 'r') as f:
        nframes = f.getnframes()
        sample_rate = f.getframerate()
        audio_data = np.frombuffer(f.readframes(nframes), dtype=np.int16)

        fft_values = np.fft.fft(audio_data)
        freq_values = np.fft.fftfreq(len(audio_data), 1/sample_rate)

        fft_values = fft_values[(freq_values >= 10) & (freq_values <= 4000)]
        freq_values = freq_values[(freq_values >= 10) & (freq_values <= 4000)]

        positive_indices = np.where(freq_values > 0)
        positive_freqs = freq_values[positive_indices]
        positive_fft_values = np.abs(fft_values[positive_indices])

        if len(positive_freqs) == 0:
            return None, None, None

        low_freq = np.min(positive_freqs)
        high_freq = np.max(positive_freqs)
        prominent_indices = positive_fft_values.argsort()[-10:][::-1]
        prominent_freqs = positive_freqs[prominent_indices]

    return low_freq, high_freq, prominent_freqs

# -----######-----###### MAIN FUNCTION TO RUN CONVERSION AND ANALYSIS WITH TQM AND CLEANUP -----######-----######
def process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=1, save_pkl=False, save_path=None):
    """
    Processes audio files in chunks, converts them to WAV if needed, and extracts prominent frequencies.
    Cleans up the temp folder by deleting processed WAV files after each chunk.
    Optionally saves the DataFrame after processing each chunk to a pickle file.

    :param df: DataFrame containing file paths in 'Path'
    :param temp_wav_folder: Folder to store WAV files
    :param audio_extensions: List of valid audio extensions (input outside the function)
    :param chunk_size: Number of files to process per chunk
    :param save_pkl: Boolean flag to save the DataFrame as a pickle file (default=False)
    :param save_path: Path where the DataFrame is saved after each chunk if save_pkl is True
    :return: Final processed DataFrame
    """
    n = df.shape[0]
    final_df = pd.DataFrame()

    with tqdm(total=n, leave=True, desc="Processing audio files with TQM") as pbar:
        for i in range(0, n, chunk_size):
            df_chunk = df.iloc[i:i + chunk_size].copy()  # Ensuring we are working on a copy to avoid warnings

            # Convert audio files to WAV if needed, and extract sr_conv, bit_depth_conv, channels_conv
            df_chunk = _convert_0110_files_to_wav_LOCATE_get_files(df_chunk, temp_wav_folder, audio_extensions)

            # Analyze frequencies from WAV files
            df_chunk = _analyze_0110_wav_frequencies_LOCATE_get_prominent(df_chunk, save_pkl)

            # Concatenate the results
            final_df = pd.concat([final_df, df_chunk], ignore_index=True)
            
            # Update the main progress bar
            pbar.update(chunk_size)

            # Save after each chunk if save_pkl is True
            if save_pkl and save_path:
                final_df.to_pickle(save_path)
                print(f"Progress saved to {save_path} after chunk {i // chunk_size + 1}")

            # Cleanup: Remove the WAV files created for this chunk
            for file in os.listdir(temp_wav_folder):
                file_path = os.path.join(temp_wav_folder, file)
                if os.path.isfile(file_path) and file.endswith('.wav'):
                    os.remove(file_path)
                    
        # Optionally: Delete the temp folder after all processing
        if os.path.exists(temp_wav_folder):
            shutil.rmtree(temp_wav_folder)

    return final_df

# -----######-----###### EXAMPLE RUN STATEMENTS -----######-----######
# Define valid audio extensions outside of the functions
audio_extensions = ['.mp3', '.flac', '.aac', '.ogg', '.wma', '.au', '.aif', '.aiff', '.wav']

# Process the files with a temporary WAV folder and save results to pickle if needed
temp_wav_folder = '/Users/yerik/Desktop/temp_wav'
df = process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=1, save_pkl=False)
df

Processing audio files with TQM:   0%|                                       | 0/13 [00:00<?, ?it/s]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.16s/it]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:34<00:00, 34.52s/it]
Processing audio files with TQM:   8%|██▍                            | 1/13 [00:35<07:08, 35.74s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:15<00:00, 15.79s/it]
Processing audio files with TQM:  15%|████▊                          | 2/13 [00:52<04:30, 24.62s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.06s/it]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:22<00:00, 22.57s/it]
Processing audio files with TQM:  23%|███████▏                       | 3/13 [01:16<04:01, 24.18s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:02<00:00,  2.39s/it]
Processing audio files with TQM:  31%|█████████▌                     | 4/13 [01:19<02:23, 15.96s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.22s/it]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:07<00:00,  7.35s/it]
Processing audio files with TQM:  38%|███████████▉                   | 5/13 [01:28<01:46, 13.30s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]

# previous

In [6]:
import os
import numpy as np
import pandas as pd
import wave
from tqdm import tqdm
from pydub import AudioSegment
import shutil  # To delete the temp folder after all processing

# -----######-----###### CORE FUNCTION FOR CONVERSION WITH EXTRA ATTRIBUTES -----######-----######
def _convert_0110_files_to_wav_LOCATE_get_files(df, temp_wav_folder, audio_extensions):
    """
    Converts audio files to WAV if necessary and saves them in the temp_wav_folder.
    Also extracts sample rate (sr_conv), bit depth (bit_depth_conv), and channels (channels_conv) for the converted WAV files.

    :param df: DataFrame containing 'Path' column
    :param temp_wav_folder: The folder to save converted wav files
    :param audio_extensions: List of valid audio extensions (input as a variable outside the function)
    :return: Updated DataFrame with 'Wav_Path', 'sr_conv', 'bit_depth_conv', and 'channels_conv' columns
    """
    
    if not os.path.exists(temp_wav_folder):
        os.makedirs(temp_wav_folder)

    df.loc[:, 'Wav_Path'] = ""
    df.loc[:, 'sr_conv'] = None
    df.loc[:, 'bit_depth_conv'] = None
    df.loc[:, 'channels_conv'] = None

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Converting files"):
        file_path = row['Path']
        ext = os.path.splitext(file_path)[1].lower()

        if os.path.exists(file_path) and ext in audio_extensions:
            wav_file_name = os.path.basename(os.path.splitext(file_path)[0] + '.wav')
            wav_path = os.path.join(temp_wav_folder, wav_file_name)

            try:
                # Convert non-WAV files to WAV using pydub
                if ext != '.wav':
                    audio = AudioSegment.from_file(file_path)
                    audio.export(wav_path, format="wav")
                else:
                    wav_path = file_path

                # Extract attributes from the WAV file (for converted file)
                with wave.open(wav_path, 'r') as wav_file:
                    sr_conv = wav_file.getframerate()
                    bit_depth_conv = wav_file.getsampwidth() * 8  # sample width in bytes, so multiply by 8 for bits
                    channels_conv = wav_file.getnchannels()

                # Store the attributes of the converted file in the DataFrame
                df.loc[index, 'Wav_Path'] = wav_path
                df.loc[index, 'sr_conv'] = sr_conv
                df.loc[index, 'bit_depth_conv'] = bit_depth_conv
                df.loc[index, 'channels_conv'] = channels_conv

            except Exception as e:
                print(f"Error processing {file_path}: {e}")

    return df

# -----######-----###### CORE FUNCTION FOR FREQUENCY ANALYSIS -----######-----######
def _analyze_0110_wav_frequencies_LOCATE_get_prominent(df, save_pkl=False):
    """
    Reads WAV files, extracts low, high, and prominent frequencies, and updates the DataFrame.

    :param df: DataFrame with 'Wav_Path' for wav file paths
    :param save_pkl: Boolean flag to save the DataFrame as a pickle file (default=False)
    :return: DataFrame updated with frequency analysis
    """
    low_freqs, high_freqs, prominent_freqs_list = [], [], []

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Analyzing frequencies"):
        file_path = row['Wav_Path']
        if file_path and os.path.exists(file_path):
            low_freq, high_freq, prominent_freqs = read_frequencies_and_prominent_wav(file_path)
            
            low_freqs.append(low_freq)
            high_freqs.append(high_freq)
            prominent_freqs_list.append(list(prominent_freqs) if prominent_freqs is not None else [])

            # Save progress after each file if save_pkl is True
            if save_pkl:
                df.to_pickle(f"{os.path.dirname(file_path)}/processed_freqs_df.pkl")
        else:
            low_freqs.append(None)
            high_freqs.append(None)
            prominent_freqs_list.append([])

    df.loc[:, 'Low_Frequency'] = low_freqs
    df.loc[:, 'High_Frequency'] = high_freqs
    df.loc[:, 'Prominent_Frequencies'] = prominent_freqs_list

    return df

# -----######-----###### SUPPORT FUNCTION FOR FREQUENCY EXTRACTION -----######-----######
def read_frequencies_and_prominent_wav(file_path):
    """
    Extracts frequencies from a WAV file.

    :param file_path: Path to the WAV file
    :return: low_freq, high_freq, prominent_freqs
    """
    with wave.open(file_path, 'r') as f:
        nframes = f.getnframes()
        sample_rate = f.getframerate()
        audio_data = np.frombuffer(f.readframes(nframes), dtype=np.int16)

        fft_values = np.fft.fft(audio_data)
        freq_values = np.fft.fftfreq(len(audio_data), 1/sample_rate)

        fft_values = fft_values[(freq_values >= 10) & (freq_values <= 4000)]
        freq_values = freq_values[(freq_values >= 10) & (freq_values <= 4000)]

        positive_indices = np.where(freq_values > 0)
        positive_freqs = freq_values[positive_indices]
        positive_fft_values = np.abs(fft_values[positive_indices])

        if len(positive_freqs) == 0:
            return None, None, None

        low_freq = np.min(positive_freqs)
        high_freq = np.max(positive_freqs)
        prominent_indices = positive_fft_values.argsort()[-10:][::-1]
        prominent_freqs = positive_freqs[prominent_indices]

    return low_freq, high_freq, prominent_freqs

# -----######-----###### MAIN FUNCTION TO RUN CONVERSION AND ANALYSIS WITH TQM AND CLEANUP -----######-----######
def process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=1, save_pkl=False, save_path=None):
    """
    Processes audio files in chunks, converts them to WAV if needed, and extracts prominent frequencies.
    Cleans up the temp folder by deleting processed WAV files after each chunk.
    Optionally saves the DataFrame after processing each chunk to a pickle file.

    :param df: DataFrame containing file paths in 'Path'
    :param temp_wav_folder: Folder to store WAV files
    :param audio_extensions: List of valid audio extensions (input outside the function)
    :param chunk_size: Number of files to process per chunk
    :param save_pkl: Boolean flag to save the DataFrame as a pickle file (default=False)
    :param save_path: Path where the DataFrame is saved after each chunk if save_pkl is True
    :return: Final processed DataFrame
    """
    n = df.shape[0]
    final_df = pd.DataFrame()

    with tqdm(total=n, leave=True, desc="Processing audio files with TQM") as pbar:
        for i in range(0, n, chunk_size):
            df_chunk = df.iloc[i:i + chunk_size].copy()  # Ensuring we are working on a copy to avoid warnings

            # Convert audio files to WAV if needed, and extract sr_conv, bit_depth_conv, channels_conv
            df_chunk = _convert_0110_files_to_wav_LOCATE_get_files(df_chunk, temp_wav_folder, audio_extensions)

            # Analyze frequencies from WAV files
            df_chunk = _analyze_0110_wav_frequencies_LOCATE_get_prominent(df_chunk, save_pkl)

            # Concatenate the results
            final_df = pd.concat([final_df, df_chunk], ignore_index=True)
            
            # Update the main progress bar
            pbar.update(chunk_size)

            # Save after each chunk if save_pkl is True
            if save_pkl and save_path:
                final_df.to_pickle(save_path)
                print(f"Progress saved to {save_path} after chunk {i // chunk_size + 1}")

            # Cleanup: Remove the WAV files created for this chunk
            for file in os.listdir(temp_wav_folder):
                file_path = os.path.join(temp_wav_folder, file)
                if os.path.isfile(file_path) and file.endswith('.wav'):
                    os.remove(file_path)
                    
        # Optionally: Delete the temp folder after all processing
        if os.path.exists(temp_wav_folder):
            shutil.rmtree(temp_wav_folder)

    return final_df

# -----######-----###### EXAMPLE RUN STATEMENTS -----######-----######
# Define valid audio extensions outside of the functions
audio_extensions = ['.mp3', '.flac', '.aac', '.ogg', '.wma', '.au', '.aif', '.aiff', '.wav']

# Process the files with a temporary WAV folder and save results to pickle if needed
temp_wav_folder = '/Users/yerik/Desktop/temp_wav'
df = process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=1, save_pkl=False)

df

Processing audio files with TQM:   0%|                                        | 0/4 [00:00<?, ?it/s]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  3.15it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:04<00:00,  4.97s/it]
Processing audio files with TQM:   0%|                                        | 0/4 [00:05<?, ?it/s]

ValueError: Must have equal len keys and value when setting with an ndarray

In [8]:
df =df_p
df

,temp_id,Path,Extension,dur_seconds,dur_min,sr,bit_rate,bit_depth,channels,file_size,...,KEY,KEYC,KEY_code,Wav_Path,sr_conv,bit_depth_conv,channels_conv,Low_Frequency,High_Frequency,Prominent_Frequencies
0,"GASOLINE-BY-HiTech,_Juan_Michael_OG_(Original_...",/Users/yerik/Downloads/_id3_sample/GASOLINE-BY...,.mp3,168.463673,2.807728,44100,320000,None,2,8209595,...,8A,Am,08A,/Users/yerik/Desktop/temp_wav/GASOLINE-BY-HiTe...,44100,16,2,10.001224,3999.999697,"[20.165720752595405, 21.332381764780006, 26.66..."
1,"Disco_Inferno-BY-Syzz,_Nora_Van_Elken_(Origina...",/Users/yerik/Downloads/_id3_sample/Disco_Infer...,.mp3,131.500408,2.191673,44100,320000,None,2,5542415,...,5A,Cm,05A,/Users/yerik/Desktop/temp_wav/Disco_Inferno-BY...,44100,16,2,10.001956,3999.998913,"[23.09957406119611, 22.049939151599446, 24.149..."
2,Sinful-BY-Rhye_(Illangelo_Remix)_KEY_A#_Major_...,/Users/yerik/Downloads/_id3_sample/Sinful-BY-R...,.mp3,307.670204,5.127837,44100,320000,None,2,12350181,...,6A,Gm,06A,/Users/yerik/Desktop/temp_wav/Sinful-BY-Rhye_(...,44100,16,2,10.000744,3999.998437,"[25.56666653889961, 24.583333210480394, 26.549..."
3,Sii-BY-JSPRV35_(Original_Mix)_KEY_E_Minor_BPM_...,/Users/yerik/Downloads/_id3_sample/Sii-BY-JSPR...,.mp3,323.030204,5.383837,44100,320000,None,2,13080050,...,11A,F#m,11A,/Users/yerik/Desktop/temp_wav/Sii-BY-JSPRV35_(...,44100,16,2,10.000000,3999.998452,"[24.150154798761612, 23.0, 26.450464396284833,..."
4,Nelic_Spore-BY-Unknown_Mobile_(2Lanes_Remix)_K...,/Users/yerik/Downloads/_id3_sample/Nelic_Spore...,.mp3,361.769796,6.029497,44100,320000,None,2,15949571,...,7A,Dm,07A,/Users/yerik/Desktop/temp_wav/Nelic_Spore-BY-U...,44100,16,2,10.000300,3999.999853,"[12.362499730453083, 12.074999736721617, 12.64..."
5,"Mi_Cuerpo-BY-Pearson_Sound,_Clara!_(Nidia_Remi...",/Users/yerik/Downloads/_id3_sample/Mi_Cuerpo-B...,.mp3,234.997551,3.916626,44100,320000,None,2,9526344,...,8A,Am,08A,/Users/yerik/Desktop/temp_wav/Mi_Cuerpo-BY-Pea...,44100,16,2,10.001415,3999.999875,"[15.500064948638462, 16.534253796117635, 41.33..."

In [9]:
import pandas as pd
import numpy as np
from collections import Counter

# Define the mapping of frequency to MIDI note
def freq_to_midi(frequency):
    return 69 + 12 * np.log2(frequency / 440.0)

# Define the mapping of MIDI note to octave and note name
def midi_to_note_octave(midi_number):
    note_names = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
    octave = (midi_number // 12) - 1
    note = note_names[int(midi_number % 12)]
    return note, octave

# Function to convert frequency to note and octave
def freq_to_note_octave(frequency):
    midi_number = freq_to_midi(frequency)
    note, octave = midi_to_note_octave(round(midi_number))
    return note, octave

# Camelot wheel mapping
camelot_wheel = {
    'C': '8B', 'C#': '3B', 'D': '10B', 'D#': '5B', 'E': '12B', 'F': '7B', 'F#': '2B', 'G': '9B', 'G#': '4B', 'A': '11B', 'A#': '6B', 'B': '1B',
    'Cm': '5A', 'C#m': '12A', 'Dm': '7A', 'D#m': '2A', 'Em': '9A', 'Fm': '4A', 'F#m': '11A', 'Gm': '6A', 'G#m': '1A', 'Am': '8A', 'A#m': '3A', 'Bm': '10A'
}

# Function to convert note and octave to Camelot key
def note_octave_to_camelot(note, octave):
    key = note + ('m' if octave % 2 == 0 else '')
    return camelot_wheel.get(key, '')

# Convert frequencies to notes and octaves
df['Notes_Octaves'] = df['Prominent_Frequencies'].apply(lambda freqs: [freq_to_note_octave(freq) for freq in freqs])

# Extract first frequency's octave
df['First_Octave'] = df['Prominent_Frequencies'].apply(lambda freqs: freq_to_note_octave(freqs[0])[1])

# Create new string column "octaves" with the format "232"
df['Octaves'] = df['First_Octave'].apply(lambda x: f"{x}{x+1}{x+2}")

# Convert frequencies to notes, octaves, and Camelot keys
df['Notes_Octaves_Camelot'] = df['Prominent_Frequencies'].apply(
    lambda freqs: [note_octave_to_camelot(*freq_to_note_octave(freq)) for freq in freqs]
)

# Extract the Camelot keys and join the first three into a single string
df['Camelot_Sequence'] = df['Notes_Octaves_Camelot'].apply(
    lambda keys: ''.join(keys[:3])
)

# Determine the most repeated Camelot key and its count
def most_repeated_key(keys):
    if keys:
        most_common_key, count = Counter(keys).most_common(1)[0]
        return f"{most_common_key}_{count}"
    return ''

df['key_1'] = df['Notes_Octaves_Camelot'].apply(most_repeated_key)

# KEY NAME CODE
df['key_code'] = (df['key_1'].astype(str) +'cnt-rnk_'+df['Camelot_Sequence'].astype(str) +'-'+df['Octaves'].astype(str)+'oct')

# Chroma cross-check function (optional)
def chroma_cross_check(prominent_freqs):
    # Placeholder: you can run a lightweight chroma analysis or compare harmonic relationships
    top_freq = prominent_freqs[0]  # Simpler: pick the first, or choose based on logic
    return top_freq  # Adjust or improve based on chroma if necessary

df['key_confirmed'] = df['Prominent_Frequencies'].apply(chroma_cross_check)

df

,temp_id,Path,Extension,dur_seconds,dur_min,sr,bit_rate,bit_depth,channels,file_size,...,High_Frequency,Prominent_Frequencies,Notes_Octaves,First_Octave,Octaves,Notes_Octaves_Camelot,Camelot_Sequence,key_1,key_code,key_confirmed
0,"GASOLINE-BY-HiTech,_Juan_Michael_OG_(Original_...",/Users/yerik/Downloads/_id3_sample/GASOLINE-BY...,.mp3,168.463673,2.807728,44100,320000,None,2,8209595,...,3999.999697,"[20.165720752595405, 21.332381764780006, 26.66...","[(E, 0), (F, 0), (G#, 0), (A#, 0), (A, 0), (D#...",0,012,"[9A, 4A, 1A, 3A, 8A, 2A, 9A, 9A, 1A, 9A]",9A4A1A,9A_4,9A_4cnt-rnk_9A4A1A-012oct,20.165721
1,"Disco_Inferno-BY-Syzz,_Nora_Van_Elken_(Origina...",/Users/yerik/Downloads/_id3_sample/Disco_Infer...,.mp3,131.500408,2.191673,44100,320000,None,2,5542415,...,3999.998913,"[23.09957406119611, 22.049939151599446, 24.149...","[(F#, 0), (F, 0), (G, 0), (C, 1), (B, 0), (G, ...",0,012,"[11A, 4A, 6A, 8B, 10A, 9B, 11B, 6A, 8B, 10A]",11A4A6A,6A_2,6A_2cnt-rnk_11A4A6A-012oct,23.099574
2,Sinful-BY-Rhye_(Illangelo_Remix)_KEY_A#_Major_...,/Users/yerik/Downloads/_id3_sample/Sinful-BY-R...,.mp3,307.670204,5.127837,44100,320000,None,2,12350181,...,3999.998437,"[25.56666653889961, 24.583333210480394, 26.549...","[(G#, 0), (G, 0), (G#, 0), (G#, 0), (G, 0), (A...",0,012,"[1A, 6A, 1A, 1A, 6A, 8A, 1A, 6A, 11A, 1A]",1A6A1A,1A_5,1A_5cnt-rnk_1A6A1A-012oct,25.566667
3,Sii-BY-JSPRV35_(Original_Mix)_KEY_E_Minor_BPM_...,/Users/yerik/Downloads/_id3_sample/Sii-BY-JSPR...,.mp3,323.030204,5.383837,44100,320000,None,2,13080050,...,3999.998452,"[24.150154798761612, 23.0, 26.450464396284833,...","[(G, 0), (F#, 0), (G#, 0), (B, 0), (G#, 0), (F...",0,012,"[6A, 11A, 1A, 10A, 1A, 4A, 3B, 8A, 11A, 8B]",6A11A1A,11A_2,11A_2cnt-rnk_6A11A1A-012oct,24.150155
4,Nelic_Spore-BY-Unknown_Mobile_(2Lanes_Remix)_K...,/Users/yerik/Downloads/_id3_sample/Nelic_Spore...,.mp3,361.769796,6.029497,44100,320000,None,2,15949571,...,3999.999853,"[12.362499730453083, 12.074999736721617, 12.64...","[(G, -1), (G, -1), (G#, -1), (D, 1), (D#, 1), ...",-1,-101,"[9B, 9B, 4B, 10B, 5B, 5B, 4A, 2B, 12A, 5B]",9B9B4B,5B_3,5B_3cnt-rnk_9B9B4B--101oct,12.362500
5,"Mi_Cuerpo-BY-Pearson_Sound,_Clara!_(Nidia_Remi...",/Users/yerik/Downloads/_id3_sample/Mi_Cuerpo-B...,.mp3,234.997551,3.916626,44100,320000,None,2,9526344,...,3999.999875,"[15.500064948638462, 16.534253796117635, 41.33...","[(B, -1), (C, 0), (E, 1), (A#, -1), (F#, 0), (...",-1,-101,"[1B, 5A, 12B, 6B, 11A, 11B, 10A, 6B, 11A, 9B]",1B5A12B,6B_2,6B_2cnt-rnk_1B5A12B--101oct,15.500065

In [ ]:
import os
import numpy as np
import pandas as pd
import wave
from tqdm import tqdm
from pydub import AudioSegment

# -----######-----###### CORE FUNCTION FOR CONVERSION WITH EXTRA ATTRIBUTES -----######-----######
def _convert_0110_files_to_wav_LOCATE_get_files(df, temp_wav_folder, audio_extensions):
    """
    Converts audio files to WAV if necessary and saves them in the temp_wav_folder.
    Also extracts sample rate (sr_conv), bit depth (bit_depth_conv), and channels (channels_conv) for the converted WAV files.

    :param df: DataFrame containing 'Path' column
    :param temp_wav_folder: The folder to save converted wav files
    :param audio_extensions: List of valid audio extensions (input as a variable outside the function)
    :return: Updated DataFrame with 'Wav_Path', 'sr_conv', 'bit_depth_conv', and 'channels_conv' columns
    """
    
    if not os.path.exists(temp_wav_folder):
        os.makedirs(temp_wav_folder)

    df.loc[:, 'Wav_Path'] = ""
    df.loc[:, 'sr_conv'] = None
    df.loc[:, 'bit_depth_conv'] = None
    df.loc[:, 'channels_conv'] = None

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Converting files"):
        file_path = row['Path']
        ext = os.path.splitext(file_path)[1].lower()

        if os.path.exists(file_path) and ext in audio_extensions:
            wav_file_name = os.path.basename(os.path.splitext(file_path)[0] + '.wav')
            wav_path = os.path.join(temp_wav_folder, wav_file_name)

            try:
                # Convert non-WAV files to WAV using pydub
                if ext != '.wav':
                    audio = AudioSegment.from_file(file_path)
                    audio.export(wav_path, format="wav")
                else:
                    wav_path = file_path

                # Extract attributes from the WAV file (for converted file)
                with wave.open(wav_path, 'r') as wav_file:
                    sr_conv = wav_file.getframerate()
                    bit_depth_conv = wav_file.getsampwidth() * 8  # sample width in bytes, so multiply by 8 for bits
                    channels_conv = wav_file.getnchannels()

                # Store the attributes of the converted file in the DataFrame
                df.loc[index, 'Wav_Path'] = wav_path
                df.loc[index, 'sr_conv'] = sr_conv
                df.loc[index, 'bit_depth_conv'] = bit_depth_conv
                df.loc[index, 'channels_conv'] = channels_conv

            except Exception as e:
                print(f"Error processing {file_path}: {e}")

    return df

# -----######-----###### CORE FUNCTION FOR FREQUENCY ANALYSIS -----######-----######
def _analyze_0110_wav_frequencies_LOCATE_get_prominent(df, save_pkl=False):
    """
    Reads WAV files, extracts low, high, and prominent frequencies, and updates the DataFrame.

    :param df: DataFrame with 'Wav_Path' for wav file paths
    :param save_pkl: Boolean flag to save the DataFrame as a pickle file (default=False)
    :return: DataFrame updated with frequency analysis
    """
    low_freqs, high_freqs, prominent_freqs_list = [], [], []

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Analyzing frequencies"):
        file_path = row['Wav_Path']
        if file_path and os.path.exists(file_path):
            low_freq, high_freq, prominent_freqs = read_frequencies_and_prominent_wav(file_path)
            
            low_freqs.append(low_freq)
            high_freqs.append(high_freq)
            prominent_freqs_list.append(list(prominent_freqs) if prominent_freqs is not None else [])

            # Save progress after each file if save_pkl is True
            if save_pkl:
                df.to_pickle(f"{os.path.dirname(file_path)}/processed_freqs_df.pkl")
        else:
            low_freqs.append(None)
            high_freqs.append(None)
            prominent_freqs_list.append([])

    df.loc[:, 'Low_Frequency'] = low_freqs
    df.loc[:, 'High_Frequency'] = high_freqs
    df.loc[:, 'Prominent_Frequencies'] = prominent_freqs_list

    return df

# -----######-----###### SUPPORT FUNCTION FOR FREQUENCY EXTRACTION -----######-----######
def read_frequencies_and_prominent_wav(file_path):
    """
    Extracts frequencies from a WAV file.

    :param file_path: Path to the WAV file
    :return: low_freq, high_freq, prominent_freqs
    """
    with wave.open(file_path, 'r') as f:
        nframes = f.getnframes()
        sample_rate = f.getframerate()
        audio_data = np.frombuffer(f.readframes(nframes), dtype=np.int16)

        fft_values = np.fft.fft(audio_data)
        freq_values = np.fft.fftfreq(len(audio_data), 1/sample_rate)

        fft_values = fft_values[(freq_values >= 10) & (freq_values <= 4000)]
        freq_values = freq_values[(freq_values >= 10) & (freq_values <= 4000)]

        positive_indices = np.where(freq_values > 0)
        positive_freqs = freq_values[positive_indices]
        positive_fft_values = np.abs(fft_values[positive_indices])

        if len(positive_freqs) == 0:
            return None, None, None

        low_freq = np.min(positive_freqs)
        high_freq = np.max(positive_freqs)
        prominent_indices = positive_fft_values.argsort()[-10:][::-1]
        prominent_freqs = positive_freqs[prominent_indices]

    return low_freq, high_freq, prominent_freqs

# -----######-----###### MAIN FUNCTION TO RUN CONVERSION AND ANALYSIS WITH TQM -----######-----######
def process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=1, save_pkl=False):
    """
    Processes audio files in chunks: converts audio to WAV if needed, then extracts prominent frequencies.
    Optionally saves the DataFrame after processing each file to a pickle file.

    :param df: DataFrame containing file paths in 'Path'
    :param temp_wav_folder: Folder to store WAV files
    :param audio_extensions: List of valid audio extensions (input outside the function)
    :param chunk_size: Number of files to process per chunk
    :param save_pkl: Boolean flag to save the DataFrame as a pickle file (default=False)
    :return: Final processed DataFrame
    """
    n = df.shape[0]
    final_df = pd.DataFrame()

    with tqdm(total=n, leave=True, desc="Processing audio files with TQM") as pbar:
        for i in range(0, n, chunk_size):
            df_chunk = df.iloc[i:i + chunk_size].copy()  # Ensuring we are working on a copy to avoid warnings

            # Convert audio files to WAV if needed, and extract sr_conv, bit_depth_conv, channels_conv
            df_chunk = _convert_0110_files_to_wav_LOCATE_get_files(df_chunk, temp_wav_folder, audio_extensions)

            # Analyze frequencies from WAV files
            df_chunk = _analyze_0110_wav_frequencies_LOCATE_get_prominent(df_chunk, save_pkl)

            # Concatenate the results
            final_df = pd.concat([final_df, df_chunk], ignore_index=True)
            
            pbar.update(chunk_size)  # Update the main progress bar

    return final_df

# -----######-----###### EXAMPLE RUN STATEMENTS -----######-----######
# Define valid audio extensions outside of the functions
audio_extensions = ['.mp3', '.flac', '.aac', '.ogg', '.wma', '.au', '.aif', '.aiff', '.wav']

# Process the files with a temporary WAV folder and save results to pickle if needed
temp_wav_folder = '/Users/yerik/Desktop/temp_wav'
df_p = process_audio_files(df, temp_wav_folder, audio_extensions, chunk_size=1, save_pkl=False)

df_p

In [4]:
import os
import numpy as np
import pandas as pd
import wave
from tqdm import tqdm
from pydub import AudioSegment

# -----######-----###### CORE FUNCTION FOR CONVERSION WITH EXTRA ATTRIBUTES -----######-----######
def _convert_0110_files_to_wav_LOCATE_get_files(df, temp_wav_folder, valid_extensions=None):
    """
    Converts audio files to WAV if necessary and saves them in the temp_wav_folder.
    Also extracts sample rate (sr), bit depth, and channels and updates the DataFrame with new WAV file paths.

    :param df: DataFrame containing 'Path' column
    :param temp_wav_folder: The folder to save converted wav files
    :param valid_extensions: List of valid extensions (defaults to common audio formats)
    :return: Updated DataFrame with 'Wav_Path', 'sr', 'bit_depth', and 'channels' columns
    """
    if valid_extensions is None:
        valid_extensions = ['.mp3', '.flac', '.aac', '.ogg', '.wma', '.au', '.aif', '.aiff', '.wav']

    if not os.path.exists(temp_wav_folder):
        os.makedirs(temp_wav_folder)

    df.loc[:, 'Wav_Path'] = ""
    df.loc[:, 'sr'] = None
    df.loc[:, 'bit_depth'] = None
    df.loc[:, 'channels'] = None

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Converting files"):
        file_path = row['Path']
        ext = os.path.splitext(file_path)[1].lower()

        if os.path.exists(file_path) and ext in valid_extensions:
            wav_file_name = os.path.basename(os.path.splitext(file_path)[0] + '.wav')
            wav_path = os.path.join(temp_wav_folder, wav_file_name)

            try:
                # Convert non-WAV files to WAV using pydub
                if ext != '.wav':
                    audio = AudioSegment.from_file(file_path)
                    audio.export(wav_path, format="wav")
                else:
                    wav_path = file_path

                # Extract attributes from the WAV file
                with wave.open(wav_path, 'r') as wav_file:
                    sr = wav_file.getframerate()
                    bit_depth = wav_file.getsampwidth() * 8  # sample width in bytes, so multiply by 8 for bits
                    channels = wav_file.getnchannels()

                # Store the attributes in the DataFrame
                df.loc[index, 'Wav_Path'] = wav_path
                df.loc[index, 'sr'] = sr
                df.loc[index, 'bit_depth'] = bit_depth
                df.loc[index, 'channels'] = channels

                # Save DataFrame after each file to prevent data loss


            except Exception as e:
                print(f"Error processing {file_path}: {e}")

    return df

# -----######-----###### CORE FUNCTION FOR FREQUENCY ANALYSIS -----######-----######
def _analyze_0110_wav_frequencies_LOCATE_get_prominent(df):
    """
    Reads WAV files, extracts low, high, and prominent frequencies, and updates the DataFrame.

    :param df: DataFrame with 'Wav_Path' for wav file paths
    :return: DataFrame updated with frequency analysis
    """
    low_freqs, high_freqs, prominent_freqs_list = [], [], []

    for index, row in tqdm(df.iterrows(), total=df.shape[0], leave=False, desc="Analyzing frequencies"):
        file_path = row['Wav_Path']
        if file_path and os.path.exists(file_path):
            low_freq, high_freq, prominent_freqs = read_frequencies_and_prominent_wav(file_path)
            
            low_freqs.append(low_freq)
            high_freqs.append(high_freq)
            prominent_freqs_list.append(list(prominent_freqs) if prominent_freqs is not None else [])

            # Save progress after each file
            df.to_pickle(f"{os.path.dirname(file_path)}/processed_freqs_df.pkl")
        else:
            low_freqs.append(None)
            high_freqs.append(None)
            prominent_freqs_list.append([])

    df.loc[:, 'Low_Frequency'] = low_freqs
    df.loc[:, 'High_Frequency'] = high_freqs
    df.loc[:, 'Prominent_Frequencies'] = prominent_freqs_list

    return df

# -----######-----###### SUPPORT FUNCTION FOR FREQUENCY EXTRACTION -----######-----######
def read_frequencies_and_prominent_wav(file_path):
    """
    Extracts frequencies from a WAV file.

    :param file_path: Path to the WAV file
    :return: low_freq, high_freq, prominent_freqs
    """
    with wave.open(file_path, 'r') as f:
        nframes = f.getnframes()
        sample_rate = f.getframerate()
        audio_data = np.frombuffer(f.readframes(nframes), dtype=np.int16)

        fft_values = np.fft.fft(audio_data)
        freq_values = np.fft.fftfreq(len(audio_data), 1/sample_rate)

        fft_values = fft_values[(freq_values >= 10) & (freq_values <= 4000)]
        freq_values = freq_values[(freq_values >= 10) & (freq_values <= 4000)]

        positive_indices = np.where(freq_values > 0)
        positive_freqs = freq_values[positive_indices]
        positive_fft_values = np.abs(fft_values[positive_indices])

        if len(positive_freqs) == 0:
            return None, None, None

        low_freq = np.min(positive_freqs)
        high_freq = np.max(positive_freqs)
        prominent_indices = positive_fft_values.argsort()[-10:][::-1]
        prominent_freqs = positive_freqs[prominent_indices]

    return low_freq, high_freq, prominent_freqs

# -----######-----###### MAIN FUNCTION TO RUN CONVERSION AND ANALYSIS WITH TQM -----######-----######
def process_audio_files(df, temp_wav_folder, chunk_size=1):
    """
    Processes audio files in chunks: converts audio to WAV if needed, then extracts prominent frequencies.
    Saves the DataFrame after processing each file.

    :param df: DataFrame containing file paths in 'Path'
    :param temp_wav_folder: Folder to store WAV files
    :param chunk_size: Number of files to process per chunk
    :return: Final processed DataFrame
    """
    n = df.shape[0]
    final_df = pd.DataFrame()

    with tqdm(total=n, leave=True, desc="Processing audio files with TQM") as pbar:
        for i in range(0, n, chunk_size):
            df_chunk = df.iloc[i:i + chunk_size].copy()  # Ensuring we are working on a copy to avoid warnings

            # Convert audio files to WAV if needed, and extract sr, bit depth, channels
            df_chunk = _convert_0110_files_to_wav_LOCATE_get_files(df_chunk, temp_wav_folder)

            # Analyze frequencies from WAV files
            df_chunk = _analyze_0110_wav_frequencies_LOCATE_get_prominent(df_chunk)

            # Concatenate the results
            final_df = pd.concat([final_df, df_chunk], ignore_index=True)
            
            pbar.update(chunk_size)  # Update the main progress bar

    return final_df

# -----######-----###### EXAMPLE RUN STATEMENTS -----######-----######
# Example DataFrame with various audio paths

# Process the files with a temporary WAV folder
temp_wav_folder = '/Users/yerik/Desktop/temp_wav'
df_p = process_audio_files(df, temp_wav_folder, chunk_size=1)

df_p

Processing audio files with TQM:   0%|                                        | 0/6 [00:00<?, ?it/s]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  3.13it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:05<00:00,  5.06s/it]
Processing audio files with TQM:  17%|█████▎                          | 1/6 [00:05<00:26,  5.39s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  3.48it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:02<00:00,  2.19s/it]
Processing audio files with TQM:  33%|██████████▋                     | 2/6 [00:07<00:14,  3.68s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  1.87it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:18<00:00, 18.52s/it]
Processing audio files with TQM:  50%|████████████████                | 3/6 [00:26<00:32, 10.72s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  1.60it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:01<00:00,  1.53s/it]
Processing audio files with TQM:  67%|█████████████████████▎          | 4/6 [00:29<00:14,  7.34s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  1.62it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:22<00:00, 22.49s/it]
Processing audio files with TQM:  83%|██████████████████████████▋     | 5/6 [00:52<00:13, 13.04s/it]
Converting files:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Converting files: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  1.98it/s]

Analyzing frequencies:   0%|                                                  | 0/1 [00:00<?, ?it/s]
Analyzing frequencies: 100%|██████████████████████████████████████████| 1/1 [00:04<00:00,  4.09s/it]
Processing audio files with TQM: 100%|████████████████████████████████| 6/6 [00:56<00:00,  9.48s/it]

,temp_id,Path,Extension,dur_seconds,dur_min,sr,bit_rate,bit_depth,channels,file_size,...,decoder,comment,BPM,KEY,KEYC,KEY_code,Wav_Path,Low_Frequency,High_Frequency,Prominent_Frequencies
0,"GASOLINE-BY-HiTech,_Juan_Michael_OG_(Original_...",/Users/yerik/Downloads/_id3_sample/GASOLINE-BY...,.mp3,168.463673,2.807728,44100,320000,16,2,8209595,...,Lavf58.20.100,"GASOLINE-BY-HiT - HiTech, Juan Michael OG_2024...",160,8A,Am,08A,/Users/yerik/Desktop/temp_wav/GASOLINE-BY-HiTe...,10.001224,3999.999697,"[20.165720752595405, 21.332381764780006, 26.66..."
1,"Disco_Inferno-BY-Syzz,_Nora_Van_Elken_(Origina...",/Users/yerik/Downloads/_id3_sample/Disco_Infer...,.mp3,131.500408,2.191673,44100,320000,16,2,5542415,...,Lavf57.83.100,engID3v1 Comment Purchased at Beatport,126,5A,Cm,05A,/Users/yerik/Desktop/temp_wav/Disco_Inferno-BY...,10.001956,3999.998913,"[23.09957406119611, 22.049939151599446, 24.149..."
2,Sinful-BY-Rhye_(Illangelo_Remix)_KEY_A#_Major_...,/Users/yerik/Downloads/_id3_sample/Sinful-BY-R...,.mp3,307.670204,5.127837,44100,320000,16,2,12350181,...,Lavf57.83.100,Sinful-BY-Rhye_ - Rhye_2018_Loma Vista Recordings,118,6A,Gm,06A,/Users/yerik/Desktop/temp_wav/Sinful-BY-Rhye_(...,10.000744,3999.998437,"[25.56666653889961, 24.583333210480394, 26.549..."
3,Sii-BY-JSPRV35_(Original_Mix)_KEY_E_Minor_BPM_...,/Users/yerik/Downloads/_id3_sample/Sii-BY-JSPR...,.mp3,323.030204,5.383837,44100,320000,16,2,13080050,...,Lavf58.20.100,Sii-BY-JSPRV35_ - JSPRV35_2024_International C...,138,11A,F#m,11A,/Users/yerik/Desktop/temp_wav/Sii-BY-JSPRV35_(...,10.000000,3999.998452,"[24.150154798761612, 23.0, 26.450464396284833,..."
4,Nelic_Spore-BY-Unknown_Mobile_(2Lanes_Remix)_K...,/Users/yerik/Downloads/_id3_sample/Nelic_Spore...,.mp3,361.769796,6.029497,44100,320000,16,2,15949571,...,Lavf58.20.100,Nelic_Spore-BY- - Unknown Mobile_2023_Quern,104,7A,Dm,07A,/Users/yerik/Desktop/temp_wav/Nelic_Spore-BY-U...,10.000300,3999.999853,"[12.362499730453083, 12.074999736721617, 12.64..."
5,"Mi_Cuerpo-BY-Pearson_Sound,_Clara!_(Nidia_Remi...",/Users/yerik/Downloads/_id3_sample/Mi_Cuerpo-B...,.mp3,234.997551,3.916626,44100,320000,16,2,9526344,...,Lavf57.83.100,engID3v1 Comment Purchased at Beatport,124,8A,Am,08A,/Users/yerik/Desktop/temp_wav/Mi_Cuerpo-BY-Pea...,10.001415,3999.999875,"[15.500064948638462, 16.534253796117635, 41.33..."

# WRITE FUNCTIONS

In [6]:
%%writefile -a /Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/_MSG_GET_song_attributes.py

import numpy as np
import pandas as pd
from pydub import AudioSegment
from pyloudnorm import Meter
from tqdm import tqdm

# -----######-----###### LUFS Calculation Function -----######-----######


def _all_au_ext_GET_12_LUFS_values(df):
    """
    Computes LUFS for each file in the DataFrame using the path from 'Path' and updating meter based on sample rate from the DataFrame.
    
    Parameters:
    df (DataFrame): DataFrame containing 'Path', 'sr', and other relevant columns.

    Returns:
    List: List of LUFS values for each file.
    """
    
    lufs_results = []

    # Loop through paths with tqdm progress bar
    for _, row in tqdm(df.iterrows(), desc="Computing LUFS", unit="file", total=len(df)):
        try:
            # Get the file path and sample rate from the DataFrame
            file_path = row['Path']
            sample_rate = row['sr']
            
            # Load the audio file using pydub
            audio = AudioSegment.from_file(file_path)
            
            # Convert audio to an array of samples
            samples = np.array(audio.get_array_of_samples())
            
            # Convert integer samples to floating point and normalize
            samples = samples / (2**15)
            
            # Check if stereo or mono and reshape accordingly
            if audio.channels == 2:
                samples = samples.reshape((-1, 2))
            else:
                samples = samples.reshape((-1, 1))
            
            # Initialize the loudness meter with the sample rate from DataFrame
            meter = Meter(rate=sample_rate)
            
            # Compute LUFS
            loudness = meter.integrated_loudness(samples)
            lufs_results.append(round(loudness, 3))
        
        except Exception as e:
            print(f"Error processing {file_path}: {e}")
            lufs_results.append(None)
    
    return lufs_results

# -----######-----###### LUFS Mapping Function -----######-----######
def _all_values_CREATE_12_LUFS_categories(lufs_value):
    """
    Maps LUFS values to energy levels.

    Parameters:
    lufs_value (float): The LUFS value.

    Returns:
    str: Energy level code corresponding to LUFS value.
    """
    if lufs_value is None:
        return None
    elif lufs_value <= -18:
        return 'LuA'
    elif -18 < lufs_value <= -16:
        return 'LuB'
    elif -16 < lufs_value <= -14:
        return 'LuC'
    elif -14 < lufs_value <= -12:
        return 'LuD'
    elif -12 < lufs_value <= -10:
        return 'Lue'
    else:
        return 'LuF'

Appending to /Users/yerik/_apple_source/PY/functions/_GLOBAL/_2ms/_MSG_GET_song_attributes.py

In [5]:
df

,temp_id,Path,Extension,dur_seconds,dur_min,sr,bit_rate,bit_depth,channels,file_size,...,rel_weekday,audio_offset,decoder,comment,BPM,KEY,KEYC,KEY_code,ms_lufs,ms_LUFS_code
0,"GASOLINE-BY-HiTech,_Juan_Michael_OG_(Original_...",/Users/yerik/Downloads/_id3_sample/GASOLINE-BY...,.mp3,168.463673,2.807728,44100,320000,None,2,8209595,...,Fri,1470004.0,Lavf58.20.100,"GASOLINE-BY-HiT - HiTech, Juan Michael OG_2024...",160,8A,Am,08A,-7.875,LuF
1,"Disco_Inferno-BY-Syzz,_Nora_Van_Elken_(Origina...",/Users/yerik/Downloads/_id3_sample/Disco_Infer...,.mp3,131.500408,2.191673,44100,320000,None,2,5542415,...,Fri,281355.0,Lavf57.83.100,engID3v1 Comment Purchased at Beatport,126,5A,Cm,05A,-6.977,LuF
2,Sinful-BY-Rhye_(Illangelo_Remix)_KEY_A#_Major_...,/Users/yerik/Downloads/_id3_sample/Sinful-BY-R...,.mp3,307.670204,5.127837,44100,320000,None,2,12350181,...,Fri,42329.0,Lavf57.83.100,Sinful-BY-Rhye_ - Rhye_2018_Loma Vista Recordings,118,6A,Gm,06A,-10.483,Lue
4,Sii-BY-JSPRV35_(Original_Mix)_KEY_E_Minor_BPM_...,/Users/yerik/Downloads/_id3_sample/Sii-BY-JSPR...,.mp3,323.030204,5.383837,44100,320000,None,2,13080050,...,Fri,157798.0,Lavf58.20.100,Sii-BY-JSPRV35_ - JSPRV35_2024_International C...,138,11A,F#m,11A,-8.580,LuF
5,Nelic_Spore-BY-Unknown_Mobile_(2Lanes_Remix)_K...,/Users/yerik/Downloads/_id3_sample/Nelic_Spore...,.mp3,361.769796,6.029497,44100,320000,None,2,15949571,...,Fri,1477736.0,Lavf58.20.100,Nelic_Spore-BY- - Unknown Mobile_2023_Quern,104,7A,Dm,07A,-11.755,Lue
6,"Mi_Cuerpo-BY-Pearson_Sound,_Clara!_(Nidia_Remi...",/Users/yerik/Downloads/_id3_sample/Mi_Cuerpo-B...,.mp3,234.997551,3.916626,44100,320000,None,2,9526344,...,Fri,125398.0,Lavf57.83.100,engID3v1 Comment Purchased at Beatport,124,8A,Am,08A,-9.835,LuF