In [1]:
# -----######-----###### CONCAT 3 PKL FILES INTO ONE DF -----######-----###### #
import pandas as pd

def _concat_1710_pkls_GET_combined_df(pkl_paths):
    """
    Concatenate 3 DataFrames from provided .pkl file paths into one DataFrame.
    Parameters:
        pkl_paths: list of 3 strings (file paths to .pkl files)
    Returns:
        pd.DataFrame: concatenated DataFrame
    """
    dfs = []
    for path in pkl_paths:
        print(f"📥 Reading: {path}")
        df = pd.read_pickle(path)
        print(f"✅ Loaded {len(df)} rows")
        dfs.append(df)

    df_final = pd.concat(dfs, ignore_index=True)
    print(f"\n🎯 Total Rows Combined: {len(df_final)}")
    return df_final

In [4]:
# Provide your file paths here
pkl_paths = [
    '_df_v_final.pkl',
    '_df_b_final.pkl',
    '_df_d_final.pkl'
]

df_combined = _concat_1710_pkls_GET_combined_df(pkl_paths)

📥 Reading: _df_v_final.pkl
✅ Loaded 1499 rows
📥 Reading: _df_b_final.pkl
✅ Loaded 419 rows
📥 Reading: _df_d_final.pkl
✅ Loaded 1368 rows

🎯 Total Rows Combined: 3286

In [16]:
df_samples = pd.read_pickle("/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_ii_STEM_SAMPLE_level-info_ID_and_BPM_and_KEYstring.pkl")

In [17]:

df_samples

,Path,base_name,id_sample,id_stem_sample,id_stem,bpm_sample,key_string,key_1,key_dj_1,key_2,key_dj_2,key_3,key_dj_3,cat_STEM
0,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s15_b4-71429-11BAmaj---25-VARIOUS-411srcbasss...,s15_b4,s15_b4-71429,71429,101,10B-Dmaj-8A-Amin_11B-Amaj,Amaj,11B,Amin,8A,Dmaj,10B,BASS
1,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s24_b4-71429-11BAmaj---25-VARIOUS-411srcbasss...,s24_b4,s24_b4-71429,71429,101,12B-Emaj-11B-Amaj_8A-Amin,Amin,8A,Amaj,11B,Emaj,12B,BASS
2,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s22_b4-71429-11BAmaj---25-VARIOUS-411srcbasss...,s22_b4,s22_b4-71429,71429,101,2A-D#min-10A-Bmin_1B-Bmaj,Bmaj,1B,Bmin,10A,D#min,2A,BASS
3,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s11_b4-71429-11BAmaj---25-VARIOUS-411srcbasss...,s11_b4,s11_b4-71429,71429,101,10A-Bmin-12B-Emaj_8A-Amin,Amin,8A,Emaj,12B,Bmin,10A,BASS
4,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s83_b4-71429-11BAmaj---25-VARIOUS-411srcbasss...,s83_b4,s83_b4-71429,71429,101,10B-Dmaj-11A-F#min_10A-Bmin,Bmin,10A,F#min,11A,Dmaj,10B,BASS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72258,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s41_d6-7151c-6AGmin---25-VARIOUS-0608srcdrums...,s41_d6,s41_d6-7151c,7151c,126,1A-G#min-9B-Gmaj_6A-Gmin,Gmin,6A,Gmaj,9B,G#min,1A,DRUM
72259,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_sb1_d6-7151c-6AGmin---25-VARIOUS-0608srcdrums...,sb1_d6,sb1_d6-7151c,7151c,126,1A-G#min-9B-Gmaj_6A-Gmin,Gmin,6A,Gmaj,9B,G#min,1A,DRUM
72260,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s43_d6-7151c-6AGmin---25-VARIOUS-0608srcdrums...,s43_d6,s43_d6-7151c,7151c,126,1A-G#min-9A-Emin_12B-Emaj,Emaj,12B,Emin,9A,G#min,1A,DRUM
72261,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_s21_d6-7151c-6AGmin---25-VARIOUS-0608srcdrums...,s21_d6,s21_d6-7151c,7151c,126,10B-Dmaj-9B-Gmaj_6A-Gmin,Gmin,6A,Gmaj,9B,Dmaj,10B,DRUM
72262,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,_sc1_d6-7151c-6AGmin---25-VARIOUS-0608srcdrums...,sc1_d6,sc1_d6-7151c,7151c,126,10B-Dmaj-5B-D#maj_6A-Gmin,Gmin,6A,D#maj,5B,Dmaj,10B,DRUM

In [14]:
# -----######-----###### MP3 PATHS + BASENAME 2-LEVEL -----######-----###### #
import os
import pandas as pd
from tqdm import tqdm

def _paths_1707_2levelmp3_GET_df(folder_root):
    """
    Traverses 2 levels deep and collects all .mp3 files.
    Returns a DataFrame with:
        - 'Path': full path to the file
        - 'file_name': filename with extension
        - 'Name': base name without extension
    """
    paths = []
    file_names = []
    base_names = []

    print(f"📂 Searching inside: {folder_root}")

    for lvl1 in tqdm(sorted(os.listdir(folder_root))):
        lvl1_path = os.path.join(folder_root, lvl1)
        if not os.path.isdir(lvl1_path): continue

        for lvl2 in sorted(os.listdir(lvl1_path)):
            lvl2_path = os.path.join(lvl1_path, lvl2)
            if not os.path.isdir(lvl2_path): continue

            for file in os.listdir(lvl2_path):
                if file.lower().endswith(".mp3") and not file.startswith("._"):
                    full_path = os.path.join(lvl2_path, file)
                    paths.append(full_path)
                    file_names.append(file)
                    base_names.append(os.path.splitext(file)[0])

    df = pd.DataFrame({
        "Path": paths,
        "file_name": file_names,
        "base_name": base_names
    })

    print(f"🎯 Total MP3s found: {len(df)}")
    return df
folder_input = "/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S"
df_mp3s = _paths_1707_2levelmp3_GET_df(folder_input)

📂 Searching inside: /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S

100%|██████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 422.03it/s]

🎯 Total MP3s found: 3286

In [15]:
df_mp3s

,Path,file_name,base_name
0,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-71413-5BD#maj---25-VARIOUS-343srcbasssil010...,b1-71413-5BD#maj---25-VARIOUS-343srcbasssil010...
1,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-71402-4AFmin---25-VARIOUS-01924basssil01000...,b1-71402-4AFmin---25-VARIOUS-01924basssil01000...
2,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-71410-12AC#min---25-VARIOUS-316srcbasssil01...,b1-71410-12AC#min---25-VARIOUS-316srcbasssil01...
3,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-7140s-8AAmin---25-VARIOUS-216srcbasssil0102...,b1-7140s-8AAmin---25-VARIOUS-216srcbasssil0102...
4,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-7140m-12BEmaj---25-VARIOUS-142srcbasssil010...,b1-7140m-12BEmaj---25-VARIOUS-142srcbasssil010...
...,...,...,...
3281,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-7144k-7ADmin---25-VARIOUS-1567srcvocalssil0...,v6-7144k-7ADmin---25-VARIOUS-1567srcvocalssil0...
3282,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-71452-2AD#min---25-VARIOUS-1588srcvocalssil...,v6-71452-2AD#min---25-VARIOUS-1588srcvocalssil...
3283,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-71463-9AEmin---25-VARIOUS-1631srcvocalssil0...,v6-71463-9AEmin---25-VARIOUS-1631srcvocalssil0...
3284,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-7141t-5ACmin---25-VARIOUS-1439srcvocalssil0...,v6-7141t-5ACmin---25-VARIOUS-1439srcvocalssil0...
3285,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-7144x-8BCmaj---25-VARIOUS-1583srcvocalssil0...,v6-7144x-8BCmaj---25-VARIOUS-1583srcvocalssil0...

In [62]:
df

,Path,base_name,id_sample,id_stem_sample,id_stem,bpm_sample,key_string,key_1,key_dj_1,key_2,key_dj_2,key_3,key_dj_3,cat_STEM
0,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_BASS/b_40_percent_silence/b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033---sec361-101-luE/_s15_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-10B-Dmaj-8A-Amin_11B-Amaj-101.mp3,_s15_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-10B-Dmaj-8A-Amin_11B-Amaj-101,s15_b4,s15_b4-71429,71429,101,10B-Dmaj-8A-Amin_11B-Amaj,Amaj,11B,Amin,8A,Dmaj,10B,BASS
1,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_BASS/b_40_percent_silence/b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033---sec361-101-luE/_s24_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-12B-Emaj-11B-Amaj_8A-Amin-101.mp3,_s24_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-12B-Emaj-11B-Amaj_8A-Amin-101,s24_b4,s24_b4-71429,71429,101,12B-Emaj-11B-Amaj_8A-Amin,Amin,8A,Amaj,11B,Emaj,12B,BASS
2,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_BASS/b_40_percent_silence/b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033---sec361-101-luE/_s22_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-2A-D#min-10A-Bmin_1B-Bmaj-101.mp3,_s22_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-2A-D#min-10A-Bmin_1B-Bmaj-101,s22_b4,s22_b4-71429,71429,101,2A-D#min-10A-Bmin_1B-Bmaj,Bmaj,1B,Bmin,10A,D#min,2A,BASS
3,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_BASS/b_40_percent_silence/b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033---sec361-101-luE/_s11_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-10A-Bmin-12B-Emaj_8A-Amin-101.mp3,_s11_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-10A-Bmin-12B-Emaj_8A-Amin-101,s11_b4,s11_b4-71429,71429,101,10A-Bmin-12B-Emaj_8A-Amin,Amin,8A,Emaj,12B,Bmin,10A,BASS
4,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_BASS/b_40_percent_silence/b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033---sec361-101-luE/_s83_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-10B-Dmaj-11A-F#min_10A-Bmin-101.mp3,_s83_b4-71429-11BAmaj---25-VARIOUS-411srcbasssil04033-luE-10B-Dmaj-11A-F#min_10A-Bmin-101,s83_b4,s83_b4-71429,71429,101,10B-Dmaj-11A-F#min_10A-Bmin,Bmin,10A,F#min,11A,Dmaj,10B,BASS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72258,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_60_percent_silence/d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010---sec407-126-luT/_s41_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-1A-G#min-9B-Gmaj_6A-Gmin-126.mp3,_s41_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-1A-G#min-9B-Gmaj_6A-Gmin-126,s41_d6,s41_d6-7151c,7151c,126,1A-G#min-9B-Gmaj_6A-Gmin,Gmin,6A,Gmaj,9B,G#min,1A,DRUM
72259,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_60_percent_silence/d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010---sec407-126-luT/_sb1_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-1A-G#min-9B-Gmaj_6A-Gmin-126.mp3,_sb1_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-1A-G#min-9B-Gmaj_6A-Gmin-126,sb1_d6,sb1_d6-7151c,7151c,126,1A-G#min-9B-Gmaj_6A-Gmin,Gmin,6A,Gmaj,9B,G#min,1A,DRUM
72260,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_60_percent_silence/d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010---sec407-126-luT/_s43_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-1A-G#min-9A-Emin_12B-Emaj-126.mp3,_s43_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-1A-G#min-9A-Emin_12B-Emaj-126,s43_d6,s43_d6-7151c,7151c,126,1A-G#min-9A-Emin_12B-Emaj,Emaj,12B,Emin,9A,G#min,1A,DRUM
72261,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_60_percent_silence/d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010---sec407-126-luT/_s21_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-10B-Dmaj-9B-Gmaj_6A-Gmin-126.mp3,_s21_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-10B-Dmaj-9B-Gmaj_6A-Gmin-126,s21_d6,s21_d6-7151c,7151c,126,10B-Dmaj-9B-Gmaj_6A-Gmin,Gmin,6A,Gmaj,9B,Dmaj,10B,DRUM
72262,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_60_percent_silence/d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010---sec407-126-luT/_sc1_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-10B-Dmaj-5B-D#maj_6A-Gmin-126.mp3,_sc1_d6-7151c-6AGmin---25-VARIOUS-0608srcdrumssil010-luT-10B-Dmaj-5B-D#maj_6A-Gmin-126,sc1_d6,sc1_d6-7151c,7151c,126,10B-Dmaj-5B-D#maj_6A-Gmin,Gmin,6A,D#maj,5B,Dmaj,10B,DRUM

In [19]:
df.to_pickle('_df_samples_STEMS_72263_25_07.pkl')

In [42]:
# -----######-----###### EXTRACT base_name FROM Name -----######-----###### #
def _parse_1707_name_GET_base_name(df):
    """
    From df['Name'], extract 'base_name' by:
    - Keeping first 3 characters
    - Appending characters up to the next '-' after that
    Adds column 'base_name'
    """
    base_names = []

    for name in df["file_name"]:
        prefix = name[:3]
        rest = name[3:]
        mid = rest.split("-")[0]
        base_name = f"{prefix}{mid}"
        base_names.append(base_name)

    df["ID"] = base_names
    print(f"🔡 base_name extracted for {len(df)} rows.")
    return df

In [44]:

df_mp3s = _parse_1707_name_GET_base_name(df_mp3s)
df_mp3s

🔡 base_name extracted for 3286 rows.

,Path,file_name,base_name,id_stem,ID
0,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-71413-5BD#maj---25-VARIOUS-343srcbasssil010...,b1-71413,71413,b1-71413
1,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-71402-4AFmin---25-VARIOUS-01924basssil01000...,b1-71402,71402,b1-71402
2,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-71410-12AC#min---25-VARIOUS-316srcbasssil01...,b1-71410,71410,b1-71410
3,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-7140s-8AAmin---25-VARIOUS-216srcbasssil0102...,b1-7140s,7140s,b1-7140s
4,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,b1-7140m-12BEmaj---25-VARIOUS-142srcbasssil010...,b1-7140m,7140m,b1-7140m
...,...,...,...,...,...
3281,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-7144k-7ADmin---25-VARIOUS-1567srcvocalssil0...,v6-7144k,7144k,v6-7144k
3282,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-71452-2AD#min---25-VARIOUS-1588srcvocalssil...,v6-71452,71452,v6-71452
3283,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-71463-9AEmin---25-VARIOUS-1631srcvocalssil0...,v6-71463,71463,v6-71463
3284,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-7141t-5ACmin---25-VARIOUS-1439srcvocalssil0...,v6-7141t,7141t,v6-7141t
3285,/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATER...,v6-7144x-8BCmaj---25-VARIOUS-1583srcvocalssil0...,v6-7144x,7144x,v6-7144x

In [49]:
#df_combined#['ID'].head(6)

In [46]:
# -----######-----###### COMPARE TWO ID COLUMNS -----######-----###### #
def _compare_1707_ids_GET_mismatch_report(df1, df2, col_name="ID"):
    """
    Compares col_name in df1 and df2:
    - Checks if both sets are identical
    - Lists missing values from each side
    - Reports count summary
    """
    set1 = set(df1[col_name].dropna())
    set2 = set(df2[col_name].dropna())

    only_in_df1 = sorted(set1 - set2)
    only_in_df2 = sorted(set2 - set1)
    common_ids = sorted(set1 & set2)

    print(f"🔍 Comparing column: '{col_name}'")
    print(f"✅ Common IDs: {len(common_ids)}")
    print(f"❌ Only in df_mp3s: {len(only_in_df1)}")
    print(f"❌ Only in df_combined: {len(only_in_df2)}")

    if only_in_df1:
        print("📁 Missing in df_combined:")
        for val in only_in_df1[:10]:
            print(f"   - {val}")
        if len(only_in_df1) > 10:
            print("   ...")

    if only_in_df2:
        print("📁 Missing in df_mp3s:")
        for val in only_in_df2[:10]:
            print(f"   - {val}")
        if len(only_in_df2) > 10:
            print("   ...")

    return {
        "only_in_df_mp3s": only_in_df1,
        "only_in_df_combined": only_in_df2,
        "common_ids": common_ids
    }

In [47]:
report_ids = _compare_1707_ids_GET_mismatch_report(df_mp3s, df_combined, col_name="ID")

🔍 Comparing column: 'ID'
✅ Common IDs: 3286
❌ Only in df_mp3s: 0
❌ Only in df_combined: 0

In [50]:
# -----######-----###### REPLACE PATHS FROM MATCHING ID -----######-----###### #
def _merge_1707_fixpaths_GET_dfnew(df_combined, df_mp3s):
    """
    Replaces df_combined['Path'] with the correct value from df_mp3s based on 'ID' match.
    Returns a new DataFrame identical to df_combined, but with updated 'Path'.
    """
    # Keep original just in case
    df_combined_updated = df_combined.copy()

    # Build dict: ID -> Path from df_mp3s
    id_to_path = dict(zip(df_mp3s["ID"], df_mp3s["Path"]))

    # Replace paths in df_combined
    df_combined_updated["Path"] = df_combined_updated["ID"].map(id_to_path)

    print(f"✅ Replaced Path values using ID match. Total rows updated: {len(df_combined_updated)}")
    return df_combined_updated

In [51]:
df_combined_fixed = _merge_1707_fixpaths_GET_dfnew(df_combined, df_mp3s)

✅ Replaced Path values using ID match. Total rows updated: 3286

In [52]:
# -----######-----###### VERIFY FILE PATHS EXIST -----######-----###### #
import os

def _check_1707_paths_GET_missing_summary(df, path_col="Path"):
    """
    Verifies which paths exist on disk for the given path column.
    Adds 'exists' column (True/False) and returns summary + missing paths.
    """
    print(f"🔎 Verifying {len(df)} paths in column: '{path_col}'")

    df["exists"] = df[path_col].apply(os.path.exists)
    total_missing = (~df["exists"]).sum()
    
    print(f"✅ Valid paths: {len(df) - total_missing}")
    print(f"❌ Missing paths: {total_missing}")

    if total_missing > 0:
        print("⚠️ Sample missing paths:")
        print(df[~df["exists"]][path_col].head(5).to_string(index=False))

    return df

In [53]:
df_combined_fixed = _check_1707_paths_GET_missing_summary(df_combined_fixed)

🔎 Verifying 3286 paths in column: 'Path'
✅ Valid paths: 3286
❌ Missing paths: 0

In [56]:
pd.set_option('display.max_colwidth', None)

df_combined_fixed['Path']

0        /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_VOCAL/v_10_percent_silence/v1-71100-6BA#maj---25-VARIOUS-000822vocalssil030---sec354-123-luI.mp3
1       /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_VOCAL/v_10_percent_silence/v1-71101-11AF#min---25-VARIOUS-000922vocalssil030---sec328-117-luO.mp3
2        /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_VOCAL/v_10_percent_silence/v1-71102-11BAmaj---25-VARIOUS-001022vocalssil030---sec215-120-luQ.mp3
3         /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_VOCAL/v_10_percent_silence/v1-71103-9AEmin---25-VARIOUS-001122vocalssil030---sec185-123-luL.mp3
4        /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_VOCAL/v_10_percent_silence/v1-71104-11BAmaj---25-VARIOUS-001222vocalssil030---sec207-123-luR.mp3
                                                                                             ...
3281      /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_80_percent_silence/d8-7154k-6BA#maj---25-VARIOUS-1364srcdrumssil080---sec131-144-luA.mp3
3282       /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_80_percent_silence/d8-7154l-4AFmin---25-VARIOUS-1365srcdrumssil080---sec371-105-luE.mp3
3283       /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_80_percent_silence/d8-7154m-8BCmaj---25-VARIOUS-1366srcdrumssil080---sec417-120-luH.mp3
3284       /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_80_percent_silence/d8-7154n-8BCmaj---25-VARIOUS-1367srcdrumssil080---sec417-120-luH.mp3
3285      /Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_25_07_DRUM/d_80_percent_silence/d8-7154o-4BG#maj---25-VARIOUS-1368srcdrumssil080---sec395-161-luA.mp3
Name: Path, Length: 3286, dtype: object

In [57]:
df_combined_fixed['ID']

0       v1-71100
1       v1-71101
2       v1-71102
3       v1-71103
4       v1-71104
          ...
3281    d8-7154k
3282    d8-7154l
3283    d8-7154m
3284    d8-7154n
3285    d8-7154o
Name: ID, Length: 3286, dtype: object

In [59]:
len(df_combined_fixed)

3286

In [61]:
df_combined_fixed.to_pickle('/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_df_STEMS_3286_25_07.pkl')

In [63]:
df.to_pickle('/Users/yerik/Music/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_3_PROD_stems_S/_df_samples_STEMS_72263_25_07.pkl')