In [2]:
import pandas as pd
df_STEMS = pd.read_pickle("_df_STEMS_3286_25_07.pkl")
df_samples_STEMS = pd.read_pickle("_df_samples_STEMS_72263_25_07.pkl")

In [3]:
print(len(df_STEMS) , len(df_samples_STEMS) )

3286 72263

In [4]:
df_exports = pd.read_pickle("_df_exports.pkl")

In [5]:
df_exports['ID']

0       5600
1       5601
2       5602
3       5603
4       5604
        ...
1001    56rt
1002    56ru
1003    56rv
1004    56rw
1005    56rx
Name: ID, Length: 1006, dtype: object

In [6]:
# -----######-----###### PATH SCANNER W/ FIRST 5 CHAR ID -----######-----###### #
import os
import pandas as pd
from tqdm import tqdm

def _paths_1807_id5_GET_df_paths_ids(folder_root):
    """
    Extracts all file paths into df['Path'] and assigns ID as the first 5 characters of file_name.
    """
    all_paths = []
    for root, _, files in os.walk(folder_root):
        for file in files:
            if file.startswith('._') or file == '.DS_Store':
                continue
            all_paths.append(os.path.join(root, file))

    df = pd.DataFrame({'Path': all_paths})
    df['file_name'] = df['Path'].apply(os.path.basename)
    df['ID'] = df['file_name'].str[:5]  # First 5 characters

    return df

In [7]:
folder_root = "/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__"
df = _paths_1807_id5_GET_df_paths_ids(folder_root)
df

,Path,file_name,ID
0,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e5600-6AGmin---25-YODJ-00262niyodjexports---se...,e5600
1,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e5602-5ACmin---25-YODJ-0737exports001scene1---...,e5602
2,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e5603-1AG#min---25-YODJ-03392niyodjexports---s...,e5603
3,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e5604-3AA#min---25-YODJ-02412niyodjexports---s...,e5604
4,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e5605-3BC#maj---25-YODJ-05342niyodjexports---s...,e5605
...,...,...,...
761,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e56rt-1AG#min---25-YODJ-06442niyodjexports---s...,e56rt
762,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e56ru-8BCmaj---25-YODJ-04232niyodjexports---se...,e56ru
763,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e56rv-4AFmin---25-YODJ-01312niyodjexports---se...,e56rv
764,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e56rw-4AFmin---25-YODJ-00492niyodjexports---se...,e56rw
765,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATE...,e56rx-12AC#min---25-YODJ-03562niyodjexports---...,e56rx

In [8]:
df['ID']

0      e5600
1      e5602
2      e5603
3      e5604
4      e5605
       ...
761    e56rt
762    e56ru
763    e56rv
764    e56rw
765    e56rx
Name: ID, Length: 766, dtype: object

In [9]:
df_exports['ID'] = 'e' + df_exports['ID']

In [10]:
df_exports['ID']

0       e5600
1       e5601
2       e5602
3       e5603
4       e5604
        ...
1001    e56rt
1002    e56ru
1003    e56rv
1004    e56rw
1005    e56rx
Name: ID, Length: 1006, dtype: object

In [11]:
# Get sets of unique IDs from both DataFrames
ids_exports = set(df_exports['ID'])
ids_main = set(df['ID'])

# Find intersection (common IDs)
common_ids = ids_exports.intersection(ids_main)

# Print results
print(f"✅ Total IDs in df_exports: {len(ids_exports)}")
print(f"✅ Total IDs in df:         {len(ids_main)}")
print(f"🔁 Matching IDs:            {len(common_ids)}")

✅ Total IDs in df_exports: 1006
✅ Total IDs in df:         766
🔁 Matching IDs:            766

In [12]:
# Filter df_export to only rows with matching IDs
df_ = df_exports[df_exports['ID'].isin(common_ids)]

In [13]:
df_

,Path,temp_id,file_name,Extension,dur_seconds,dur_min,sr,bit_depth,bit_rate,channels,...,centroid_desc,Path_png_bar_centroid,Path_csv_freq,Path_png_dr,Path_png_id_and_key,year_written_id3,bought_year,comment,re_name,audio_hash
0,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,15.238118,0.253969,44100,16,None,2,...,Muted emotion,images/centroid_donut_5600.png,tables/table_freq_5600.csv,images/dbs_plot_5600.png,images/key_and_id_5600.png,Unsupported,None,e5600-6A-Gmin---25-SAMPLE-00262niyodjexports--...,e5600-6AGmin---25-YODJ-00262niyodjexports---se...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
2,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_...,TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_...,.aiff,17.999977,0.3,44100,16,None,2,...,Sparkling energy,images/centroid_donut_5602.png,tables/table_freq_5602.csv,images/dbs_plot_5602.png,images/key_and_id_5602.png,Unsupported,None,e5602-5A-Cmin---25-SAMPLE-0737exports001scene1...,e5602-5ACmin---25-YODJ-0737exports001scene1---...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
3,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,68.571406,1.142857,44100,16,None,2,...,"Jungle, tribal pulse",images/centroid_donut_5603.png,tables/table_freq_5603.csv,images/dbs_plot_5603.png,images/key_and_id_5603.png,Unsupported,None,e5603-1A-G#min---25-SAMPLE-03392niyodjexports-...,e5603-1AG#min---25-YODJ-03392niyodjexports---s...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
4,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,30.967755,0.516129,44100,16,None,2,...,Dramatic & haunting,images/centroid_donut_5604.png,tables/table_freq_5604.csv,images/dbs_plot_5604.png,images/key_and_id_5604.png,Unsupported,None,e5604-3A-A#min---25-SAMPLE-02412niyodjexports-...,e5604-3AA#min---25-YODJ-02412niyodjexports---s...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
5,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,15.73771,0.262295,44100,16,None,2,...,Airy textures,images/centroid_donut_5605.png,tables/table_freq_5605.csv,images/dbs_plot_5605.png,images/key_and_id_5605.png,Unsupported,None,e5605-3B-C#maj---25-SAMPLE-05342niyodjexports-...,e5605-3BC#maj---25-YODJ-05342niyodjexports---s...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,8.0,0.133333,44100,16,None,2,...,Dubby twilight,images/centroid_donut_56rt.png,tables/table_freq_56rt.csv,images/dbs_plot_56rt.png,images/key_and_id_56rt.png,Unsupported,None,e56rt-1A-G#min---25-SAMPLE-06442niyodjexports-...,e56rt-1AG#min---25-YODJ-06442niyodjexports---s...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
1002,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,3.934444,0.065574,44100,16,None,2,...,Emotional but soft,images/centroid_donut_56ru.png,tables/table_freq_56ru.csv,images/dbs_plot_56ru.png,images/key_and_id_56ru.png,Unsupported,None,e56ru-8B-Cmaj---25-SAMPLE-04232niyodjexports--...,e56ru-8BCmaj---25-YODJ-04232niyodjexports---se...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
1003,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0131__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0131__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,31.47542,0.52459,44100,16,None,2,...,"Assertive, bright",images/centroid_donut_56rv.png,tables/table_freq_56rv.csv,images/dbs_plot_56rv.png,images/key_and_id_56rv.png,Unsupported,None,e56rv-4A-Fmin---25-SAMPLE-01312niyodjexports--...,e56rv-4AFmin---25-YODJ-01312niyodjexports---se...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
1004,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0049__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0049__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,31.47542,0.52459,44100,16,None,2,...,"Assertive, bright",images/centroid_donut_56rw.png,tables/table_freq_56rw.csv,images/dbs_plot_56rw.png,images/key_and_id_56rw.png,Unsupported,None,e56rw-4A-Fmin---25-SAMPLE-00492niyodjexports--...,e56rw-4AFmin---25-YODJ-00492niyodjexports---se...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...
1005,/Users/yerik/Music/__EXPORTS__/__RNRNexports/T...,TRkw__0356__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,TRkw__0356__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_...,.aiff,3.934422,0.065574,44100,16,None,2,...,"Harsh, clinical, hyper-bright",images/centroid_donut_56rx.png,tables/table_freq_56rx.csv,images/dbs_plot_56rx.png,images/key_and_id_56rx.png,Unsupported,None,e56rx-12A-C#min---25-SAMPLE-03562niyodjexports...,e56rx-12AC#min---25-YODJ-03562niyodjexports---...,FFmpeg Error: ffmpeg version 7.1.1 Copyright (...

In [14]:
# Drop old Path in df_ (if exists), then merge correct Path from df
df_ = df_.drop(columns=['Path'], errors='ignore')
df_ = df_.merge(df[['ID', 'Path']], on='ID', how='left')

In [15]:
print("🎯 Total updated rows in df_:", len(df_))
print("✅ Non-null paths:", df_['Path'].notna().sum())
print("❌ Missing paths:", df_['Path'].isna().sum())

🎯 Total updated rows in df_: 766
✅ Non-null paths: 766
❌ Missing paths: 0

In [17]:
import os

# Add 'base_name' column from 'Path'
df_['base_name'] = df_['Path'].apply(lambda x: os.path.basename(x) if pd.notna(x) else None)

# Reorder columns: Path, base_name, ID first — rest stay in original order
cols = ['Path', 'base_name', 'ID'] + [col for col in df_.columns if col not in ['Path', 'base_name', 'ID']]
df_ = df_[cols]

In [20]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

df_
import os

df_['file_exists'] = df_['Path'].apply(lambda x: os.path.exists(x) if pd.notna(x) else False)
total = len(df_)
valid = df_['file_exists'].sum()
missing = total - valid

print(f"📁 Total paths checked: {total}")
print(f"✅ Existing files:      {valid}")
print(f"❌ Missing files:       {missing}")

📁 Total paths checked: 766
✅ Existing files:      766
❌ Missing files:       0

/var/folders/pp/n6z2gh0x56ngpvp6vx5ml9j00000gn/T/ipykernel_88042/773361164.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_['file_exists'] = df_['Path'].apply(lambda x: os.path.exists(x) if pd.notna(x) else False)

In [21]:
df_

,Path,base_name,ID,temp_id,file_name,Extension,dur_seconds,dur_min,sr,bit_depth,...,Path_png_bar_centroid,Path_csv_freq,Path_png_dr,Path_png_id_and_key,year_written_id3,bought_year,comment,re_name,audio_hash,file_exists
0,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5600-6AGmin---25-YODJ-00262niyodjexports---sec15-126-luT.aiff,e5600-6AGmin---25-YODJ-00262niyodjexports---sec15-126-luT.aiff,e5600,TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,15.238118,0.253969,44100,16,...,images/centroid_donut_5600.png,tables/table_freq_5600.csv,images/dbs_plot_5600.png,images/key_and_id_5600.png,Unsupported,None,e5600-6A-Gmin---25-SAMPLE-00262niyodjexports---timeSEC-15-bpm126-luT,e5600-6AGmin---25-YODJ-00262niyodjexports---sec15-126-luT,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600002f54700] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
1,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5602-5ACmin---25-YODJ-0737exports001scene1---sec17-120-luS.aiff,e5602-5ACmin---25-YODJ-0737exports001scene1---sec17-120-luS.aiff,e5602,TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,17.999977,0.3,44100,16,...,images/centroid_donut_5602.png,tables/table_freq_5602.csv,images/dbs_plot_5602.png,images/key_and_id_5602.png,Unsupported,None,e5602-5A-Cmin---25-SAMPLE-0737exports001scene1---timeSEC-17-bpm120-luS,e5602-5ACmin---25-YODJ-0737exports001scene1---sec17-120-luS,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x6000038c8a00] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
2,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5603-1AG#min---25-YODJ-03392niyodjexports---sec68-126-luV.aiff,e5603-1AG#min---25-YODJ-03392niyodjexports---sec68-126-luV.aiff,e5603,TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,68.571406,1.142857,44100,16,...,images/centroid_donut_5603.png,tables/table_freq_5603.csv,images/dbs_plot_5603.png,images/key_and_id_5603.png,Unsupported,None,e5603-1A-G#min---25-SAMPLE-03392niyodjexports---timeSEC-68-bpm126-luV,e5603-1AG#min---25-YODJ-03392niyodjexports---sec68-126-luV,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x6000024a8a00] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
3,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5604-3AA#min---25-YODJ-02412niyodjexports---sec30-123-luS.aiff,e5604-3AA#min---25-YODJ-02412niyodjexports---sec30-123-luS.aiff,e5604,TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,30.967755,0.516129,44100,16,...,images/centroid_donut_5604.png,tables/table_freq_5604.csv,images/dbs_plot_5604.png,images/key_and_id_5604.png,Unsupported,None,e5604-3A-A#min---25-SAMPLE-02412niyodjexports---timeSEC-30-bpm123-luS,e5604-3AA#min---25-YODJ-02412niyodjexports---sec30-123-luS,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x6000017c4600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
4,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5605-3BC#maj---25-YODJ-05342niyodjexports---sec15-123-luH.aiff,e5605-3BC#maj---25-YODJ-05342niyodjexports---sec15-123-luH.aiff,e5605,TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,15.73771,0.262295,44100,16,...,images/centroid_donut_5605.png,tables/table_freq_5605.csv,images/dbs_plot_5605.png,images/key_and_id_5605.png,Unsupported,None,e5605-3B-C#maj---25-SAMPLE-05342niyodjexports---timeSEC-15-bpm123-luH,e5605-3BC#maj---25-YODJ-05342niyodjexports---sec15-123-luH,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600003440600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e56rt-1AG#min---25-YODJ-06442niyodjexports---sec8-0-luV.aiff,e56rt-1AG#min---25-YODJ-06442niyodjexports---sec8-0-luV.aiff,e56rt,TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,8.0,0.133333,44100,16,...,images/centroid_donut_56rt.png,tables/table_freq_56rt.csv,images/dbs_plot_56rt.png,images/key_and_id_56rt.png,Unsupported,None,e56rt-1A-G#min---25-SAMPLE-06442niyodjexports---timeSEC-8-bpm0-luV,e56rt-1AG#min---25-YODJ-06442niyodjexports---sec8-0-luV,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600003c38600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
762,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e56ru-8BCmaj---25-YODJ-04232niyodjexports---sec3-0-luN.aiff,e56ru-8BCmaj---25-YODJ-04232niyodjexports---sec3-0-luN.aiff,e56ru,TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,3.934444,0.065574,44100,16,...,images/centroid_donut_56ru.png,tables/table_freq_56ru.csv,images/dbs_plot_56ru.png,images/key_and_id_56ru.png,Unsupported,None,e56ru-8B-Cmaj---25-SAMPLE-04232niyodjexports---timeSEC-3-bpm0-luN,e56ru-8BCmaj---25-YODJ-04232niyodjexports---sec3-0-luN,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600001904600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True

In [22]:
print(df_.columns.tolist())

['Path', 'base_name', 'ID', 'temp_id', 'file_name', 'Extension', 'dur_seconds', 'dur_min', 'sr', 'bit_depth', 'bit_rate', 'channels', 'file_size', 'file_size_human', 'num_frames', 'error', 'ms_lufs', 'ms_LUFS_code', 'id_cat_lufs', 'mean_bpm', 'std_bpm', 'min_bpm', 'max_bpm', 'variation_percentage', 'dominant_bpm', 'bpm_consistency', 'bpm_consistency_cat', 'title', 'title_file', 'artist', 'artist_file', 'LABEL', 'label_file', 'genre', 'genre_file', 'rel_year', 'rel_year_file', 'KEY', 'key_file', 'mix_name', 'remixer', 'remix', 'date_purchased', 'rel_date', 'rel_date_file', 'key_dj', 'key_music', 'status', 'Relative_Key', 'Key_Up', 'Key_Down', 'Jaw_s_Mix', 'Mood_Shifter', 'Path_jpg_album', 'Path_jpg_key', 'Path_jpg_clip', 'Path_png_bar_dyn', 'ms_LUFS_norm', 'Path_png_bar_lufs', 'Spectral_Bandwidth', 'Spectral_Flatness', 'HEX_shape_texture', 'Path_png_bar_text', 'spec_centroid_hz', 'centroid_color', 'centroid_desc', 'Path_png_bar_centroid', 'Path_csv_freq', 'Path_png_dr', 'Path_png_id_and_key', 'year_written_id3', 'bought_year', 'comment', 're_name', 'audio_hash', 'file_exists']

In [23]:
missing_counts = df_.isna().sum()
missing_counts = missing_counts[missing_counts > 0]

print("🔍 Missing values by column:")
print(missing_counts.sort_values(ascending=False))

🔍 Missing values by column:
bit_rate       766
error          766
bought_year    766
key_music        1
dtype: int64

In [25]:
df_

,Path,base_name,ID,temp_id,file_name,Extension,dur_seconds,dur_min,sr,bit_depth,...,Path_png_bar_centroid,Path_csv_freq,Path_png_dr,Path_png_id_and_key,year_written_id3,bought_year,comment,re_name,audio_hash,file_exists
0,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5600-6AGmin---25-YODJ-00262niyodjexports---sec15-126-luT.aiff,e5600-6AGmin---25-YODJ-00262niyodjexports---sec15-126-luT.aiff,e5600,TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,15.238118,0.253969,44100,16,...,images/centroid_donut_5600.png,tables/table_freq_5600.csv,images/dbs_plot_5600.png,images/key_and_id_5600.png,Unsupported,None,e5600-6A-Gmin---25-SAMPLE-00262niyodjexports---timeSEC-15-bpm126-luT,e5600-6AGmin---25-YODJ-00262niyodjexports---sec15-126-luT,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600002f54700] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0026__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
1,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5602-5ACmin---25-YODJ-0737exports001scene1---sec17-120-luS.aiff,e5602-5ACmin---25-YODJ-0737exports001scene1---sec17-120-luS.aiff,e5602,TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,17.999977,0.3,44100,16,...,images/centroid_donut_5602.png,tables/table_freq_5602.csv,images/dbs_plot_5602.png,images/key_and_id_5602.png,Unsupported,None,e5602-5A-Cmin---25-SAMPLE-0737exports001scene1---timeSEC-17-bpm120-luS,e5602-5ACmin---25-YODJ-0737exports001scene1---sec17-120-luS,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x6000038c8a00] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0737_Exports_001_Scene_1_ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
2,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5603-1AG#min---25-YODJ-03392niyodjexports---sec68-126-luV.aiff,e5603-1AG#min---25-YODJ-03392niyodjexports---sec68-126-luV.aiff,e5603,TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,68.571406,1.142857,44100,16,...,images/centroid_donut_5603.png,tables/table_freq_5603.csv,images/dbs_plot_5603.png,images/key_and_id_5603.png,Unsupported,None,e5603-1A-G#min---25-SAMPLE-03392niyodjexports---timeSEC-68-bpm126-luV,e5603-1AG#min---25-YODJ-03392niyodjexports---sec68-126-luV,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x6000024a8a00] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0339__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
3,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5604-3AA#min---25-YODJ-02412niyodjexports---sec30-123-luS.aiff,e5604-3AA#min---25-YODJ-02412niyodjexports---sec30-123-luS.aiff,e5604,TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,30.967755,0.516129,44100,16,...,images/centroid_donut_5604.png,tables/table_freq_5604.csv,images/dbs_plot_5604.png,images/key_and_id_5604.png,Unsupported,None,e5604-3A-A#min---25-SAMPLE-02412niyodjexports---timeSEC-30-bpm123-luS,e5604-3AA#min---25-YODJ-02412niyodjexports---sec30-123-luS,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x6000017c4600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0241__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
4,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e5605-3BC#maj---25-YODJ-05342niyodjexports---sec15-123-luH.aiff,e5605-3BC#maj---25-YODJ-05342niyodjexports---sec15-123-luH.aiff,e5605,TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,15.73771,0.262295,44100,16,...,images/centroid_donut_5605.png,tables/table_freq_5605.csv,images/dbs_plot_5605.png,images/key_and_id_5605.png,Unsupported,None,e5605-3B-C#maj---25-SAMPLE-05342niyodjexports---timeSEC-15-bpm123-luH,e5605-3BC#maj---25-YODJ-05342niyodjexports---sec15-123-luH,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600003440600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0534__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e56rt-1AG#min---25-YODJ-06442niyodjexports---sec8-0-luV.aiff,e56rt-1AG#min---25-YODJ-06442niyodjexports---sec8-0-luV.aiff,e56rt,TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,8.0,0.133333,44100,16,...,images/centroid_donut_56rt.png,tables/table_freq_56rt.csv,images/dbs_plot_56rt.png,images/key_and_id_56rt.png,Unsupported,None,e56rt-1A-G#min---25-SAMPLE-06442niyodjexports---timeSEC-8-bpm0-luV,e56rt-1AG#min---25-YODJ-06442niyodjexports---sec8-0-luV,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600003c38600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0644__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True
762,/Volumes/MUSIC_PROD/_4_MUSIC_PROD/_0_PROD_MATERIAL/_ALL_6_PROD_exports/_25-56_EXPORTS__/e56ru-8BCmaj---25-YODJ-04232niyodjexports---sec3-0-luN.aiff,e56ru-8BCmaj---25-YODJ-04232niyodjexports---sec3-0-luN.aiff,e56ru,TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06,TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff,.aiff,3.934444,0.065574,44100,16,...,images/centroid_donut_56ru.png,tables/table_freq_56ru.csv,images/dbs_plot_56ru.png,images/key_and_id_56ru.png,Unsupported,None,e56ru-8B-Cmaj---25-SAMPLE-04232niyodjexports---timeSEC-3-bpm0-luN,e56ru-8BCmaj---25-YODJ-04232niyodjexports---sec3-0-luN,"FFmpeg Error: ffmpeg version 7.1.1 Copyright (c) 2000-2025 the FFmpeg developers\n built with Apple clang version 16.0.0 (clang-1600.0.26.6)\n configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon\n libavutil 59. 39.100 / 59. 39.100\n libavcodec 61. 19.101 / 61. 19.101\n libavformat 61. 7.100 / 61. 7.100\n libavdevice 61. 3.100 / 61. 3.100\n libavfilter 10. 4.100 / 10. 4.100\n libswscale 8. 3.100 / 8. 3.100\n libswresample 5. 3.100 / 5. 3.100\n libpostproc 58. 3.100 / 58. 3.100\n[in#0 @ 0x600001904600] Error opening input: No such file or directory\nError opening input file /Users/yerik/Music/__EXPORTS__/__RNRNexports/TRkw__0423__2_NI_YODJ_EXPORTS__ARkw_YODJ_MXkw_original_KYkw_NA_BPkw_NA_GNkw_M-plus-exports_LBkw_YODJ-M-plus-exports_RYkw_2025_01_01_PYkw_2025_05_06.aiff.\nError opening input files: No such file or directory",True

In [ ]:
df_.to_pickle('_df_Exports.pkl')